mlc-ai/mlc-llm

cpp/cli_main.cc
This PR addds stats command in cli to display
the stats of last round of convo.
=> [CLI] Add stats command

cpp/llm_chat.cc
=> Fix typo in llm_chat.cc

mlc_llm/relax_model/moss.py
Fix the fp16 compilation for MOSS model.
=> [Bugfix] Fix the bug of MOSS compilation with fp16

README.md
Fixed small capitalization typos
=> docs: Update README.md / typos fixed

README.md
As I reported in https://github.com/mlc-ai/mlc-llm/issues/15#issuecomment-1533637131, it works out of the box on Intel dGPU as well.
=> Update README to mention Intel GPU support

ios/README.md
Git submodules are not cloned accordingly.
=> Update IOS installation instructions

mlc_llm/relax_model/modules.py
=> [Hotfix] Fix the bug in `modules.py`

mlc_llm/relax_model/gpt_neox.py
* Added `create_sofrmax_func` from [llama.py](https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py#L640-L648) to `gpt_neox.py`
* Fixes #116
=> Add missing create_softmax_func to gpt_neox.py

android/README.md
This PR updates the Android build-from-source instructions. Some dependency steps were missed previously.
=> Update Android insturcions for build from source

README.md
We created an MLC-AI discord server for users and developers to discuss mlc-llm, TVM-Unity, and related topics.
=> [Community] Add link to Discord server

CMakeLists.txt, android/MLCChat/app/src/main/java/ai/mlc/mlcchat/LLMChat.java, build.py, cpp/cli_main.cc, cpp/llm_chat.cc, ios/MLCChat/LLMChat.mm, mlc_llm/relax_model/commons.py, mlc_llm/relax_model/gpt_neox.py, mlc_llm/relax_model/llama.py, mlc_llm/relax_model/moss.py
This PR introduces a new function to the model IRModule which returns the model's metadata required during chat, and thereby reduces the arguments that are currently hardcoded.
=> Introducing model metadata function

build.py, cpp/llm_chat.cc, ios/MLCChat.xcodeproj/project.pbxproj, ios/MLCChat/ChatState.swift, ios/MLCChat/ChatView.swift, ios/MLCChat/LLMChat.mm, ios/MLCChat/MLCChat-Bridging-Header.h, ios/MLCChat/MLCChatApp.swift, ios/MLCChat/ModelConfig.swift, ios/MLCChat/ModelConfig/default-mlc-llm-config.json, ios/MLCChat/ModelState.swift, ios/MLCChat/ModelView.swift, ios/MLCChat/StartState.swift, ios/MLCChat/StartView.swift, ios/app-config.json, ios/prepare_libs.sh, ios/prepare_model_lib.py, ios/prepare_params.sh, mlc_llm/utils.py
This PR updates the iOS to use the latest APIs
=> Update iOS to use latest APIs in llm chat

cpp/cli_main.cc, cpp/llm_chat.cc
filesystem path cannot be implicitly converted to string
=> Fix Windows build

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatState.java, android/MLCChat/app/src/main/java/ai/mlc/mlcchat/LLMChat.java, build.py, cpp/cli_main.cc, cpp/llm_chat.cc, ios/MLCChat/ChatState.swift, ios/MLCChat/LLMChat.mm, ios/MLCChat/MLCChat-Bridging-Header.h, mlc_llm/relax_model/gpt_neox.py, mlc_llm/relax_model/llama.py, mlc_llm/relax_model/moss.py, tests/chat.py, tests/debug/compare_lib.py, tests/evaluate.py
This PR changes the occurance of encode step in LLM to prefill, which is a more standard terminology
=> Use prefill for term consistency

cpp/cli_main.cc, cpp/llm_chat.cc, ios/MLCChat/ChatState.swift, ios/MLCChat/LLMChat.mm, ios/MLCChat/MLCChat-Bridging-Header.h, site/index.md
This PR makes API to be consistent across iOS and C++ implementation.
- Use ChatModule as the wrapper API.
- Use the same function name across implementations
modulo style to match language native preference
- Initial round of documentations about these API
=> API Consistency

mlc_llm/dispatch/llama/main.py
=> Update tir dispatch for vicuna fp32

cpp/cli_main.cc
Also avoids reloading the same library
=> Fix Path finding for library with arch suffix

mlc_llm/dispatch/dispatch_tir_operator_adreno.py
```
Name                                              Time (ms)   Count   Total time (ms)   Percentage (%)
fused_decode3_fused_NT_matmul4_add7_cast8_cast12_add58.0945      31      250.9300          32.50
fused_decode1_fused_NT_matmul1_add4               1.9810      96      190.1715          24.63
fused_decode2_fused_NT_matmul3_add6_gelu1_cast11  4.0514      32      129.6458          16.79
fused_softmax1_cast10                             2.3737      32      75.9587           9.84
fused_decode1_fused_NT_matmul1_add4_add5          1.9897      32      63.6707           8.25
matmul7                                           1.1842      32      37.8929           4.91
fused_NT_matmul2_divide1_maximum1_minimum1_cast9  0.3109      32      9.9500            1.29 …
```
=> prefill kernels of RedPajama on Adreno

mlc_llm/utils.py
This PR enables weight compression in GPU. Previously the weight
compression is run in CPU because the uncompressed weight is too large
to fit in GPU, and running on CPU is pretty slow in fp16 case. Now we
switch to GPU. The technique we use to fit the uncompressed weight into
GPU memory is lazy loading. We load the weight right before the first
use, and instantly free it after the last use.
By testing, this PR reduces the quantization computation time for
Vicuna-v1-7b under `q3f16_0` quantization setting by **6 min** on Linux
machine with **RTX 4090, Ryzen 3970X and 64GB of RAM**, and reduces
the time by 40 sec on Mac Studio with 32 GB of memory.
At this moment, to build the vicuna-7b-v1 model, for Linux machines
we only need more than 28GB of memory in total (compared with over
50GB …
=> Enable weight compression in GPU

scripts/prep_deps.sh
Add `source "$HOME/.cargo/env"` to add `cargo` to the current shell.
=> Fix `prep_deps.sh`

.github/workflows/documentation.yml, CONTRIBUTORS.md, docs/Makefile, docs/contribute/community.rst, docs/requirements.txt, scripts/build_site.sh, scripts/gh_deploy_site.sh, scripts/local_deploy_site.sh, site/_config.yml
This PR adds GH actions for docs
=> Gihhub actions for docs

cpp/conv_templates.cc, cpp/conversation.h, cpp/llm_chat.cc
This PR is the first step to refactor conv template so it is more reusable. Everything consolidated
into GetPromptArrayInternla function.
It intentionalley removed a few predefined sep styles as many can be recreated from fewer pattern. They can be added back later.
Need followup work to make the parameters json
configurable and from app config so users can
change these setups.
=> [REFACTOR] Refactor conv template

docs/install/index.rst
=> [Minor] fix typos

build.py, cpp/conversation.cc, cpp/conversation.h, cpp/llm_chat.cc, mlc_llm/utils.py, tests/cpp/conv_unittest.cc
This PR enables vulkan for rwkv, removes the vulkan from local detection as it can cause cross platform issues. Introduce max_gen_len parameter for chat
=> Enable vulkan for RWKV and some misc updates

CMakeLists.txt, mlc_llm/utils.py, python/README.md, python/mlc_chat/__init__.py, python/mlc_chat/chat_module.py, python/mlc_chat/gradio.py, python/mlc_chat/libinfo.py, python/mlc_chat/rest.py, python/setup.py
This PR refactors the mlc-chat into a formal package Still need some followup TODOs on cleaning up
the rest and gradio API.
=> Refactor mlc_chat into a formal package

docs/contribute/community.rst, docs/index.rst, docs/install/index.rst, docs/install/software-dependencies.rst, docs/misc/faq.rst, docs/model-zoo.rst, docs/tutorials/compile-models.rst, docs/tutorials/deploy-models.rst
- Add tags for all headings
- Slight changes on the navigation panel.
=> [Doc] Update doc

python/README.md, python/mlc_chat/rest.py, python/mlc_chat/sample_client.py
This PR refactors the REST API to support https://github.com/mlc-ai/mlc-llm/pull/266.
=> Refactor REST API

docs/index.rst, docs/install/index.rst, docs/tutorials/deploy-models.rst
=> [Doc] Navigation page refactor

README.md, docs/model-zoo.rst, docs/tutorials/compile-models.rst, docs/tutorials/deploy-models.rst, ios/prepare_params.sh, site/index.md
=> [Doc] Update document for RWKV

cpp/llm_chat.cc
Caused by upstream change: https://github.com/apache/tvm/pull/14902
=> Fix broken build after TVM updates

mlc_llm/utils.py
This PR serves as a workaround solution to fix #294 .
@MasterJH5574 @junrushao @tqchen
=> [Bugfix] Load models with bfloat16 dtype

cpp/llm_chat.cc
=> [FIX] Fix the behavior when input is empty

ios/MLCChat/StartState.swift
This PR adds the code for handling the invalid input URL of new model.
=> [iOS] Handle invalid input URL

.gitmodules, CMakeLists.txt, android/README.md, android/prepare_libs.sh, docs/install/tvm.rst, ios/README.md, ios/prepare_libs.sh, scripts/prep_deps.sh
=> Make relax a submodule of mlc-llm

android/MLCChat/app/src/main/assets/app-config.json, android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt, android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatView.kt, android/MLCChat/app/src/main/java/ai/mlc/mlcchat/StartView.kt
This PR introduces the options to clear downloaded data of model, or delete the model completely.
And this PR improves the model URL part code, to support base url of model homepage
=> [Android] Support model data clear and deletion

mlc_llm/utils.py
=> Detect macOS CPU Arch

docs/index.rst, docs/install/conda.rst, docs/install/gpu.rst, docs/install/tvm.rst
Add docs for:
- GPU (moved from software dependencies)
- Conda installation and troubleshooting
=> [Doc] Add Conda and GPU

docs/install/tvm.rst
=> [Doc] Clarify TVM Build Instruction

ios/MLCChat.xcodeproj/project.pbxproj, ios/prepare_model_lib.py, ios/prepare_params.sh
This PR enables build iOS app from prebuilt
model and library distro same as CLI
=> [iOS] Enable built from prebuilt

build.py
Previously we will always create the `debug` directory and dump the dynamic/static TIR functions, regardless of the `debug-dump` flag.
This PR changes to dump only when flag is set.
=> [Build] Dump debug files only when debug-dump flag set

ios/MLCChat/ChatState.swift, ios/MLCChat/ChatView.swift, ios/MLCChat/ModelState.swift, ios/MLCChat/ModelView.swift, ios/MLCChat/StartState.swift, ios/MLCChat/StartView.swift, ios/MLCChat/app-config.json
This PR overhauls the UX in iOS app. It adds the support for model clear or deletion. And it finalizes the logic of states and transitions in `ModelState` and `ChatState`, with clear and concise code structure. Meanwhile, this PR improves some helper in starting view and alert view for better information displaying.
=> [iOS][UX] UX Overhaul

docs/deploy/cli.rst, docs/get_started/try_out.rst, docs/prebuilt_models.rst, site/index.md
Dependency: https://github.com/mlc-ai/package/pull/27
=> [Doc] Rename `mlc-chat-nightly` conda package to `mlc-chat-cli-nightly`

docs/compilation/compile_models.rst, docs/compilation/distribute_compiled_models.rst, docs/prebuilt_models.rst
This PR further improves the model distribution documentation page with example commands throughout the flow.
=> [Docs] Refine the model distribution page with commands

site/index.md
This PR add the reference of the try-out page into the project page.
=> Link to try-out documentation page in project page

docs/requirements.txt
Fix the error in https://github.com/mlc-ai/mlc-llm/actions/runs/5364491803/jobs/9732720579 .
=> [Hotfix] Fix requirements.txt for documentation

.github/workflows/documentation.yml, scripts/build_site.sh
Followup of https://github.com/mlc-ai/package/pull/30, previously our cpu wheels is problematic because of symbol conflict.
=> [Hotfix] Fix CPU wheels for Python API reference

examples/rest/sample_client.py, python/mlc_chat/interface/openai_api.py, python/mlc_chat/rest.py
This PR makes some changes to the REST server in order to support [integration with web-llm](https://github.com/mlc-ai/web-llm/pull/136).
=> Some fixes to support REST API in web-llm

docs/deploy/android.rst
This PR updates the docs to follow changes in #478.
=> [Doc] Update docs for new Android build

mlc_llm/relax_model/gpt_neox.py
This PR supports GPT-NeoX with ParamManager and the embedding separation. Performance is validated on RedPajama-3B chat model through q4f16_0 scheme.
This PR also validates that q4f16_1 compilation flow on GPT-NeoX gives a desired graph which is ready for dlight application.
=> Support GPT-NeoX with ParamManager and embedding separation

mlc_llm/relax_model/gpt_bigcode.py, mlc_llm/utils.py
`python3 build.py --hf-path bigcode/gpt_bigcode-santacoder --target metal --quantization q4f16_0`
https://huggingface.co/matthoffner/BigCode_SantaCoder-metal
=> add gpt_bigcode-santacoder as build option

docs/community/guideline.rst, docs/deploy/ios.rst, ios/prepare_libs.sh, ios/prepare_params.sh
This PR updates the iOS app build scripts for robustness, and also adds a new image to the iOS build documentation for better clarity.
=> [Docs] Enhances iOS app build scripts and docs

mlc_llm/relax_model/minigpt.py
This PR adds parameter manager for MiniGPT.
Note:
* Since no quantization is applied on MiniGPT for now, I did not apply `param_manager.quantization_transform()`. (we can iterate later)
* The model weights for MiniGPT comes from three parts, all in the form of "xxx.pth" (single weight file) without `pytorch_model.bin.index.json` or any weight shard, so `load_torch_pname2binname_map` cannot be used effectively, and thus I did not add the value of `pidx2pname` and `pname2binname`. Instead, I directly gather all weight values into a param_list which works well.
=> [Fix] Param Manager for MiniGPT

mlc_llm/relax_model/gpt_bigcode.py
This PR brings ParamManager support to GPTBigCode.
Validated on StarCoder and WizardCoder locally.
=> Supporting GPTBigCode with ParamManager

build.py, docs/prebuilt_models.rst, mlc_llm/dispatch/dispatch_tir_operator.py, mlc_llm/relax_model/gptj.py, mlc_llm/relax_model/modules.py, mlc_llm/utils.py
As reported in #457, The GPTJ codebase is outdated and not compatible with new parameter managers.
This PR fixes the issue.
=> [Bugfix] Make GPTJ compatible with new codebase

build.py, docs/prebuilt_models.rst, docs/requirements.txt, docs/tutorials/bring-your-own-models.rst, mlc_llm/dispatch/dispatch_tir_operator.py, mlc_llm/relax_model/gptj.py, mlc_llm/relax_model/modules.py, mlc_llm/utils.py
[YuLan Chat](https://github.com/RUC-GSAI/YuLan-Chat/) is a fine-tuned Chinese LLaMA variant.
=> [Model] Add YuLan, and update documentation on supported model architectures

build.py
Given that the fallback GPU schedule in dlight can already deliver better performance than the DefaultGPUSchedule pass (e.g., the dlight fallback GPU schedule inlines blocks as many as possible), this PR switches the DefaultGPUSchedule pass to dlight fallback GPU schedule.
=> Switch DefaultGPUSchedule pass to dlight fallback GPU schedule

build.py, cpp/conv_templates.cc, mlc_llm/relax_model/llama.py, mlc_llm/utils.py
Rebased #498 and added functionality to allow individual models to override config model types to bridge discrepancy between hf model categories and mlc model categories.
=> Adds model category from hf config file

mlc_llm/relax_model/minigpt.py, mlc_llm/utils.py, tests/debug/compare_lib.py, tests/evaluate.py
This PR mainly updates the evaluation scripts for more accurate profiling results. It is accompanied by another few minor fixes.
=> [Misc] Update of evaluation script

CMakeLists.txt
This PR hide symbol by default and can improve compact for libstdc++ versions.
=> [CMAKE] Hide symbol by default

tests/evaluate.py
CC: @MasterJH5574 @spectrometerHBH
=> [Testing] Add memory bandwidth to the evaluation script

mlc_llm/transform/decode_take.py
type of annotated decode may be 'expr.DataflowVar'
=> [BugFix] Add annotated decode type check for FuseDecodeTake

mlc_llm/relax_model/llama.py
This PR supports QKV and MLP matmul combination for LLaMA.
It adds an option to LlamaConfig, which controls if to combine the QKV computation. Right now, we will combine the QKV and MLP matmul as long as the quantization method is not AutoGPTQ. The option can be also manually set in llama.py.
=> QKV and MLP matmul combination for LLaMA

ios/prepare_libs.sh
This PR is to enable iOS Simulator build
=> [iOS] Enable iOS Simulator (x86_64, arm64)

cmake/gen_cmake_config.py, mlc_llm/utils.py
AMD users might compile models to the OpenCL backend on PC.
=> Add OpenCL+LLVM to compile targets

python/mlc_chat/utils.py
Sorry there is a file that I forgot to clean up. Thanks!
=> [cleanup] remove utils.py

cpp/conv_templates.cc, mlc_llm/build.py, mlc_llm/utils.py
This PR introduces support for LLaMA-2 model.
It also brings the application of a few dlight rules with priority lower than the existing dispatch, which can be viewed as a safety net of dispatching in terms of performance.
=> [Model] LLaMA-2 support

mlc_llm/quantization/__init__.py
This PR introduces the `q4f16_1` group quantization scheme.
=> Introducing `q3f16_1` group quantization scheme

ios/MLCChat/app-config.json, ios/prepare_libs.sh, ios/prepare_params.sh
NOTE: llama2 testflight quick try. Vicuna is a bit out dated and can be added back once we upgrade everything
=> [iOS] llama2 setup

docs/compilation/compile_models.rst, docs/get_started/try_out.rst
This PR introduces the CLI instructions for Llama-2
=> [Docs] CLI and compilation instructions for Llama-2

python/mlc_chat/rest.py
=> [Fix][REST] Shared library suffix on Windows

cpp/cli_main.cc, cpp/llm_chat.cc
We need to have a rigorous e2e speed benchmark to compare different implementations.
Also, we want to see how dynamic len affects perf.
Example usage:
```
~/mlc-llm (e2e-bench ✔) ./build/mlc_chat_cli --local-id Llama-2-7b-chat-hf-q4f16_1 --evaluate --eval-prompt-len 1024 --eval-gen-len=256
Use MLC config: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/params/mlc-chat-config.json"
Use model weights: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/params/ndarray-cache.json"
Use model library: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-cuda.so"
[18:04:46] /home/bohan/mlc-llm/cpp/llm_chat.cc:678: encoding-time=466.727ms, 
[18:04:46] /home/bohan/mlc-llm/cpp/llm_chat.cc:689: [i: 0] decoding-time=8.62598ms tok/s: 115.929.
[18:04:46] …
```
=> [Perf] end-to-end benchmark, configurable prompt-len and gen-len

mlc_llm/core.py
Use cutlass unless user explicitly told the compiler not to. What do you think @masahi?
=> Enable cutlass by default

mlc_llm/core.py
@junrushao Sorry somewhere during rebasing, the actual application of the pass got dropped...
=> [FIX] Split -> Rotary fusion not getting applied

mlc_llm/core.py
The SM number is used only during CUTLASS attention kernel codegen.
=> Fix hardcoded SM version in CUTLASS offload

mlc_llm/relax_model/gpt_neox.py
This PR supports combined QKV matmul computation for GPT-NeoX.
Validated on RedPajama locally.
=> [Model] QKV matmul combination for GPT-NeoX

ios/MLCChat/StartState.swift, ios/MLCChat/app-config.json, ios/prepare_params.sh
This PR switches the iOS app config and scripts from `q4f16_0` quantization mode to `q4f16_1` quantization mode.
=> [iOS] Update config to use `q4f16_1` for RedPajama

cpp/llm_chat.cc, examples/python/sample_chat_module.py, python/mlc_chat/__init__.py, python/mlc_chat/callback.py, python/mlc_chat/chat_module.py
This PR is currently in progress and being iterated. Any comments/suggestions are welcome!
Actionable items:
We'll leave the following to follow-up PRs:
T1 (cont'd). Multimodality support.
T3. Python benchmarking
T4. update doc and step-by-step guide
T5. overall cross-API consistency, i.e. Gradio, rest
Co-author: @CharlieFRuan @sudeepag
=> Python API overhaul

ios/MLCChat/ChatView.swift
When the user connects a keyboard with the iPad app, they can use the keys **command + return** to send a message to chat with the LLM.
=> [iOS] - Send out the message when the user presses command + return keys on a keyboard.

mlc_llm/utils.py
Prior to this PR, the CUDA library build is speficic to a single CUDA compute capability, which makes the library not compatible across different compute capabilities (for example, the model compiled for RTX 4090 cannot run for RTX 2070).
This PR brings the multi-architecture CUDA model compilation support.
=> Support CUDA multiarch build for compatibility

examples/python/benchmark.py, python/mlc_chat/chat_module.py, python/mlc_chat/gradio.py, python/mlc_chat/rest.py
This PR exposes the perf evaluation interface (method `evaluate`) of ChatModule, and provides a demo benchmark scripts in `examples/python/sample_chat_module.py`.
Meanwhile, this PR hides the VM functions of ChatModule for clarity. Those functions are not expected to be directly invoked.
=> [Python] Perf evaluation interface, and publicity update

cpp/cli_main.cc, cpp/llm_chat.cc, cpp/llm_chat.h, examples/python/sample_chat_module.py, python/mlc_chat/base.py, python/mlc_chat/callback.py, python/mlc_chat/chat_module.py
This PR updates the callback routine of the generate() function. Also updates device arg in ChatModule.
=> [Python API] high-level function update

python/mlc_chat/rest.py
Fix REST API after ChatModule API update in https://github.com/mlc-ai/mlc-llm/pull/696.
=> Update ChatModule usage in REST API

docs/compilation/compile_models.rst, docs/deploy/python.rst, examples/python/benchmark.py, examples/python/sample_chat_module.py, python/mlc_chat/base.py, python/mlc_chat/chat_module.py
See progress in 
- https://github.com/mlc-ai/mlc-llm/issues/682
Co-author: @CharlieFRuan
=> [Docs] Python API finer documentation

docs/deploy/rest.rst, python/mlc_chat/rest.py
This PR updates the REST API docs to reflect the new args introduced in https://github.com/mlc-ai/mlc-llm/pull/681 and https://github.com/mlc-ai/mlc-llm/pull/698.
=> Update REST API docs to reflect new args

docs/deploy/python.rst
=> [Docs] Add StreamToStdout to Python API examples

mlc_llm/quantization/__init__.py
This PR adds the `q8f16_1` quantization registry.
=> Add `q8f16_1` for benchmark

docs/install/gpu.rst
Add the instruction about how to set up OpenCL and Mali-GPU driver on Orange Pi 5 Plus SBC with Ubuntu system
=> [Doc] Add the Mali-OpenCL setup instruction

docs/prebuilt_models.rst
Update documentation for prebuilt models, reflecting the current prebuilt we support.
Following up to #752.
=> [Doc] Update doc for prebuilt models

CMakeLists.txt
This PR adds check for rust (cargo) installed.
cc @yzh119
=> [CMAKE] Add check for rust installed

cpp/conv_templates.cc, mlc_llm/utils.py
This PR adds support for CodeLlama models, providing the necessary templates for its execution. Tested on `CodeLlama-7b`, `CodeLlama-7b-Instruct` and `CodeLlama-7b-Python`.
=> [Model Support] CodeLlama

docs/deploy/android.rst
=> [Docs] fix typo in android.rst

android/MLCChat/app/src/main/assets/app-config.json, android/prepare_libs.sh
This PR updates the app to use llama2 model
=> [Android] llama2 app

cpp/llm_chat.cc, cpp/llm_chat.h
=> Remove Legacy ChatModule

mlc_llm/relax_model/llama.py
This makes MLC-LLM properly support codellama and removes an issue I was seeing with the output being very odd in certain circumstances. 
@sunggg @zxybazh
=> Add support for rope_theta a necessary feature of codellama

.gitignore, cpp/cli_main.cc, cpp/llm_chat.cc, mlc_llm/core.py, mlc_llm/relax_model/llama.py, mlc_llm/relax_model/param_manager.py, mlc_llm/utils.py
This PR provides multi-GPU TP inference for MLC LLM based on TVM Disco runtime.
=> Multi-GPU Tensor Parallelism Support

mlc_llm/core.py, mlc_llm/transform/decode_matmul_ewise.py
As https://github.com/apache/tvm/pull/15730 merged, it's no need to dispatch pre-tuned kernel anymore. This PR disables the dispatch.
cc @spectrometerHBH @junrushao
=> [Perf] Disable dispatch

cpp/llm_chat.cc, mlc_llm/core.py, python/mlc_chat/chat_module.py
This PR fixes Python API to follow the latest API of ChatModule (specifically, the "reload" function) changed in #867.
=> [Fix] Python API following latest ChatModule reload

cpp/llm_chat.cc
In multi-GPU setting, a hard constraint is that currently only shared library is supported, and a string path is required to be provided to Disco's session as:
```python
sess.load_vm_module("/path/to/shared/lib.so")
```
And therefore, previously in PR #867, we made a breaking change to the signature of `ChatModule.reload` API as below:
```diff
- void Reload(tvm::runtime::Module lib, ...);
+ void Reload(String lib_path, ...);
```
However, it brings an unexpected breaking change, which on iOS and Android apps, we expect the library being bundled together as static system libraries rather than shared libraries, and in these cases, the string path is not available, making them crash after the PR merge.
This PR re-enables backward compatibility for those apps and also preserves the ability to …
=> [BugFix] Revert Breaking Change to `ChatModule.Reload` API

android/CMakeLists.txt, android/prepare_libs.sh
=> [Fix] android cmake

mlc_llm/relax_model/param_manager.py
This PR fixes the ft quantization error in param manager.
cc: @MasterJH5574 @masahi
=> [Fix] Fix ft quantization in param manager

docs/deploy/android.rst
This PR adds the new revamped Android doc to MLC LLM.
Some principles:
- All dependencies are listed in the very beginning, along with 1) links to actionable installation instructions; 2) environment variables to be set; 3) minimum version required;
- All commands are copy-pastable, and by executing those commands in order, one could generate the result Android APK without reading the text;
- Line commands (e.g. `mlc_llm.build`) are broken to multiple lines;
- Always show help message before running MLC-related commands.
Future TODOs:
- Explain how to access any function exposed in `tvm.runtime.module` in Java;
- Explain how to use prebuilt models.
=> [Doc] Revamp Android Doc

cpp/conv_templates.cc
Meta has suggested deprecating its super long system prompt for a while, and the shortened system prompt seems to help Llama2 have a more helpful conversation.
=> Shorten the System Prompt of Llama2

docs/deploy/android.rst, docs/install/tvm.rst
Added:
- Download link for the demo app
- Ask to check environment variables again in case users missed out
=> [Doc] Add more details in the Android doc

README.md
This PR revamps README.md for better clarity. Revamp of project landing page will follow up soon.
=> [Docs] README revamp

docs/deploy/python.rst
Documentation for Raw Text Generation. Part of #773.
=> [Doc] Raw Text Generation

cpp/llm_chat.cc, mlc_llm/core.py, mlc_llm/relax_model/commons.py, mlc_llm/relax_model/llama.py, mlc_llm/relax_model/param_manager.py, python/mlc_chat/cli/benchmark.py
This PR internalizes `shard_info.json` into the model DSO so that it
doesn't have to release an extra JSON file which is a burden. Meanwhile,
after this file, model weights are not dependent of the `num_shards`
hyperparameter, meaning varying `num_shards` doesn't need to do
quantization again.
=> Finalize Multi-GPU Inference

cpp/llm_chat.cc
=> Fix the max window length fetching in local mode

mlc_llm/core.py
Closes https://github.com/mlc-ai/mlc-llm/issues/923. It needs the TVM commit https://github.com/apache/tvm/pull/15856
=> Fix hard-coded epsilon parameter for cutlass RMS norm

mlc_llm/relax_model/param_manager.py
=> Fix type hints for shard strategy

cpp/llm_chat.cc
fix disco break introduced by #1016
=> [Bugfix] Fix Disco break 

cpp/llm_chat.cc, python/mlc_chat/cli/benchmark.py
A minor C++ syntax error. Seems introduced by https://github.com/mlc-ai/mlc-llm/pull/1007
=> Fix compilation error

README.md, docs/compilation/distribute_compiled_models.rst, docs/prebuilt_models.rst
Iterating https://github.com/mlc-ai/mlc-llm/pull/1000, small modifications on the prebuilt model tables on both documentation and README.
cc @junrushao
=> [Docs] Iterate model prebuilts docs

mlc_llm/utils.py
A convenience feature to display the progress through the parameter transformation.  If `tqdm` isn't installed, display of the progress bar is skipped.
=> [ParamManager] Added progress bar for get_item/set_item

python/mlc_chat/chat_module.py
This PR lifts the device string parsing (just a few of lines) to a standalone function, so that on the serving side the serving can make use of this function as well.
Tested Python API and it does not seem to incur regression.
=> [Python] Extract common device str parse function in ChatModule

cpp/serve/engine.cc, cpp/serve/request_state.h, python/mlc_chat/serve/engine.py, tests/debug/test_serve_engine.py
This PR introduces the engine for request serving.
The PR includes the C++ side (which is the main implementation of the engine) and the Python side (which is a wrapper class of Engine in C++). This is similar to our implementation of ChatModule.
One test file is added to run text generation for a batch of sequences by directly calling into the Engine methods.
=> [Serving] Serving Engine

python/mlc_chat/cli/benchmark.py
=> Update `benchmark.py` according to #1086

python/mlc_chat/__init__.py, python/mlc_chat/chat_module.py, python/mlc_chat/embeddings/openai.py, python/mlc_chat/gradio.py, python/mlc_chat/interface/openai_api.py, python/mlc_chat/rest.py
The commands I am using are:
```
isort --profile black python/
black python/
```
It is always recommended to format the code before submission, given we don't have a linter CI yet.
=> [Format] Apply isort and black for `python/`

python/mlc_chat/rest.py
fix error introduced by recent code changes
fixes #1116
=> fix mismatched argument name

mlc_llm/core.py, python/mlc_chat/chat_module.py
Add missing docs discovered by #794
=> [Docs] Add doc for max and mean gen len, shift factor; and buildArgs

docs/community/faq.rst, docs/community/guideline.rst, docs/compilation/compile_models.rst, docs/compilation/distribute_compiled_models.rst, docs/compilation/get-vicuna-weight.rst, docs/compilation/python.rst, docs/deploy/android.rst, docs/deploy/cli.rst, docs/deploy/ios.rst, docs/deploy/javascript.rst, docs/deploy/python.rst, docs/deploy/rest.rst
Fixed Grammatical and Typographical Improvements
=> Grammatical and Typographical improvements

cpp/llm_chat.cc, python/mlc_chat/chat_module.py
Some minor enhancements to `ChatModule`, mainly handle the device parsing solely in `_parse_device_str` instead of handling it both in the member function and the `__init__` function to avoid redundancy; and some type annotation fix.
=> Minor enhancements to `ChatModule`

docs/install/tvm.rst
Updating the tvm install docs to assist a user in finding and copying zstd.dll to the correct folder.
=> updating tvm install docs

python/mlc_chat/rest.py
Fixing issue #804. I adopted @WanderingMeow's fix, and verified it works well!
Co-authored-by: WanderingMeow <128711250+wanderingmeow@users.noreply.github.com>
=> [Rest] Fix emoji handling in Rest API.

python/mlc_chat/rest.py
Followup PR of #1142 to document the emoji handling.
cc @junrushao @tqchen
=> [Rest] Document emoji handling

python/mlc_chat/compiler/compile.py, python/mlc_chat/support/auto_target.py
When setting `MLC_MULTI_ARCH`:
When this environment variable is not set:
=> Support CUDA Multi-Arch Compilation

cpp/llm_chat.cc, mlc_llm/core.py
I successfully ran the rwkv-world-3b fp16 model on my Xiaomi phone. This PR is to fix a bug on the main branch where the rwkv model outputs only one word and then stop.
=> fix llm_chat.cc rwkv bug

docs/install/tvm.rst
See https://github.com/mlc-ai/mlc-llm/issues/1135#issuecomment-1793389364
=> [Docs] Clarify zstd installation on Windows

cpp/serve/engine.cc, cpp/serve/sampler.cc
This PR updates the widely used `GetFunction` in engine to pre-stored PackedFuncs. This reduces the overhead of getting packed function using strings every time.
=> [Serving] Replace `GetFunction` uses with pre-stored functions

docs/deploy/rest.rst, python/mlc_chat/interface/openai_api.py
Added documentation for RestAPI endpoints `/v1/completions` and `/v1/chat/completions` parameters and necessary objects.
=> [RestAPI] Added docs

cpp/llm_chat.cc
PR #1203 introduces some unnecessary and redundant logging messages. This PR gets them removed.
=> [Fix] Remove Redundant Warnings

python/mlc_chat/compiler/compile.py
Now it shows a more reasonable upper bound for sequence length = 4096.
```json
{
"_initialize_effect": 0,
"prefill": 3479311360,
"softmax_with_temperature": 0,
"decode": 34531840
}
```
Thanks @MasterJH5574 for helping with the fix!
=> [Fix] Variable Upperbound Should be Injected before Build Pipeline

mlc_llm/relax_model/llama.py
This PR supports the Llama modeling with batched prefill, which can bring higher throughput for the overall prefill process in serving.
Besides, the PR splits the attention function used in batching settings into two separate ones, so that we do not dispatch to the prefill/decode attention functions at runtime.
=> [Llama] Support batched prefill

mlc_llm/core.py
This PR makes the ForceNarrowIndexToInt32 to skip application when batching is enabled.
The reason is because the flattened index of the KV cache append function may exceed the range of int32 when the cache is large. For example, in Llama-7b, when a KV cache supports more than 8192 tokens, the total cache size will be at least
```
8192 * 2 (K/V) * 32 (layers) * 4096 = 2147483648,
```
which reaches the maximum int32 value.
=> [Core] Skip PrimExpr index int32 downcasting for batching

cpp/serve/engine.cc, cpp/serve/function_table.cc, cpp/serve/function_table.h, cpp/serve/model.cc, cpp/serve/request_state.cc, cpp/serve/request_state.h, python/mlc_chat/serve/engine.py, tests/python/serve/benchmark.py, tests/python/serve/evaluate_engine.py, tests/python/serve/test_serve_engine.py
This PR supports the current serving framework with batched prefill, which helps improve the throughput of prefill.
Some data structures are tweaked for less runtime overhead.
This PR also brings the benchmark of serving engine with real-time dataset as input.
=> [Serving] Support batched prefill and benchmark

mlc_llm/relax_model/mistral.py, python/mlc_chat/cli/compile.py, python/mlc_chat/compiler/compile.py, python/mlc_chat/compiler/flags_model_config_override.py, python/mlc_chat/compiler/model/__init__.py, python/mlc_chat/compiler/model/llama/llama_loader.py, python/mlc_chat/compiler/model/llama/llama_model.py, python/mlc_chat/compiler/model/llama/llama_quantization.py, python/mlc_chat/compiler/model/llama_quantization.py, python/mlc_chat/compiler/model/mistral/mistral_loader.py, python/mlc_chat/compiler/model/mistral/mistral_model.py, python/mlc_chat/compiler/model/mistral/mistral_quantization.py, python/mlc_chat/compiler/model/mistral_model.py, python/mlc_chat/compiler/model/model.py, tests/python/model/test_mistral.py
This PR introduces a more concise Mistral implementation using nn.Module for the new compilation flow
cc @CharlieFRuan @junrushao
=> [nn.Module] Mistral implementation

python/mlc_chat/cli/delivery.py, python/mlc_chat/support/download.py
This PR introduces a few enhancements:
- Allow to override temporary path via environment variable `MLC_TEMP_DIR`;
- Add a 10-time retry when uploading the quantized weights to HuggingFace Hub. It could fail at times;
- Echo the commands being used to quantize the models in `logs.txt`;
- Fix a compatibility issue when pulling individual weights down from HuggingFace Hub in Git LFS.
=> Enhance Model Delivery

cpp/serve/engine_state.h
=> [Serving] Minor Tweaks in Detailed Impl

rust/examples/mlc_chat.rs, rust/rustfmt.toml, rust/src/chat_module.rs, rust/src/config.rs, rust/src/lib.rs
This PR does the following enhancements to the Rust code implementation:
- Introduce the `tvm_func_invoke` macro to reduce the repetitive code. The macro dispatches to two cases, and it looks up a PackedFunc in a tvm Module and invokes it with user-provided variadic arguments.
- Add a constructor to `ChatMessage` for ergonomics.
- Add a `rustfmt.toml` to configure the formatting.
- More documentation.
=> [Rust] A few enhancements

python/mlc_chat/rest.py
Add compatibility with OpenAI's streaming API.
fixes #1300
=> Add terminator for streaming REST API

python/mlc_chat/interface/openai_api.py, python/mlc_chat/rest.py, tests/python/api/test_rest.py
- Updated n (number of return sequences) and stop (stop string) parameters for /v1/completions. 
- Added tests for /v1/completions endpoint
=> [RestAPI] Update parameters for /v1/completions and add tests

examples/rest/nodejs/sample_client.js, examples/rest/python/sample_client.py
Recent OpenAI compatibility changes in the REST streaming API broke these examples.
=> fix broken REST examples due to recent compatibility change

python/mlc_chat/serve/__init__.py, python/mlc_chat/serve/entrypoints/openai_entrypoints.py, python/mlc_chat/serve/server/__init__.py, python/mlc_chat/serve/server/__main__.py, python/mlc_chat/serve/server/popen_server.py, python/mlc_chat/serve/server/server_context.py, tests/python/serve/benchmark.py, tests/python/serve/evaluate_engine.py, tests/python/serve/server/conftest.py, tests/python/serve/test_serve_async_engine.py, tests/python/serve/test_serve_engine.py
This PR moves the server-related files to the subdirectory `server/`. The previous `server.py` is now the `__main__.py` file under directory `server/`.
This PR also optimizes a bit on `__init__.py` under the serve namespace.
=> [Serving] Server file movements

docs/compilation/compile_models.rst
- Update compile_models.rst
-  compilation models for iPhone target  must be On MacOS
=> docs(compile_models.rst) 

cpp/conv_templates.cc
=> Add OpenHermes to list of conv templates

cpp/streamer.cc, tests/python/support/test_streamer.py
This PR enhances the TextStreamer to handle more complicated UTF-8 cases, including consecutive emojis, mixture of emojis and invalid characters, etc.
Regression tests are added.
=> [Serving] Enhance TextStreamer for complicated UTF-8 support

python/mlc_chat/interface/openai_api.py, python/mlc_chat/rest.py
This PR adds rest API function calling feature. As per the open AI documentation, the recipe for function api calling is as follows:
> The basic sequence of steps for function calling is as follows:
> 
> - Call the model with the user query and a set of functions defined in the [functions parameter](https://platform.openai.com/docs/api-reference/chat/create#chat/create-functions).
> - The model can choose to call one or more functions; if so, the content will be a stringified JSON object adhering to your custom schema (note: the model may hallucinate parameters).
> - Parse the string into JSON in your code, and call your function with the provided arguments if they exist.
> - Call the model again by appending the function response as a new message, and let the model summarize the results …
=> [REST] OpenAI Rest API compatible function calling

cpp/conv_templates.cc
This PR fixes some issues on conv templates that led to some minor bugs on Mistral and chatml templates based models
cc @CharlieFRuan
=> [Fix] conv templates

ci/bash.sh, ci/jenkinsfile.groovy, ci/task/black.sh, ci/task/build_clean.sh, ci/task/build_lib.sh, ci/task/build_wheel.sh, ci/task/clang-format.sh, ci/task/isort.sh, ci/task/mypy.sh, ci/task/pylint.sh, python/mlc_chat/callback.py, python/setup.py
This PR will only include compilation into CI, and testing is left for future work
=> Establish CUDA CI

python/mlc_chat/compiler/flags_model_config_override.py, python/mlc_chat/compiler/model/gpt_bigcode/gpt_bigcode_loader.py, python/mlc_chat/compiler/model/gpt_bigcode/gpt_bigcode_model.py, python/mlc_chat/compiler/model/gpt_bigcode/gpt_bigcode_quantization.py, python/mlc_chat/compiler/model/model.py
This PR migrates the `gpt_bigcode` architecture to the SLM compilation flow.
cc @CharlieFRuan
=> [SLM] gpt_bigcode migration

docs/community/guideline.rst, docs/compilation/compile_models.rst, docs/compilation/configure_quantization.rst, docs/compilation/define_new_models.rst, docs/compilation/distribute_compiled_models.rst, docs/compilation/python.rst, docs/deploy/android.rst, docs/deploy/cli.rst, docs/deploy/javascript.rst, docs/deploy/python.rst, docs/get_started/mlc_chat_config.rst, docs/index.rst, docs/install/emcc.rst, docs/install/mlc_llm.rst, docs/install/tvm.rst, docs/tutorials/customize/define_new_models.rst, python/mlc_chat/compiler/help.py
This PR is the S1 part of https://github.com/mlc-ai/mlc-llm/issues/1420
=> [Doc][SLM] Update documentation to rollout SLM

cpp/llm_chat.cc, cpp/metadata/model.cc, cpp/metadata/model.h
Still compatible with the former flow
=> [SLM][CLI] cli naming so it matches slm `sliding_window_size`

ios/MLCChat.xcodeproj/project.pbxproj, ios/MLCChat/MLCChat.entitlements, ios/MLCChat/States/AppState.swift, ios/MLCChat/Views/StartView.swift, ios/MLCChat/app-config.json, ios/prepare_params.sh
Also drops the support for add new models as it is fragile atm. Add extended virtual memory option so we can go beyond 4G for q4.
=> [iOS] Update mistral v2 support

python/mlc_chat/compiler/compile.py, python/mlc_chat/compiler/compiler_pass/pipeline.py, python/mlc_chat/compiler/extern/__init__.py, python/mlc_chat/compiler/extern/extern.py, python/mlc_chat/compiler/extern/flashinfer.py, python/mlc_chat/compiler/flags_optimization.py, python/mlc_chat/compiler/model/extern_op.py, python/mlc_chat/compiler/model/llama/llama_model.py, python/mlc_chat/support/auto_target.py
This PR integrates FlashInfer into llama model.
=> Integrate FlashInfer into llama model

python/mlc_chat/cli/delivery.py
Update `delivery.py` to reflect new SLM changes such as `mlc_chat_gen_config` --> `gen_config`.
Include all `gen_config` arguments  (e.g. `sliding_window_size`, etc.); make all of them optional, since that is the case when using `gen_config` directly.
=> [Delivery] Update delivery script

cpp/conv_templates.cc
Small fix on wizard coder and math template.
=> [Smallfix] Fix wizard math template

docs/deploy/javascript.rst, docs/index.rst, docs/prebuilt_models.rst, docs/prebuilt_models_deprecated.rst
Change the prebuilt page to SLM models; still include the previous prebuilt page but deprecated. Will follow up with runtime documentation.
=> [Docs][Prebuilt] Add new prebuilt page

cpp/serve/engine.cc, cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/action_commons.h, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/engine_state.cc, cpp/serve/engine_state.h, cpp/serve/function_table.cc, cpp/serve/function_table.h, cpp/serve/model.cc, cpp/serve/model.h, cpp/serve/request_state.cc, cpp/serve/request_state.h, mlc_llm/relax_model/llama.py, tests/python/serve/benchmark.py
PR apache/tvm#16273 introduces the new KV cache interface. This PR updates the serving framework to align the KV interface changes.
Verified that the performance can align the perf prior to refactor. And all tests can pass.
=> [Serving] Integrate with new KV interface

python/mlc_chat/model/gpt_neox/gpt_neox_model.py, python/mlc_chat/support/tensor_parallel.py
Test commands:
```bash
QUANT=q4f16_1
MODEL_PATH=/PATH/TO/RedPajama-INCITE-Chat-3B-v1
OUTPUT_PATH=./dist/new-red-pajama-${QUANT}/
mkdir -p $OUTPUT_PATH
python -m mlc_chat gen_config $MODEL_PATH/config.json --quantization $QUANT \
--conv-template redpajama_chat -o $OUTPUT_PATH/params --tensor-parallel-shards 2
python -m mlc_chat compile $OUTPUT_PATH/params -o $OUTPUT_PATH/red-pajama.so
python -m mlc_chat convert_weight $MODEL_PATH --quantization $QUANT -o $OUTPUT_PATH/params
python -m mlc_chat.cli.benchmark --model $OUTPUT_PATH/params --model-lib $OUTPUT_PATH/red-pajama.so \
--device "cuda:0" --prompt "What is the meaning of life?" --generate-length 256
```
=> [SLM] Red-pajama Disco support

docs/compilation/define_new_models.rst, docs/index.rst
Update Define New Model Architectures page to include new notebook by @rickzx https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_add_new_model_architecture_in_tvm_nn_module.ipynb
=> [Doc] Update define new models page

python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
PR to fix issue with tensor parallel on bigcode SLM definition, which was preventing bigcode models from compiling
cc @CharlieFRuan
=> [Fix] tp bigcode

python/mlc_chat/compiler_pass/cublas_dispatch.py, python/mlc_chat/compiler_pass/pipeline.py, python/mlc_chat/interface/compile.py
add a pass that dispatch to cublas
=> [SLM] cublas dispatch 

python/mlc_chat/support/auto_weight.py
I'm creating this PR as requested, but I'm unsure how to test it and how to fix the lint issue.
Maintainers, please feel free to make any changes to this PR.
- Resolves #1519
=> Add support for loading weights from a safetensor file

python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py, python/mlc_chat/model/gpt_neox/gpt_neox_model.py, python/mlc_chat/model/llama/llama_model.py, python/mlc_chat/quantization/group_quantization.py, python/mlc_chat/quantization/utils.py, python/mlc_chat/support/tensor_parallel.py
1. support n-dimension tensor sharding
2. remove unnecessary `row`, `col` and `group` field
=> Refactor tensor parallel

python/mlc_chat/interface/compile.py, python/mlc_chat/interface/convert_weight.py, python/mlc_chat/model/llama/llama_quantization.py, python/mlc_chat/model/model.py, python/mlc_chat/op/__init__.py, python/mlc_chat/op/gemm.py, python/mlc_chat/quantization/__init__.py, python/mlc_chat/quantization/ft_quantization.py, python/mlc_chat/quantization/quantization.py
This PR enbales the FasterTransformer quantization of `q4f16_ft`.
=> [SLM] Enable FasterTransformer quantization

python/mlc_chat/model/mistral/mistral_model.py
```
MODEL = "HF://junrushao/Mistral-7B-Instruct-v0.2-q4f16_1-MLC"
TP_SHARDS = 2
from mlc_chat import ChatConfig, ChatModule, callback
from mlc_chat.support import logging
logging.enable_logging()
cm = ChatModule(
MODEL,
device="cuda",
chat_config=ChatConfig(
context_window_size=1024,
prefill_chunk_size=1024,
tensor_parallel_shards=TP_SHARDS,
opt="flashinfer=0;cublas_gemm=1;cudagraph=0",
),
)
cm.generate(
"What is the meaning of life?",
progress_callback=callback.StreamToStdout(callback_interval=2),
)
```
cc: @junrushao @jinhongyii
=> [SLM] Mistral Multi-GPU support

cpp/serve/config.cc, cpp/serve/config.h, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/request_state.cc, cpp/serve/request_state.h, cpp/serve/sampler.cc, python/mlc_chat/protocol/openai_api_protocol.py, python/mlc_chat/serve/config.py, tests/python/serve/server/test_server.py
This PR supports OpenAI-API-compatible frequency penalty and presence penalty. Unit tests are provided.
=> [Serving] Support frequency and presence penalty

python/mlc_chat/serve/engine.py
Following #1508, this PR brings JIT compile to serving.
Locally tested the functionality, and it works pretty well.
=> [Serving] Support JIT compile when model lib lookup failure

python/mlc_chat/model/phi/phi_loader.py, python/mlc_chat/model/phi/phi_model.py, python/mlc_chat/support/auto_config.py
See discussion: https://github.com/mlc-ai/mlc-llm/issues/1567#issuecomment-1883771537
=> Support legacy Phi format: mixformer-sequential

python/mlc_chat/interface/compile.py
A minor fix to the compilation script to allow compilation of non-groupquantized models.
=> [FIX] Fix compilation with non-groupquantized models

cpp/serve/function_table.cc, cpp/serve/request_state.h, python/mlc_chat/model/llama/llama_model.py, python/mlc_chat/nn/__init__.py, python/mlc_chat/nn/kv_cache.py, python/mlc_chat/op/position_embedding.py
This PR supports TIR-kernel-based PagedKVCache modeling and uses it for Llama.
Co-authored-by: Hongyi Jin <jinhongyi02@gmail.com>
Co-authored-by: Bohan Hou <spectrometerh@gmail.com>
=> [Serving] Support TIR kernel for PagedKVCache in Llama

python/mlc_chat/nn/kv_cache.py, python/mlc_chat/op/position_embedding.py
PR #1570 was merged before testing. Some issues are caught during testing and this PR fixes the issues.
Validated that with this fix, the TIR kernels pass end-to-end tests.
=> [Serving] Fix TIR RoPE issue

python/mlc_chat/__main__.py, python/mlc_chat/chat_module.py, python/mlc_chat/cli/chat.py, python/mlc_chat/help.py, python/mlc_chat/interface/chat.py, python/mlc_chat/interface/compiler_flags.py, python/mlc_chat/support/config.py
New Chat CLI! Inspired by https://github.com/mlc-ai/mlc-llm/pull/1293. Thanks @Sing-Li  
```bash
python -m  mlc_chat chat HF://junrushao/Llama-2-7b-chat-hf-q4f16_1-MLC \
--device "cuda:0" \
--overrides context_window_size=1024 \
--opt "O2" 
```
special commands in CLI:
```
/help               print the special commands
/exit               quit the cli
/stats              print out the latest stats (token/sec)
/reset              restart a fresh chat
/set [overrides]    override settings in the generation config. For example,
`/set temperature=0.5;max_gen_len=100;stop=end,stop`
Note: Separate stop words in the `stop` option with commas (,).
Multi-line input: Use escape+enter to start a new line.
```
Co-authored-by: Sing-Li
=> [SLM] Chat CLI

python/mlc_chat/__main__.py, python/mlc_chat/cli/bench.py, python/mlc_chat/help.py, python/mlc_chat/interface/bench.py
```bash
python -m  mlc_chat bench HF://junrushao/Llama-2-7b-chat-hf-q4f16_1-MLC \
--prompt "Introduce yourself" \
--device "cuda:0" \
--overrides context_window_size=1024 \
--opt "O2" 
```
=> [SLM] mlc_chat CLI bench

python/mlc_chat/cli/bench.py
=> [SLM] Fix typo in benchmark

python/mlc_chat/nn/kv_cache.py
Return LSE in TIR PagedKVCache kernels
=> [Serving] Return LSE in TIR PagedKVCache kernels

python/mlc_chat/nn/kv_cache.py
PR #1594 fails to compile and this PR is a hot fix.
=> [Serving] Hotfix TIR kernels for LSE computation

python/mlc_chat/nn/kv_cache.py
=> [Serving] TIR MergeStateInplace kernel

python/mlc_chat/nn/kv_cache.py
BatchPrefillRaggedKVCache TIR kernel
=> [Serving] BatchPrefillRaggedKVCache TIR kernel

cpp/tokenizers.cc
This PR fixes the windows build.
=> [WINDOWS] Fix windows build

python/mlc_chat/nn/kv_cache.py
Vulkan doesn't support shuffle atm
=> [Serving] Fix BatchPrefillPagedKVCache kernel

cpp/serve/engine.cc, cpp/serve/function_table.cc, cpp/serve/function_table.h, cpp/serve/model.cc, cpp/serve/model.h
Remove dynamic cuda allocation in CopyToWorker0 by using a cache
=> [Serving] Remove dynamic allocation in FunctionTable

python/mlc_chat/op/moe_misc.py
This fixed out-of-bound writes.
cc @jinhongyii @junrushao
=> [SLM] Fix impl of get_indices for Mixtral

python/mlc_chat/op/moe_misc.py
Topk func has static thread group size now, which enables compilation on vulkan
=>  Topk func has static thread group size

python/mlc_chat/model/gpt_neox/gpt_neox_model.py, python/mlc_chat/model/phi/phi_model.py, python/mlc_chat/support/tensor_parallel.py
Instructions:
```
MODEL = "HF://junrushao/phi-2-q4f16_1-MLC"
TP_SHARDS = 2
from mlc_chat import ChatConfig, ChatModule, callback
from mlc_chat.support import logging
logging.enable_logging()
cm = ChatModule(
MODEL,
device="cuda",
chat_config=ChatConfig(
context_window_size=1024,
prefill_chunk_size=1024,
tensor_parallel_shards=TP_SHARDS,
opt="flashinfer=0;cublas_gemm=1;cudagraph=0",
),
)
cm.generate(
"What is the meaning of life?",
progress_callback=callback.StreamToStdout(callback_interval=2),
)
```
=> [SLM] Phi Multi-GPU support

cpp/conv_templates.cc, mlc_llm/utils.py, python/mlc_chat/model/model.py, python/mlc_chat/model/qwen/qwen_loader.py, python/mlc_chat/model/qwen/qwen_model.py, python/mlc_chat/model/qwen/qwen_quantization.py
This PR introduces Qwen model (https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py) support using the new nn.Module compilation pipeline. Qwen is a large language model family built by Alibaba Cloud.
```
build/mlc_chat_cli --model models/Qwen-7B-Chat-q4f16_1/params --model-lib-path /ssd1/rickzhou/rick_fork/binary-mlc-llm-libs/Qwen-7B-Chat-q4f16_1-cuda.so
Use MLC config: "/ssd1/rickzhou/rick_fork/mlc-llm/models/Qwen-7B-Chat-q4f16_1/params/mlc-chat-config.json"
Use model weights: "/ssd1/rickzhou/rick_fork/mlc-llm/models/Qwen-7B-Chat-q4f16_1/params/ndarray-cache.json"
Use model library: "/ssd1/rickzhou/rick_fork/binary-mlc-llm-libs/Qwen-7B-Chat-q4f16_1-cuda.so"
You can use the following special commands:
/help               print the special commands
/exit               quit …
```
=> [SLM] Add support for Qwen model

android/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt, android/app/src/main/java/ai/mlc/mlcchat/StartView.kt, android/library/src/main/assets/app-config.json, docs/deploy/android.rst
This PR updates the model record field in android to match with IOS and webllm.
=> [SLM] Android update Model Record Fields

ci/jenkinsfile.groovy, ci/task/build_lib.sh, ci/task/build_wheel.sh, ci/task/test_model_compile.sh
This PR attempts to introduce the CI for Metal and iOS.
=> [CI] Metal and iOS model compilation CI

cpp/serve/config.cc, cpp/serve/config.h, cpp/serve/engine.cc, cpp/serve/engine_actions/action.h, cpp/serve/engine_actions/batch_verify.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/engine_state.cc, cpp/serve/model.cc, python/mlc_chat/model/llama/llama_model.py, python/mlc_chat/nn/__init__.py, python/mlc_chat/nn/kv_cache.py, python/mlc_chat/op/position_embedding.py, python/mlc_chat/serve/async_engine.py, python/mlc_chat/serve/config.py, python/mlc_chat/serve/engine.py, python/mlc_chat/serve/server/__main__.py, tests/python/model/test_kv_cache.py
Following apache/tvm#16456, this PR leverages the RoPE mode and AttentionWithFusedQKV function in llama.
=> [Serving] Use RoPE mode and AttentionWithFusedQKV

docs/deploy/python.rst, docs/install/mlc_llm.rst, python/setup.py
This PR introduces the following minor changes:
- Updated `python/setup.py` to include missing packages (Partially fixes #1626)
- Remaining to update wheels to reflect changes in prebuilt packages
- Update Docs `install/mlc_llm.rst` and `deploy/python.rst` to fix minor package not found errors and remove conflicts in conda install
=> [Fix] MLC LLM Python Package Dependencies and Docs

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, docs/deploy/android.rst
Updates the gradle version from 8.0 to 8.2 so that the project can compile for higher OpenJDK versions (#1653)
=> [Fix] Update Gradle version for Android

docs/deploy/ios.rst, ios/MLCChat/app-config.json, ios/prepare_model_lib.py
refactor `app-config.json` to match #1659 convention
=> [iOS] AppConfig refactor

cpp/serve/sampler.cc
This PR removes unused code in sampler. The code removed was migrated to TVM threading backend a while ago.
=> [Serving] Remove unused code in sampler

python/mlc_chat/model/mixtral/mixtral_model.py, python/mlc_chat/op/moe_misc.py
=> Fuse gating topk and softmax in moe

ci/task/black.sh
This PR updates the CI command for running black
so that required changes are shown.
=> [CI] "black" showing diff for changes

python/mlc_chat/nn/kv_cache.py
When compiling a TensorIR function to ROCm backends, we need to be careful to store and load local registers in a consistent approach (either using vector access or scalar access), or otherwise there will be correctness issue.
This PR fixes the attention kernel for ROCm.
Meanwhile, it brings support for float32 dtype and head dim other than 128.
=> [KVCache] Fix attention kernel for ROCm

mlc_llm/relax_model/llama.py
This PR fixes the Llama compilation failure in the old flow.
* updating the uses of `relax.call_inplace_paked` and other ops to follow the signature in TVM.
* fixing the typo on attention computation introduced by #1536.
=> [Fix] Fix llama model compilation failure

python/mlc_chat/model/baichuan/baichuan_quantization.py, python/mlc_chat/model/gpt2/gpt2_quantization.py, python/mlc_chat/model/gpt_bigcode/gpt_bigcode_quantization.py, python/mlc_chat/model/gpt_neox/gpt_neox_quantization.py, python/mlc_chat/model/llama/llama_quantization.py, python/mlc_chat/model/mistral/mistral_quantization.py, python/mlc_chat/model/mixtral/mixtral_quantization.py, python/mlc_chat/model/model.py, python/mlc_chat/model/phi/phi_quantization.py, python/mlc_chat/model/qwen/qwen_quantization.py, python/mlc_chat/model/qwen2/qwen2_quantization.py, python/mlc_chat/model/stable_lm/stablelm_quantization.py
Related to: https://github.com/mlc-ai/mlc-llm/issues/1780
Tested on Phi, Stable-LM and Qwen models
=> [SLM] Support ft quantization in all SLM models

android/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt, android/library/src/main/assets/app-config.json, android/library/src/main/java/ai/mlc/mlcllm/ChatModule.java, python/mlc_chat/chat_module.py
This PR fixed the model loading error because of argument mismatch. The bug was due to the KVCache config not being passed to the `reload` function in Android.
This should fix issues #1785 and #1741.
=> [BugFix] Fix Model Load in Android

python/mlc_chat/interface/compile.py
Cudagraph is enabled in O3 mode but the flag is not propagated to build config. This fixes it.
cc @Hzfengsy @tqchen
=> [SLM] Enable cuda graph in O3 mode

cpp/llm_chat.cc, ios/MLCChat/app-config.json, python/mlc_chat/chat_module.py
This PR unblocks the iOS version of Gemma. The attention runtime is backed by PagedKVCache on iPhone.
We will follow up and release the iOS app.
=> [iOS][Gemma] Support Gemma on iOS

ios/MLCChat.xcodeproj/project.pbxproj, ios/MLCChat/app-config.json
So it works for gemma build from prebuild binary
=> [iOS] Minor updates to iOS setup

python/mlc_chat/support/preshard.py
Fixed issue that `named_params` is not updated after presharding.
cc @sunggg @tqchen
=> [SLM] Update param names after presharding

python/mlc_chat/nn/kv_cache.py
This PR enables the decode attn kernel to have awareness of the webgpu backend, so that it helps make sure the total number of threads does not exceed the 256 limit of WebGPU.
Co-authored-by: Bohan Hou <spectrometerh@gmail.com>
=> [Attn] Making decode attn kernel be aware of webgpu target

cpp/llm_chat.cc, mlc_llm/core.py, python/mlc_chat/compiler_pass/attach_to_ir_module.py, python/mlc_chat/interface/gen_config.py, python/mlc_chat/model/model.py, python/mlc_chat/model/model_preset.py, python/mlc_chat/model/rwkv5/rwkv5_loader.py, python/mlc_chat/model/rwkv5/rwkv5_model.py, python/mlc_chat/model/rwkv5/rwkv5_quantization.py, python/mlc_chat/nn/rnn_state.py, tests/legacy-python/dump_intermediate.py
This PR adds RWKV5 support with RNNState, a similar interface as PagedAttention.
=> [SLM] RWKV5 World Support

python/mlc_chat/conversation_template.py
Following #1854 , this pr registers the ChatML conversation template.
=>  [Serving] Register the ChatML conversation template

mlc_llm/core.py, mlc_llm/relax_model/commons.py, mlc_llm/relax_model/param_manager.py, mlc_llm/transform/reorder_transform_func.py
This allows it to be used as part of a optimization pipeline specified as a `tvm.ir.transform.Sequential`.
=> [Build] Update transform_params_for_each_rank to IRModule pass

ci/jenkinsfile.groovy
Sometimes scm checkout can timeout, this PR add retry to that
=> [CI] Add retry to scm checkout

python/mlc_chat/nn/kv_cache.py
Prior to this PR, the TIR attention kernels does not cast matmul operands to fp32 before multiplying.
For models like Phi-2 which may have large Q/K/V data (at the level of a few hundreds), the fp16 multiplication exceeds the range of fp16, and lead to attention result being NAN sometimes.
This PR fixes this issue.
=> [Attn] Use float32 accumulation in attention kernel

docs/index.rst
As pointed out by #1830, this PR fixes the Android app download link in docs.
=> [Docs] Update Android APK download link

docs/compilation/compile_models.rst, docs/compilation/convert_weights.rst, python/mlc_chat/model/qwen/qwen_model.py
Support Qwen Model 1.0 PagedKV Cache, and tested with ChatModule generate.
=> [KVCache] Qwen 1.0 Model PagedKV Support

python/mlc_chat/compiler_pass/rewrite_kv_cache_creation.py, python/mlc_chat/model/gpt_bigcode/gpt_bigcode_loader.py, python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
Compilation and runtime smooth. I will open follow-up PRs to enable starcoder2 support in the same model definition file
cc @CharlieFRuan @MasterJH5574
=> [KVCache] Migrate bigcode arch to PagedKVCache

cpp/serve/function_table.cc
=> [Serving] Fix loading presharded weights

python/mlc_chat/nn/kv_cache.py
Manually select better hyper params for TIR PagedAttn kernel on Android.
The old script generates incorrect code when tile_size_per_bdx=1 on Android.
=> [Android] Improve perf of TIR PagedAttn kernel on Android

python/mlc_chat/conversation_template.py
Following #1882, this pr register StableLM3B conversation template for MLC serve.
=> [Serving] Register the StableLM3B conversation template

cpp/serve/engine.cc, cpp/serve/engine_actions/action.h, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/batch_draft.cc, cpp/serve/engine_actions/batch_verify.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/function_table.cc, cpp/serve/function_table.h, cpp/serve/model.cc, cpp/serve/model.h, cpp/serve/sampler/cpu_sampler.cc, cpp/serve/sampler/gpu_sampler.cc, cpp/serve/sampler/sampler.h, python/mlc_llm/compiler_pass/attach_embedding_allocator.py, python/mlc_llm/compiler_pass/attach_logit_processor.py, python/mlc_llm/compiler_pass/attach_sampler.py, python/mlc_llm/compiler_pass/attach_support_info.py, python/mlc_llm/compiler_pass/pipeline.py
This PR introduces the GPU sampler for CUDA only. The GPU sampler makes use of the GPU sampling ops introduced in apache/tvm#16575.
We will follow up to benchmark the performance of the GPU sampler over CPU sampler.
=> [Serve] Introducing GPU sampler for CUDA

cpp/llm_chat.cc
This PR is a fix to address #1952.
=> [Fix] Fix embedding shape check in ChatModule

python/mlc_llm/support/download.py
Prior to this PR, when running commands like
```shell
python3 -m mlc_chat chat HF://mlc-ai/gemma-7b-it-q4f16_2-MLC
```
only the binary weight files are downloaded, among all the Git LFS files.
For models like Gemma whose tokenizer is large and also in Git LFS file, the tokenizer files are not effectively downloaded automatically. For example, the cloned Gemma `tokenizer.json` file has content
```
version https://git-lfs.github.com/spec/v1
oid sha256:05e97791a5e007260de1db7e1692e53150e08cea481e2bf25435553380c147ee
size 17477929
```
and this content is never realized to the actual tokenizer. This will lead to the issue of #1913.
This PR fixes the issue by pulling all the Git LFS files that are not binary files.
=> [Fix] Fetching the Git-LFS tokenizer files

python/mlc_llm/op/moe_misc.py
Thanks @masahi for reporting this
=> [Model] Use static hidden size in mixtral scatter_output

cpp/serve/model.cc
PR apache/tvm#16738 updated the Allocator signature. This PR updates the caller side accordingly.
=> [Fix] Fix serve model to adapt the latest Allocator signature

python/mlc_llm/interface/compile.py, python/mlc_llm/interface/compiler_flags.py, python/mlc_llm/model/mixtral/mixtral_model.py, python/mlc_llm/nn/expert.py, python/mlc_llm/op/cutlass.py, python/mlc_llm/op/extern.py
=> [Model] Use optimized group gemm for Mixtral

python/mlc_llm/op/moe_misc.py
This PR fixes the malformed MoE TIR scripts.
=> [Model] Fix the top-k TIR script for well-formedness

python/mlc_llm/compiler_pass/attach_sampler.py
=> Fix invalid use of dataflow var in sampler output

python/mlc_llm/quantization/awq_quantization.py, python/mlc_llm/quantization/ft_quantization.py, python/mlc_llm/quantization/group_quantization.py, python/mlc_llm/quantization/utils.py
This PR skips quantizing the MoE gate layer.
=> [Quantization] Skip MoE gate layer

python/mlc_llm/model/gemma/gemma_model.py, python/mlc_llm/model/gpt2/gpt2_model.py, python/mlc_llm/model/gpt_bigcode/gpt_bigcode_model.py, python/mlc_llm/model/gpt_neox/gpt_neox_model.py, python/mlc_llm/model/llama/llama_model.py, python/mlc_llm/model/mistral/mistral_model.py, python/mlc_llm/model/orion/orion_model.py, python/mlc_llm/model/phi/phi_model.py, python/mlc_llm/model/qwen2/qwen2_model.py
=> [Model] Add missing broadcast of logit_position for multigpu

python/mlc_llm/interface/convert_weight.py, python/mlc_llm/loader/huggingface_loader.py, python/mlc_llm/support/preshard.py
This change the behavior of presharding by apply presharding after quantization. This makes the behavior consistent with or without presharding
cc @tqchen @csullivan
=> [Preshard] apply presharding after quantization

python/mlc_llm/model/baichuan/baichuan_model.py
This pr enable TP function of Baichuan2 model.
=> [SLM] Baichuan Multi-GPU support

python/mlc_llm/compiler_pass/lift_global_buffer_alloc.py
This PR fixes the GlobalVar struct info mismatch issue cased by pass LiftGlobalBufferAlloc after a latest TVM commit.
=> [Pass] Fix LiftGlobalBufferAlloc for proper GlobalVar struct info

python/mlc_llm/compiler_pass/attach_support_info.py, python/mlc_llm/compiler_pass/pipeline.py, python/mlc_llm/interface/compile.py
=> [Pipeline] Insert hints to enable cuda graph symbolic capture

cpp/loader/multi_gpu_loader.cc
=> [Loader] Print message when multi-GPU loader is finished

cpp/serve/logit_processor.cc, cpp/serve/sampler/gpu_sampler.cc
This PR introduces copy stream to LogitProcessor and GPUSampler for CUDA, so that auxiliary data can be copied on a separate stream and overlap with the computation time.
=> [Serving] Support copy stream in LogitProcessor and GPUSampler

python/mlc_llm/model/stable_lm/stablelm_model.py
This pr enable TP function of Stablelm model.
=> [SLM] Stablelm Multi-GPU support

python/mlc_llm/nn/kv_cache.py
This PR introduces the single page copy TIR function for KV cache. This function is helpful for sequence fork at specified positions.
NOTE: this PR is a breaking change, so you will need to re-compile your model and update TVM or the MLC-AI pip package to the latest.
Related PR: apache/tvm#16813
Co-authored-by: Yaxing Cai <caiyaxing666@gmail.com>
=> [KVCache] Introducing single page copy func for KV cache fork

docs/deploy/rest.rst
https://github.com/mlc-ai/mlc-llm/issues/2059
=> [Docs] Fix docs for python server and rest call

cpp/llm_chat.cc, python/mlc_llm/interface/gen_config.py, python/mlc_llm/model/model.py, python/mlc_llm/model/rwkv6/rwkv6_loader.py, python/mlc_llm/model/rwkv6/rwkv6_model.py, python/mlc_llm/model/rwkv6/rwkv6_quantization.py
This PR adds RWKV6 support and tokenizer for RWKV vocab.
=> [SLM] Add support for RWKV6 model 

cpp/streamer.cc, python/mlc_llm/conversation_template.py
- Add check for empty stop string
- Fix VanillaLM conversation template
=> [Serve] Bugfix for empty stop string 

python/mlc_llm/model/internlm/internlm_model.py
This pr enable TP function of Internlm model.
=> [SLM] Internlm Multi-GPU support

python/mlc_llm/model/qwen/qwen_model.py
This pr enable TP function of Qwen model.
=>  [SLM] Qwen Multi-GPU support

tests/python/serve/test_grammar_parser.py, tests/python/serve/test_grammar_state_matcher_custom.py
This PR fixes some grammar parser tests that were broken.
=> [Grammar] Fix broken grammar tests

python/mlc_llm/conversation_template.py
As reported and discussed in #2086, this PR fixes the RedPajama template.
=> [Conversation] Fix RedPajama conversation template

cpp/serve/engine_actions/batch_decode.cc, python/mlc_llm/serve/engine_base.py
This PR enhances the robustness, which had issue when the KV capacity is small.
=> [Serving] Enhance robustness with small KV capacity

docs/index.rst, docs/install/mlc_llm.rst
This PR clarifies the vulkan loader dependecy.
Some system may not have the right vulkan loader
and we need to install them via conda.
=> [DOCS] Clarify vulkan loader dependency

python/mlc_llm/quantization/utils.py
This PR fixes weight conversion on the platform with OpenCL device(ex: OrangePi).
=> [Quantization] Add OpenCL device

python/mlc_llm/serve/engine.py, python/mlc_llm/serve/engine_base.py, python/mlc_llm/serve/entrypoints/openai_entrypoints.py, tests/python/serve/test_serve_async_engine.py, tests/python/serve/test_serve_engine.py
The previous refactoring PR formalizes the MLC serve Python API but does not respect the `stream` flag properly: no matter if `stream` is True or False, the functions always work in a streaming style. This PR supports the non-stream case.
=> [Serving] Support stream=True for Python API

python/mlc_llm/model/gemma/gemma_model.py
This is in line with the implementation in the [transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma/modeling_gemma.py#L183) library. Also, the [gemma-1.1](https://huggingface.co/google/gemma-1.1-2b-it/blob/main/config.json#L10) model config.
=> [Model] Use tanh approximation of GeLU in Gemma MLP

python/mlc_llm/support/auto_target.py
=> Revert "Allow "mlc_llm --host" option to override host triple the model compi…"

python/mlc_llm/op/moe_misc.py
This updates mixtral to use relax ops for topk and cumsum so that the workspace can be managed by relax via the dispatch pass.
cc @tqchen @yongwww
=> [Model] Use R.topk/cumsum for mixtral

python/mlc_llm/serve/engine_base.py
This PR revamps the logging info for engine mode selection to provide more detailed information and the rationale of different modes.
Right now, the logging info under different engine modes are:
```
[2024-04-12 21:44:44] INFO engine_base.py:395: Under mode "local", max batch size is set to 4, max KV cache token capacity is set to 4096, prefill chunk size is set to 4096. We choose small max batch size and KV cache capacity to use less GPU memory.
[2024-04-12 21:44:46] INFO engine_base.py:395: Under mode "interactive", max batch size is set to 1, max KV cache token capacity is set to 4096, prefill chunk size is set to 4096. We fix max batch size to 1 for interactive single sequence use.
[2024-04-12 21:44:47] INFO engine_base.py:395: Under mode "server", max batch size is set to 80, max KV …
```
=> [Serving] Revamp engine mode selection logging info

python/mlc_llm/model/chatglm3/chatglm3_model.py
This pr enable TP function of Chatglm3 model.
=> [SLM] Chatglm3 Multi-GPU support

docs/get_started/introduction.rst, docs/index.rst
Some minor tweaks on the introduction doc
=> [DOCS] Update introduction

python/mlc_llm/conversation_template.py
=> [Fix] Fix llama 3 conv template

README.md, docs/deploy/cli.rst, docs/get_started/introduction.rst
This PR updates README for Llama3 quick start examples.
=> [Docs] Update README

cpp/serve/engine_actions/action_commons.h, cpp/serve/event_trace_recorder.h, cpp/serve/grammar/grammar_serializer.h, docs/deploy/python_engine.rst, docs/get_started/introduction.rst, python/mlc_llm/serve/engine_base.py, python/mlc_llm/serve/event_trace_recorder.py, python/mlc_llm/testing/debug_chat.py
This PR completes the documentation page of LLMEngine and AsyncLLMEngine in our Python API.
=> [Docs] Documentation of LLMEngine in Python API

README.md, docs/deploy/python_engine.rst, docs/index.rst, site/index.md
This PR mainly updates the project website, and also updates some minor points for other docs.
=> [Docs] Update project website

docs/requirements.txt, scripts/build_mlc_for_docs.sh, scripts/build_site.sh, scripts/gh_deploy_site.sh
This PR fixes the issue of the API reference not displayed in the documentation.
=> [Docs] Fix API reference not displayed

python/mlc_llm/nn/kv_cache.py
It improves 2x time for tir based page attention for opencl adreno.
=> [PYTHON][KVCACHE] Enhance the thread limit for opencl

python/mlc_llm/serve/engine_base.py
This PR removes the imports of functions in `cli.model_metadata` from engine_base.py. The file `cli.model_metadata` is not designed for import directly, and when importing functions from the file, it repetitively reports warnings of
```
RuntimeWarning: 'mlc_llm.cli.model_metadata' found in sys.modules after
import of package 'mlc_llm.cli', but prior to execution of
'mlc_llm.cli.model_metadata'; this may result in unpredictable behaviour
```
=> [Serving] Remove `cli.model_metadata` import from engine base

cpp/serve/sampler/gpu_sampler.cc
This PR adds the early exit for the GPU sampler, which ran into GPU kernels even when the batch size is 0 prior to this commit.
The 0 batch size case can happen when parallel generation of a request and engine preemption exists. In this case, the GPU sampler should just synchronization and return, and not run into any GPU kernel.
=> [Sampler] Fix GPU sampler behavior when batch size is 0

cpp/serve/sampler/gpu_sampler.cc
This PR integrates the sampling function in FlashInfer. We integrate the one without top-p for now.
=> [Sampler] FlashInfer sampling func integration

python/mlc_llm/cli/lib_delivery.py
This PR adds support for automatic model library compilation. 
Usage:
```
python python/mlc_llm/cli/lib_delivery.py --spec model_lib_delivery_example.json
```
where
```model_lib_delivery_example.json
{
"binary_libs_dir": "./dist/prebuilt_libs/",
"default_quantization": ["q4f16_1"],
"default_compile_options": [
{
"device": "cuda",
"overrides": {
"context_window_size": 4096
}
}
],
"tasks": [
{
"model_id": "Llama-2-7b-chat-hf",
"model": "./dist/Llama-2-7b-chat-hf-q4f16_1-MLC",
"quantization": ["q4f32_1"],
"compile_options": [
{
"device": "android",
"overrides": {
"context_window_size": 768
}
}
]
},
{
"model_id": "phi-2",
"model": "https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC"
}
]
}
```
=> Model Library Delivery

cpp/serve/engine_actions/batch_verify.cc, cpp/serve/engine_actions/eagle_batch_verify.cc, cpp/serve/engine_state.cc, cpp/serve/engine_state.h, cpp/serve/threaded_engine.cc, cpp/serve/threaded_engine.h, python/mlc_llm/serve/engine_base.py, python/mlc_llm/serve/entrypoints/debug_entrypoints.py
=> [Serving] Add engine stats for speculative decoding

python/mlc_llm/cli/serve.py, python/mlc_llm/compiler_pass/attach_spec_decode_aux_funcs.py, python/mlc_llm/compiler_pass/pipeline.py
=> [Eagle] Fix missing broadcast in hidden states gather/scatter

python/mlc_llm/model/llava/llava_model.py
This PR removes the unused import in llava model to fix lint.
=> [Model] Remove unused import to fix lint

cpp/serve/engine_actions/batch_verify.cc
This PR fixes a bug in the BatchVerify action.
When a draft model's proposal is fully accepted by the main model, there is an extra token which is already in the main model's KV cache but not in the draft model's KV cache.
Prior to this PR, BatchVerify action does not feed this extra token into the draft model's KV cache, which causes size mismatch between the main model's KV cache and draft model's KV cache.
This PR fixes this issue by adding an additional BatchDecode step for the requests whose draft proposals are fully accepted by the main model.
=> [Serving] Fix BatchVerify to feed the extra token when fully accepted

cpp/serve/engine_actions/eagle_batch_verify.cc
This is a follow up of https://github.com/mlc-ai/mlc-llm/pull/2285 to apply the same fix to eagle
cc @tqchen @MasterJH5574
=> [Eagle] Run additional decode for draft model when all proposals are accepted

python/mlc_llm/compiler_pass/fuse_dequantize_matmul_ewise.py, python/mlc_llm/nn/kv_cache.py, python/mlc_llm/support/auto_target.py
1. Improved tir schedule of page attention (It improved 40% to this function).
2. Enable missing dequant+matmul fusion when 3 elementwise op followed by matmul.  (it will improve "ph-2 model" to 2x improvement.)
=> [KVCACHE][TIR] Improved tir schedule for decode tir page attention

python/mlc_llm/interface/compile.py
=> Enable cuda graph for batch_verify

docs/deploy/android.rst
Avoid showing full tree and mention what the dist/lib/mlc4j stands for
=> [DOCS] Update android doc

cpp/serve/engine_actions/eagle_batch_draft.cc, cpp/serve/engine_actions/eagle_batch_verify.cc, cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/model.cc, cpp/serve/model.h, python/mlc_llm/model/llama/llama_model.py
=> [Model] Removing unnecessary reshapes in get_logits

docs/deploy/android.rst
This PR sets a more clear instruction for android JDK setup
=> [DOCS] More clear android instruction

cpp/serve/engine_actions/batch_prefill_base.cc, cpp/serve/engine_actions/batch_prefill_base.h, cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/engine_actions/new_request_prefill.cc
This extracts common part of `NewRequestPrefill` and `EagleNewRequestPrefill` to a bass class `BatchPrefillBaseActionObj`.
Part of the changes is extracted from #2295 
Co-Authored-By: Yaxing Cai \<caiyaxing666@gmail.com\>
cc @tqchen @cyx-6
=> [Serving] Refactor to consolidate new request prefill

ios/MLCSwift/Sources/Swift/LLMEngine.swift
Created a struct (`ChatCompletionRequest`) as `chatCompletion`'s input.
Converted the struct to json before invoking engine for completion.
=> Added structured input for chatCompletion in LLMEngine

cpp/json_ffi/openai_api_protocol.cc, cpp/json_ffi/openai_api_protocol.h, ios/MLCEngineExample/MLCEngineExample/MLCEngineExampleApp.swift, ios/MLCSwift/Sources/Swift/LLMEngine.swift, ios/MLCSwift/Sources/Swift/OpenAIProtocol.swift
This PR modifies the MLCEngine chatCompletion to take in structured data.
=> [iOS] Make MLCEngine input to take in structured data

cpp/metadata/model.cc, cpp/metadata/model.h, cpp/serve/config.cc, cpp/serve/config.h, cpp/serve/engine.cc, cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/action_commons.h, cpp/serve/engine_actions/batch_prefill_base.cc, cpp/serve/engine_actions/batch_prefill_base.h, cpp/serve/engine_actions/eagle_batch_verify.cc, cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/function_table.cc, cpp/serve/model.cc, cpp/serve/model.h, python/mlc_llm/cli/serve.py, python/mlc_llm/interface/compile.py, python/mlc_llm/interface/serve.py, python/mlc_llm/model/medusa/medusa_loader.py, python/mlc_llm/model/medusa/medusa_model.py, python/mlc_llm/model/medusa/medusa_quantization.py, python/mlc_llm/model/model.py, python/mlc_llm/serve/config.py, python/mlc_llm/serve/engine.py, python/mlc_llm/serve/engine_base.py, python/mlc_llm/testing/debug_chat.py
cc @yongwww @tqchen @MasterJH5574
=> [Serving] Add Medusa speculative decoding

python/mlc_llm/compiler_pass/cublas_dispatch.py
=> Fix cublas offloading

cpp/llm_chat.cc, cpp/serve/function_table.cc
A minor update in response to the recent changes in TVM: https://github.com/apache/tvm/pull/16993
@tqchen @vinx13
=> Add false for arg worker0_only in disco.empty

cpp/json_ffi/json_ffi_engine.cc, python/mlc_llm/json_ffi/engine.py
1. Refactor init_background_engine in JSONFFIEngine to use device_type and device_id arguments.
2. request_stream_callback is called on each string of the array of strings.
=> [JSONFFIEngine] Refactor device argument and request_stream_callback argument

cpp/json_ffi/json_ffi_engine.cc, ios/MLCSwift/Sources/ObjC/LLMEngine.mm, ios/MLCSwift/Sources/Swift/LLMEngine.swift
This PR updates the MLCEngine API to latest JSON FFI convention.
=> [iOS] Update MLCEngine API to latest JSON FFI convention

cpp/serve/config.cc
This PR fixes the automatic engine config inference which did not respect the sliding window size, which led to memory usage higher than expected in the interactive mode for mistral model.
=> [Fix][Serving] Respect sliding window size in config inference

cpp/serve/engine.cc, cpp/serve/engine_actions/action.h, cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/batch_prefill_base.cc, cpp/serve/engine_actions/batch_prefill_base.h, cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/request_state.h
This PR supports the prefill conditions with sliding window awareness. Now when the input length is larger than the sliding window size, the prefill can still be processed without error.
=> [Serving] Sliding-window-aware request prefill

ios/MLCEngineExample/MLCEngineExample/MLCEngineExampleApp.swift, ios/MLCSwift/Sources/Swift/LLMEngine.swift
It also refactors the MLCSwift to be follow
engine.chat.completions.create style as per
other OpenAI APIs.
It also removes the cyclic dependencies in
the closure capture by having a separate EngineState
=> [iOS] Update MLCSwift to fully follow OAI style.

cpp/serve/logit_processor.cc
add nvtx info in Update of logic_processor
cc: @tqchen @vinx13 @cyx-6
=> Add nvtx in logic update

python/mlc_llm/json_ffi/engine.py
Noticed this when researching #2383
=> [FIX] Typo on OpenAI Chat class in engine

android/mlc4j/prepare_libs.py, docs/compilation/package_libraries_and_weights.rst, python/mlc_llm/cli/package.py, python/mlc_llm/interface/help.py, python/mlc_llm/interface/package.py
This PR fixes the mlc llm source dir argument
in android packaging.
=> [FIX] Fix mlc llm source dir argument

python/mlc_llm/serve/sync_engine.py
This PR updates the missange change in engine ffi func name from #2390.
=> [Fix] Update missing change in engine ffi func name

cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/prefix_cache.cc, cpp/serve/prefix_cache.h, tests/python/serve/test_serve_engine_prefix_cache.py
This PR fixes the no prefix cache, to avoid double adding of new sequence.
=> [Fix] Fix no prefix cache

python/mlc_llm/serve/engine_base.py
Hello,
This PR will fix attr not exists error when running with `mlc_llm serve ...` .
=> add hasattr safecheck for MLCEngineBase

python/mlc_llm/serve/engine_base.py
This PR fixes a format issue caused by #2400.
=> [Fix] Fix format issue of MLCEngineBase

cpp/json_ffi/json_ffi_engine.cc, cpp/serve/config.cc, cpp/serve/config.h, cpp/serve/engine.cc, cpp/serve/model.h, cpp/serve/sampler/sampler.h, cpp/serve/threaded_engine.cc
This PR enables a centralized validation logic in GenerationConfig.
=> [REFACTOR] Enable validation logic in GenerationConfig

cpp/serve/radix_tree.cc
#2183
I find that `RadixPage` fits more for this struct's name.
=> Change name RedixPage -> RadixPage in RadixTree.cc

cpp/serve/sampler/gpu_sampler.cc, cpp/serve/sampler/sampler.h, python/mlc_llm/compiler_pass/attach_sampler.py, python/mlc_llm/compiler_pass/pipeline.py
It's WIP as waiting for the TVM compiler support
=> [Serving] Enable GPU Sampling

python/mlc_llm/support/constants.py, python/mlc_llm/support/download.py
This PR renames MLC_LLM_READONLY_WEIGHT_CACHES=>MLC_LLM_READONLY_WEIGHT_CACHE to be consistent with rest of env var convention
=> [REFACTOR] Rename MLC_LLM_READONLY_WEIGHT_CACHES

python/mlc_llm/chat_module.py, python/mlc_llm/cli/delivery.py, python/mlc_llm/interface/package.py, python/mlc_llm/serve/engine_base.py, python/mlc_llm/support/auto_config.py, python/mlc_llm/support/constants.py, python/mlc_llm/support/download_cache.py
This PR renames download to download_cache for better clarity.
=> [REFACTOR] Terminology download=>download_cache

cpp/serve/threaded_engine.cc, ios/MLCChat/MLCChat/States/AppState.swift, ios/MLCChat/MLCChat/States/ChatState.swift, ios/MLCChat/mlc-package-config.json
This PR fixes rare deadlock cases when engine unload/reload
=> [BUGFIX] Fix rare deadlock in threaded engine

README.md, docs/get_started/introduction.rst, docs/index.rst, site/_includes/hero.html, site/index.md
This PR simplifies readme so most attention
can be pointed to our docs page.
=> [DOCS] Simplify read me

python/mlc_llm/cli/model_metadata.py, python/mlc_llm/interface/compile.py
This PR removes the KV cache size from model metadata. This is because we have fully switched to the new compilation flow with PagedKVCache and MLCEngine as backend, where KV cache size is runtime dependent and will be estimated at runtime.
=> [Metadata] Remove stale KV cache size

ios/MLCChat/MLCChat/States/ChatState.swift, ios/MLCEngineExample/MLCEngineExample/MLCEngineExampleApp.swift, ios/MLCEngineExample/mlc-package-config.json, ios/MLCSwift/Sources/Swift/LLMEngine.swift
This PR updates all MLCSwift APIs to be async
for consistency purposes.
=> [iOS] Update the MLCSwift APIs to async

python/mlc_llm/serve/engine_base.py, tests/python/serve/server/test_server.py
This PR fixes some server tests which were broken due to recent refactors.
=> [Fix][REST] Fix usage-related server tests

android/mlc4j/CMakeLists.txt, android/mlc4j/prepare_libs.py
This PR add a few patches to enable build under windows
=> [ANDROID] Patches to enable windows usescase

docs/deploy/android.rst, python/mlc_llm/serve/engine.py
This PR updates the URL of the Android APK.
cc @tqchen
=> [DOCS] Updates the URL of the Android APK

ci/task/build_lib.sh
This PR updates the CI CUDA build script with FlashInfer compile options after a recent bump of FlashInfer version.
=> [CI] Update CUDA build script with FlashInfer options

ci/bash.sh, ci/jenkinsfile.groovy, ci/task/pylint.sh, ci/task/test_unittest.sh, tests/python/conftest.py
This PR enables GPU env in ci docker/bash.sh
=> [CI] Enable GPU env in CI 

cmake/gen_cmake_config.py
This PR updates the config.cmake generation script to provide the FlashInfer compile options explicitly.
=> [CMake] Update config.cmake generation script

python/mlc_llm/bench/metrics.py, python/mlc_llm/bench/prompts.py, python/mlc_llm/bench/request.py
Address the comments in https://github.com/mlc-ai/mlc-llm/pull/2474.
@tqchen
=> [Bench] Add seed to __init__ and some minor change

cpp/serve/sampler/gpu_sampler.cc
This PR improves the check in GPU sampler for whether FlashInfer is enabled. Previously we did not check the CUDA compute capability, which makes the GPU sampler not able to properly run on Colab where the T4 GPU has a compute version of 7.5 which FlashInfer does not support.
With this PR, when the compute capability is less than 8.0, we will not use FlashInfer in GPU sampler.
=> [Sampler] Enhance checks for whether FlashInfer is enabled

android/MLCChat/mlc-package-config.json, docs/deploy/android.rst
This PR updates the default mode list for Android App and the APK link in the document.
cc @tqchen
=> [Android] Updates the default mode list and the APK link in the document

cpp/serve/threaded_engine.cc, ios/MLCChat/MLCChat/States/AppState.swift, ios/MLCChat/MLCChat/States/ChatState.swift
This PR reapplies #2429, which is missing in the main branch.
Below is the original commit message:
This PR fixes rare deadlock cases when engine unload/reload
=> [Reapply][BUGFIX] Fix rare deadlock in threaded engine (#2429)

docs/deploy/android.rst
Android project path corrected
=> Corrected the folder path for Android Studio Project

ios/MLCChat/MLCChat.xcodeproj/project.pbxproj, ios/MLCChat/MLCChat/States/ChatState.swift, ios/MLCChat/MLCChat/Views/ChatView.swift, ios/MLCChat/mlc-package-config.json
his PR corrects the mistral q3 url
This PR also add a handler for screen switch off.
For now we just reset if the app is generating,
we will update to pause/resume once they are supported.
=> [iOS] correct mistral q3 url and handle screen switch off

python/mlc_llm/bench/metrics.py, python/mlc_llm/bench/prompts.py, python/mlc_llm/bench/request.py
Use aiohttp as default client for request. 
cc: @tqchen
=> [Bench] Defaults to aiohttp client, add ServerMetrics

android/mlc4j/prepare_libs.py
This PR fixes the TVM_SOURCE_DIR parsing issue on Windows.
=> [Android] Remove var capture in TVM_SOURCE_DIR

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py, python/mlc_llm/nn/kv_cache.py, python/mlc_llm/op/tree_attn.py
This PR fixes the TIR prefill attention kernels to support a broader list of GQA group sizes.
=> [Attention] Fix attn kernel for general GQA group size

python/mlc_llm/nn/kv_cache.py, python/mlc_llm/op/tree_attn.py
This PR fixes TIR issues in the attn kernels.
=> [Fix] Fix attn kernel build issue

ios/MLCChat/mlc-package-config.json
This PR add Qwen2 support to MLC Chat
=> [iOS] Add Qwen2 support

android/MLCChat/mlc-package-config.json, docs/deploy/android.rst
=> [Android] Add Qwen2 support

python/mlc_llm/cli/delivery.py
Some improvements of the delivery script:
- provide different overrides for different quantization. e.g. we can change prefill chunk size for q0/q3/q4
- rerun gen config only if only conv_template changes
- do NOT recreate HF repo when the repo already exists. This will preserve commit history
- dry-run validation
=> Update model delivery script

python/mlc_llm/bench/prompts.py, python/mlc_llm/bench/request.py
This PR refactors mlc bench to enable json mode in dataset.
cc: @yongwww
=> [Bench] Json mode bench

python/mlc_llm/op/moe_misc.py
This PR introduces a top-4 kernel for MoE model (particularly for the Qwen-MoE) at this moment.
This is still a manual implementation and has some duplication with the existing top-2 kernel. In the future we'll consider leveraging meta-programming of TIR to unify the top-k kernel implementations.
=> [Op] Top-4 implementation for MoE model

android/mlc4j/CMakeLists.txt, android/mlc4j/src/cpp/tvm_runtime.h, cpp/loader/multi_gpu_loader.cc, cpp/serve/engine.cc
This PR updates the Android app the reduce the binary size. Right now it can be reduced to 108MB when only building with the Phi-3-mini-4k model.
=> [Android] Reduce binary size

python/mlc_llm/model/gemma/gemma_model.py
This PR fixes the Gemma config compatibility issue.
=> [Fix] Gemma hidden_activation compatibility

cpp/serve/engine_actions/batch_prefill_base.cc
This PR fixes a bug of the prefill chunking which may cause the running batch size exceeding the maximum allowed batch size.
=> [Fix] Fix the chunked prefill condition

python/mlc_llm/model/internlm2/internlm2_model.py
This PR enable TP function of internlm2 model.
=> [SLM] Internlm2 Multi-GPU support

cpp/serve/engine_actions/new_request_prefill.cc
This PR supports merging multiple token embedding lookup into a single one, since each token embedding lookup needs to go through the model, and multiple lookup will introduces extra overhead.
=> [Serving] Merge multiple token embedding lookup into one

python/mlc_llm/model/model_preset.py
InternLM2.5 series that have outstanding features were released just days ago, and this PR support Internlm2.5 by adding model preset of internlm_2_5_7b.
=> [Model] Support Internlm2.5

cpp/tokenizers/tokenizers.cc
This PR fixes the issue where the tokenizer would fail in decoding tokens for ByteLevel BPE when the token is not recognized by ByteLevel. E.g. in decoding,
```
"hello" -> "hello" (recognized by ByteLevel)
"Ġthere" -> " there" (recognized by ByteLevel)
"\n" -> fail, not recognized by ByteLevel
"\u203c" -> fail, not recognized by ByteLevel
```
This PR adds the logic that in decoding, when the token is not recognized by ByteLevel, the original token will be returned. Then
```
"hello" -> "hello" (recognized by ByteLevel)
"Ġthere" -> " there" (recognized by ByteLevel)
"\n" -> "\n" (not recognized by ByteLevel)
"\u203c" -> "\u203c" (not recognized by ByteLevel)
```
This behavior is align to huggingface tokenizers.
=> [Fix][Tokenizer] Fix failure in decoding tokens for ByteLevel BPE

cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/batch_prefill_base.cc, cpp/serve/prefix_cache.cc, cpp/serve/request_state.cc, cpp/serve/request_state.h, cpp/tokenizers/streamer.cc, cpp/tokenizers/streamer.h
This PR optimizes the post-process overhead and adds more detailed nvtx instruments.
=> [Engine] Reduce action post-process overhead

python/mlc_llm/model/starcoder2/starcoder2_loader.py, python/mlc_llm/model/starcoder2/starcoder2_model.py, python/mlc_llm/model/starcoder2/starcoder2_quantization.py
This PR supports TP function of starcoder2 and fixes two typos.
=>  [SLM] Starcoder2 Multi-GPU support

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py, python/mlc_llm/conversation_template/llama.py, python/mlc_llm/interface/gen_config.py, python/mlc_llm/model/llama/llama_model.py, python/mlc_llm/nn/kv_cache.py, python/mlc_llm/op/position_embedding.py, python/mlc_llm/op/tree_attn.py
This PR supports the [Llama3.1](https://huggingface.co/collections/meta-llama/llama-31-669fc079a0c406a149a5738f) family.
Particularly we introduced the conversation template and RoPE scaling for Llama3.1. In the future we will bring the support of more RoPE scaling.
=> [Model] Support Llama3.1

python/mlc_llm/compiler_pass/fuse_add_norm.py
This PR revamps the FuseAddRMSNorm pass with manual pattern matching, in purpose of avoiding `rewrite_bindings` which is recursive and may cause unaffordable time when the model is large.
=> [Pass] Rewrite FuseAddRMSNorm to avoid binding rewrite recursion

cpp/serve/config.cc, cpp/serve/config.h, cpp/serve/engine.cc, cpp/serve/engine_actions/batch_prefill_base.cc, python/mlc_llm/serve/config.py, tests/python/serve/test_serve_sync_engine.py
This PR exposes the option of prefill mode to chunked prefill or hybrid prefill with split fuse decode.
=> [Serve] Expose prefill mode option

cpp/serve/engine_actions/batch_prefill_base.cc
This PR fixes the #2701 when the prefill mode is chunked but the prefill requests are not collected.
=> [Fix] Fix hybrid prefill disabled

python/mlc_llm/interface/compiler_flags.py
=> Turn on custom allreduce by default in O3

cpp/serve/engine_actions/new_request_prefill.cc
This PR fixes the index error when hybrid prefill is enabled.
=> [Fix] Fix hybrid prefill index error

cpp/serve/engine_actions/batch_draft.cc, cpp/serve/engine_actions/batch_verify.cc, cpp/serve/engine_actions/eagle_batch_verify.cc
cc @MasterJH5574 @tqchen @cyx-6
=> [Serving] Fix handling of num_tokens_for_next_decode in spec decoding

python/mlc_llm/model/gemma/gemma_model.py, python/mlc_llm/model/gemma2/gemma2_loader.py, python/mlc_llm/model/gemma2/gemma2_model.py, python/mlc_llm/model/gemma2/gemma2_quantization.py, python/mlc_llm/model/model.py
This doesn't work because I think we are missing the sliding window implementation in Gemma2, where the the sliding window is applied every other layer of attention: https://huggingface.co/blog/gemma2#sliding-window-attention
Would love to get some guidance/help to get the sliding window implemented if possible. I tried navigating the TVM codebase but somehow my VLOG doesn't work correctly, nor was I able to figure out a way to set sliding windows for only some layers of the attention and not universally.
=> Add support for Gemma2

android/MLCChat/mlc-package-config.json, docs/deploy/android.rst, python/mlc_llm/model/phi3/phi3_loader.py, python/mlc_llm/model/phi3/phi3_model.py, python/mlc_llm/model/phi3v/phi3v_loader.py, python/mlc_llm/model/phi3v/phi3v_model.py
* Update android package config from gemma 2b to gemma 2 2b
* Revert phi3 model definition for backward compatibility
=> [Android] Update model for Andorid APK

ios/MLCChat/mlc-package-config.json
This commit switches the Gemma model in iOS app to Gemma2.
=> [iOS] Add Gemma2 for iOS app

python/mlc_llm/bench/dataset.py
This PR adds the LLMPerf into benchmark module.
=> [Bench] LLMPerf dataset

python/mlc_llm/conversation_template/gemma.py
This commit adds `<bos>` to the gemma's conversation template.
=> [ConvTemplate] Update Gemma template with <bos>

python/mlc_llm/bench/__main__.py
This removes the row index in the output csv
=> [Bench] Remove index column in csv output

python/mlc_llm/bench/__main__.py
This PR adds the option for cuda profiling as mlc-ai/llmperf.
=> [Bench] Enable cuda profile

cpp/serve/engine_actions/action_commons.cc
=> [Fix] Fix casting token data error

python/mlc_llm/cli/serve.py, python/mlc_llm/interface/help.py, python/mlc_llm/interface/serve.py
=> [Serving] Add prefill-mode to cli option

python/mlc_llm/bench/__main__.py
=> [Bench] Allow running cuda-profile on existing mlc endpoint

docs/compilation/convert_weights.rst
=> [DOCS] Update convert_weights.rst

python/mlc_llm/bench/api_endpoint.py
This PR introduces the trt-llm API backend for benchmarking.
=> [Bench] Support tensorrt-llm API backend

cpp/serve/data.cc, cpp/serve/data.h, cpp/serve/engine.cc, cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/action_commons.h, cpp/serve/engine_actions/batch_decode.cc, cpp/serve/engine_actions/batch_prefill_base.cc, cpp/serve/engine_actions/batch_prefill_base.h, cpp/serve/engine_state.cc, cpp/serve/engine_state.h, cpp/serve/model.cc, cpp/serve/prefix_cache.cc, cpp/serve/prefix_cache.h, cpp/serve/request.h, cpp/serve/request_state.cc, cpp/serve/request_state.h
This PR contains some efforts in reducing the CPU overhead when engine executes, including some data structure refactor and helper function signature updates.
=> [Engine] Reducing MLC engine CPU overhead

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt, android/MLCChat/mlc-package-config.json, docs/deploy/android.rst
* Update Llama 3 8B to 3.1 8B
* Add history message for multi-turn conversations
=> [Android] Update Andorid APK

cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_actions/batch_draft.cc, cpp/serve/engine_actions/eagle_batch_draft.cc, cpp/serve/engine_actions/eagle_new_request_prefill.cc, cpp/serve/engine_actions/new_request_prefill.cc, cpp/serve/engine_state.cc, cpp/serve/engine_state.h, cpp/serve/prefix_cache.cc
This PR fixes the commit of prefix cache to make it updated with kvcache. And this PR renames the postproc from states to workspace.
=> [Fix] Commit prefix cache update

cpp/serve/config.cc
=> [Config] Fix model limits

python/mlc_llm/bench/dataset.py, python/mlc_llm/bench/request_processor.py
This PR adds the json schema dataset, from https://huggingface.co/datasets/NousResearch/json-mode-eval?.
=> [Bench] Json schema dataset

python/mlc_llm/cli/check_device.py
=> [CLI] Add CPU check device option

python/mlc_llm/nn/kv_cache.py, python/mlc_llm/support/auto_target.py
Added windows compilers option for adreno target
=> [Windows] Windows build target definitions for adreno

cpp/serve/config.cc, cpp/serve/prefix_cache.cc, cpp/serve/radix_tree.cc, python/mlc_llm/bench/__main__.py, python/mlc_llm/cli/serve.py, tests/python/serve/test_radix_tree.py
This PR fixes the forking of radix tree in prefix cache and exposes some setting to bench interface.
=> [Fix] Fix prefix cache

python/mlc_llm/bench/request_processor.py
This PR updates the warmup phase of the benchmark so that the warmup phase will invoke as more batch sizes as possible.
=> [Bench] Update warmup phase to warm up more batch sizes

cpp/multi_gpu/multi_gpu_loader.cc, cpp/serve/config.cc, cpp/serve/function_table.cc
This PR fixes the memory estimation when pipeline parallelism is enabled.
=> [MultiGPU] Fix memory estimation for pipeline parallelism

python/mlc_llm/model/vision/clip_vision.py, python/mlc_llm/nn/__init__.py, python/mlc_llm/nn/kv_cache.py, python/mlc_llm/op/attention.py
This pr uses TIR attn kernel for vision encoder
=> [Model] Use attention kernel implemented by tir for CLIP vision encoder

cpp/serve/engine_actions/batch_prefill_base.cc
This PR fixes the policy in prefill when new request cannot be prefilled entirely.
=> [Fix] Improve prefill policy for prefix cache reuse

python/mlc_llm/conversation_template/qwen2.py
This PR fixes stop strings in the Qwen2 conversation template.
=> [Conv] Fix Qwen2 conv template

python/mlc_llm/op/moe_misc.py
the compilation of mixtral failed due to the upstream change https://github.com/apache/tvm/pull/17285
cc: @vinx13 @tqchen
=> Fix the dtype of batch_size to ensure mixtral ir well-formed

ci/task/pylint.sh, ci/task/test_model_compile.sh, docs/install/mlc_llm.rst, docs/install/tvm.rst
This PR updates the uses of the nightly CPU package
=> [CI][Docs] Update nightly CPU package

python/mlc_llm/model/llava/llava_model.py, python/mlc_llm/model/phi3v/phi3v_image.py, python/mlc_llm/model/phi3v/phi3v_model.py, python/mlc_llm/model/vision/__init__.py, python/mlc_llm/model/vision/clip_vision.py, python/mlc_llm/model/vision/image_processing.py, python/mlc_llm/op/attention.py, python/mlc_llm/serve/data.py
This PR add image preprocess for vision model
=> [Model] Add image preprocess for vision model

python/mlc_llm/bench/__main__.py, python/mlc_llm/serve/entrypoints/debug_entrypoints.py
This PR tries to print the MLC server metrics after benchmark when the server is enabled with debug mode.
=> [Bench] Print server metrics when enabled

cpp/serve/engine_actions/auto_spec_decode.cc, cpp/serve/engine_actions/batch_draft.cc
This PR fixes the bug which happens when switching over from batch decode mode to the spec decoding mode.
=> [Fix][Spec] Fix adaptive spec decoding

python/mlc_llm/cli/gen_config.py, python/mlc_llm/model/baichuan/baichuan_model.py, python/mlc_llm/model/chatglm3/chatglm3_model.py, python/mlc_llm/model/cohere/cohere_model.py, python/mlc_llm/model/gemma/gemma_model.py, python/mlc_llm/model/gpt2/gpt2_model.py, python/mlc_llm/model/gpt_bigcode/gpt_bigcode_model.py, python/mlc_llm/model/gpt_neox/gpt_neox_model.py, python/mlc_llm/model/internlm/internlm_model.py, python/mlc_llm/model/internlm2/internlm2_model.py, python/mlc_llm/model/llama/llama_model.py, python/mlc_llm/model/minicpm/minicpm_model.py, python/mlc_llm/model/mistral/mistral_model.py, python/mlc_llm/model/orion/orion_model.py, python/mlc_llm/model/phi/phi_model.py, python/mlc_llm/model/phi3/phi3_model.py, python/mlc_llm/model/phi3v/phi3v_model.py, python/mlc_llm/model/qwen/qwen_model.py, python/mlc_llm/model/qwen2/qwen2_model.py, python/mlc_llm/model/stable_lm/stablelm_model.py, python/mlc_llm/model/starcoder2/starcoder2_model.py
This PR updates the default prefill chunk size from 2048 to 8192, and the default max batch size from 80 to 128.
=> [Model] Udpate default prefill chunk size and max batch size

python/mlc_llm/bench/dataset.py
This PR fixes the json dataset input and tokens counted.
=> [Fix] Fix json dataset

cpp/serve/engine_actions/batch_verify.cc
This PR fixes a bug which missed to add the PopN to erase the unaccepted tokens for the draft model, when the draft is in chain shape and no tree draft is enabled.
=> [Fix][Spec] Add the draft model PopN in chain speculative decoding

python/mlc_llm/op/cutlass.py, python/mlc_llm/op/extern.py, python/mlc_llm/quantization/per_tensor_quantization.py
This PR introduces the CUTLASS FP8 gemm kernels for sm_90a for better performance over cuBLAS.
=> [CUTLASS] Add FP8 gemm kernels

ci/jenkinsfile.groovy
This PR updates the docker image for CI.
=> [CI] Update docker image

cpp/serve/function_table.cc
Pre compiler cache enable for opencl to avoid kernel compile affecting benchmark
=> [SERVE][OPENCL] Pre compiler cache enable for opencl

docs/get_started/quick_start.rst
This PR updates the Android APK link in quick start
=> [Docs] Update the Android APK link in quick start

python/mlc_llm/model/llava/llava_model.py, python/mlc_llm/model/phi3v/phi3v_model.py, python/mlc_llm/model/vision/image_processing.py
This PR improves the performance of image preprocessing for vision model. Generally, image storage formats include NCHW and NHWC, with NCHW being more suitable for GPU-based computations. Additionally, performance is enhanced by binding the for loop to GPU hardware threads.
=> [Model] Optimize image preprocess for vision model

docs/compilation/configure_quantization.rst, docs/index.rst
Added doc for quantization and calibration
=> [Doc] Add quantization documentation

python/mlc_llm/support/auto_target.py
No need build again to export cl source code.
=> Dont build twice to export cl source code.

python/mlc_llm/model/deepseek/deepseek_model.py
This PR supports TP function of Deepseek Model
=> [SLM] Deepseek Multi-GPU support

docs/compilation/compile_models.rst
This PR updates the conversation template's link in guide docs
=> [Docs] Update model template link address

python/mlc_llm/model/internlm2/internlm2_model.py
This PR fixes a bug that causes incorrect output when running internlm2 with tensor parallelism.
=> [Fix][Model] Fix tensor parallelism of internlm2 model

ci/task/test_model_compile.sh, ci/task/test_unittest.sh
This PR updates the TVM package used for CI from cuda 12.1 to 12.3.
=> [CI] Update TVM package for CI

python/mlc_llm/op/moe_misc.py
This PR introduces the meta-programming top-k kernel for expert selection in MoE. With this PR, we can deprecate the previous ad-hoc kernels specialized for k=2 and k=4.
=> [Python] Update top-k kernel with TIR meta-programming

python/mlc_llm/model/deepseek/deepseek_model.py, python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py
This PR supports tensor parallelism for Deepseek-v2 model.
=> [Model] Support multi-GPU for Deepseek-v2

python/mlc_llm/bench/__main__.py, python/mlc_llm/bench/dataset.py, python/mlc_llm/bench/request_processor.py
This PR introduces the [AzureLLMInference dataset](https://github.com/Azure/AzurePublicDataset). This dataset contains the timestamp for each entries, and this PR also introduces the dataset replay mode for mlc-llm benchmark. This mode reuses the provided timestamps for benchmark.
=> [Bench] Add AzureLLMInference dataset

python/mlc_llm/support/auto_device.py
This PR moves the CPU detection to the last device after checking all GPUs.
=> [Device] Defer the CPU detection

ci/jenkinsfile.groovy
This PR updates the CI CUDA build docker to 12.8.
=> [CI] Update CUDA build docker to 12.8

python/mlc_llm/serve/entrypoints/openai_entrypoints.py
Fixes the merging logic of logprobs of different tokens  for the same choice.
Earlier response 
```{
"id": "cmpl-0e79013e278c497a8926be59641d0381",
"choices": [
{
"finish_reason": "length",
"index": 0,
"logprobs": {
"text_offset": null,
"token_logprobs": [
0.0
],
"tokens": [
""
],
"top_logprobs": [
{
"": -23.0259,
"<unk>": -23.0259,
"<s>": -23.0259,
"</s>": -23.0259
}
]
},
"text": "2, and "
}
],
"created": 1741063066,
"model": "/home/annanyac/mlc-llm/dist/Llama-2-7b-chat-hf-q0f16-MLC/",
"object": "text_completion",
"usage": {
"prompt_tokens": 6,
"completion_tokens": 5,
"total_tokens": 11,
"extra": null
}
}
```
New response 
```{
"id": "cmpl-d6b2bc3820f8441fbfbe9d5d0be3d9ce",
"choices": [
{
"finish_reason": "length",
"index": 0,
"logprobs": {
"text_offset": null,
"token_logprobs": [
0.0, …
```
=> Fixed log prob result generation

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py
=> Revert "[Fix] Resolve TVM Compatibility Issue by Removing Unsupported Argument"

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py, python/mlc_llm/model/gemma3/gemma3_loader.py, python/mlc_llm/model/gemma3/gemma3_model.py, python/mlc_llm/model/model.py
This PR updates the Gemma3 weight loader implementation to support the 1b variant.
=> [Model] Update Gemma3 to support 1b variant

python/mlc_llm/compiler_pass/fuse_add_norm.py
In this PR I have added support for bfloat16 in fuse add norm. I have confirmed that this is applied by compiling LLama3 in debug mode.
=> [Bfloat16] Added support for bfloat16 in fuse add norm

python/mlc_llm/interface/compiler_flags.py, python/mlc_llm/model/model.py, python/mlc_llm/model/qwen3/qwen3_loader.py, python/mlc_llm/model/qwen3/qwen3_model.py, python/mlc_llm/model/qwen3/qwen3_quantization.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_loader.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_model.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_quantization.py, python/mlc_llm/op/extern.py, python/mlc_llm/op/moe_misc.py, python/setup.py
This PR supports the Qwen3 and Qwen3MoE models. The FP8 support is still in progress.
A bug of topk-softmax is fixed in the PR.
=> [Model] Qwen3 support

python/mlc_llm/model/model.py, python/mlc_llm/model/qwen3/qwen3_loader.py, python/mlc_llm/model/qwen3/qwen3_model.py, python/mlc_llm/model/qwen3/qwen3_quantization.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_loader.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_model.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_quantization.py
This PR enables the FP8 support for Qwen3 family.
=> [Model] Qwen3 FP8 support

cpp/serve/sampler/cpu_sampler.cc, ios/MLCChat/mlc-package-config.json, ios/MLCSwift/Package.swift, ios/MLCSwift/Sources/ObjC/LLMEngine.mm, ios/prepare_libs.sh
This PR updates the iOS build flow so that it works with the recent FFI refactor.
=> [iOS] Enable iOS build flow after FFI refactor

ci/task/build_lib.sh, tests/python/serve/test_radix_tree.py
This PR tries to fix a cmake error of a 3rdparty dependency in CI.
=> [CI] Fix cmake error in CI build flow

cpp/metadata/model.cc, cpp/metadata/model.h, cpp/serve/model.cc, python/mlc_llm/compiler_pass/attach_support_info.py, python/mlc_llm/compiler_pass/pipeline.py, python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py, python/mlc_llm/model/qwen3_moe/qwen3_moe_model.py, python/mlc_llm/nn/expert.py, python/mlc_llm/op/batch_matmul.py, python/mlc_llm/op/cutlass.py, python/mlc_llm/op/extern.py, python/mlc_llm/op/moe_matmul.py, python/mlc_llm/op/triton.py, python/mlc_llm/quantization/block_scale_quantization.py, tests/python/op/test_fp8_block_matmul.py
This PR introduces the FP8 support for Qwen3 series on Blackwell GPUs.
=> [Model] Enable Qwen3 FP8 support on Blackwell GPUs

cpp/json_ffi/json_ffi_engine.cc, cpp/multi_gpu/builtin.cc, cpp/multi_gpu/multi_gpu_loader.cc, cpp/serve/data.cc, cpp/serve/engine.cc, cpp/serve/event_trace_recorder.cc, cpp/serve/model.cc, cpp/serve/radix_tree.cc, cpp/serve/request.cc, cpp/serve/threaded_engine.cc, cpp/tokenizers/streamer.cc, cpp/tokenizers/tokenizers.cc
This PR updates the C++-side global function registration to align with the latest mainline TVM which has the new registration mechanism with the new reflection.
=> [C++] Update global function registration per latest reflection refactor

cpp/json_ffi/json_ffi_engine.cc, cpp/serve/config.cc, cpp/serve/data.cc, cpp/serve/engine_actions/action.cc, cpp/serve/engine_actions/action_commons.cc, cpp/serve/engine_state.cc, cpp/serve/event_trace_recorder.cc, cpp/serve/logit_processor.cc, cpp/serve/model.cc, cpp/serve/prefix_cache.cc, cpp/serve/prefix_cache.h, cpp/serve/radix_tree.cc, cpp/serve/radix_tree.h, cpp/serve/request.cc, cpp/serve/request_state.cc, cpp/serve/sampler/cpu_sampler.cc, cpp/serve/threaded_engine.cc, cpp/tokenizers/streamer.cc, cpp/tokenizers/tokenizers.cc
This PR updates MLC codebase to align with the latest refactors in TVM mainline.
=> [FFI] Update MLC per latest FFI refactor

python/requirements.txt, python/setup.py
This PR introduces apache-tvm-ffi to the package dependency due to its separation in mainline tvm.
=> [Python] Add apache-tvm-ffi as package dependency

.github/ISSUE_TEMPLATE/bug-report.md, docs/community/faq.rst, docs/compilation/compile_models.rst, docs/compilation/convert_weights.rst, docs/compilation/package_libraries_and_weights.rst, docs/deploy/android.rst, docs/deploy/ios.rst, docs/deploy/webllm.rst, docs/install/emcc.rst, docs/install/gpu.rst, docs/install/mlc_llm.rst, docs/install/tvm.rst, python/mlc_llm/interface/compile.py
This PR updates the build-from-source instructions of MLC and TVM.
=> [Doc] Update build-from-source instructions

scripts/build_mlc_for_docs.sh
This PR fixes the doc build cmake issue.
=> [Docs] Update doc build script
