cpp/llm_chat.cc
ios/MLCChat/ChatState.swift
ios/MLCChat/MLCChat-Bridging-Header.h
mlc_llm/transform/dispatch_tir_operator.py

This PR makes the chat.cc mostly static allocate memory to reduce overall memory allocations in runtime.

Moving most device memory static

---

mlc_llm/transform/quantization.py

Always use lower-cased TIR ops, i.e. `tir.Max` -> `tir.max`, because they will help do auto type promotion.

Fix: dtype mismatch during quantization

---

mlc_llm/relax_model/llama.py

Previously we will copy all parameters while creating TVM NDArray parameters. This will consume two times of memory usage.
This PR deletes the model from pre_trained in advance. Thus, python runtime can delete useless params at the right time, reducing the duplicate memory usage.

Reduce memory usage in model building process

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/MainActivity.java

This PR is a quick fix for the android app on stats collection. Without this PR the android app will crash when build in Android Studio.
The released APK doesn't have this issue so no need to build a new APK.

Fix Android app stats collection

---

build.py
cpp/cli_main.cc
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/moss.py
mlc_llm/utils.py
tests/chat.py
tests/debug/compare_lib.py
tests/evaluate.py

This PR introduces three preset compilation modes, which specify the quantization options and model dtype of the compilation flow.
At this moment, only three modes are supported. To ease running commands, we turned off manual customization (like specifying all options one by one). If you do want to customize, you can choose to add a preset mode to the codebase.
This PR thereby also reorganizes the artifact names (including the library name, cached IRModule name, etc.). Therefore, we will need to update the HuggingFace model repo and the binary repo after merging this PR.
The behaviors of `build.py`, `tests/chat.py`, `tests/evaluate.py` and `tests/debug/compare_lib.py` and the CLI (including Conda install and build from source) are tested.

Introduce preset compilation modes and organize artifact name

---

cpp/cli_main.cc

Minor adjustment made to correctly parse the argument as per the argparse documentation

fix for `--device_id` argument

---

build.py
cpp/cli_main.cc
mlc_llm/utils.py
tests/chat.py
tests/debug/compare_lib.py
tests/evaluate.py

This PR reorganizes the artifact structure. We now have two separate types of directories to store the libs/weights/..., with one "prebuilt" directory which holds all the prebuilt libs and weights downloaded from internet, and other model directories that are generated by local builds.
CLI and test scripts are updated accordingly for this change.

Further reorganize artifact structure

---

README.md
android/README.md
build.py
cpp/README.md
ios/README.md

Previously when we introducing the support of "local model path" and "HuggingFace model path", we removed the support of specifying model name when build. This turns out preventing us from only specifying the much shorter model name, as well as doing automatic search for models existing on the disk.
Therefore, this PR brings back the argparse support for `--model`. Now we will carefully handle the case where both the model name and one of the model path / HF path are specified. We now also support model searching on disk, and support specifying the model only by a short model name.

Allow specifying model name in build

---

README.md
android/README.md
build.py
cpp/README.md
cpp/cli_main.cc
ios/README.md
mlc_llm/relax_model/llama.py
mlc_llm/utils.py

This PR updates three places for better experience.
* Unify the `--model-path` and `--model` args in build.py. Now we only take `--model`.
* Hardcode the rotary embedding size for LLaMA to 2048. This enables us to build a model with different max sequence length without changing the built weights.
* Update the generated config file name to `mlc-chat-config.json`.

Unify model specification in build / Hardcode cached rotary emb size / Update config name

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/LLMChat.java
cpp/cli_main.cc
cpp/llm_chat.cc
ios/MLCChat/LLMChat.mm

At this moment the max-gen-len argument in our chat module is duplicate with the max-window-size arg in terms of functionality.
This PR removes it for clarity.

Remove max-gen-len from chat module due to duplication

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/LLMChat.java
build.py
cpp/cli_main.cc
cpp/llm_chat.cc
ios/MLCChat/LLMChat.mm
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/moss.py

This PR supports initialization the chat module from JSON-structured string.
* The CLI is updated with the latest json initialization.
* The iOS/Android app sides are remained using the previous way of initialization. Now the previous function is renamed to `init_chat_legacy`, which we will remove after updating the app and web sides accordingly.
* This PR reverts part of the previous metadata PR as a wrong assumption was made on the conversation template.
* This PR removes `stream_interval` from chat module as it is unused. Now `stream_interval` is only kept on the CLI side.

Initialize chat module from config JSON string

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/LLMChat.java
cpp/cli_main.cc
cpp/llm_chat.cc
cpp/llm_chat.h
ios/MLCChat/LLMChat.mm

This PR introduces the model reload functionality to the chat module and the CLI.
* In CLI, the usage is `/reload [model_id]`, for example `model_id` can be `vicuna-v1-7b-q3f16_0`. When `model_id` is specified, CLI will search the corresponding model for `model_id` in candidate paths, and load the specified model. When it is not specified, CLI will reload the currently running model again.
* The effect of the reload operation is to load the (specified) model as if loading it at the very beginning. This means the chat module will completely release and forget everything happened before reload.
* Regarding the implementation, this PR unifies the previous `init_chat` function with the `Init` function into the `Reload` function.
* Verified the behavior of reload between Vicuna-v1-7b and …

Support model reload in chat module and CLI

---

mlc_llm/relax_model/gpt_neox.py

This PR changes the GPT-NeoX KV cache creation function to create to full size at the beginning, so no memory allocation will be required when running on the fly.

GPT-NeoX allocating full-length KV cache

---

build.py
mlc_llm/transform/__init__.py
mlc_llm/transform/lift_tir_global_buffer_alloc.py

This PR introduces the pass which can help lift all the global-scope buffer allocation in all TIR PrimFunc to the Relax function side.
With this PR, we will no longer (in most of the cases where the pass is able to resolve the symbolic var relation across TIR and Relax function side) have global alloc_buffers at TIR level.
Confirmed its effect on RedPajama.

[Transform] Lift global buffer allocation in TIR PrimFunc

---

mlc_llm/dispatch/dispatch_tir_operator_adreno.py
mlc_llm/utils.py

```
Name                                              Time (ms)   Count   Total time (ms)   Percentage (%)
fused_decode6_fused_matmul9_add7_cast8_cast12_add50.9462      31      29.3330           31.23
fused_layer_norm1_cast8                           0.3802      64      24.3335           25.90
fused_decode4_fused_matmul6_add4                  0.1434      96      13.7626           14.65
fused_decode5_fused_matmul8_add6_gelu1_cast11     0.4078      32      13.0499           13.89
fused_decode4_fused_matmul6_add4_add5             0.1436      32      4.5941            4.89
fused_NT_matmul4_divide2_maximum1_minimum1_cast9  0.1039      32      3.3243            3.54
fused_decode3_matmul3                             1.7050      1       1.7050            1.81 …
```

decoding kernels of RedPajama on Adreno

---

build.py
mlc_llm/utils.py

This PR brings the database merge feature, which automatically merges all database under the specified `--db-path` (which is `./log_db/` by default).
For example, when there are two database under `./log_db/`: `./log_db/vicuna` and `./log_db/redpajama`, we won't need to manually specify one database to use. Instead, `build.py` will now load each of the database and merge them into one in memory.
We are also backward compatible. Say if we have only one database which is `./log_db` itself, we are still able to load it in.

Database in-memory merge

---

build.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/transformers.py
mlc_llm/utils.py

To avoid potential symbolic conflicts in some shared libraries (e.g. LLVM)

Isolate model fetching in a separate process

---

site/index.md

clone the lib files into the path that mlc-chat expects

fix minor typo that causes lib not found

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general.md
.github/ISSUE_TEMPLATE/model-request.md
.github/ISSUE_TEMPLATE/speed-report.md

The `about` field of `contact_links` in `config.yml` is missing.
Also, add labels for each issue template.

[Github] Fix the issue templates format issue

---

python/README.md
python/mlc_chat/chat_module.py
python/mlc_chat/gradio.py

In this PR, the Gradio interface is refactored to accommodate the formal package in #266. In addition, it makes the following changes:
1. Allow the selection from local model ids, which is consistent with web-llm.
2. Disable the launching of HF tunnel by default.

refactor gradio interface

---

docs/install/index.rst

To avoid symbol conflict with other packages such as PyTorch (#272 ).

[Doc] Fix the TVM Unity installation

---

.gitmodules

Currently, MLC-LLM relies on the TVM-Unity codebase which already incorporates picojson.
This PR removes picojson submodule to avoid duplication.

Remove picojson submodule 

---

build.py
mlc_llm/relax_model/llama.py
mlc_llm/transform/__init__.py
mlc_llm/transform/reorder_transform_func.py
mlc_llm/utils.py

This PR enables loading LLaMA-family models on shard level. We no longer use `from_pretrained` to load LLaMA-family models.
This means when loading LLaMA-family models in build.py, we no longer need to load the full model weights into memory (which is of huge pain for machines without large enough memory). With this PR, the largest RAM usage when building LLaMA-family models will be about the size of the largest shard file.
For example, the largest shard file of Vicuna-7B is roughly 10GB, which means the largest RAM usage during build is about 10GB.
We implement this functionality based on pass LazyTransformParams and a topological-sort-based weight computation reordering algorithm.
Corresponding update to GPT-NeoX and RWKV will follow this PR soon.

LLaMA family loading model on shard level - reducing memory usage

---

cpp/cli_main.cc
cpp/conversation.h
cpp/llm_chat.cc

The current system prompts are run after the first input, which may slow down the first reply, especially for RWKV model.
This commit introduces a new step to run the system prompts before the conversation. Note that this change is 100% backward compatible, and we will update iOS, Android, and Web SDKs later.
Here are the output of new impl:
```
Use MLC config: "/data/syfeng/dist/prebuilt/mlc-chat-vicuna-v1-7b-q3f16_0/mlc-chat-config.json"
Use model weights: "/data/syfeng/dist/prebuilt/mlc-chat-vicuna-v1-7b-q3f16_0/ndarray-cache.json"
Use model library: "/data/syfeng/dist/prebuilt/lib/vicuna-v1-7b-q3f16_0-vulkan.so"
You can use the following special commands:
/help               print the special commands
/exit               quit the cli
/stats              print out the latest stats …
```

Introduce System Prompts Step

---

cpp/llm_chat.cc

Fix the bug reported by https://github.com/mlc-ai/mlc-llm/issues/307

[FIX] Fix Crash when running Conversations without system prompts

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatModule.kt

Replace some functions in `AppViewModel` and `ChatModule` to make the code more in line with the usage habits of Android developers
1. Replace `assert` with `require`, `assert` is generally only used in unit tests
2. Use `android.util.Log` instead of `System.err` to output key information
3. The naming of some `func*` definitions in ChatModule adopts a unified camel case naming style
4. The `func*` variable is defined as non-null instead of nullable, because `getFunction` internally returns a non-null object as much as possible (or throws IllegalArgumentException)

[Android] Replace some functions in `AppViewModel` and `ChatModule` to make the code more in line with the usage habits of Android developers

---

cpp/README.md

In the README for `cpp/` it seems that there is a missing `mkdir` command so this PR just adds the command.

Add missing mkdir to cpp/README.md

---

.gitmodules

In https://github.com/mlc-ai/mlc-llm/pull/368 we uses ssh for relax submodule which is problematic on machines without github ssh configuration such as CI.

[Hotfix] Replace ssh with https for relax submodule

---

android/MLCChat/app/build.gradle
android/MLCChat/app/src/main/jni/tvm_runtime.h

1. Restore tvm_runtime.h file
2. Revert code that reads ndk-build path from local.properties

[Android] Fix compile error (#310) and `ndk-build` cannot reference

---

cpp/llm_chat.cc

**Problem**
There was a problem with the json config file properly overriding the default conv template specified. 
**Solution**
I have rearranged the logic (with as little code as possible to achieve the logic below) that checks whether a conv template or conv config exists so as to behave as expected:
- If only a conv template exists, load the template
- If a conv template _and_ conv config exists, load the template then load the config with partial update
- If only a conv config exists, load the config with no partial update
**Bug details**
Currently, the bug can be recreated like so:
1. specify a valid conv_template string within the mlc-chat-config.json file
2. specify a conv_config with only a subset of attributes required, eg:
```
...
"conv_config": {
"separator_style": 1
}
...
``` …

[Bugfix] Fix json config overriding conv template logic

---

python/mlc_chat/rest.py
python/mlc_chat/sample_client.py

Fix an unnecessary import and change default artifact path to be the path to dist when `rest.py` is invoked using `python -m mlc_chat.rest`.

Fix incorrect import in REST API

---

docs/requirements.txt

Currently, the autodoc for Python API doesn't work because of the following error:
```
WARNING: autodoc: failed to import class 'ChatModule' from module 'mlc_chat'; the following exception was raised:
No module named 'tvm'
```
This PR fixes the issue by adding mlc-ai-nightly as documentation requirements.

[Hotfix] Add mlc-ai-nightly as requirements for documentation

---

docs/deploy/python.rst
docs/deploy/rest.rst
docs/requirements.txt

- `mlcchat_build_from_source` is a duplicate label.
- `mlc-chat-nightly` need to be added to the requirements for building autodoc.

[Hotfix] Fix duplicate labels in documentation and add `mlc-chat-nightly` to requirments

---

ios/MLCChat/ChatState.swift

- Fixed the unit for `estimatedVRAMReq` from `GB` to `MB`

Typo fix for error logs in ChatState.swift

---

.github/workflows/documentation.yml

The `libmlc_llm.so` need to be loaded from `build/` directory for autodoc to work for Python APIs.

[Doc] Link `libmlc_llm.so` for auto doucmenting Python APIs

---

build.py
mlc_llm/__init__.py
mlc_llm/dispatch/llama/main.py
mlc_llm/quantization/__init__.py
mlc_llm/quantization/group_quantization.py
mlc_llm/quantization/quantization.py
mlc_llm/quantization/tir_utils.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/param_manager.py
mlc_llm/transform/__init__.py
mlc_llm/transform/decode_matmul_ewise.py
mlc_llm/transform/decode_take.py
mlc_llm/transform/decode_transpose.py
mlc_llm/transform/quantization.py
mlc_llm/transform/reorder_transform_func.py
mlc_llm/transform/transpose_matmul.py
mlc_llm/utils.py

This PR introduces parameter manager, which keeps information of all parameters throughout the entire model, and is in charge of applying quantization and dequantization to the model. Now all parameters are managed in a unified and deterministic way, and the quantization computation will no longer be affected by the optimization passes.
Together with the ParamManager, this PR does an overhaul of the quantization framework with more modular and customizable quantization modules. Specifically, we have
- QuantizationScheme, which describes how an entire model is quantized, and
- QuantizationSpec, which describes how a particular parameter is quantized.
With them and the ParamManager, we now decoupled the quantization algorithm description with the model transformation, which provides us with …

ParamManager and new quantization framework

---

build.py
mlc_llm/quantization/__init__.py
mlc_llm/transform/decode_matmul_ewise.py
mlc_llm/transform/decode_transpose.py
mlc_llm/transform/transpose_matmul.py
mlc_llm/utils.py

This PR supports the quantization scheme `q4f16_1` with desired fusion pattern. Compared with `q3f16_0` or `q4f16_0`,
* this scheme does not transpose the linear layer weights in quantization,
* under this scheme we fuse all transpose with matmul so that the fused matmul is of layout "NT".
The purpose of this PR is to provide initial support of the quantization scheme and ensure the desired fusion pattern under this scheme. The TIR functions under this scheme is not fully optimized. We will introduce the optimization with dlight (the default schedule package) soon.
The performance of other quantization schemes are not affected. We will do clean up for some of the optimization passes in the future (for example, remove the "`gemv_only`" condition in decode-matmul-ewise fusion) when dlight …

Initial `q4f16_1` quantization support with fusion

---

build.py
cpp/llm_chat.cc
mlc_llm/relax_model/llama.py
python/mlc_chat/chat_module.py

This PR separates embed from the prefill function, in order to satisfy some needs of using the embedding of prompts. It is a newer version of #408 in order to incorporate some changes made lately in the repo.
Three changes are made:
1. in build.py, `--sep-embed` is an optional flag for building a model (llama-related only) separating embed from prefill. 
2. in llm_chat.cc, `EmbedStep` and `PrefillWithEmbedStep` should be used together for models with separate embed function. This is automatically handled in `PrefillStep` by detecting whether the model has embed function and select which routine to run.
3. in the Python API, `embed` and `prefill_with_embed` API are exposed.

Separate embed as a new function

---

cpp/llm_chat.cc
mlc_llm/relax_model/llama.py

This PR fixes a bug in ChatModule embedding separation. Besides, this PR also reorganizes the logic a bit, including:
* extracts some common code for share by "PrefillStep" and "EmbedStep",
* defines `embed_total_time` for embedding time accumulation,
* renames two "Forward" functions to "ForwardTokens" and "ForwardEmbeddings" respectively.
With this PR, Vicuna-v1-7B performance is validated on q3f16_0.

Minor bug fix and reorganization on ChatModule embed separation

---

docs/compilation/compile_models.rst

Some of the previous WebGPU target compilation instructions are accidentally wrong. This PR updates them to the correct ones.

[Docs] Update WebGPU target compilation instructions

---

build.py
cpp/conv_templates.cc
cpp/conversation.h
cpp/llm_chat.cc
mlc_llm/dispatch/dispatch_tir_operator.py
mlc_llm/relax_model/minigpt.py
mlc_llm/utils.py
python/mlc_chat/chat_module.py
python/mlc_chat/gradio.py

This PR tested and confirmed the quality of running minigpt from cli and massively polished the gradio interface. 
To build:
* make sure to compile vicuna models with `--sep-embed` flag
* it is recommended to download minigpt 7b weights from [https://drive.google.com/file/d/1RY9jV0dyqLX-o38LrumkKRh6Jtaop58R/view?usp=sharing](url) and store as a **single file** (no folders!) under artifact-path/models/
Features changed:
* add `PlaceInPrompt` enum class that allows the user to decide where to place a text input in a prompt, choices are "kBegin" / "kMiddle" / "kEnd" / "kAll" (default is "kAll").
Demo:
https://github.com/mlc-ai/mlc-llm/assets/65606304/78722672-b95b-4533-9400-e591b75f9762

gradio polish and minigpt cli

---

cpp/conv_templates.cc
mlc_llm/relax_model/llama.py
mlc_llm/utils.py

This PR adds support for [WizardLM](https://github.com/nlpxucan/WizardLM). 
Step 1: Download relevant files
```
cd mlc-llm/dist/models
git lfs install
git clone https://huggingface.co/WizardLM/WizardLM-7B-V1.0
git clone https://github.com/nlpxucan/WizardLM.git
mkdir wizardlm-v1-7b
ls 
>>> WizardLM WizardLM-7B-V1.0 llama-7b-hf wizardlm-v1-7b
cd WizardLM/WizardLM/src
```
Step 2: Add missing file
Create a document `train.py` in `src`, paste in the following, which can be found in [this repo](https://github.com/artidoro/qlora/blob/main/qlora.py#L363) or [this repo](https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py):
```
from typing import Dict
import transformers
def smart_tokenizer_and_embedding_resize(
special_tokens_dict: Dict,
tokenizer: transformers.PreTrainedTokenizer, …
```

Add support for WizardLM

---

cpp/conversation.h

This PR fixed a small bug in the behavior of PlaceInPrompt.Middle to ensure that it does not spawn the system prompt at the initial trial. 
Thanks @sudeepag for spotting this bug!

[BugFix] PlaceInPrompt behavior

---

mlc_llm/transform/decode_transpose.py

Prior to this PR, the FuseDecodeTranspose pass creates the fused PrimFunc which directly reuses the blocks in the functions being fused. This lead to tir.Schedule error when a Schedule is constructed on an IRModule which contains both the post-fusion and pre-fusion functions.
This PR calls `tir.stmt_functor.renew_defs` on the fused PrimFunc for the purpose of simple deep copy.
Other fusion passes are confirmed with no similar issue.

[Fix] FuseDecodeTranspose pass with PrimFunc deep copy

---

mlc_llm/utils.py

It is variant of resolution of issue #458. I'm not sure that it is ideal, see my thoughts below.
Quantization tag `qMfN` (e.g. "q3f16") can be splitted on two parts: `M` defines number of bits for low-precision quantization of weights; `N` defines size of floating point type for calculation. But there is white spot: if M = 0 the weights are not quantized and `N` value does not influence on storage data type. Additionally if the original weigth data is "bfloat16" it is converted to "float32" that affects memory usage (#458). Thus we do not control data type for M = 0 in good way.
Just now I propose to convert "bfloat16" to N-bits floating point during transfer torch weights to numpy. There are two obvious options more: 1. convert "bfloat16" to "float16" immediately to effectively use …

[General] Correct processing of bfloat16 weights

---

build.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/minigpt.py
mlc_llm/relax_model/param_manager.py
mlc_llm/relax_model/rwkv.py
mlc_llm/transform/reorder_transform_func.py
mlc_llm/utils.py

This PR refactors the lazy parameter loading logic, integrating it into the ParamManager so that the concept of ParamManager is more self-contained.
On top of this, this PR supports the lazy parameter loading with an additional functionality. Prior to this PR, the lazy parameter loading only supports the case of "one Relax parameter comes from one torch parameter". In this setting, we can support "the torch nn.Module has combined QKV while our Relax nn.Module separates them". However, we did not support the reverse - we did not support "the torch nn.Module separates Q, K, V, and the Relax nn.Module combines them together".
This PR now supports this. It opens the floor for the QKV combination for models like LLaMA (whose PyTorch nn.Module implementation does not combine Q, K, V together). …

[Refactor] Param loading integration into ParamManager

---

mlc_llm/relax_model/llama.py

This PR supports QKV and MLP matmul combination for LLaMA.
It adds an option to LlamaConfig, which controls if to combine the QKV computation. Right now, we will combine the QKV and MLP matmul as long as the quantization method is not AutoGPTQ. The option can be also manually set in llama.py.

QKV and MLP matmul combination for LLaMA

---

cpp/conv_templates.cc
mlc_llm/build.py
mlc_llm/quantization/__init__.py

This PR adds a stop string for the Llama-2 conversation, adds the `q4f32_1` quantization for web.

Stop-str for Llama-2, and `q4f32_1` for web

---

docs/get_started/try_out.rst

This PR adds the CLI instructions to run Llama 2 13B model.

[Docs] Llama 2 13B CLI instructions

---

README.md
docs/get_started/try_out.rst

W/ #567 get merged, MLC-LLM now supports Llama-2-70B-Chat, tested on Mac Station w/ M2 Ultra (decoding speed: 9.8 toks/s).
Weight: https://huggingface.co/mlc-ai/mlc-chat-Llama-2-70b-chat-hf-q4f16_1
Binary: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Llama-2-70b-chat-hf-q4f16_1-metal.so

[Doc] Announce Llama 2 70B CLI support

---

mlc_llm/relax_model/llama.py

This PR fixes a minor bug introduced by the grouped query attention PR, and sets the correct number-of-heads value in the kv-cache creation function.

[Fix] Correcting num-kv-heads in Llama kv-cache creation func

---

python/mlc_chat/libinfo.py

Always use abspath for all module in case
there are wrong directories.

[PYTHON] Use abspath for dll module

---

examples/rest/sample_client.py
examples/rest/sample_langchain.py
python/mlc_chat/interface/openai_api.py
python/mlc_chat/rest.py

`pydantic` made a [breaking change](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields) in their major version update to how `Optional` fields work with FastAPI. This PR updates the OpenAI interface to reflect this change, while ensuring backward compatibility with Pydantic v1.
A few things worth calling out:
- `sample_client` and `sample_openai` have both been tested with `pydantic` v1 and `pydantic` v2, and are expected to run successfully.
- `langchain` has a dependency on `pydantic` v1, so `sample_langchain` will not work with `pydantic` v2. This is reflected in [inline comments](https://github.com/mlc-ai/mlc-llm/pull/592/files#diff-e9e785f066c79b626e8c3c6220b1b6d4fe763cf0488767c93347b7c9fafee5b8R13-R15) within the sample code. However, it is expected to …

Add support for Pydantic v2

---

mlc_llm/core.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/minigpt.py
mlc_llm/relax_model/param_manager.py
mlc_llm/relax_model/rwkv.py
mlc_llm/utils.py

This main part of this PR separates the weight conversion func construction from the model IRModule transformation, so that we can now choose to only convert the model weights or only to build the model library, by specifying corresponding build arguments.
With this PR, the `mod_transform_before_build` function no longer has anything to do with the weight conversion computation.
Besides, this PR also
* removes some dump functions to utils,
* making the dumped `.pkl` IRModule independent of the architecture.

Lift weight conversion to an early stage

---

docs/prebuilt_models.rst

Currently, the [Supported Model Architectures](https://mlc.ai/mlc-llm/docs/prebuilt_models.html#supported-model-architectures) does not show the table due to the first row having an extra item.

[Docs] Small fix on supported architectures

---

python/mlc_chat/rest.py

As described in issue #608, currently the Rest API incorrectly reads `.dylib` files instead of `.so` files on Apple Silicon macOS.
This PR fixes this problem. If `sys.platform` is `darwin` (macOS), it will additionally judge the CPU brand string through `sysctl -n machdep.cpu.brand_string` to confirm whether it is Apple Silicon or Intel (x86) architecture.
Note: Using `platform.processor()` to confirm the macOS architecture may lead to misjudgment under Rosetta or different Python version, so the relatively stable `machdep.cpu.brand_string` is used for judgment.

[Fix] Rest API: Update system platform checks for Apple Silicon (#608)

---

mlc_llm/quantization/__init__.py
mlc_llm/quantization/autogptq_quantization.py
mlc_llm/quantization/group_quantization.py
mlc_llm/quantization/quantization.py
mlc_llm/quantization/rwkv_quantization.py
mlc_llm/relax_model/param_manager.py

This PR supports the quantization function registration of a QuantizationSpec with a relax function that takes in a BlockBuilder and a list of relax Vars, computes the (de)quantization and returns the results.
Prior to this PR, only TE functions are allowed, which is a bit restrictive. With this function, we are able to register more general quantization computation (such as calling external functions), which enables more possibility.

Supports more general quantization func registration

---

mlc_llm/core.py

Currently, if the specific workflow does not produce a corresponding path, the `build_model` API would run into an error.
For instance, if we are reusing the cache, we would not need `args.params_path`, hence running into error when returning at `build_model`: 
```
AttributeError: 'Namespace' object has no attribute 'params_path'
```
Similarly, depending on the arguments when building, the paths we want to return may or may not apply.

[Bug fix] Fix build model api return value

---

android/MLCChat/app/src/main/assets/app-config.json
docs/compilation/compile_models.rst
docs/compilation/configure_quantization.rst
docs/compilation/distribute_compiled_models.rst
docs/deploy/android.rst
docs/deploy/ios.rst
docs/get_started/mlc_chat_config.rst
docs/get_started/try_out.rst
docs/prebuilt_models.rst
ios/MLCChat/app-config.json
ios/prepare_params.sh
mlc_llm/core.py
site/index.md

`q4f16_0` has been widely used in documentation, tutorials and command line default values since the beginning.
With the latest push, we have introduced `q4f16_1`, which is faster and has arithmetically equivalent precision.
Therefore, this PR aims to remind that `q4f16_1` is more preferrable than `q4f16_0` in case of any potential issues.

Suggest using `q4f16_1` than `q4f16_0`

---

mlc_llm/core.py

A fix, PR https://github.com/mlc-ai/mlc-llm/pull/626 has a simple typo which accidentally deleted type= of add_arguments.
https://github.com/mlc-ai/mlc-llm/blob/9c77d19a4212323d05033cd077d6a9b9b62ddc50/mlc_llm/core.py#L121-L134
the line of 133 should be 
`args.add_argument(field_name, type=field.type, default=field.default, **kwargs)`
as the params of add_arguments are:
```
def add_argument(
*name_or_flags: str,
action: _ActionStr | type[Action] = ...,
nargs: int | _NArgsStr | _SUPPRESS_T = ...,
const: Any = ...,
default: Any = ...,
type: ((str) -> _T@add_argument) | FileType = ...,
choices: Iterable[_T@add_argument] | None = ...,
required: bool = ...,
help: str | None = ...,
metavar: str | tuple[str, ...] | None = ...,
```

[bugfix] quick fix of convert_build_args_to_argparser

---

docs/compilation/compile_models.rst
mlc_llm/core.py
mlc_llm/quantization/autogptq_quantization.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/minigpt.py
mlc_llm/relax_model/param_manager.py
mlc_llm/relax_model/rwkv.py

As brought up in Issue #585, it would be great to include support for `.safetensors` files. 
This PR allows users to use `.safetensors` instead of the default `.bin` to compile their model. To trigger this, users would specify `use_safetensors=True` in `BuildArgs`, or equivalently `--use-safetensors` in CLI.
Updated docs correspondingly.
Tested:
- Building Llama-2-7b-chat-hf with `.safetensors`
- Building Llama-2-7b-chat-hf with `.bin`

Add support for safetensors

---

android/MLCChat/app/src/main/assets/app-config.json
docs/compilation/compile_models.rst
docs/compilation/distribute_compiled_models.rst
docs/deploy/ios.rst
docs/get_started/mlc_chat_config.rst
docs/get_started/try_out.rst
docs/prebuilt_models.rst
ios/MLCChat/app-config.json
ios/prepare_params.sh
site/index.md

We are in the process of upgrading to q4f16_1.
This PR keeps the docs in sync as the prebuilts for RedPajama are only at q4f16_0 atm.
An updated PR to docs can be sent once the prebuilts are updated and we confirmed that the flow works.
The how to compile model flow is kept at q4f16_1 as that already works and do not depend on prebuilt.

[DOCS] Update docs to keep in sync with current state

---

cpp/cli_main.cc
mlc_llm/utils.py
tests/debug/compare_lib.py

Depending on this PR: https://github.com/apache/tvm/pull/15464
On 7900 xtx. ROCm 5.6
```
~/mlc-llm (rocm ✔) ./build/mlc_chat_cli --local-id Llama-2-7b-chat-hf-q4f16_1
Use MLC config: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/params/mlc-chat-config.json"
Use model weights: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/params/ndarray-cache.json"
Use model library: "/home/bohan/mlc-llm/dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-rocm.so"
You can use the following special commands:
/help               print the special commands
/exit               quit the cli
/stats              print out the latest stats (token/sec)
/reset              restart a fresh chat
/reload [local_id]  reload model `local_id` from disk, or reload the current model if `local_id` is not …
```

[Backend] Add ROCm support

---

mlc_llm/core.py
mlc_llm/transform/__init__.py
mlc_llm/transform/rewrite_attention.py

With TVM built with `USE_CUTLASS`, adding `--use-cutlass-attn --use-cutlass-norm` enables offloading attention and layer / RMS norm to CUTLASS.
On RTX 4080 and Vicuna 7B, attention offload brings 12-15 tok / s improvement, and RMS norm offload adds another 4-5 tok / sec.

Enable offloading attention and layer / RMS norm to CUTLASS

---

mlc_llm/core.py
mlc_llm/quantization/__init__.py
mlc_llm/quantization/group_quantization.py
mlc_llm/quantization/quantization.py
mlc_llm/relax_model/param_manager.py

This PR introduces QuantSpecUpdator, which is a subclass of Relax's PyExprVisitor. The QuantSpecUpdator takes a ParamManager instance as the constructor input. It has the capability to update the QuantizationSpec for the parameters in this ParamManager.
We can inherit the QuantSpecUpdator to write the update logic in the subclass.
Each QuantizationScheme now optionally takes a QuantSpecUpdator class as input. In the model build flow, after the IRModule is constructed, we will use all the registered QuantSpecUpdator to go through the IRModule, and update the QuantizationSpec accordingly.
This PR also provides a demo example of inheriting QuantSpecUpdator (GroupQuantDemoUpdater in `group_quantization.py`). The demo's functionality is validated on RedPajama (by disabling the Matmul and …

[Quantization] QuantSpecUpdator visitor

---

mlc_llm/core.py
mlc_llm/transform/__init__.py
mlc_llm/transform/fuse_split_rotary_embedding.py

When matmuls for QKV projection are combined, we get an additional `split` overhead. This pass removes that overhead by "manually" fusing rotary embedding into the preceeding `split`.
On RTX 4080 and 7B, this gives 2-3 tok / s improvement. On 13B the improvement is smaller (~1 tok / sec).

Add pass to fuse split after QKV projection and rotary embedding

---

mlc_llm/core.py
mlc_llm/quantization/__init__.py
mlc_llm/quantization/ft_rowwise_quantization.py
mlc_llm/quantization/tir_utils.py
mlc_llm/transform/decode_transpose.py

This adds two Q schemes, `q4f16_ft` and `q8f16_ft`, for quantizing weights in the format as expected by the FT fp16 A - int B kernel. The resulting `decode -> matmul` sequences are offloaded to the FT kernel via CUTLASS BYOC.
The new Q scheme is a simple symmetric one where each column of `(K, N)` matrix is scaled by the corresponding element from a scale vector of shape `(N,)`. Each scale is calculated over the `K` axis. For int4, the weight matrix needs to be packed into int8 storage with shape `(K, N / 2)`. 
The quantized weight is further preprocessed by relax `cutlass.ft_preprocess_weight` packed call, which is made possible by the recent improvement https://github.com/mlc-ai/mlc-llm/pull/622. Moreover, based on the attributes of the consumer matmul or weight shape, we may need to …

FasterTransformer offloading integration

---

mlc_llm/core.py

This PR fixes an issue after weight conversion lifted to the early stage. After the lift, the tokenizer files are not yet copied to `local_id/params/` when dumping `mlc-chat-config.json`, and thus the dumped JSON file does not contain the tokenizer filenames.
This PR fixes this issue.

[Fix] Copy tokenizer files before dumping config

---

mlc_llm/core.py

MLP and QKV projection between two attention layers are completely static, so they can be put into a graph. Several matmuls, RMS norm, silu etc are executed in one graph launch. This brings 1-2 tok / sec speed up.

Enable cuda graph for the decoder

---

mlc_llm/core.py

The behavior of [os.path.basename()](https://docs.python.org/3/library/os.path.html#os.path.basename):
```python
os.path.basename("/models/Llama-2-7b-chat-hf")
>>> Llama-2-7b-chat-hf
os.path.basename("/models/Llama-2-7b-chat-hf/")
>>> ""
```
This method can remove potential trailing `/`: [os.path.normpath()](https://docs.python.org/3/library/os.path.html#os.path.normpath)
```python
os.path.normpath("/models/Llama-2-7b-chat-hf/")
>>> /models/Llama-2-7b-chat-hf
```
There aren't many places in the repo where we use os.path.basename. For those that do, they seem to be fine except in this case.
cc @junrushao

[Bug fix] Remove potential trailing backslash

---

docs/compilation/compile_models.rst
docs/compilation/distribute_compiled_models.rst
docs/deploy/cli.rst
docs/deploy/ios.rst
docs/get_started/mlc_chat_config.rst
docs/get_started/project_overview.rst
docs/get_started/try_out.rst
docs/prebuilt_models.rst
mlc_llm/core.py

This PR updates the documentation in the following aspects:
* (mainly) switch the quantization mode for RedPajama from `q4f16_0` to `q4f16_1`,
* add the WebGPU compilation commands for Llama2,
* update the iOS documentation page per latest changes,
* switch the model compilation commands for Vicuna-7B from `q3f16_0` to `q4f16_1`,
* switch some other occurrences of Vicuna-q3f16_0 to Llama2-q4f16_1.

[Docs] Update with RedPajama `q4f16_1` quantization

---

android/MLCChat/app/src/main/assets/app-config.json
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
docs/deploy/android.rst
ios/MLCChat/StartState.swift

This PR add a checker for both Android and iOS app, to make sure that the added model have supported model libs. Otherwise, the app will pop the information.
Meanwhile, this PR updates the doc for Android ADB, due to the outdated model path.

[Android][docs][iOS] Add model lib check and update docs

---

mlc_llm/transform/decode_take.py

FuseTIR do not support handle Relax.Constant params in call_tir, Relax.Constant is not supported in primitive functions.

[BugFix] Add take indices type check for FuseDecodeTake

---

cpp/llm_chat.cc
python/mlc_chat/chat_module.py

This PR fixes a bug in the embed step mentioned by @sudeepag earlier. It is thoroughly tested and returns the correct shape after each call to `embed_text` now.

[BugFix] Embed Step

---

cpp/conv_templates.cc
cpp/conversation.cc
cpp/conversation.h
cpp/llm_chat.cc
mlc_llm/core.py
mlc_llm/dispatch/dispatch_tir_operator.py
mlc_llm/relax_model/chatglm.py
mlc_llm/relax_model/modules.py
mlc_llm/utils.py

This PR introduces [ChatGLM2](https://huggingface.co/THUDM/chatglm2-6b) in MLC LLM, a bilingual (Chinese-English) chat model, recently showing superiority on chinese evaluation [leaderboards](https://cevalbenchmark.com/). The implemented architecture also supports the multilingual code generation model: [CodeGeeX2](https://huggingface.co/THUDM/codegeex2-6b).
**Some notes:**
- The ChatGLM2 tokenizer relies on a configuration file, that wraps the base sentencepiece tokenizer to add special tokens that support causal generation (see [tokenization_chatglm.py and tokenizer_config.json](https://huggingface.co/THUDM/chatglm2-6b/tree/main)). Currently, MLC LLM is not able to read from this configuration and still uses the base sentencepiece tokenizer. Since this special tokens prefix all the next …

[Model Support] ChatGLM2 & CodeGeeX2

---

docs/install/gpu.rst

This PR adds the ROCm installation docs. Right now we only support ROCm 5.6.

[Docs] ROCm installation docs

---

examples/python/sample_chat_module.py
python/mlc_chat/callback.py
python/mlc_chat/chat_module.py
python/mlc_chat/rest.py

This PR updates the REST API to support the new ChatModule API. 
- The non-streaming `/v1/chat/completions` and `/v1/completions` endpoints have been updated to use the new `generate` API. 
- As far as I can tell, it doesn't seem possible for us to use the `generate` API for the streaming use case in the `/v1/chat/completions` endpoint. This is because the endpoint needs to return a `StreamingResponse` with an `AsyncGenerator`.  However, this does not currently seem possible with the way callbacks are defined for the API (please let me know if you think otherwise). I've therefore kept the usage of the internal API for the streaming use case.
I've tested all the sample scripts, and have confirmed that they are running successfully.

Update REST API to support new ChatModule API

---

cpp/llm_chat.cc
examples/python/benchmark.py
python/mlc_chat/chat_module.py

This PR introduces the `RawGenerate` function to ChatModule for benchmarking purpose, which generates text by taking the input prompt and target generation length. The raw text generation does not use system prompt and ignores the stop tokens of the conversation template.
Based on the raw generation, this PR also brings the `benchmark_generate` method to the Python ChatModule. The function first warms up and then invoke the raw generation. After `benchmark_generate`, we can use `stats()` to get the generation performance of the model.
The `benchmark_generate` methods replaces the previous public `evaluate` method in the Python ChatModule.

[ChatModule] Raw text generation and benchmark

---

python/mlc_chat/chat_module.py

Previously the `benchmark_warmup` method does not reset chat before warming up.

[Fix][Python] Reset chat before benchmark warmup

---

docs/get_started/try_out.rst

This PR links the Jupyter notebook of Python API to the Python try-out tab.

[Docs] Link the Python API notebook to Python API try-out

---

docs/get_started/try_out.rst
examples/python/sample_mlc_chat.py
python/mlc_chat/chat_module.py

This PR uses the stdout stream for Python API examples so that the output will go to string which gives a smoother experience.

[Examples] Use stdout stream for Python API examples

---

docs/deploy/python.rst
python/mlc_chat/gradio.py

This PR reassembles the Gradio interface in accordance with the new Python API and ChatModule. Thanks to the overhaul of Python API (#645), the overcomplicated model reloading and selecting, as well as the ask-answer pipeline, is now hugely simplified. It now supports running LLM with much fewer lines of code.
The vision-related pipeline is temporarily removed, because the previous image reloading & pairing and prefilling logic are overcomplicated and not compatible with the new Python API anymore. To make it clean, we shall re-introduce it in the follow-up PRs after a multimodality-compatible ChatModule is merged.
Overall, this PR makes gradio **light-weighted** and **simple**, so that adding more functionalities is easy.

[Gradio] Update in accordance with new ChatModule

---

mlc_llm/core.py

This PR upstreams the cuBLAS offload from https://github.com/octoml/mlc-llm/pull/8. It adds a flag `--use-cublas` to enable cublas offloading on CUDA target.
cc @masahi

Add cublas offload

---

python/mlc_chat/rest.py

Small fix to change from `"None"` to `None`. The former is treated as a string and considers the user passing in a path.

[Bug fix] Small fix on RestAPIArgs

---

python/mlc_chat/chat_module.py

This fixes a bug where extra parameters loaded from the "mlc-chat-config.json" not supported by ChatConfig would cause ChatConfig initialization to fail and the program to crash.
#721

[BugFix] Fix extra ChatConfig args crash

---

cpp/cli_main.cc
mlc_llm/utils.py

This PR updates the way CLI parses device and device id.
Previously these two are separately assigned and parsed as the CLI arguments, and this PR changes the style to `name:id` which also aligns the Python API.
Validated on machine with two NVIDIA cards.

[CLI] Device parsing in `"device:id"` style

---

docs/install/tvm.rst

In the build instructions of TVM-unity, there is an issue with the variable "USE_OpenCL" in cmake additions, which should be capitalised (i.e. `USE_OPENCL`). 
If someone follows the guide and copies the instructions, they will not be compiling with support for OpenCL, unless they set the proper variable to ON.

Fix OPENCL variable in tvm.rst

---

cpp/cli_main.cc
mlc_llm/utils.py

Currently, we need to specify `mali` device when we use CLI, but cannot be auto-detected.

[Mali] Add CLI support for Mali device

---

mlc_llm/core.py
mlc_llm/utils.py

This PR will add a script dumped in debug dump mode for dlight bench benchmarking. Example see https://github.com/mlc-ai/dlight-bench/pull/6. An example of generated script can be found [here](https://gist.github.com/zxybazh/a74ebfd46393eed65a112b39f022a76c).
With this PR it would be easy to extract PrimFuncs from llm models and port to later development benchmarking.
CC: @sunggg

Add PrimFunc Benchmark Script Dump in Debug Dump Mode

---

cpp/conv_templates.cc
mlc_llm/utils.py

- Make the current WizardLM template only for WizardLM 7B (which does not support multi-round chat)
- All other WizardLMs (e.g. 13B and 70B) use Vicuna's conversation template (suggested by their repo)
- Create a template shared by WizardCoder and WizardMATH
- Tested: compiled and chat with WizardLM, Coder, and MATH
Part of the effort for bringing explicit support for [Wizard's series of models](https://github.com/nlpxucan/WizardLM): 
- #739

Add conversation template support for Wizard models

---

android/MLCChat/app/src/main/AndroidManifest.xml

Add the libOpenCL-pixel.so library as a dependency so it can be used on pixel phones. 
This depends on: https://github.com/mlc-ai/relax/pull/282 to be merged to be useful.

[Android] Add libOpenCL-pixel for supporintg Pixel phones.

---

mlc_llm/utils.py

This PR skips generating benchmark scripts when the NotImplementedError thrown by
https://github.com/apache/tvm/blob/unity/python/tvm/dlight/benchmark/extract.py#L138 is hit.

[Utils] Skip generating benchmark scripts in cases

---

cpp/conversation.cc
python/mlc_chat/chat_module.py

This change will automatically set the `offset` parameter if the `messages` parameter is set while still allowing the user to override the offset if necessary.

Automatically set 'offset' parameter if 'messages' parameter is set

---

cpp/conv_templates.cc
cpp/conversation.h
cpp/llm_chat.cc
docs/prebuilt_models.rst
mlc_llm/relax_model/gpt_neox.py
mlc_llm/utils.py

This PR refines the code completion support for MLC LLM. Previously, these code completion models used inappropriate templates, that were harming the completion task. This template was changed to execute the LM without memory, and also to ignore roles and separators. Code instruct models still use the normal conversational templates, since were trained for this purpose (e.g., CodeGeeX2, StableCode-Instruct). I was able to test it with the vscode hf code completion extension (solves #748, concludes #761). For this extension, models trained using the Fill-in-the-Middle objective are the most suitable (e.g., StarCoder). If you try others than these you may get worse results.
Additionaly this PR adds support for [StableCode-Instruct](https://huggingface.co/stabilityai/stablecode-instruct-alpha …

Improve code completion experience

---

mlc_llm/core.py
mlc_llm/relax_model/llama.py
mlc_llm/transform/fuse_split_rotary_embedding.py

… and cos functions.
Currently if you need to make the max sequence length of a llama2 model larger than 2048 it will run into issues actually handling more than 2048 tokens. The model would spit out garbage data or segfault if greater than 2048 tokens was sent in. The root cause I believe is due to this hardcoding of the sin and cos functions and I have been able to increase the max sequence length using these updates.

Update Llama2 cached sin/cos to use max_sequence_length

---

python/mlc_chat/rest.py

Currently getting this error when trying to call the rest api from the browser:
```
Access to XMLHttpRequest at 'http://127.0.0.1:8000/v1/chat/completions' from origin 'http://localhost:4000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

added cors to fast api

---

docs/deploy/android.rst

closes https://github.com/mlc-ai/mlc-llm/issues/769 to mention some necessary prerequisites for building on Android.

[Doc] Minor update to `Build Android Package from Source` section

---

mlc_llm/core.py
mlc_llm/transform/fuse_split_rotary_embedding.py

This one fixes error introduced in #780, where `max_seq_len` is set to `-1` when `max_seq_len` is not specified in the config file.

[FIX] Fix error `max_seq_len == -1`

---

mlc_llm/core.py

This is a better fix than https://github.com/mlc-ai/mlc-llm/pull/797. Otherwise split rotary fusion is not getting applied when `max_seq_len` is not given in the cmd line.
@Hzfengsy @junrushao

Optionaly use max_sequence_length in config for split rotary fusion

---

cpp/cli_main.cc
python/mlc_chat/chat_module.py

This PR updates the CLI interface to be more consistent with the ChatModule interface. Apart from updating the input args, the PR also aligns the error messages. Some examples below.
**Invalid model folder:**
```shell
./build/mlc_chat_cli --model hello-world-model
[18:37:21] /home/sudeepag/cli/mlc-llm/cpp/cli_main.cc:339: The model folder provided does not seem to refer to a valid mlc-llm model folder. Specifically, we cannot find `mlc-chat-config.json`, a required file. You should provide a path that contains the file. According to your input `hello-world-model`, we looked at folder(s):
- hello-world-model
- dist/prebuilt/hello-world-model
- dist/hello-world-model/params
- dist/prebuilt/mlc-chat-hello-world-model
```
**Invalid lib:**
```shell
$ ./build/mlc_chat_cli --model …
```

Update CLI to be more consistent with ChatModule

---

cpp/llm_chat.cc

In some cases, the model may produce a single EOS token for system prompt and cause assertion errors in https://github.com/mlc-ai/mlc-llm/blob/main/cpp/conversation.h#L198. It is actually not necessary to decode the system prompts since it is followed by users inputs.

Disable decoding for system prompts

---

mlc_llm/core.py
mlc_llm/quantization/__init__.py
mlc_llm/quantization/autogptq_quantization.py
mlc_llm/quantization/quantization.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/param_manager.py
mlc_llm/utils.py

This PR refactors the AutoGPTQ integration to better align with the framework design. The PR, meanwhile, supports the AutoGPTQ quantization in MLC LLM with matmul combination.
With this PR, you will be able to compile Llama2 using the following command:
```python
python -m mlc_llm.build --model=Llama-2-7b-chat-hf --quantization autogptq_llama_q4f16_1 --target cuda
```
to use the AutoGPTQ quantization. **Note that the first run may take around 10 min for AutoGPTQ quantization computation, and the following runs will be much quicker.** The AutoGPTQ quantization requires the Python `auto_gptq` package to have version at least 0.2.0.
Co-authored-by: Ruihang Lai <ruihangl@cs.cmu.edu>

[Quantization] AutoGPTQ refactor and matmul combination support

---

mlc_llm/utils.py

As reported in #813, we need pytest package in the default building flow. It is indeed needed when we want to dump scripts for debugging, but should be removed in the default building flow.
cc @zxybazh

[Minor] Remove PyTest Dependencies by default

---

docs/get_started/try_out.rst

Converted --local-id to --model to ensure that the commands work 😄  
Moved the note about needing to have the vulcan driver before the core instructions -- this should be done before the rest of the instructions, so should appear before then.

Update try_out.rst (changed --local-id param to --model and moved notes about drivers.

---

mlc_llm/core.py
mlc_llm/relax_model/chatglm.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/minigpt.py
mlc_llm/relax_model/rwkv.py

This does not seem to get set for most cases since the config constructed by the model creation is never actually passed back out and therefore this value does not get set for llama models. 
Was getting while building my llama model
```
File "/home/noah/anaconda3/envs/tvm-build-venv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/noah/anaconda3/envs/tvm-build-venv/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/noah/workplace/mlc-llm/mlc_llm/build.py", line 13, in <module>
main()
File "/home/noah/workplace/mlc-llm/mlc_llm/build.py", line 10, in main
core.build_model_from_args(parsed_args)
File "/home/noah/workplace/mlc-llm/mlc_llm/core.py", line 578, in …
```

Make max_sequence_length config check optional.

---

cpp/llm_chat.cc

This PR fixes a long-hiding bug which makes the conversation (or LM generation history) not be properly shifted and lead to random text generation when "fake shift" happens.

[Fix][ChatModule] Generation history not properly shifted

---

mlc_llm/core.py
mlc_llm/relax_model/rwkv.py

core.py:362引起报错：
把in改成hasattr修复。另外rwkv的world系列模型在hf是以大写开头的，这里把rwkv的只判断小写开头也顺手改掉。

fix a small bug in mod_transform_before_build

---

docs/install/gpu.rst

fix typo of #784
the view of document
the Origininal rst

[Doc]  fix-missing-code-block of `Download OpenCL ICD loader and manually add libmali to ICD` section

---

mlc_llm/relax_model/llama.py
mlc_llm/transform/fuse_split_rotary_embedding.py

This PR fixes an issue introduced by #780, which broke our intended behavior to make the cos/sin shape independent of the max sequence length, so that no matter what max sequence length people use, they can always use a same set of prebuilt weight and do not need to clone different weight repositories. This intended behavior is broken by #780.
However, it is true that the needs for larger max sequence length are growing. Prior to #780, when the max sequence length is larger than 2048, the cached cos/sin do not work anymore and break. To be compatible as much as possible, this PR changes the behavior to "taking the maximum value of 2048 and the specified max sequence length when building the model lib".
With this fix, when the maximum sequence length is smaller than 2048, we are still able …

[Fix] Lib with small `max_seq_len` incompatible with prebuilt weight

---

docs/deploy/android.rst

the model weights to be copied to device is created under dist/model_name/params

Update android.rst: fix commands of copying generated model weights

---

mlc_llm/core.py
mlc_llm/utils.py

Add nvidia/jetson target for cross-compile model. #847 
Also add `cc_path` parameter at `mlc_llm.BuildArgs` for using custom cross compiler which currently only used for cross-compile for nvidia/jetson device.
Usage : just set target according to user's jetson board name (ex, nvidia/jetson-agx-xavier)
``` python
build_args = mlc_llm.BuildArgs(
hf_path="togethercomputer/RedPajama-INCITE-Chat-3B-v1",
quantization="q4f16_1",
target="nvidia/jetson-agx-xavier")
```
If someone wants to use custom cross compiler (default : `""` but when target is nvidia/jetson, automatically converted `/usr/bin/aarch64-linux-gnu-g++`)
``` python
build_args = mlc_llm.BuildArgs(
hf_path="togethercomputer/RedPajama-INCITE-Chat-3B-v1",
quantization="q4f16_1",
target="nvidia/jetson-agx-xavier", …
```

Add nvidia/jetson target for cross-compile model

---

mlc_llm/relax_model/param_manager.py

Prior to this PR, ParamManager always assumes (and asserts) all the parameters have static shape. As MLC LLM goes to the support for LoRA, dynamic vocabulary size and more cases, the assumption of static-shape parameters no longer holds.
This PR updates ParamManager so that it supports dynamic-shape parameters.

[ParamManager] Support dynamic-shape parameters

---

mlc_llm/core.py
mlc_llm/relax_model/llama.py
mlc_llm/transform/fuse_split_rotary_embedding.py

This PR supports Llama2 with the online rotary embedding computation and removes the dependency on the cached cos/sin values, so that no matter how much the max-seq-len of the newly built libraries is, the prebuilt weights can be used without issues (hopefully).
Tested `q4f16_1` on RTX 4090 and observed no performance regression.

[Llama] Online rotary embedding

---

mlc_llm/relax_model/llama.py

This PR uses a `tvm.tir.Var` to represent the `vocab_size` when compiling Llama models. 
The goal is to reuse Llama-2's model library when running its model variants like WizardMath. The default `vocab_size` is `32000`, but some models can have `32001`. 
Previous behavior:
```python
from mlc_chat import ChatModule
cm = ChatModule(
model="dist/mlc-chat-WizardMath-7B-V1.0-q4f16_1",
lib_path="dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-cuda.so"
)
output = cm.generate(prompt="hi")
```
```bash
...
RuntimeError: Check failed: input_shape[i] == reg (32001 vs. 32000) : ErrorContext(fn=prefill, loc=param[3], param=params, annotation=R.Tuple(R.Tensor((32000, 512), dtype="uint32"), ...)  match_cast error,  shape[0] mismatch to specified constant.
``` …

Use dynamic vocab_size for llama

---

cpp/llm_chat.cc

MSVC we are using in nightly wheels doesn't seem to support implicit conversion from `std::filesystem::path` to `std::string` according to the error messages below:
```
llm_chat.cc(211,44): error C2664: 'std::string mlc::llm::LoadBytesFromFile(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
llm_chat.cc(212,32): error C2664: 'std::string mlc::llm::LoadBytesFromFile(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
llm_chat.cc(217,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of …
```

Fix windows build

---

cpp/llm_chat.cc

Following up with the previous commit, MSVC is still unhappy saying:
```
D:\a\package\package\mlc-llm\cpp\llm_chat.cc(209,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\fstream(29,23): message : see declaration of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
D:\a\package\package\mlc-llm\cpp\llm_chat.cc(210,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of 'std::filesystem::path' …
```

Fix windows build again

---

cpp/llm_chat.cc
python/mlc_chat/base.py
python/mlc_chat/rest.py

Set random seed uniformly for torch, numpy, random, and lm_chat. Expose arg control of the random seed to the mlc-chat rest server. Maintain use of `std::random_device{}` by default in lm_chat if seed is unset.

[Chat] Support deterministic runtime

---

cpp/llm_chat.cc
python/mlc_chat/chat_module.py

To run multi-GPU inference, one could do the following:
```python
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout
cm = ChatModule(model="llama-2-7b-chat-hf-q4f16_1")
output = cm.generate(
prompt="Hi",
progress_callback=StreamToStdout(callback_interval=2),
)
print(f"Statistics: {cm.stats()}\n")
```

[Multi-GPU] Use Process-based Workers

---

docs/deploy/ios.rst

The link of previous iOS App Store download badge is broken. Updated to a new one.

[Docs] Fix App Store download badge

---

mlc_llm/utils.py

Before this change, int64 is used as index/loop variables in quantization as the default dtype for integers in TVM. However, int64 is not always available on certain GPU architectures. This PR fixes this behavior by force-converting the index/loop variables back to int32.

[Bugfix] Always use int32 in quantization

---

mlc_llm/models/__init__.py
mlc_llm/models/llama.py
mlc_llm/models/llama_param_map.py
mlc_llm/models/model_config_base.py
mlc_llm/param_loader/__init__.py
mlc_llm/param_loader/hf_torch_loader.py
mlc_llm/param_loader/param_mapping.py
tests/python/test_model_llama.py
tests/python/test_param_loader_llama.py

This PR introduces `mlc_llm.param_loader` as a new subpackge of MLC LLM compiler, with the following components:
**`ParameterMapping`** that describes how a MLC parameter maps to one or more PyTorch parameters by their names. For example, the MLC parameter `qkv_proj.weight` corresponds to three parameters in PyTorch, which are `q_proj.weight`, `k_proj.weight` and `v_proj.weight`, and to map PyTorch parameters to this MLC parameter, the mapping function is:
```python
lambda q, k, v: np.concatenate([q, k, v], axis=0)
```
**`HFTorchLoader`** that loads HuggingFace's PyTorch parameters in a certain ordering to save peak memory footprint. More specifically, HuggingFace shards the full parameter set into a few `.bin` files of more reasonable size (usually less than 10G each), and the loader …

Parameter Loading for New `nn.Module` API

---

cpp/llm_chat.cc

This PR fixes a issue where the order of `temperature` and `top_p` is inconsistent between relax and mlc-llm.
In [relax function implementation](https://github.com/mlc-ai/relax/blob/afaeeb1381c91362f4821db7e5365fe30529b29d/src/runtime/relax_vm/lm_support.cc#L277) the function calls temperature first so moving the order in mlc-llm.
```c++
int SampleTopPFromLogits(NDArray logits, double temperature, double top_p, double uniform_sample) ...
```
And this function is later used via FFI
```c++
TVM_REGISTER_GLOBAL("vm.builtin.sample_top_p_from_logits").set_body_typed(SampleTopPFromLogits);
```
In MLC it's called via FFI
```c++
auto fsample_topp_from_logits_ptr =
tvm::runtime::Registry::Get("vm.builtin.sample_top_p_from_logits");
ICHECK(fsample_topp_from_logits_ptr)
<< "Cannot find env function …
```

[BugFix] Correct Order of Temperature and Top_P in Sample Function

---

cpp/llm_chat.cc

When using disco runtime, prefill time calculated does not reflect the actual prefill time because the runtime is async. We add a sync_worker before the time measuring

Fix prefill stats

---

mlc_llm/relax_model/llama.py

I found that latest MLCLLM project cannot compile vicuna. The error show "max_sequence_length" has multiple value. 
The config.json in Llama and Llama-2 is different:
Llama config has max_sequence_length value
Llama2 config dont has max_sequence_length value
After delete max_sequence_length param setting in LlamaConfig() will compatible vicuna and llama2

Compatible with vicuna

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/model-request.md
README.md
android/README.md
cpp/README.md
docs/index.rst
docs/privacy.rst
ios/MLCSwift/README.md
ios/README.md
python/README.md
site/_config.yml
site/index.md

According to existing effort:
- https://github.com/mlc-ai/mlc-llm/pull/962
- https://github.com/mlc-ai/mlc-llm/pull/961
However, the remaining item is that we need to figure out a way to redirect `llm.mlc.ai/docs/*` to `llm.mlc.ai/*`

[Doc] Update URL to llm.mlc.ai

---

cpp/conv_templates.cc
mlc_llm/core.py
mlc_llm/utils.py

To build the model on macOS:
```
git clone https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1
python build.py --model <path_to_model_checkout> --quantization q4f16_1 --target metal
./build/mlc_chat_cli --model Mistral-7B-Instruct-v0.1-q4f16_1
```

Minimal changes to get Mistral-7B-Instruct-v0.1 working

---

python/mlc_chat/chat_module.py

1. add `num_shards` and `max_window_size` in ChatConfig
2. correctly handle partial custom chat config
This PR fixes #976

[BugFix][Python] Fix custom chat config parsing

---

docs/deploy/python.rst

Raw Text Generation [tutorial](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_raw_text_generation.ipynb) added to docs. Concludes #773.

[Doc] Raw Text Generation tutorial

---

CMakeLists.txt
cpp/cli_main.cc
mlc_llm/core.py
mlc_llm/transform/rewrite_attention.py

Following https://github.com/apache/tvm/pull/15831, this is the mlc-side change to enable MQA offload. 
To use the new option, `use_flash_attn_mqa`, `${TVM_HOME}` must point to a TVM build with that commit. In particular, since the TVM submodule pulled by mlc is [a custom one](https://github.com/mlc-ai/relax) that doesn't support flash attention at all, it cannot use this new feature. The option is set to False by default to avoid potential troubles.

Enable offloading multi-query attention by Flash Attention

---

docs/install/tvm.rst

A few changes:
* CUDA 11.6 is deprecated
* Support for CUDA 12.2
* Support for ROCm 5.7; Existing ROCm 5.6 wheel is renamed from rocm to rocm56
* Support for Python 3.12

Add pypi wheels for ROCm 5.7 and CUDA 12.2

---

mlc_llm/relax_model/llama.py

Single-letter variable names may be difficult to recognize when encountered in other contexts.  This commit changes the name of the `tir.Var` used for the vocab size in the llama model definition, so that it can be more easily recognized when occurring in error messages and when used in `relax.transform.BindSymbolicVars`.

[Llama] Rename dynamic vocab size from "v" to "vocab_size"

---

mlc_llm/core.py
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/llama.py

I found myself repeatedly copy-pasting the cryptic code
```
num_key_value_heads = (
config.num_key_value_heads is None
and config.num_attention_heads
or config.num_key_value_heads
) 
```
to get the kv head size correctly. Also hit a bug where `config.num_key_value_heads` is accessed directly but found to be None (vicuna). 
I added a helper function to `LlamaConfig` to avoid these troubles.
@junrushao @LeshengJin

Clean up `num_key_value_heads` accessor

---

cpp/llm_chat.cc

I am using openchat v3.2 which uses <|end_of_turn|> as the stop string, and when the bot replied with short messages, e.g. "Hi, are you ok?<|end_of_turn|>", i got something like "Hi, are you ok?<|" returned to me. I narrowed it down to the backtracking loop and fixed the bug, which was that backoff was compared to `output_ids_.size()` while output_ids_.size() was decreasing due to `pop()`. Along the way I noted and fixed another bug (backoff was too small by 1 as it wasn't incremented if we used `break` to leave the loop.
Bug 1: old code would stop early because output_ids was shortened in-place during the loop
Bug 2: off-by-one in backoff size due to break

Fix two bugs in kv-cache backtrack loop

---

mlc_llm/build.py
mlc_llm/core.py

This PR adds an optional `--pdb` flag to the `build.py` script.  If passed, any exception raised that would otherwise terminate the script will first enter a pdb post-mortem, allowing the error to be inspected.

[Build] Added --pdb flag to build.py, drop into pdb on error

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/StartView.kt
android/prepare_libs.sh

This PR changes the `Toast` to `AlertDialog` in Android error reporting, for better demonstration. In addition, in the dialog, we support `copy` button to copy the error message into clipboard directly.
cc: @spectrometerHBH @junrushao

[Android] Use `AlertDialog` instead of `Toast`

---

docs/community/guideline.rst
docs/conf.py
docs/deploy/python.rst

For `ChatModule` python API, linked in-code comments to documentation for `ChatConfig`, `ConvConfig`, and `GenerationConfig` at https://llm.mlc.ai/docs/compilation/python.html#api-reference.
For model compilation python API, fixed previous issue where sphinx cannot import `mlc-llm`. Now `BuildArgs` and `build_model()` documentation should show up on https://llm.mlc.ai/docs/compilation/python.html#api-reference.

Add doc for ChatConfig, ConvConfig, GenerationConfig, BuildArgs

---

cpp/conv_templates.cc
mlc_llm/core.py
mlc_llm/relax_model/stablelm_3b.py
mlc_llm/utils.py

Support for the recently released [stablelm-3b-4e1t](https://huggingface.co/stabilityai/stablelm-3b-4e1t) model. `mlc_llm/relax_model/stablelm_3b.py` is a copy of `mlc_llm/relax_model/llama.py` with a few key modifications:
1. `RotaryEmbedding` from `GPT-NeoX`.
2. `LayerNorm` instead of `RMSNorm`.
Also, the stop token for this model is token `0`, so I had to add a different conv template `StableLM3B`, which is identical to the `LM` conv template, except for the stop token. There's a lot of room for code deduplication between `mlc_llm/relax_model/stablelm_3b.py` and `mlc_llm/relax_model/llama.py`, since they're nearly identical.
Build command:
```bash
python build.py --model path/to/stablelm-3b-4e1t --quantization q4f16_1 --target metal --use-safetensors
```

Support for the Stable LM 3B model

---

cpp/base.h
cpp/image_embed.h
cpp/llm_chat.cc
cpp/llm_chat.h
cpp/random.h
cpp/support.h
cpp/tokenizers.cc
cpp/tokenizers.h

This PR separates out the tokenizer creation function, the random number generator out from `llm_chat.cc` as a preparation step for batching inference support, since these functions/modules are also used in the same way in batching inference.

[CPP] Separate common utils out from llm_chat.cc

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/data.cc
cpp/serve/data.h
cpp/serve/request.cc
cpp/serve/request.h
cpp/serve/request_state.cc
cpp/serve/request_state.h

This PR sets up the basic data structures (multi-modality data, requests, etc.) for the continuous batching serving support.
Specifically, this PR contains
* multi-modality `Data` class,
* supports text and token ids as data for now, embedding data will be introduced in the future
* `Request` class for user-submitted requests,
* `RequestState`/`RequestModelState` class for the engine to maintain the generation status of requests.
* Configuration data classes for generation and KV cache.

[Serving] Basic data structure set up

---

mlc_llm/core.py
mlc_llm/transform/fuse_split_rotary_embedding.py

Prior to this commit, the `transform.fuse_split_rotary_embedding` function was only applicable to the `decode` function of a Llama-type model.  This was due to the sequence length being restricted to one, both in the pattern-match rule and in the `split_rotary` function, and the function being restricted to operate only on the `decode` function.
This commit updates the `transform.fuse_split_rotary_embedding` pass to be a `tvm.ir.transform.Pass`, operating on all applicable matched in the `IRModule`.  The `split_rotary` function is now produced as a fully-generic function, with static parameters substituted in afterwards.  At this stage, the sequence length is retained as a dynamic parameter, such that it can be used by the `prefill` function.

[Transform] Apply split_rotary optimization on prefill

---

mlc_llm/core.py
mlc_llm/transform/fuse_split_rotary_embedding.py

This reverts commit b9179cfdf02e041be15871b36e74400ab9001921 as elaborated here https://github.com/mlc-ai/mlc-llm/pull/1033#issuecomment-1760386712

Revert "[Transform] Apply split_rotary optimization on prefill (#1033)"

---

mlc_llm/relax_model/llama.py

PR https://github.com/mlc-ai/mlc-llm/pull/973 was introduced to support Llama-1 variants since their hf model config directly encodes `max_sequence_length` unlike Llama-2 that uses `max_position_embeddings` instead. 
Unfortunately, it was a breaking change for Llama-2 variants like CodeLlama. 
Therefore, this PR fixes that problem and reads both Llama-1 & Llama-2 configs correctly. 
cc. @qc903113684

[BugFix] Set the right `max_sequence_length` for both Llama-1 and Llama-2 families

---

docs/install/mlc_llm.rst
docs/install/tvm.rst

`--force-reinstall` will reinstall all dependencies to a python package, which is unnecessary. `-U` is a better choice in this case.

[Doc] Use -U instead of --force-reinstall

---

cpp/llm_chat.cc
mlc_llm/core.py
mlc_llm/relax_model/llama.py
mlc_llm/transform/decode_take.py
mlc_llm/transform/fuse_split_rotary_embedding.py
tests/debug/test_batching_llama.py

This PR introduces the initial batched input support for llama models. To make the code managable, we keep both the single-sequence handling flow and the batching handling flow in the Llama modeling.
Now, with `--enable-batching` as a build argument, we build Llama for the batched version.
NOTE: The paged attention kernel/TIR func are not included in this PR, so currently the built library with batching enabled is not runnable. We will follow up with the attention kernel in the future.
This PR guarantees that the existing single-sequence inference (Python API, CLI, etc.) is not broken.
P.S.. The batching flow is subject to bug fixes as we integrate with the attention function and run the e2e flow in the future.

[Model] Initial batching support for Llama

---

mlc_llm/relax_model/stablelm_3b.py

Building StableLM 3B based models was throwing an exception due to an unrelated change introduced in #1027. Also, pulled in the Llama change to rename the vocab size variable from #1019.
```python
File "/Users/jeethu/Developer/mlc-llm/build.py", line 4, in <module>
main()
File "/Users/jeethu/Developer/mlc-llm/mlc_llm/build.py", line 42, in main
core.build_model_from_args(parsed_args)
File "/Users/jeethu/Developer/mlc-llm/mlc_llm/core.py", line 644, in build_model_from_args
mod = mod_transform_before_build(mod, param_manager, args, model_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jeethu/Developer/mlc-llm/mlc_llm/core.py", line 403, in mod_transform_before_build
num_key_value_heads = …
```

Fix Stable LM 3B build

---

mlc_llm/core.py
mlc_llm/relax_model/minigpt.py

This commit removes the `if`/`elif` chain in `core.py`, where the body of each conditional assigns the same `mod, param_manager, params, model_config`, and is identical except for the choice of model being built.

[Core] Remove duplication in MODEL.get_model calls

---

mlc_llm/core.py
mlc_llm/relax_model/param_manager.py
mlc_llm/utils.py

This commit replaces the single-parameter
`relax_model.param_manager.create_quantize_func` function with a method on the `ParamManager`, `create_parameter_transformation`.  This avoids potential typos between `param_manager` as the imported Python module `mlc_llm.relax_model.param_manager` and an instance of the `ParamManager` class named `param_manager`, and makes the functionality easier to find.
This function also takes an optional `optimize_parameter_order` flag, defaulting to `True`, which applies the `ReorderTransformFunc` pass. Since the `ReorderTransformFunc` is intended to be used with several configuration objects owned by `ParamManager`, this simplifies the common path of producing an optimally-ordered parameter transformation module.

[ParamManager] Cleanup creation of quantization IRModule

---

mlc_llm/core.py

Fixed a minor typo that was breaking building models.
```
🚀 python build.py --model ~/LLM_models/stablelm-3b-4e1t --quantization q4f16_1 --target metal --use-safetensors --use-cache=0
Using path "/Users/jeethu/LLM_models/stablelm-3b-4e1t" for model "stablelm-3b-4e1t"
Host CPU dection:
Target triple: arm64-apple-darwin23.0.0
Process triple: arm64-apple-darwin23.0.0
Host CPU: apple-m1
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
File "/Users/jeethu/Developer/mlc-llm/build.py", line 4, in <module>
main()
File "/Users/jeethu/Developer/mlc-llm/mlc_llm/build.py", line 42, in main
core.build_model_from_args(parsed_args)
File …
```

Minor typo fix

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/data.cc
cpp/serve/request.cc
cpp/serve/request.h
python/mlc_chat/__init__.py
python/mlc_chat/serve/__init__.py
python/mlc_chat/serve/_ffi_api.py
python/mlc_chat/serve/config.py
python/mlc_chat/serve/data.py
python/mlc_chat/serve/request.py

This PR introduces the Python-side abstraction for the basic data structures introduced in #1046. These abstraction in Python leverages the object system and FFI in TVM.

[Serving] Python-side data structure abstractions

---

cpp/llm_chat.cc
mlc_llm/relax_model/llama.py

PR #1048 updated the signature of softmax in the built model library and changed the temperature buffer shape in ChatModule. This causes some existing demo unable to run since we did not do a round of model library update.
This PR reverts the ChatModule change, and adds back the softmax function in non-batching case. With this PR, the regression should be fixed.

[Fix] ChatModule incorrect temperature buffer shape

---

mlc_llm/core.py

The pass `fuse-split-rotary` assumes the compute dtype is fp16, which usually is, but in certain cases, e.g. `q0f32` and `q4f32_1`, the compute is based on fp32 instead. This PR strengthens the check guard.

[Bugfix] Compilation Error in q4f32_1

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h
cpp/serve/sampler.cc
cpp/serve/sampler.h
cpp/serve/tokenizer.cc
cpp/serve/tokenizer.h
python/mlc_chat/serve/config.py

This PR introduces the backbone runtime modules
* `ModelModule`, which runs LLM with an internally maintained KV cache,
* `TokenizerModule`, which encodes text to tokens and decodes tokens to text,
* `SamplerModule`, which helps compute prob distribution from logits and sample tokens from prob distributions.
Meanwhile this PR adds `stop_tokens` to GenerationConfig.

[Serving] Model/Sampler/Tokenizer runtime modules

---

cpp/serve/engine.cc
python/mlc_chat/serve/data.py
python/mlc_chat/serve/engine.py
tests/debug/benchmark_latency.py
tests/debug/test_serve_engine.py

This PR introduces the high-level `generate` function to do text generation for a batch of input prompts. This PR also adds the initial latency benchmark scripts.
Depending on #1075

[Serving] Engine "`generate`" function and latency benchmark

---

cpp/cli_main.cc
docs/deploy/cli.rst
docs/deploy/python.rst
python/mlc_chat/chat_module.py

This PR addresses a couple of confusions on `model` vs.  `model_lib` vs. `lib_path`. See the relevant discussions here: https://github.com/mlc-ai/mlc-llm/issues/1080#issuecomment-1766916967
- It disables the ability to override `ChatConfig.model_lib` in Python API to avoid confusion against `ChatModule.lib_path`. Now if a user attempts to override `ChatConfig.model_lib`, they will see a warning message and the override will be ignored
```
...../chat_module.py:359: UserWarning: WARNING: Do not override "model_lib" in ChatConfig. This override will be ignored. Please use ChatModule.lib_path to override the full model library path instead.
```
- It supports the same ability to override the full model library path in C++ CLI with `lib_path` argument. Some improvements on the helper message of …

Support lib_path override in C++. Improvements on docs and error messages

---

mlc_llm/core.py

As we discussed in #1085, we should disable disco for q4f16_ft and q8f16_ft quantization for now.

Disable Disco for q4f16_ft and q8f16_ft quantization

---

.github/workflows/python_lint.yml
ci/task/black.sh
ci/task/isort.sh

This PR enables two Python formatters "black" and "isort" on the following directory:
- `./python/`
- `./tests/python/`
Enabling pylint and mypy is left for future work

Enable Python Linter

---

.github/workflows/python_lint.yml
ci/task/black.sh
ci/task/mypy.sh
ci/task/pylint.sh
pyproject.toml
python/mlc_chat/compiler/model/llama_parameter.py
python/mlc_chat/compiler/parameter/mapping.py
python/mlc_chat/support/config.py
tests/python/parameter/test_hf_torch_loader.py

This PR establishes the initial Python tooling infra with Pylint and
Mypy. Currently only the newest modules, i.e. `mlc_chat.support` and
`mlc_chat.compiler` are covered, and we expect to cover the entire
package, as being tracked in https://github.com/mlc-ai/mlc-llm/issues/1101.

Add Basic Pylint and Mypy Tooling

---

python/mlc_chat/support/auto_config.py
python/mlc_chat/support/auto_weight.py
tests/python/test_auto_config.py
tests/python/test_auto_weight.py

P0. [LLM-H1-1]
Smart path finding functions:
```python
def find_config_json(config_path: str) -> str:
"""Find and return the path to config.json. If config_path is a directory,
it looks for config.json within it.
"""
def find_weight(weight_path: str, config_json_path: str) -> str:
"""Find the weight directory.
If user provides `weight_path`, check if it exists.
If not,
Step 1. Find the `weight_path` in config file
Step 2. Find the weight files in the same directory as config.json
"""
def validate_weight_format(weight_path: str, weight_format: str):
"""Valide weight format. Available weight formats:
- PyTorch (Validate via checking pytorch_model.bin.index.json)
- SafeTensor (Validate via checking model.safetensors.index.json)
- AWQ
- GGML/GGUF
"""
```
cc: @junrushao @zxybazh

[Slim-LM] Smart path finding for config and weight

---

mlc_llm/core.py
mlc_llm/transform/rewrite_attention.py

Prior to this commit, `mlc_llm.transform.rewrite_attention` updated a single function.  This commit modifies it to instead be a transform operating on any pattern matches within an `IRModule`.

[Transform] Provide IRModule transform for rewrite_attention

---

mlc_llm/core.py
mlc_llm/relax_model/param_manager.py

Prior to this commit, `ParamManager.transform_quantize` function took as input functions with separate parameters for each weight tensor, and produced output functions with a tuple parameter for all weights. Because `LiftTransformParams` had the same convention, neither could be applied as part of the same build flow.
This commit updates `ParamManager.transform_quantize` pass to produce outputs with separate tensor parameters, using the `BundleModelParams` transform to later combine them into a single tuple parameter.  The analogous change was also performed for `LiftTransformParams` as part of https://github.com/apache/tvm/pull/15657.
In addition, prior to this commit, the `ParamManager.transform_dequantize` function operated directly on a `IRModule` object.  As a result, any debug …

[ParamManager] Use BundleModelParams for transform_dequantize

---

mlc_llm/core.py
mlc_llm/relax_model/param_manager.py

Reverts mlc-ai/mlc-llm#1056
This causes a regression impacting all MLC LLM nightlies as it violates the existing calling convention in MLC Chat runtime. An example: https://github.com/mlc-ai/mlc-llm/issues/1060#issuecomment-1776761032

Revert "[ParamManager] Use BundleModelParams for transform_dequantize"

---

python/mlc_chat/chat_module.py

This PR removes an inaccurate warning from #1086, which warns about `model_lib` overriding regardless of whether or not it's actually overridden. With this commit, we only warn if its value is not None.

Remove inaccurate warning message

---

cpp/llm_chat.cc
python/mlc_chat/chat_module.py
python/mlc_chat/interface/openai_api.py
python/mlc_chat/rest.py

**Add support for additional parameters in REST API**
This PR extends support for the following rest API parameters in accordance with [OpenAI API reference](https://platform.openai.com/docs/api-reference/chat/create) :
- temperature
- top_p
- n
- stop
- max_gen_len
- presence_penalty
- frequency_penalty 
The PR also adds support for passing conversation history in the chat completion endpoint.

[REST] OpenAI compatible Rest API

---

mlc_llm/core.py
mlc_llm/relax_model/param_manager.py

Prior to this commit, `ParamManager.transform_quantize` function took as input functions with separate parameters for each weight tensor, and produced output functions with a tuple parameter for all weights. Because `LiftTransformParams` had the same convention, neither could be applied as part of the same build flow.
This commit updates `ParamManager.transform_quantize` pass to produce outputs with separate tensor parameters, using the `BundleModelParams` transform to later combine them into a single tuple parameter.  The analogous change was also performed for `LiftTransformParams` as part of https://github.com/apache/tvm/pull/15657.
In addition, prior to this commit, the `ParamManager.transform_dequantize` function operated directly on a `IRModule` object.  As a result, any debug …

[ParamManager][Redo] Use BundleModelParams for transform_dequantize

---

docs/install/mlc_llm.rst

32bit version of the zstd.dll library was causing issues, so updated the doc to be more specific and download the 64bit version.

added details to windows installation

---

cpp/cli_main.cc

When user use command `mlc_chat_cli --help`, the output will be something like
Usage: `mlc_chat` [--help] ...
That's because the program name specified in `cli_main.cc` is "mlc_chat".   
It will be less confusing if the output of help info shows
Usage: `mlc_chat_cli `[--help] ...

Make the help info consistent with program name

---

pyproject.toml
python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/model/llama_model.py

Depends on https://github.com/apache/tvm/pull/16007

Support parameter packing

---

python/mlc_chat/cli/compile.py
python/mlc_chat/compiler/__init__.py
python/mlc_chat/compiler/model/__init__.py
python/mlc_chat/compiler/model/model.py
python/mlc_chat/support/auto_config.py

This PR adds support for compiling a preset of models without having to provide a `config.json` on disk using the commands below:
```diff
python -m mlc_chat.cli.compile \
--quantization q4f16_1 -o /tmp/1.so \
-       --config /models/Llama-2-7b-chat-hf
+       --config llama2_7b
```
This allows easier testing and binary distribution without having to depend on external model directory.

Compile Model Preset without External `config.json`

---

python/mlc_chat/compiler/model/llama_model.py
python/mlc_chat/support/auto_config.py

Existing dlight optimization only works for NT matmul, but not NN. As a result, the new `nn.Module`-based implementation, which uses NN matmul, fails compilation at HEAD for now. This PR fixes this issue by tweaking `k` to the preferred layout.
The following commands now work with the new compilation pipeline:
```bash
python -m mlc_chat.cli.compile --config llama2_7b  --quantization q4f16_1 -o /tmp/1.so
python -m mlc_chat.cli.compile --config llama2_13b --quantization q4f16_1 -o /tmp/1.so
python -m mlc_chat.cli.compile --config llama2_70b --quantization q4f16_1 -o /tmp/1.so
```
Note that the quantization algorithm per se, `q4f16_1`, has not been implemented yet, meaning this code path is not yet ready for use so far.

Update attention layer

---

mlc_llm/core.py
mlc_llm/transform/fuse_split_rotary_embedding.py

Prior to this commit, the `transform.fuse_split_rotary_embedding` function was only applicable to the `decode` function of a Llama-type model.  This was due to the sequence length being restricted to one, both in the pattern-match rule and in the `split_rotary` function, and the function being restricted to operate only on the `decode` function.
This commit updates the `transform.fuse_split_rotary_embedding` pass to be a `tvm.ir.transform.Pass`, operating on all applicable matched in the `IRModule`.  The `split_rotary` function is now produced as a fully-generic function, with static parameters substituted in afterwards.  At this stage, the sequence length is retained as a dynamic parameter, such that it can be used by the `prefill` function.
This commit reapplies the reverted commit …

[Transform][Redo] Apply split_rotary optimization on prefill

---

mlc_llm/core.py

Fixes a bug introduced in https://github.com/mlc-ai/mlc-llm/pull/1052, where use of the `--use-flash-attn-mqa` flag on a model that doesn't use MQA would prevent the use of CUTLASS attention at all.

Apply rewrite for normal attention and MQA

---

mlc_llm/build.py

This is a follow-up to #1017, which added a `--pdb` flag to enter a debugger on exit.  This commit checks the type of the raised exception, and only enters the debugger if it is a subclass of `Exception`.  This ensures that implementation-details, such as a thrown `SystemExit` or `KeyboardInterrupt`, do not cause an erroneous entry to pdb.

[Utility] Check for isinstance(exc, Exception) before entering pdb

---

mlc_llm/utils.py

Prior to this commit, each parameter was converted to a numpy-owned array as part of a total size computation.  This commit computes the size directly, removing the conversion.

[Utils] Remove conversion to numpy array in utils.save_params

---

python/mlc_chat/rest.py

I was formatting code yesterday but accidentally upper-cased “app” to “APP”…

[Fix][REST] Use lowered-cased "app"

---

mlc_llm/relax_model/llama.py

This PR updates the packed function name of the attention kernel in Llama model, so that at runtime the correct PackedFunc will be found and used.

[Serving] Update Llama model with attn kernel

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt

This PR fixes #1122 
Current MLCChat android app downloads model config to a temp file in Downloads directory. 
Android 10 introduced Scoped Storage, so our app does not have write access to Downloads directory. Android 11 introduced write access to Downloads, but only files written by our app can be read. So the error occurs only in Android 10. 
Changed logic to download model config in app's scoped storage instead of Downloads directory.

Fix Android app Permission denied error on Android 10 

---

python/mlc_chat/compiler/quantization/group_quantization.py
tests/python/model/test_llama_quantization.py
tests/python/quantization/test_group_quantization.py

This PR fixes the group quantization and add relatex unit tests.

[SLM] Fix group quantization

---

.gitmodules

This PR updates the 3rdparty FlashInfer URL to its current location (https://github.com/flashinfer-ai/flashinfer).
Turn on `-USE_FLASHINFER=ON` when executing cmake to build MLC LLM runtime with FlashInfer enabled.

[Serving] Update FlashInfer repo link

---

python/mlc_chat/cli/convert_weight.py
python/mlc_chat/compiler/model/llama_quantization.py
python/mlc_chat/compiler/parameter/huggingface_loader.py
python/mlc_chat/compiler/parameter/utils.py
python/mlc_chat/compiler/quantization/group_quantization.py
python/mlc_chat/support/auto_target.py
python/mlc_chat/support/auto_weight.py
tests/python/support/test_auto_weight.py

This PR enables weight conversion in command line.
Sample command: `python3 -m mlc_chat.cli.convert_weight --config dist/models/llama-2-13b-chat-hf/ --quantization "q4f16_1" --output dist/test/`
CC: @cyx-6 @junrushao @LeshengJin

[SLM][AutoLLM] Enable Command Line Weight Conversion

---

python/mlc_chat/compiler/parameter/utils.py

After https://github.com/apache/tvm/pull/16046, the top-level module's name would not begin with a dot (.) prefix.

[Fix][SLM] Update q4f16 quantization with the new mutator name rule

---

cpp/serve/engine.cc
cpp/serve/request_state.h
python/mlc_chat/serve/engine.py
tests/python/serve/benchmark.py

This PR improves the benchmark scripts.
With this commit, we benchmark with 5 metrics:
* end-to-end latency (sec) of processing an entire batch,
* end-to-end request throughput (req/min),
* prefill per-token latency (ms/tok),
* decode per-token latency (ms/tok),
* token throughput (tok/s), including both prefill and decode.
The benchmark input initialization so far is still in a fixed pattern (only supports generating all requests to a same length). This part will be improved in follow-up PRs.

[Serving] Benchmark script enhancement

---

cpp/serve/engine.cc
cpp/serve/sampler.cc

This PR unifies the memory copy (GPU to CPU) of logits/prob arrays. Prior to this PR, the logits/probs array of each token is copied separately. This incurs some overhead without doubt. This PR unifies the memory copy, so that we only need to copy once for the entire running batch during decoding at a time.
In terms of implementation, this PR simplies the sampler logic by completely removing the memory copy logic. On the other hand, it brings the copy logic to engine. It does not bring much complexity to the engine.
This PR also lifts the random number generation from sampler to engine, as a preparation step for potential multi-threading token sampling.
Need to incorporate https://github.com/apache/tvm/pull/16069 to run. We can merge this PR first.

[Serving] Update sampling logits to unify memory copy

---

python/mlc_chat/interface/openai_api.py
python/mlc_chat/rest.py

This PR enables ```llm-vscode``` extension API support for copilot-like code completion, following [HF's LSP](https://github.com/huggingface/llm-ls). Fully compatible with ```CodeLlama``` and ```starcoder``` on mlc-llm. 
- https://github.com/huggingface/llm-vscode/pull/103 enhances extension user experience when used with mlc-llm rest api.
Thanks @pacman100, who came up with this on his latest blogpost: https://huggingface.co/blog/personal-copilot

[API] ```llm-vscode``` extension support

---

cpp/json_parser.h

The error message below
```
In file included from /usr/share/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1699286394016/work/cpp/./json_parser.h:9,
from /usr/share/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1699286394016/work/cpp/model_metadata.cc:5:
/usr/share/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1699286394016/work/3rdparty/tvm/3rdparty/picojson/picojson.h: In member function 'std::string picojson::value::to_str() const':
/usr/share/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1699286394016/work/3rdparty/tvm/3rdparty/picojson/picojson.h:494:37: error: expected ')' before 'PRId64'
494 |       SNPRINTF(buf, sizeof(buf), "%" PRId64, u_.int64_);
|               ~                     ^~~~~~~ …
```

Try fix macOS build with picojson

---

python/mlc_chat/interface/openai_api.py

The breakage was resulting from newer syntax being used for type annotations, as part of https://github.com/mlc-ai/mlc-llm/pull/592. So long as `mlc_chat.interface.openai_api` wasn't imported, the breaking changes were not encountered.  In https://github.com/mlc-ai/mlc-llm/pull/1107, the addition of `from .interface.openai_api import ChatMessage` caused this module to be imported, breaking compatibility of `mlc_chat.ChatModule` with Python3.8.
This commit updates the type annotations to the supported syntax.

Fix Python3.8 compatibility breakage

---

python/mlc_chat/chat_module.py

#1167 imports `LIB` in `chat_module.py`, causing the doc-making process unable to find `LIB`, hence the API reference is not displayed in https://llm.mlc.ai/docs/deploy/python.html#api-reference.

[Bugfix] Fix Cannot import name '_LIB' from 'mlc_chat.base'

---

python/mlc_chat/compiler/quantization/group_quantization.py
python/mlc_chat/compiler/quantization/quantization.py
tests/python/quantization/test_group_quantization.py

This PR supports the int3 and float32 group quantization, and fixes some minor issue in quantization impl and tests.

[SLM] Support `q3f16_1` and `q4f32_1`

---

cpp/llm_chat.cc
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/mistral.py

This PR adds sliding window size and sliding window chunk size to metadata, so that we can read such info from the model library instead of the `mlc-chat-config.json` in huggingface. Related to https://github.com/mlc-ai/web-llm/pull/208.
In addition, there are some small changes in the invariants for `sliding_window` and `sliding_window_chunk_size` in `llm_chat.cc`. In runtime, we assume that both parameters are valid. We cannot use one-chunk-prefill (with an unspecified chunk size) since that way there is no limit on the input's sequence length.
cc @davidpissarra

[Mistral][SWA] Add sliding window to metadata

---

cpp/conv_templates.cc

I added `chatml` support because of TinyLlama-1.1b. TinyLlama-1.1B is a 1.1B llama model that's being trained on 3 trillion tokens. Since it's a very small model it will run on almost any device which make it very suitable for MLC-LLM.
https://github.com/jzhang38/TinyLlama
They published a checkpoint version with 500B parameters trained and fine-tuned to chat (chatml format), which I converted to MLC-LLM format:
https://huggingface.co/acalatrava/mlc-chat-TinyLlama-1.1B-Chat-v0.2-q4f16_1
I also created a fine-tuned version and converted to MLC-LLM using the orca dataset.
https://huggingface.co/acalatrava/mlc-chat-TinyLlama-1.1B-orca-gpt4-q4f16_1
https://github.com/mlc-ai/binary-mlc-llm-libs/pull/32

Support for `chatml` format conversation (for TinyLlama-1.1B-Chat-v0.2)

---

python/mlc_chat/chat_module.py

This PR fixes doc building failure caused by how the packages required by `.infterface.openai_api` are not installed, as observed in https://github.com/mlc-ai/mlc-llm/pull/1214#issuecomment-1801184180.
We remove the dependency on `.infterface.openai_api` with `typing.TYPE_CHECKING` so that the import would not be evaluated when building the doc. We also make `CheckMessage` type hint into a string to "forward declare them".
Reference: https://stackoverflow.com/a/39757388
cc @junrushao

[Bugfix] Remove dependency on openai_api in chat module

---

python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/compiler_pass/estimate_memory_usage.py
python/mlc_chat/compiler/compiler_pass/pipeline.py

With this PR, the metadata in a DSO file using `vm["_metadata"]()` now have information about the upper bound RAM estimate on each function. As an example, the JSON string now is:
```json
{
"quantization": "q4f16_1",
"model_type": "llama",
"memory_usage": {
"_initialize_effect": 0,
"prefill": 136192,
"softmax_with_temperature": 0,
"decode": 218624
},
"params": [
{"name": "model.embed_tokens.q_weight", "shape": [32000, 512], "dtype": "uint32"},
{"name": "model.embed_tokens.q_scale", "shape": [32000, 128], "dtype": "float16"},
...
]
}
```
This helps the MLC runtime to better determine if a method is going to OOM and plan ahead, e.g. plan pre-allocated KVCache, accordingly.
The idea originates from @MasterJH5574's ancient PR that prints memory usage estimate as debugging information for demo …

Bake in RAM Usage in the Generated DSO

---

python/mlc_chat/chat_module.py

Some small fixes:
- Update type annotation for `messages` and `offset` in `ConvConfig`
- `num_return_sequences = 1` is unnecessary in the else branch in the `generate` member function

[Fix] ChatModule python

---

cpp/llm_chat.cc
mlc_llm/core.py
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/param_manager.py
mlc_llm/utils.py
python/mlc_chat/chat_module.py

Prior to this PR, sharding of model weights was done as the model is being initialized.  This allows a single set of model weights to be used regardless of the number of GPUs available, but may have slow model start-up time, due to the processing performed during start-up.  This processing is done by GPU-0, which then scatters the resulting model weights to all other GPUs.
This PR allows generation and use of pre-sharded model weights.  Here, the sharding of weight tensors is performed at model-build time, removing the run-time computations.  In addition, because each sharded weight tensor is only required by a specific worker, each worker can directly load their subset of the model weights.
The improvement in startup time when compared to initialization-time sharding depends on the …

[MultiGPU] Support pre-sharded model weights

---

python/mlc_chat/cli/convert_weight.py
python/mlc_chat/compiler/loader/loader.py
python/mlc_chat/compiler/model/model.py
python/mlc_chat/compiler/quantization/awq_quantization.py
python/mlc_chat/support/auto_weight.py

Follow the instructions in [llm-awq](https://github.com/mit-han-lab/llm-awq#usage) to generate the quantized weights.
```
python -m mlc_chat.cli.compile --config llama2_7b --quantization q4f16_awq -o ./dist/new-llama-awq/llama.so --max-sequence-length 4096
```
```
python -m mlc_chat.cli.convert_weight --quantization q4f16_awq -o ./dist/new-llama-awq --config ../models/Llama-2-7b-chat-hf/config.json --source-format awq --source dist/models/llama-2-7b-chat-w4-g128-awq.pt
```
```
python -m mlc_chat.cli.benchmark --model ./dist/new-llama-awq/ --model-lib ./dist/new-llama-awq/llama.so --device "cuda:3" --prompt "What is the meaning of life?" --generate-length 256
```

[AWQ] e2e awq-quantized model

---

python/mlc_chat/compiler/model/llama_model.py
python/mlc_chat/compiler/model/llama_quantization.py
python/mlc_chat/compiler/model/model.py
python/mlc_chat/compiler/quantization/__init__.py
python/mlc_chat/compiler/quantization/no_quantization.py
python/mlc_chat/compiler/quantization/quantization.py
tests/python/model/test_llama_quantization.py
tests/python/quantization/test_group_quantization.py

This PR adds the support of `q0f16` and `q0f32`, and change `RMSNorm` to `nn.RMSNorm`.

[SLM] Support `q0f16` and `q0f32`

---

mlc_llm/core.py
mlc_llm/relax_model/llama.py

This PR introduces the `max_vocab_size` and `max_batch_size` as two new compile arguments. The purpose is for better memory planning.
The default value for `max_vocab_size` is set to 40000, which I think is larger than the values of most models. The default value for `max_batch_size` is currently set as 256. It is possible that we update this value in the future to have a good default number.

[Core][Llama] Argument `max_vocab_size` and `max_batch_size`

---

mlc_llm/core.py

Currently, `max_gen_len` defaults to 512 in `dump_mlc_chat_config`. However, the instantiations of `dump_mlc_chat_config` within `mlc-llm.build` currently omit the `max_gen_len` argument (even when it's specified in the HF config), so the default of 512 gets set for every `mlc-chat-config.json` that is created by `mlc-llm.build`. This PR fixes the issue.

ensure that max_gen_len is set properly in mlc_chat_config

---

python/mlc_chat/__main__.py
python/mlc_chat/cli/compile.py
python/mlc_chat/cli/convert_weight.py
python/mlc_chat/cli/gen_mlc_chat_config.py

This PR makes it possible to use subcommands of `mlc_chat` package to control quantization and compilation. Example:
```bash
python -m mlc_chat convert_weight \
--model ./dist/models/Llama-2-7b-hf \
--quantization q4f16_1 \
-o ./dist/new-llama/
python -m mlc_chat gen_mlc_chat_config \
--model ./dist/models/Llama-2-7b-hf \
--quantization q4f16_1 \
--max-sequence-length 4096 \
--conv-template LM \
-o ./dist/new-llama \
python -m mlc_chat compile \
--model ./dist/models/Llama-2-7b-hf \
--quantization q4f16_1 \
--max-sequence-length 4096 \
-o ./dist/new-llama/llama.so
```
It slightly simplifies the workflow.

Introduce mlc_chat subcommands

---

rust/examples/mlc_chat.rs
rust/src/chat_module.rs
rust/src/config.rs

This PR introduces `Prompt` and `ChatMessage` structures, and enhances the `ChatModule` to generate tokens using either a single string (via `Prompt::String`) or a vector of `ChatMessage` (via `Prompt::MessageList`). An example is provided in [rust/examples/mlc_chat.rs](https://github.com/mlc-ai/mlc-llm/compare/main...YuchenJin:mlc-llm:multi-prompts?expand=1#diff-4ffa9349207c1df6ceeebe06a9afc8f2015000e031b39d677bbbe7e85ae2819b).
Here is a snippet demonstrating the interface:
```rust
let message1 = ChatMessage {
role: "user".to_owned(),
content: "suppose we already have projects llama, alpaca and vicuna, what do you think would be a great name for the next project?".to_string(),
};
let message2 = ChatMessage {
role: "assistant".to_owned(),
content: "based on the previous projects, a …
```

[Rust] Support multiple prompts

---

mlc_llm/core.py
mlc_llm/relax_model/stablelm_3b.py
tests/legacy-python/test_build_model_from_args.py

This is a frequent typo among multiple developers, as "weights" is typically plural.  This commit updates the command-line-argument from `--convert-weight-only` to `--convert-weights-only`.  For backwards compatibility, the original spelling is kept as an equivalent usage.

 [UI] Correct "convert_weight_only" to "convert_weights_only"

---

ci/task/mypy.sh
pyproject.toml
python/mlc_chat/support/download.py

This PR allows programmably downloading from HuggingFace to MLC's cache
directory, which locates in `$HOME/.cache/mlc_chat/model_weights/` by
default.
This PR relies on Git to clone the metadata, and Python's requests
library to fetch concrete weights as large files instead of the less
reliable Git LFS.
The example demonstrates downloading the 4-bit quantized Llama2-7B
model:
```python
from mlc_chat.support.download import download_mlc_weights
download_mlc_weights("HF://mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q4f16_1")
```
Screenshot:

Add a downloader from HuggingFace

---

python/mlc_chat/chat_module.py

During my Rust implementation of the project, I noticed an inconsistency between the Python and C++ implementations of `ConvConfig`. Specifically, the Python version lacks the `prefix_tokens` field, which is present in the C++ version.: https://github.com/mlc-ai/mlc-llm/blob/5e02cacd8ebba2e0206d5a447225a137de2dac0d/cpp/conversation.h#L69-L70.
This can cause the [`_load_json_override`](https://github.com/mlc-ai/mlc-llm/blob/5e02cacd8ebba2e0206d5a447225a137de2dac0d/python/mlc_chat/chat_module.py#L1062C26-L1062C26) fails to work in the `_prefill` function.
I think a simple unit test would help, I'd like to add a regression test if the CI has been set up.

[Fix] Add prefix_tokens to `ConvConfig` in Python to match C++ implementation

---

python/mlc_chat/__main__.py
python/setup.py

This PR makes it possible to invoke mlc_chat subcommands directly.
Previously one has to use `python -m` as the prefix to invoke `mlc_chat`:
```bash
python -m mlc_chat compile \
--model /models/Llama-2-7b-chat-hf \
--quantization q4f16_1 \
--max-sequence-length 4096 \
-o ./llama.so
```
This PR makes is possible to use it without the `python -m` prefix:
```bash
mlc_chat compile \
--model /models/Llama-2-7b-chat-hf \
--quantization q4f16_1 \
--max-sequence-length 4096 \
-o ./llama.so
```

Add `mlc_chat.__main__` as command line entrypoint

---

rust/examples/mlc_chat.rs
rust/src/chat_module.rs

Following PR #1253, I think ergonomics of the `generate` function of `ChatModule` can be improved (given it's an important public-facing API). 
This PR simplifies the function's usage by implementing the `From` trait for the `Prompt` enum. Also updated the example code.
Now the interface changes to:
```rust
/// Single prompt case:
cm.generate("what is the meaning of life?", None)
/// Multiple prompt case:
let messages: Vec<ChatMessage> = vec![message1, message2, message3];
let output = cm.generate(messages, None).unwrap();
```

[Rust] Improve ergonomics of `generate` function in `ChatModule` 

---

mlc_llm/relax_model/mistral.py

This PR fixes a bug with `max_gen_len` for the mistral-based models. #1249 introduced customizable `max_gen_len` based on the config's `max_sequence_length`, but mistral used to ignore `max_sequence_length` and this argument was set to -1. Consequently `max_gen_len` would also be set to -1 and the model would not generate outputs. As suggested in the Mistral paper, `max_sequence_length` can be set as `sliding_window * 4`.

[Fix] mistral `max_gen_len`

---

python/mlc_chat/compiler/quantization/group_quantization.py
tests/python/quantization/test_group_quantization.py

This PR fixes the shape infer for group quantization.

Fix group quantization shape infer

---

python/mlc_chat/cli/delivery.py
python/mlc_chat/compiler/convert_weight.py
python/mlc_chat/compiler/loader/huggingface_loader.py
python/mlc_chat/support/download.py

This PR provides a script that automatically quantizes models from HuggingFace using various quantization formats as specified.
Example: When being provided the following JSON file:
```json
{
"destination": "{username}/{model_id}-{quantization}", # Name of HF repo
"default_quantization": ["q0f16", "q0f32", "q3f16_1", "q4f16_1", "q4f32_1"],
"tasks": [
{
"model_id": "Llama-2-7b-hf",
"model": "/models/Llama-2-7b-hf", # Can be HF URL or a local path
"context_window_size": 4096,
"conv_template": "LM",
"quantization": [
{
"format": "q4f16_awq",
"model": "https://huggingface.co/TheBloke/Llama-2-7B-AWQ", # Overriding default `source`
"source_format": "awq"
}
]
}
]
}
```
The script will automatically run quantization and upload them to the following repos:
- …

Continuous Model Delivery

---

ci/task/pylint.sh
tests/python/api/test_python.py
tests/python/api/test_rest.py

This PR adds tests for the Python and Rest api for few different cases. Currently It uses models `Llama-2-7b-chat-hf-q4f16_1` present in the `dist` directory, which would probably need to be changed for Github testing.

add python, rest api test

---

ci/jenkinsfile.groovy

Initialize Jenkins CI files. The current CI file is duplicated from GitHub Actions and can depreciate later.
cc @junrushao @tqchen

Enable Jenkins CI

---

cpp/serve/engine.cc
python/mlc_chat/chat_module.py
python/mlc_chat/cli/convert_weight.py
python/mlc_chat/serve/engine.py
python/mlc_chat/support/auto_device.py
python/mlc_chat/support/auto_target.py

This PR refactors the engine logics with the following changes:
1) Adopt explicit [vtable convention](https://github.com/mlc-ai/mlc-llm/blob/a40d0cc15d7fe2e64ea8cc68b543ffa557301889/cpp/serve/engine.cc#L202-L209)
of TVM's runtime Module in C++;
2) Migrate to vtable convention in Python by consolidating vtable
functions into a single `self._ffi` member as the Python-side vtable,
created by a single [TVM call](https://github.com/mlc-ai/mlc-llm/blob/a40d0cc15d7fe2e64ea8cc68b543ffa557301889/python/mlc_chat/serve/engine.py#L120-L123).
3) Consolidate and unify automatic device detection logic into
`mlc_chat.support.auto_device` with detailed logging logic and fallback
mechanisms.
4) Explicitly require `max_single_sequence_length` and `tokenizer_path`
on C++ side, and to keep backward …

[Serving] Refactor Engine Logics

---

cpp/llm_chat.cc
mlc_llm/core.py
mlc_llm/relax_model/chatglm.py
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/mistral.py
mlc_llm/relax_model/stablelm_3b.py
python/mlc_chat/cli/compile.py
python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/flags_model_config_override.py
python/mlc_chat/compiler/help.py
python/mlc_chat/compiler/model/llama/llama_model.py
python/mlc_chat/compiler/model/mistral/mistral_model.py

Prior to this PR, only Mistral supported chunking the prompt during the prefill step. Chunking allows memory reduction, typically during the QK computation, in all models since the prefill is bound to chunk size. As of now, chunking is not restricted to SWA anymore. For instance, with `max_seq_len = 4096` llama goes from roughly 9GB to 6GB of VRAM consumption (chunk_size=128). This option was renamed to `--prefill-chunk-size`.
cc @CharlieFRuan @junrushao

[Feature] Prefill chunking for non-SWA models

---

mlc_llm/core.py
mlc_llm/quantization/__init__.py
mlc_llm/quantization/ft_quantization.py

This PR adds two new quantization mode, `q4f16_ft_group` and `q8f16_ft_group`. It's similar to group quantization with `group_size = 64` but uses extra preprocessing steps to allow offloading to fastertransformer/tensorrt-llm kernels
cc @masahi @MasterJH5574

Add q4/q8_ft_group quantization mode

---

ci/jenkinsfile.groovy

Cleaning the workspace before building, so that the previous corrupted directory will not affect the current CI build.
Used the `cleanWS` from here https://www.jenkins.io/doc/pipeline/steps/ws-cleanup/

[CI] Clean workspace before build

---

python/mlc_chat/cli/check_device.py
python/mlc_chat/support/auto_device.py

This PR separates the device detection into separate subprocesses.
The change is because the device detection will setup the driver, which consumes some GPU VRAM (for example, `tvm.device("opencl", 0).exist` consumes 390MB of VRAM on RTX 4090). Consider the case we detect if CUDA, Vulkan and OpenCL are available. When they are all available, each detection holds some VRAM, larger than 430MB altogether.
If the device detection is in the same process as the main process, the VRAM consumed by device detection will never be released. This means that in the example above, we detect CUDA, Vulkan and OpenCL, while in the end we prioritize the CUDA device. Consequently, the memory held by Vulkan and OpenCL detection will never be released.
Motivated by this issue, we separate the detection into …

Detect Driver/Device in a Separate Process

---

python/mlc_chat/compiler/loader/utils.py

When converting weight for some huggingface models, (https://huggingface.co/stanford-crfm/music-medium-800k in this case), the pretrained weight contains empty entries, leading to error shown below.
This PR skips such None param, logs a warning, and continues. Though this may be an error on the model releaser's end, perhaps we could make the weight conversion more tolerant.
```
File "python/mlc_chat/cli/convert_weight.py", line 87, in main
convert_weight(
File "python/mlc_chat/compiler/convert_weight.py", line 146, in convert_weight
_convert_args(args)
File "python/mlc_chat/compiler/convert_weight.py", line 97, in _convert_args
for name, param in LOADER[args.source_format](
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "python/mlc_chat/compiler/loader/huggingface_loader.py", line 87, in __init__ …
```

[SLIM] Skip None param when loading rather than failing

---

mlc_llm/utils.py

This removes the ndk reference for mali targets when building and fixes the error folks may run into below.
When I tried compiling this on my Orange Pi, I ran into this error when trying to build for mali since I didnt have the NDK setup on it:
```
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/x/DEV/LLM/mlc-llm/mlc_llm/build.py", line 47, in <module>
main()
File "/home/x/DEV/LLM/mlc-llm/mlc_llm/build.py", line 43, in main
core.build_model_from_args(parsed_args)
File "/home/x/DEV/LLM/mlc-llm/mlc_llm/core.py", line 910, in build_model_from_args
build(mod, args)
File …
```

remove ndk referencce from mali build target

---

ios/MLCChat/app-config.json
ios/prepare_params.sh

This PR concludes Mistral support on iOS (q3f16) with sliding window attention. Tested on iPhone 14 pro max. Uses full context (4K SW tokens) with 128 of chunk size, making it consume less than 4GB of memory.
Mistral iphone lib: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.1-q3f16_1-iphone.tar
Mistral q3f16 weights: https://huggingface.co/mlc-ai/mlc-chat-Mistral-7B-Instruct-v0.1-q3f16_1

[iOS] Mistral support

---

mlc_llm/utils.py

This is useful for compiling for H100s without also creating larger binaries to support T4s. This follows the conventions used by [torch](https://github.com/pytorch/pytorch/blob/main/setup.py#L135) and [vLLM](https://github.com/vllm-project/vllm/blob/main/setup.py#L54), but a dedicated option might be more suited for this project's build system.
This addresses #1309

read CUDA_ARCH_LIST to set CUDA capability versions for nvcc

---

ci/task/pylint.sh
cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_state.h
cpp/serve/request.h
cpp/serve/request_state.cc
cpp/serve/request_state.h
python/mlc_chat/__init__.py
python/mlc_chat/interface/openai_api.py
python/mlc_chat/protocol/__init__.py
python/mlc_chat/protocol/openai_api_protocol.py
python/mlc_chat/protocol/protocol_utils.py
python/mlc_chat/rest.py
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/entrypoints/__init__.py
python/mlc_chat/serve/entrypoints/entrypoint_utils.py
python/mlc_chat/serve/entrypoints/openai_entrypoints.py
python/mlc_chat/serve/request.py
python/mlc_chat/serve/server.py
python/mlc_chat/serve/server_variables.py
tests/python/serve/server/conftest.py
tests/python/serve/server/test_server.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_engine.py

This PR supports the RESTful API server with OpenAI v1/completions compatibility. We have unit tests in
`tests/python/serve/server/test_server.py` that is designed for pytest testing.
Regarding the internal engine, this PR changes the callback function API to incorporate the request finish reason.

[Serving] OpenAI v1/completions REST API

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h
cpp/serve/request.cc
cpp/serve/request.h
cpp/serve/request_state.cc
cpp/serve/request_state.h
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/request.py
tests/python/serve/test_serve_engine.py

Prior to this PR, each request has its own callback function. This PR switches to using a global callback function that all requests share, so that the conversion of Python function to PackedFunc only happens once.
Additionally, this PR introduces the use of `call_soon_threadsafe` method of asyncio in AsyncEngine.

[Serving] Switching to global request callback

---

python/mlc_chat/cli/check_device.py
python/mlc_chat/support/auto_device.py
python/mlc_chat/support/auto_target.py

TVM's Vulkan runtime emits a non-zero exit code on certain Windows drivers on DLL offloading. While there is definitely a way to fix this, for now, we quickly get around this by not checking the exit code in device detection.
This PR also improves clarify when multiple GPUs presents by emitting logging messages on all GPUs available, rather than only GPU 0.

[Bugfix] Ignore exit code in device detection

---

cpp/tokenizers.cc
mlc_llm/utils.py
python/mlc_chat/compiler/gen_mlc_chat_config.py

Fix the issue of tokenizer not recognizing special vocabs like `</s>`.
Currently, mlc-llm prioritizes using `tokenizer.model` with sentencepiece. However, using this alone misses other token mappings such as the stop token `</s>` -- instead we have been relying on registering `</s>` as a `stop_str`. This is experienced in models like Llama-2 and Mistral (probably most models), mentioned in https://github.com/mlc-ai/mlc-llm/issues/1315.
This is probably due to how [tokenizer.cc](https://github.com/mlc-ai/mlc-llm/blob/main/cpp/tokenizers.cc) only uses `tokenizer.model` and not other files like `added_tokens.json`, `tokenizer_config.json`, etc.
Instead, we prioritize using `tokenizer.json` with huggingface's "Fast tokenizer".
For models that do not come with `tokenizer.model` (e.g. …

[Tokenizer] Prioritize huggingface tokenizer.json, generate one if not included

---

rust/Cargo.toml
rust/build.rs

Adding metadata to the crate.
I am planning to publish the mlc-llm rust package on [create.io](http://create.io/) so that more developers can find/install it, and most importantly the code documentation can be generated and published to [docs.rs](http://docs.rs/). Everything is ready, but is blocked on a stale dependency of Heim crate in tvm-build: https://github.com/octoml/tvm-build/pull/14. Once it's fixed, we can publish the crate.

[Rust] Prepare for publishing

---

cpp/llm_chat.cc
python/mlc_chat/compiler/compile.py

Currently, when running a SLIM-compiled model with `llm_chat.cc`, we cannot read information like `max_window_size`, `sliding_window`, or `prefill_chunk_size`.  We add such info to `_metadata`, which is also needed for web-llm.

[SLIM] Add info to metadata in SLIM and make compatible with llm_chat.cc

---

ci/task/pylint.sh
cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/request_state.cc
python/mlc_chat/conversation_template.py
python/mlc_chat/protocol/conversation_protocol.py
python/mlc_chat/protocol/openai_api_protocol.py
python/mlc_chat/protocol/protocol_utils.py
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/config.py
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/entrypoints/openai_entrypoints.py
python/mlc_chat/serve/server_context.py
tests/python/serve/benchmark.py
tests/python/serve/evaluate_engine.py
tests/python/serve/server/test_server.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_engine.py

This PR supports the `v1/chat/completions` entrypoint of OpenAI API:
* protocol: `python/mlc_chat/protocol/openai_api_protocol.py`,
* entrypoint: `python/mlc_chat/serve/entrypoints/openai_entrypoints.py`
To support the chat functionality, this PR introduces the conversation template definition and register on Python side in `python/mlc_chat/serve/conversation.py`.
Compared with the current implementation of conversation template in C++, this version supports overriding the content of the system prompt without changing formatting texts (like the `[INST]` string in Llama2).
This PR adds a series of tests:
* temperature test for `v1/completions`,
* three different history message tests for `v1/chat/completions`,
* `max_tokens` test for `v1/chat/completions`,
* "wrong system prompt" position …

[Serving] Conversation template and OpenAI v1/chat/completions

---

python/mlc_chat/cli/compile.py
python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/flags_model_config_override.py
python/mlc_chat/compiler/flags_optimization.py
python/mlc_chat/compiler/gen_mlc_chat_config.py
python/mlc_chat/compiler/help.py
python/mlc_chat/support/auto_config.py
python/mlc_chat/support/config.py

This PR proposes changes to the new compilation CLI to complete A1 and A2 from #1364:
- Rename `max-window-size` to `context-window-size` (unless there is a reason, having different namings can be misleading since I believe both represent the same);
-  deprecate the usage of `config.json` in `mlc_chat compile`;
- use `mlc-chat-config.json` (created by `mlc_chat gen_mlc_chat_config`)  in `mlc_chat compile`;
- remove overlapped arguments from `mlc_chat compile` (namely `context-window-size`, `prefill_chunk_size`, `sliding_window` and `quantization`) and create `--overrides` argument to serve the purpose of overriding such settings in `mlc-chat-config.json` if needed.
I will add follow-up PRs to approach the next action items.
cc @junrushao @tqchen

[SLM] UX `mlc_chat compile` improvement

---

ios/MLCChat/app-config.json
ios/prepare_params.sh

note: OpenHermes-2.5-Mistral-7B is able to leverage the mistral_q3f16_1 lib
decoding: 6.0 tok/s (iphone 14 pro max)

[iOS] OpenHermes-2.5-Mistral-7B support

---

python/mlc_chat/compiler/gen_config.py

In some config.json, it already provides chat-related config, like bos_token_id, eos_token_id, temperature, etc. We should check the provided config.json before applying the system defaults.

Check config.json before applying system defaults in gen_config

---

cpp/serve/engine.cc
cpp/serve/engine.h
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/event_trace_recorder.cc
cpp/serve/event_trace_recorder.h
cpp/serve/model.cc
cpp/serve/request_state.cc
cpp/serve/request_state.h
cpp/serve/sampler.cc
cpp/serve/sampler.h
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/entrypoints/__init__.py
python/mlc_chat/serve/entrypoints/debug_entrypoints.py
python/mlc_chat/serve/entrypoints/openai_entrypoints.py
python/mlc_chat/serve/event_trace_recorder.py
python/mlc_chat/serve/server/__main__.py
python/mlc_chat/serve/server/popen_server.py
tests/python/serve/server/conftest.py
tests/python/serve/server/test_server.py
tests/python/serve/test_event_trace_recorder.py

This PR introduces the EventTraceRecorder in MLC LLM serving, which can
record event times for each request on invocation, and can dump
all the recorded events to Chrome Trace Event format, so that
we can visualize the events and the timeline of all requests.
This PR brings the optional flag `enable_tracing` to Engine,
AsyncEngine/AsyncThreadedEngine, server entry and PopenServer.
This flag defaults to `False`, in which case we do not enable
tracing.
This PR introduces a new server entrypoint `/debug/dump_event_trace`,
under file `python/mlc_chat/serve/entrypoints/debug_entrypoints.py`.
This entrypoint accepts a model name, and returns the dumped events
in Chrome Trace Event format (in JSON string).
This PR contains a basic EventTraceRecorder test and a basic test for
entrypoint …

[Serving] Introducing EventTraceRecorder

---

python/mlc_chat/compiler/quantization/awq_quantization.py
python/mlc_chat/compiler/quantization/group_quantization.py

This PR solves the same issue as https://github.com/apache/tvm/pull/16220, but for the quantized linear; motivated by trying to support GPTNeoX in SLIM.
Tested GroupQuantLinear with:
- llama q4f16, q4f32 (multilinear, no bias)
- RedPajama q4f16, q4f32 (linear, has bias, with out_dtype being float32)
- gpt2 q4f16, q4f32 (linear, no bias)
Did not test with awq quantization but same idea should apply.

[SLIM] Support out dtype for quantizeLinear

---

python/mlc_chat/compiler/model/gpt2/gpt2_model.py
python/mlc_chat/compiler/model/gpt_neox/gpt_neox_model.py

Otherwise: `gen_config` for gpt2 and gpt_neox runs into:
```
File "mlc-llm/python/mlc_chat/compiler/gen_config.py", line 98, in gen_config
tensor_parallel_shards=model_config.tensor_parallel_shards,
```

[SLIM][Fix] Quick fix on sharding config for non supported models

---

python/mlc_chat/cli/gen_config.py
python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/flags_model_config_override.py
python/mlc_chat/compiler/gen_config.py
python/mlc_chat/compiler/help.py
python/mlc_chat/compiler/model/mistral/mistral_model.py
python/mlc_chat/compiler/model/model.py

Rename `sliding_window` to `sliding_window_size` to be consistent with `context_window_size` and `prefill_chunk_size` https://github.com/mlc-ai/mlc-llm/issues/1364#issuecomment-1837914257
Note: only renaming on SLM, runtime should be updated, as well as prebuilts metadata and mlc-chat-config.json, when making SLM default

[SLM] rename `sliding_window` to `sliding_window_size`

---

python/mlc_chat/cli/compile.py
python/mlc_chat/support/auto_target.py

Item A6 from #1364. It enables the automatic creation of a system lib prefix (if not provided) typically required by Android and iOS libs

[SLM] auto system lib prefix

---

mlc_llm/relax_model/chatglm.py
mlc_llm/relax_model/commons.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/llama_batched_vllm.py
mlc_llm/relax_model/mistral.py
mlc_llm/relax_model/rwkv.py
mlc_llm/relax_model/stablelm_3b.py

Struct info inference can benefit from the implicit >= 0 bound of SizeVar.
cc @MasterJH5574 @tqchen @Hzfengsy

Use SizeVar instead of Var for model definition

---

cpp/llm_chat.cc
mlc_llm/core.py
mlc_llm/relax_model/mistral.py
python/mlc_chat/cli/gen_config.py
python/mlc_chat/compiler/flags_model_config_override.py
python/mlc_chat/compiler/gen_config.py
python/mlc_chat/compiler/help.py
python/mlc_chat/compiler/model/mistral/mistral_model.py
python/mlc_chat/compiler/model/model.py

Also added sinks support on `llm_chat.cc`. Haven't finished SLM sinks support, but it should be ready very soon (had some work to merge for quite some time on the former flow, so decided to finish on this one first).
Follow-up PRs to make attention sinks default to other models.
Note: Mistral with attention sinks can withstand long contexts with small sliding windows as low as 1024 (tested 768 and it can provide acceptable results too) and only 4 sinks. Despite maintaining good performance, one thing that I noticed is that sometimes quantized models start repeating emojis and paragraphs. However, this can be softened by slightly increasing the `repetition_penalty` (around 1.2 was enough to get much better results)
cc @tqchen

[Feature] Attention sinks kvcache on mistral

---

python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/compiler_pass/attach_to_ir_module.py
python/mlc_chat/compiler/compiler_pass/estimate_memory_usage.py
python/mlc_chat/compiler/compiler_pass/pipeline.py
python/mlc_chat/support/auto_target.py

Previously, to conform with TVM's `relax.build` API, we have to guarantee that the passes run in `mlc_llm` pipeline produce consistent IRModule for the subsequent `default_build` pipeline in `relax.build` to work on.
However, it is not usually the case and some passes will have to be rerun or have their outcome being discarded. `EstimateMemoryUsage`, as a notable example, runs half of `default_build` pipeline to lower the RelaxIR into a right stage, collects an integer representing number of bytes allocated in each Relax function, then discards the half-way lowering only to give back this func-name-to-integer dictionary. Another issue is that it makes certain IR manipulation more challenging as part of the pass infra, resulting in boilerplate logics in `compile.py` such as …

[SLM] Streamlined Compilation Pipeline

---

python/mlc_chat/compiler/extern/flashinfer.py
python/mlc_chat/compiler/model/extern_op.py
python/mlc_chat/compiler/model/llama/llama_model.py

This PR fixes two issues:
It fixes multi-query attention on the fallback code path, which was broken by one of latest commits: https://github.com/mlc-ai/mlc-llm/commit/d406c175d2f9164a08450a4a3eafbda061f30393.
It also adjusts RoPE application, and the rule of thumb right now is: it is always applied immediately after QKV projection to QK, and K-cache always stores the K with RoPE applied. FlashInfer will never fuse RoPE into its attention kernel.

Fix MQA and RoPE Application

---

python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/server/popen_server.py

This PR adds the logic of killing child processes prior to killing the main process in PopenServer, so that when running models in tensor parallelism, the GPU memory held by processes other than the main process can get released after terminating the server.

[Serving] Kill child processes in PopenServer

---

CMakeLists.txt

Should fix recent breaks of MLC nightly packaging on x86 mac, e.g. https://github.com/mlc-ai/package/actions/runs/7243831194/job/19731257538.

Define `__STDC_FORMAT_MACROS` by default

---

python/mlc_chat/compiler/model/llama/llama_loader.py
python/mlc_chat/compiler/quantization/awq_quantization.py
python/mlc_chat/compiler/quantization/quantization.py
python/mlc_chat/compiler/quantization/utils.py

Previously #1229, we only supported loading INT4-GEMV-awq weights quantized by [the original repo](https://github.com/mit-han-lab/llm-awq#usage). This pr supports loading INT4-GEMM format weights quantized by [AutoAWQ](https://github.com/casper-hansen/AutoAWQ). Here is an example that loads from [TheBloke/Llama-2-7b-Chat-AWQ](https://huggingface.co/TheBloke/Llama-2-7B-Chat-AWQ) and runs the benchmark.
```bash
MODEL_PATH=/opt/models/llama-2/llama-2-7b-chat-hf/
OUTPUT_PATH=./dist/new-llama-awq/
QUANT=q4f16_autoawq
python -m mlc_chat gen_config $MODEL_PATH/config.json --quantization $QUANT -o $OUTPUT_PATH --conv-template llama-2
python -m mlc_chat compile $OUTPUT_PATH -o $OUTPUT_PATH/llama.so
python -m mlc_chat convert_weight $MODEL_PATH --quantization $QUANT -o $OUTPUT_PATH --source-format …
```

[SLIM][AWQ] AWQ GEMM support

---

cpp/metadata/model.cc
cpp/metadata/model.h
python/mlc_chat/compiler/compile.py
python/mlc_chat/compiler/model/gpt2/gpt2_loader.py
python/mlc_chat/compiler/model/gpt_bigcode/gpt_bigcode_loader.py
python/mlc_chat/compiler/model/gpt_neox/gpt_neox_loader.py
python/mlc_chat/compiler/model/llama/llama_loader.py
python/mlc_chat/compiler/model/mistral/mistral_loader.py
python/mlc_chat/support/auto_target.py

Add attention sink to metadata in SLM primarily for web-llm runtime. This way, we do not rely on `attention_sink` in `mlc-chat-config.json` downloaded from HF in runtime, which binds with the weight, while the `attention_sink` should really be binded with the model library (since it is built into the model's `self.attention_sink_size`). This way, we guarantee that the `attention_sink` used in runtime is the one that matches the model library's.
Did not change anything on `llm_chat.cc` so this PR doe not affect anything on any runtime platform except for web-llm.

[Sink] Add sink size to metadata

---

docs/compilation/compile_models.rst
docs/compilation/convert_weights.rst
docs/deploy/javascript.rst

Add end-to-end tutorial for webLLM using the SLM workflow. We go through two cases:
1. Only adding a model variant -- pointing to the convert weight page
2. Compiling a model library -- pointing to the compile model library page

[Docs][SLM] Add end-to-end tutorial for webLLM in SLM

---

docs/deploy/javascript.rst

Change webllm tutorial's model library link according to https://github.com/mlc-ai/binary-mlc-llm-libs/pull/59

[Docs][Fix] Change webllm model lib link

---

python/mlc_chat/compiler/compiler_pass/fuse_split_rotary_embedding.py
python/mlc_chat/compiler/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/compiler/model/llama/llama_model.py
python/mlc_chat/compiler/model/mistral/mistral_model.py

If the attr `"split_rotary_fuse"` of PrimFunc `rotary_embedding` is missing or `False`, we would not rewrite the bindings in `FuseSplitRotaryEmbedding` pass.

[Fix] Skip FuseSplitRotaryEmbedding via attrs

---

python/mlc_chat/compiler/extern/extern.py
python/mlc_chat/compiler/extern/flashinfer.py
python/mlc_chat/compiler/model/extern_op.py

Depends on https://github.com/apache/tvm/pull/16274.

Prefer Extern Operators to `nn.SourceModule`

---

docs/compilation/compile_models.rst
docs/compilation/convert_weights.rst
docs/deploy/cli.rst
docs/deploy/javascript.rst
docs/deploy/python.rst
docs/get_started/project_overview.rst
docs/index.rst
docs/prebuilt_models.rst
examples/python/sample_mlc_chat.py

This PR updates the runtime portion of the documentation to reflect changes in SLM, as per https://github.com/mlc-ai/mlc-llm/issues/1420.
- We specify the full model path and model lib path in Python/CLI runtime (S5).
- Update project overview to remove `local_id` and `model_lib` fields from `mlc-chat-config.json` ([redrew figure](https://github.com/mlc-ai/web-data/blob/main/images/mlc-llm/tutorials/mlc-llm-flow-slm.svg) to highlight model weights and model lib) (S6)

[Docs][SLM] Update runtime tutorials

---

python/mlc_chat/compiler/convert_weight.py

This PR fixes the weight store of `q0f32` with fp16 on disk.

[SLM] Store fp32 weight as fp16 on disk

---

CMakeLists.txt

Otherwise, cmake and then make raises errors complaining the lack of __android_log.

Fix CMake for Android to avoid unlinked android log symbol

---

.gitignore
python/mlc_chat/cli/compile.py
python/mlc_chat/compiler_pass/pipeline.py
python/mlc_chat/help.py
python/mlc_chat/interface/compile.py

This PR enables the debug dump feature. The command would be something like
```
mlc_chat compile ./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json --device cuda -o dist/libs/Llama-2-7b-chat-hf-q4f16_1-cuda.so --debug-dump-path debug/
```
And it would dump 6 files in the `debug/` folder:
```
debug-phase0.py
debug-phase1.py
debug-phase2.py
debug-phase3.py
debug-phase4.py
debug-final.py
```

[SLM] Enable Debug Dump

---

docs/deploy/android.rst

Improvements to the formatting of Android deploy instructions under the Compile Android-capable models section

---

python/mlc_chat/__init__.py
python/mlc_chat/chat_module.py
python/mlc_chat/cli/compile.py
python/mlc_chat/cli/delivery.py
python/mlc_chat/interface/flags_model_config_override.py
python/mlc_chat/support/auto_config.py
python/mlc_chat/support/auto_device.py
python/mlc_chat/support/auto_target.py
python/mlc_chat/support/download.py

This PR introduces support for auto-downloading quantized model from HuggingFace, and optionally JIT-compile and generate corresponding model lib if missing.
**Auto-downloading.** When creating a ChatModule, if `model` is prefixed with `HF://`, MLC will search its model cache and automatically download it from HuggingFace if missing. This way, users won't have to download the model on their own using Git LFS.
**JIT compilation.** When creating a ChatModule and `model_lib_path` is neither supplied nor found using the existing path finding protocol, MLC will generate a model lib DSO and cache it on disk.
**Caching.** Model weights are in `$MLC_CACHE_DIR/mlc_chat/model_weights` once downloaded from HuggingFace, and the model libs are cached under `$MLC_CACHE_DIR/mlc_chat/model_lib`. By …

Auto-downloading and Just-in-Time Compilation in ChatModule

---

python/mlc_chat/cli/delivery.py

Use `sys.executable` instead of `python` in delivery script.

[Fix][Delivery] Use sys executable in delivery

---

python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/operator/position_embedding.py

Integrate fused rope into model gpt_neox and phi. 
Add an optional parameter `rotary_dim` to `llama_rope`. `rotary_dim` indicates the number of dimensions in the embedding that RoPE is applied to. By default `rotary_dim` is the same as `head_dim`. In model `Phi`, `rotary_dim` is set to a different number based on the config.

[SLM] Fused Rope Integration

---

docs/deploy/android.rst

A minor path fix in the Android Doc, as the file `prepare_libs.sh` is under the `library` folder.
cc @Kartik14 @junrushao

[Doc] Minor Fix Android Doc

---

CMakeLists.txt
cpp/cli_main.cc
cpp/conversation.h
cpp/image_embed.cc
cpp/llm_chat.cc
cpp/metadata/json_parser.h
python/mlc_chat/__init__.py
python/mlc_chat/base.py
python/mlc_chat/chat_module.py
python/mlc_chat/cli/delivery.py
python/mlc_chat/help.py
python/mlc_chat/interface/compile.py
python/mlc_chat/interface/compiler_flags.py
python/mlc_chat/interface/gen_config.py
python/mlc_chat/interface/jit.py
python/mlc_chat/libinfo.py
python/mlc_chat/support/auto_target.py
python/mlc_chat/support/constants.py
python/mlc_chat/support/download.py

This PR introduces an environment variable `MLC_JIT_POLICY` as a follow-up item to PR [#1508](https://github.com/mlc-ai/mlc-llm/pull/1508#issuecomment-1871611605). It allows to enable/disable the JIT behavior by:
- `OFF`: never JIT, and will throw an error if `model_lib` is missing;
- `ON` (default): JIT whenever the model lib is missing and there's a cache miss;
- `REDO`: whenever the model lib is missing, always do JIT compilation even if cache hits;
- `READONLY`: never do JIT compilation but look up the JIT cache whenever the model lib is missing.
It also dissolves the newly-introduced `JITOption` into `ChatConfig` so that it can be used more seamlessly with exactly the existing APIs. By doing so, users can simply specify `context_window_size`, `prefill_chunk_size` to control the VRAM …

Introduce MLC_JIT_POLICY and Dissolve JITOptions into ChatConfig

---

python/mlc_chat/chat_module.py
python/mlc_chat/cli/benchmark.py
python/mlc_chat/cli/model_metadata.py
python/mlc_chat/interface/compile.py
python/mlc_chat/interface/compiler_flags.py
python/mlc_chat/interface/gen_config.py
python/mlc_chat/interface/jit.py
python/mlc_chat/model/gpt2/gpt2_model.py
python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/model/mistral/mistral_model.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/op/attention.py

This PR introduces a command that reports the estimated upper-bound memory usage based on the metadata section of an SLM-compiled model.
Example:
```bash
>> python -m mlc_chat.cli.model_metadata /path/to/model_lib.so --memory-only
[2023-12-31 18:40:43] INFO model_metadata.py:49: Parameter size: 3885.14 MB
[2023-12-31 18:40:43] INFO model_metadata.py:58: Temporary buffer size: 7184.15 MB
[2023-12-31 18:40:43] INFO model_metadata.py:71: KVCache size when context/sliding window size is 4096: 512.00 MB
[2023-12-31 18:40:43] INFO model_metadata.py:79: Total memory usage: 11581.29 MB
[2023-12-31 18:40:43] INFO model_metadata.py:84: Tweaking `prefill_chunk_size`, `context_window_size` and `sliding_window_size` to reduce memory usage
```
Addresses both B1 and B2 in …

Report upper-bound memory usage based on SLM model lib

---

python/mlc_chat/cli/model_metadata.py
python/mlc_chat/interface/compiler_flags.py
python/mlc_chat/interface/jit.py
python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_chat/op/attention.py

This PR turns on FlashInfer in O2 mode given it has been relatively stable over the past few weeks.
This commits also brings a few misc improvements:
- Pass in scratch memory managed by RelaxVM's memory pool - this change depends on TVM's [PR #16327](https://github.com/apache/tvm/pull/16327) and FlashInfer's [PR #43](https://github.com/flashinfer-ai/flashinfer/pull/43)
- Enable FlashInfer for group size = 4, which is a setting used in Mistral models;
- Slightly shorten and clarify the log message on memory usage on model lib loading.
- Integrate FlashInfer into GPT-BigCode models.
With this PR, FlashInfer is integrated into Mistral, Llama, GPT-NeoX, GPT-BigCode, Phi. The only left out is GPT2, which has a special flag `scale_attn_by_inverse_layer_idx` which applies an elementwise …

Enable FlashInfer in O2 mode

---

python/mlc_chat/interface/jit.py
python/mlc_chat/loader/utils.py
python/mlc_chat/op/attention.py

This PR includes two minor fixes to support TinyLlama:
- Fix BF16 loading via SafeTensor - it was broken because numpy does not support bf16, which leads to an exception in safetensor internally.
- FlashInfer doesn't support `head_dim == 64`, which we skipped in this PR.
After this PR, the following snippet runs TinyLlama pretty conveniently:
```python
from mlc_chat import ChatConfig, ChatModule, callback
from mlc_chat.support import logging
logging.enable_logging()
MODEL = "HF://junrushao/TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC"
def main():
cm = ChatModule(
MODEL,
device="metal",
chat_config=ChatConfig(context_window_size=1024),
)
cm.generate(
"What is the meaning of life?",
progress_callback=callback.StreamToStdout(callback_interval=2),
)
if __name__ == "__main__":
main()
```

Support TinyLlama in SLM flow

---

cpp/llm_chat.cc
python/mlc_chat/cli/gen_config.py
python/mlc_chat/help.py
python/mlc_chat/interface/compile.py
python/mlc_chat/interface/gen_config.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/nn/kv_cache.py
python/mlc_chat/op/kv_cache.py
tests/python/model/test_kv_cache.py

This PR introduces the batched llama modeling with Paged KV cache in SLM flow.

[SLM] Batched Llama

---

cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/server/__main__.py
python/mlc_chat/serve/server/popen_server.py
tests/python/serve/benchmark.py
tests/python/serve/evaluate_engine.py
tests/python/serve/server/conftest.py
tests/python/serve/server/test_server.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_engine.py

PR #1520 introduces batched llama to SLM. This PR
updates the serving codebase and fully switch the model definition to SLM flow. Most changes in this PR are trivial.
Note that with this PR merged in, the previous batching model definition flow becomes outdated and no longer usable.

[Serving] Switching to SLM model definition flow

---

python/mlc_chat/nn/__init__.py

This is a quick fix to #1547. Sorry for missing the init file in the nn subpackage.

[Fix][Python] `__init__.py` under `nn` subpackage

---

python/mlc_chat/op/moe_misc.py

A follow-up of my previous PR (https://github.com/mlc-ai/mlc-llm/pull/1529).
This PR makes Mixtral work on Metal GPUs that macOS comes with. There are honestly no much change needed, except for that Metal doesn't support fp64 data types.
A python script to run Mixtral:
```python
from mlc_chat import ChatConfig, ChatModule, callback
from mlc_chat.support import logging
logging.enable_logging()
MODEL = "HF://junrushao/Mixtral-8x7B-Instruct-v0.1-q4f16_1-MLC"
NUM_GPU = 1
def main():
cm = ChatModule(MODEL, chat_config=ChatConfig(
sliding_window_size=1024,
tensor_parallel_shards=NUM_GPU,
))
cm.generate("What is the meaning of life?", progress_callback=callback.StreamToStdout(callback_interval=2))
if __name__ == "__main__":
main()
```
Quantization formats:
- 3-bit (19.662 GB): …

Support Mixtral on macOS

---

README.md

I was looking into running a good embedding model locally. The popular [embedding model leaderboard](https://huggingface.co/spaces/mteb/leaderboard) currently (2024-01-07) shows [`e5-mistral-7b-instruct`](https://huggingface.co/intfloat/e5-mistral-7b-instruct) as top entry. I checked mlc-llm's README and it didn't seem to support the Mistral architecture. Only when checking the docs that turned out to be wrong.
=> As many people might be quick to leave when not finding Mistral on the README, I propose to include this info on the README directly, instead of only in the docs.
To have a smaller README, maybe some of the other listed models can be removed, which might be less popular?
It might also be worth adding one row with `...` or `... (see docs)` with a link, to the docs, which might …

Add Mistral and Phi to model table

---

python/mlc_chat/compiler_pass/pipeline.py
python/mlc_chat/compiler_pass/prune_relax_func.py
python/mlc_chat/interface/compile.py

We recently noticed that when FlashInfer is not built due to unsupported cuda architecture or platform, running single-sequence ChatModule will hit VM function initialization error, where the function is used in `create_flashinfer_paged_kv_cache`, which won't actually be invoked in single-sequence flow.
This is due to relax VM eagerly initializes all used PackedFunc at initialization stage (instead of lazy load). Therefore, even when the `create_flashinfer_paged_kv_cache` is not invoked, the PackedFuncs will be looked up. So whenever FlashInfer is not available, the issue will happen.
This PR adds a compiler pass which removes
`create_flashinfer_paged_kv_cache` (and also other similar functions that may be introduced in the future) based on the target. This pass can effectively address …

[Pass] PruneRelaxFunc to remove Relax function based on target

---

cpp/serve/async_threaded_engine.cc
cpp/serve/async_threaded_engine.h
python/mlc_chat/serve/async_engine.py

This PR fixes a threading issue when using AsyncThreadedEngine on Metal. This issue does not exist for CUDA.
Prior to this PR, the engine is constructed on one threaded and is driven by the other thread. After this PR, both the construction and the engine drive is on the same thread, which does not raise issue in the current Metal runtime.

[Serving] Fix AsyncThreadedEngine for Metal

---

cpp/llm_chat.cc
rust/src/chat_module.rs

In the Rust code, we are linking to the `libmlc_llm_module.so` with the rustc **-l** flag in the [build script](https://github.com/mlc-ai/mlc-llm/blob/eddc5b146f458d331ca89d414c608b2465c0947a/rust/build.rs#L4), so that we can get the registered packed func `mlc.llm_chat_create` via the TVM Rust API `Function::get()` as in the code: https://github.com/mlc-ai/mlc-llm/blob/eddc5b146f458d331ca89d414c608b2465c0947a/rust/src/chat_module.rs#L342-L343
However, when we create another Rust crate that depends on the MLC LLM Rust crate, we have to link to the [libmlc_llm_module.so](https://github.com/mlc-ai/mlc-llm/blob/main/CMakeLists.txt#L142) in the new crate again. This happens because the rustc compiler prunes off linking to components without direct dependency, as happens here when we look up a …

[Rust] Add a dummy function in cpp file to force linking

---

python/mlc_chat/interface/compile.py
python/mlc_chat/op/attention.py
python/mlc_chat/quantization/awq_quantization.py
python/mlc_chat/quantization/ft_quantization.py
python/mlc_chat/quantization/group_quantization.py
python/mlc_chat/quantization/quantization.py
python/mlc_chat/quantization/utils.py

As `q4f16_0` is useful at Adreno and potentially benefits Hexagon backends, this PR adds support for `q4f16_0` and `q3f16_0` quantization back to SLM.
Note that the current flow does not support Mixtral.
Confirmed `q3f16_0`, `q4f16_0`, and `q4f16_1` work well on a single Cuda device. I suppose it would work on other platforms as it's backend-independent. But would be great if you could help confirm if it works with disco
cc @junrushao @LeshengJin

[SLM] Support Quantization `q4f16_0` and `q3f16_0`

---

python/mlc_chat/model/model.py
python/mlc_chat/model/phi/phi_loader.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/support/auto_config.py

Add support for the latest Phi-1 and Phi-1.5.
Introduce model_type `phi`, which is model type of the latest Phi-1 and Phi-1.5
Discussion: https://github.com/mlc-ai/mlc-llm/issues/1567
cc: @federicoparra @junrushao

[SLM] Phi-1/Phi-1.5 new model type support

---

cpp/metadata/model.cc

In certain environment the throw may be disabled,
this patch enhances the backward compact path
so the function can work in those cases.

[COMPACT] allow skip meta-data

---

mlc_llm/core.py
mlc_llm/quantization/ft_quantization.py
mlc_llm/relax_model/commons.py
mlc_llm/utils.py

Since weight preprocessing needs to happen after weights are sharded, we need to preshard weights for FT quantization + multi gpus. For convince, `--use-presharded-weights` is automatically set in this case.
@sunggg @vinx13 @cyx-6

Add multi-gpu support for FT quantization

---

python/mlc_chat/nn/kv_cache.py

The tile size of local m, d should be `ceil(tile_x, 32 * num_warps)` rather than 1.
Now It won't go wrong unless `tile_x > 32 * num_warps`

[Serving] Fix BatchPrefillPagedKVCache TIR kernel

---

python/mlc_chat/compiler_pass/attach_to_ir_module.py
python/mlc_chat/compiler_pass/pipeline.py

This PR adds a pass into the model compilation pipeline, which attach an attribute `"relax.memory_plan_dynamic_func_output"` for each Relax function in the IRModule. This attribute suggests that the Relax functions' output tensors, though having dynamic shapes, are statically plannable.
This enhancement makes sure that in serving scenarios, our memory allcoation is completely static after stablized. So we will not be worried about continuing memory usage growth, and can allocate more memory for KV cache.
This PR can be early merged, but it will not take effects until apache/tvm#16111 is merged.

[Pass] Attach memory-planning attributes for dynamic func output

---

cpp/serve/config.cc
python/mlc_chat/nn/kv_cache.py

This PR updates the KV cache to use the latest attention kernels which support on-the-fly RoPE calculation.
Validated locally that the update can pass tests.

[Serving] Update KV cache with fused RoPE attn kernels

---

python/mlc_chat/serve/async_engine.py

Type subscriptable is introduced in Python 3.9, this PR fixes for Python 3.8

[Minor] Update Python Annotation to support Python 3.8

---

cpp/metadata/json_parser.h
cpp/metadata/model.cc
python/mlc_chat/cli/model_metadata.py
python/mlc_chat/interface/compile.py
python/mlc_chat/interface/convert_weight.py
python/mlc_chat/loader/huggingface_loader.py
python/mlc_chat/loader/stats.py
python/mlc_chat/model/gpt2/gpt2_model.py
python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/model/mistral/mistral_model.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/quantization/group_quantization.py

This PR adds support for dyanmic shape parameters, specifically substituting llama's appearance of `config.vocab_size` to `llama.vocab_size`. 
Models that share the same architecture may only differ in the vocab size, making us have to recompile a model library. With dynamic vocab size, we can use the same llama model library for llama-2, code-llama, wizardMath, wizardCoder, etc.
1. Quantization
a. GroupQuantization: During `_dequantize()`, insetad of passing in `IntImm`, ~~pass in `tir.Var` when shape is not int~~ pass in weight's shape, which is a tir.Var (cannot initialize a new var since it would create `vocab_size_1` in script)
b. No change is needed for AWQ since it does not seem to quantize the embedding layer nor the `lm_head`: …

[SLIM] Allow dynamic shape parameters

---

python/mlc_chat/model/mistral/mistral_quantization.py
python/mlc_chat/model/model.py

Non-quanitzed fp16 and fp32 formats is previously overlooked in Mistral. This PR adds its support.

Support q0f16 and q0f32 in Mistral

---

python/mlc_chat/cli/model_metadata.py
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/config.py
python/mlc_chat/serve/engine.py
python/mlc_chat/serve/server/__main__.py
python/mlc_chat/serve/server/popen_server.py
tests/python/serve/benchmark.py
tests/python/serve/evaluate_engine.py
tests/python/serve/server/conftest.py

This PR supports the functionality that automatically estimates the maximum KV cache capacity. This leverages the following sources:
* total GPU global memory (through TVM device API),
* model parameter memory (computed during weight conversion),
* runtime temporary memory (comptued by memory planning).
With this PR, when `max_total_sequence_length` is set to None, we will automatically estimate a KV cache capacity that can make most use of the GPU.
Alternatively, users can choose to specify total GPU global memory size via the environment variable `"MLC_GPU_SIZE_BYTES"`. If this env variable is detected, we will use this number as the GPU VRAM size.
Effects of this PR:
```
[2024-01-14 15:35:39] INFO engine.py:186: Estimated KVCacheConfig "max_total_sequence_length": 18267.
[2024-01-14 …
```

[Serving] Automatically estimate KV cache capacity

---

ci/jenkinsfile.groovy
ci/task/test_model_compile.sh
tests/python/integration/test_model_compile.py

This PR adds basic testing infra for the command:
```bash
mlc_chat chat ...
```
This is imminently necessary because it got broken quite frequently upon almost every new feature, and it's quite non-trivial to test all the quadruples `(model, quant, device, tensor-parallel-shards)`.
This testing infra addresses this issue by installing the wheel produced by the previous build pipeline, and run `mlc_chat chat` commands in a subprocess to make sure at least the compilation process will not break. Correctness is not validated in this PR, as they are more likely to be guaranteed by unit-tests.
This PR is largely inspired by @Hzfengsy's series of work, particularly the set up of Jenkins pipeline.

[CI] Test Model Compilation

---

cpp/llm_chat.cc
cpp/loader/multi_gpu_loader.cc
cpp/metadata/json_parser.h
cpp/metadata/model.cc
cpp/metadata/model.h
cpp/serve/config.cc
cpp/serve/event_trace_recorder.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/sampler.cc
python/mlc_chat/chat_module.py
python/mlc_chat/serve/engine.py

This PR fixes the issue introduced due to the dynamic-shape parameter support.
The way is to introduce a temporary data structure called `SymShapeTuple` in model metadata reading. The `SymShapeTuple` instance may contain `-1` in some of its dimensions, and have a corresponding symbolic name on such dimensions. The symbolic shape tuple will be instantiated to `ShapeTuple` with the concrete shape in model config.

[Disco] Dynamic-shape parameter loading in TP

---

ci/jenkinsfile.groovy
ci/task/test_model_compile.sh
tests/python/integration/test_model_compile.py

This PR turns on ROCm and WebGPU in our testing pipeline.
It depends on [this commit](https://github.com/mlc-ai/relax/commit/dbb7d630774c98598766b85595a7d35bbd6ad186) that fixed compilation for GPT-NeoX, GPT-BigCode and Mixtral, which will go into effect tonight.

[CI] Enable ROCm & WebGPU

---

cpp/serve/request_state.h

This PR updates the time point type to unified
`std::chrono::high_resolution_clock::time_point`, which exists across different backends, including mobile.

[Serving] Fix clock type compilation issue

---

mlc_llm/utils.py
tests/legacy-python/dump_intermediate.py

This PR updates `debug_intermediate.py` that uses instrumenting to debug a compiled model library, adding some comments on the script and making it SLM-model compatible.
To run:
```
python tests/legacy-python/dump_intermediate.py --model dist/phi-2-q4f16_1-MLC --model-lib-path dist/phi-2_q4f16_1-cuda.so
```
While we can use JIT to print intermediate values for debugging, as of now it only supports cpu. Some issues are platform-specific, and this script could still come in handy (e.g. helped solve https://github.com/apache/tvm/pull/16438, https://github.com/mlc-ai/mlc-llm/pull/1638).

[Debug] Update instrument debugging script

---

python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/op/attention.py

This PR adds an argument ~`attn_weights_out_dtype`~ `qk_dtype` for `attention.py`, essentially making `matmul(q, k, out_dtype=qk_dtype)`.
The motivation is that some models (e.g. phi), when operating under float16, can observe INF in Q@K. Thus, we accumulate in float32 to avoid this.

[Attention] Add out dtype for QK matmul

---

python/mlc_chat/interface/gen_config.py

Previously `max_batch_size` is dumped twice into `mlc_chat_config.json`: one in `model_config` field, and another one in the outmost scope.
Given `max_batch_size` is a field what we only levarage during model compilation for memory planning, we want to keep this field only in `model_config`.
This PR removes `max_batch_size` from the outmost scope and only keep it in `model_config` with the right value.

[Config] Fix `max_batch_size` in dumped config

---

python/mlc_chat/cli/model_metadata.py
python/mlc_chat/interface/compile.py
python/mlc_chat/support/config.py

For devices like iOS, Android, and WebGPU, the compiled model library cannot reuse the `model_metadata` script but need a script on their own device ([e.g. for webllm](https://github.com/mlc-ai/web-llm/tree/main/utils/vram_requirements)).
We print out the VRAM requirements in this PR during `mlc_chat compile`.

[VRAM] Report memory usage in mlc_chat compile

---

android/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/library/prepare_model_lib.py
android/library/src/main/assets/app-config.json

This PR introduces the following minor refactors for Android apk
- Modify `app-config.json` to move `model_lib_path` to a. separate field 
- Remove `model_path` from `ModelRecord` class since not needed

[SLIM] Android AppConfig refactor

---

python/mlc_chat/compiler_pass/estimate_memory_usage.py

The latest memory planning pass uses `R.memory.alloc_storage` for symbolic shape tensors, and breaks the estimation pass which assumes all `alloc_storage` are static shaped.
This PR fixes the pass to skip dynamic-shape storage allocation since these are not part of memory planning.

[Pass] Fix estimate memory usage per latest change

---

ci/task/test_model_compile.sh

Given our metal CI does not have an indepenent env every time, we'll need to reinstall the package every time.

[CI] Force reinstall package on metal

---

python/mlc_chat/compiler_pass/fuse_add_norm.py
python/mlc_chat/compiler_pass/pipeline.py
python/mlc_chat/interface/jit.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/model/mistral/mistral_model.py
python/mlc_chat/model/mixtral/mixtral_model.py
python/mlc_chat/support/constants.py

This PR adds a fusion pass that applies to "binary add" and "RMSNorm".
This is a temporary workaround that allows us to fuse "add" into RMSNorm
once it is not fused into GEMM epilogue.

[SLM] Fuse Add and RMSNorm

---

ci/task/test_model_compile.sh

The metal/iOS CI did not force reinstall the built mlc chat package every time, which may lead to regression caused by cache.

[CI] Fix Metal/iOS CI regression

---

cpp/llm_chat.cc

Before this PR, we pass presence penalty to both arguments of `ApplyPresenceAndFrequencyPenaltyOnCPU`

[Fix] Fix frequency penalty when sampling

---

python/mlc_chat/interface/gen_config.py
python/mlc_chat/support/convert_tiktoken.py

This PR adds support for tiktoken support during the gen_config phase.
Some models, like Qwen and StableLM-2 does not have Huggingface tokenizer files. Instead, they rely on AutoTokenizer and the https://github.com/openai/tiktoken package to write their own tokenizer. We will convert these custom tiktoken tokenizer to be compatible with Huggingface tokenizer if possible.
Example with stable-lm-2:
```
[2024-02-02 09:59:57] INFO gen_config.py:131: Not found tokenizer config: /ssd1/rickzhou/rick_fork/mlc-llm/models/stablelm-2-zephyr-1_6b/tokenizer.model
[2024-02-02 09:59:57] INFO gen_config.py:131: Not found tokenizer config: /ssd1/rickzhou/rick_fork/mlc-llm/models/stablelm-2-zephyr-1_6b/tokenizer.json
[2024-02-02 09:59:57] INFO gen_config.py:131: Not found tokenizer config: …
```

[SLM] Add tiktoken tokenizer support in gen_config

---

cpp/llm_chat.cc

Prior to this PR, if we do multiple round chat with Llama-2-q4f16_1, we would run into the error below due to shape mismatch
```
File "/home/cfruan/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc", line 725
TVMError: Check failed: total_seq_length == qkv_data->shape[0] (68 vs. 38) :
```
This PR fixes it.

[Fix] Paged KVCache forward shape

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/request_state.cc
cpp/serve/request_state.h
cpp/streamer.cc
cpp/streamer.h
cpp/tokenizers.cc
cpp/tokenizers.h
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/engine.py
python/mlc_chat/streamer.py
tests/python/support/test_streamer.py

This PR enhances the stop string matching algorithm.
Prior to this PR, our stop string matching works on frontend after UTF-8 decoding, and always caches a suffix string that has length not exceeding the stop string length. This algorithm is not optimal though, since it may delay the response time for a request til the first token, due to the string suffix cache.
This PR makes two changes:
1. applying KMP algorithm for linear stop string matching with minimum caching,
2. move the stop string handling from front-end back into the engine side, so that frontend only handles UTF-8.
The stop string is validated to be efficient, as tested in `tests/python/support/test_streamer.py`.
----------------------
NOTE: this PR bumps `3rdparty/tokenizers-cpp`. You may need to remove the CMakeCache.txt …

[Serving] Stop string matching algo enhancement

---

cpp/serve/engine.cc
cpp/serve/request_state.cc
cpp/serve/request_state.h
cpp/streamer.cc
cpp/streamer.h
cpp/tokenizers.cc
cpp/tokenizers.h
python/mlc_chat/serve/entrypoints/openai_entrypoints.py

Given the token table is continuous, there is no
need to use `std::unordered_map<int32_t, std::string>` as the token table type, and we can switch to use `std::vector`.

[Serving] Update token table type to vector

---

android/library/prepare_libs.sh

This PR updates the build command for the `tvm4j_runtime_packed` target in the Android library's build file. The previous make command has been replaced with a CMake build command to ensure a more standardized and cross-platform build process.
- Replaced `make tvm4j_runtime_packed -j10` with `cmake --build . --target tvm4j_runtime_packed --config release` to invoke CMake for building the `tvm4j_runtime_packed` target in release configuration.
cc @tqchen

[Android] Update build command for tvm4j_runtime_packed in Android library

---

cpp/serve/engine.cc
cpp/serve/model.cc
cpp/serve/model.h

This PR supports automatically inferring the max concurrency from the model `"num_shards"` field, so that the disco processes will not be stuck by the CPU sampler due to the overuse of threads (which roots from the TVM threading backend mechanism).

[Serving] Set max threading concurrency for sampling manually

---

python/mlc_chat/embeddings/openai.py

`async_embed_with_retry` and _embed_with_retry_ were moved to `langchain_community.embeddings.openai`

Fix Langchain support

---

cpp/llm_chat.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
python/mlc_chat/model/llama/llama_model.py

1. change the signature of `decode` and `prefill` to embed-in-logit-out when using paged kv cache
2. run `decode` / `prefill` instead of `batch_decode` / `batch_prefill` when batch size = 1 in mlc serve

[Serve] Single-sequence specialization for MLC serve

---

python/mlc_chat/compiler_pass/pipeline.py

Related to: https://github.com/apache/tvm/pull/16515
Quote @MasterJH5574:
Since the Vulkan target information is required at the time of lowering, the pass BindTarget needs to apply before lowering, so that the functions have correct target information.
We need to apply the target binding in MLC pipeline

Annotate TIR PrimFunc with a target to allow target-specific transform

---

python/mlc_chat/nn/kv_cache.py

Previously the flash attention kernel for paged attention decode has hard requirement which limits all models to have head dim 128. After reexamination, we think this constraint can be removed.

[KVCache] Remove "bdx == 32" assertion

---

python/mlc_chat/quantization/ft_quantization.py

This PR fixes the issue brought up in https://github.com/mlc-ai/mlc-llm/issues/1723.
The issue is due to how the `lm_head` of Llama has `out_features` defined as a `tir.Var("vocab_size")`. However, in the FT quantization scheme, the linear layer would be quatnzied to shape `(in_features, tir.ceildiv(out_features, config.num_elem_per_storage)),`. This causes the shape of the parameter to be a FloorDiv operation rather than just a `tir.Var`. Later it would lead to issue during shape-lowering:
```
tvm-unity/src/relax/backend/vm/vm_shape_lower.cc", line 305
InternalError: Check failed: (it != slot_map_.end()) is false: Var vocab_sizeis not defined in the function but is referenced by (vocab_size + T.int64(2) - T.int64(1)) // T.int64(2)
```
Instead, we skip quantizing `lm_head` here.

[Fix] Skip lm_head quantization for q4f16_ft

---

mlc_llm/relax_model/chatglm.py
mlc_llm/relax_model/gpt_bigcode.py
mlc_llm/relax_model/gpt_neox.py
mlc_llm/relax_model/gptj.py
mlc_llm/relax_model/llama.py
mlc_llm/relax_model/llama_batched_vllm.py
mlc_llm/relax_model/mistral.py
mlc_llm/relax_model/rwkv.py
mlc_llm/relax_model/stablelm_3b.py

Currently, many MLC models use packed functions in dataflow blocks, which is not permitted. I plan to add a well-formedness check into the Relax parser to prevent that. Fortunately, `call_pure_packed` and `call_inplace_packed` can be used to avoid breaking any MLC models with this change. There are not many updates that need to be made, thankfully.
(Note: A few unrelated code changes were due to autoformatting.)

[Purity] Use `call_pure_packed` and `call_inplace_packed` where applicable

---

python/mlc_chat/compiler_pass/fuse_add_norm.py
python/mlc_chat/compiler_pass/pipeline.py

The current FuseAddRMSNorm would result in a workgroup of size 1024, while targets like webgpu maxes out at 256. This PR sets `TX` to `target.max_num_threads`.

[Pass] FuseAddRMSNorm max_num_threads awareness

---

android/library/src/main/assets/app-config.json
docs/deploy/android.rst

This PR fixes the `model_lib` field in `app-config.json` for phi-2 to match correctly with the `system-lib-prefix`.

[Andoird] Fix `model_lib` for phi-2

---

cmake/gen_cmake_config.py
docs/install/mlc_llm.rst
docs/install/tvm.rst

When using CUDA with compute capability >80, it is required to build runtime with `USE_FLASHINFER` and specifying `FLASHINFER_CUDA_ARCHITECTURES` and `CMAKE_CUDA_ARCHITECTURES`. Otherwise, users may run into issues like `Cannot find PackedFunc flashinfer.single_prefill in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable`.
This is related to issues https://github.com/mlc-ai/mlc-llm/issues/1728 and https://github.com/mlc-ai/mlc-llm/issues/1551

[Make] Add USE FLASHINFER into doc and gen cmake config

---

python/mlc_chat/quantization/group_quantization.py
python/mlc_chat/quantization/quantization.py

`q4f16_2` is useful for some models (like RWKV), which does not quantize the embedding layer and the final fc.

[SLM] Introduce `q4f16_2` Quantization

---

python/mlc_chat/interface/gen_config.py

Related to https://github.com/mlc-ai/mlc-llm/issues/1727
The new error message will look like:
```
[2024-02-14 10:06:49] WARNING gen_config.py:153: Convertion to `tokenizer.json` Failed with the exception below. Skipping the conversion. Tokenizer will only use `tokenizer.model`
...
```

Provide a better error message when conversion to tokenizer.json failed

---

mlc_llm/transform/reorder_transform_func.py

A pass must not mutate the `IRModule` that it receives as input. Unlike most functions exposed through the python API, the `IRModule.__setitem__` method mutates the underlying `IRModuleNode`. This can impact other users of the shared `IRModule` object, which expect mutation to be done using copy-on-write.
See https://github.com/apache/tvm/issues/11372 for more details.

[Bugfix] Remove mutation of IRModule in ReorderTransformFunc

---

mlc_llm/transform/lift_tir_global_buffer_alloc.py

Prior to this commit, the implementation of `mlc_llm.transform.LiftTIRGlobalBufferAlloc` assumed that every PrimFunc in a module was schedulable.  If the module contained a non-schedulable PrimFunc, the `assert isinstance(func.body, tir.BlockRealize)` would produce an error.
This commit updates `LiftTIRGlobalBufferAlloc` to leave unrecognized PrimFunc instances, and their callsites, unmodified.

[Transform] Handle non-schedulable func in LiftTIRGlobalBufferAlloc

---

mlc_llm/transform/transpose_matmul.py

A relax function may have `None` for `function.attrs`.  If this occurs, checking `"Composite" in function.attrs` would raise an error.

[Transform] Add check for function.attrs

---

mlc_llm/relax_model/commons.py
mlc_llm/relax_model/llama.py

Prior to this commit, the `weight.shard_dim` and `weight.shard_strategy` fields were defined when `combine_matmul=True`, but were left undefined in some locations for `combine_matmul=False`.  This commit adds definitions for these cases.

[Models] Define sharding strategy when combine_matmul=False

---

mlc_llm/relax_model/param_manager.py
mlc_llm/utils.py

Prior to this commit, the `loaded_idx_set`, `loaded_torch_bins`, `cached_relax_params`, and `cached_torch_params` objects were passed by the calling scope into `ParamManager.get_param_loading_functions`. These objects are implementation details for caching purposes, and are not required by the calling scope.
This commit updates `ParamManager.get_param_loading_functions` to construct the cache object internally.  The closures `get_item` and `set_item` returned from `get_param_loading_functions` have reference to the internal cache objects.

[ParamManager] Simplify get_param_loading_functions signature

---

mlc_llm/relax_model/commons.py
mlc_llm/relax_model/param_manager.py

Previously, the `transform_dequantize` pass would output a function where all parameters were named `f"param_{i}"`, which could be quite difficult to read.  This commit updates `transform_dequantize` to propagate the parameter names.
If a parameter is not quantized, its name remains the same.  If a parameter is quantized and produces a single output tensor, the new name is `f"{old_name}.{new_dtype}"`.  If a parameter is quantized and produces multiple output tensors, they are named
`f"{old_name}.{new_dtype}.{i}"`.

[ParamManager] Preserve variable names in transform_dequantize

---

mlc_llm/relax_model/llama.py
mlc_llm/relax_model/llama_batched_vllm.py
python/mlc_chat/nn/kv_cache.py

Because the symbolic variables may appear in many places throughout the resulting module, they should have more descriptive names, which can be understood outside of their original contexts.

[Llama] Add descriptive names for symbolic variables

---

mlc_llm/core.py
mlc_llm/dispatch/dispatch_tir_operator_adreno.py
mlc_llm/relax_model/llama.py
mlc_llm/transform/__init__.py
mlc_llm/transform/transpose_matmul.py

This improves the adreno dispatches for best unitization of hardware resources
Changes to the network to avoid unnecessary transposes which are not required for Adreno.
The decode performance is improved up to
Snapdragon Gen 2 :  11 toks/sec
Snapdragon Gen 3 : 14 toks/sec

[ANDROID][ADRENO] Various enhancements for Adreno target 

---

mlc_llm/relax_model/param_manager.py
mlc_llm/utils.py

Prior to this commit, `get_param_loading_functions` generated and returned both `get_item` and `set_item`.  The code paths for these two were entirely independent, and did not depend on each other.  This commit splits it into `get_param_get_item`, which returns the `get_item` function, and `get_param_set_item`, which returns the `set_item` function.

[ParamManager] Separate get_param_loading_functions for get/set

---

cpp/llm_chat.cc

Currently, line 1292 would lead to seg fault as we never initialize `support_backtracking_kv_` nor populate `fkvcache_array_popn_` when using PagedKVCache.

[Fix] Add PopN to single sequence for PagedKVCache

---

python/mlc_chat/conversation_template.py
python/mlc_chat/protocol/conversation_protocol.py
python/mlc_chat/protocol/openai_api_protocol.py
python/mlc_chat/serve/entrypoints/openai_entrypoints.py
python/mlc_chat/serve/server/server_context.py
tests/python/serve/server/test_server.py
tests/python/serve/server/test_server_function_call.py

This PR adds OpenAI compatible function calling functionality in serving.
**Summary of Changes**
- The `openai_entrypoints` module has been updated to handle function calls.
- New roles and message placeholders have been created for user, assistant, and functions.
- The `as_prompt` function has been modified to support the creation of prompts that include function calls.
- The `openai_api_protocol` has been expanded to include a new ChatToolCall class.
**Additional Note**
When `stream = True`, the output from function calls is currently returned in the `content` field, rather than the `tool_calls` field, which is used for non-streaming output.
The changes were collaboratively worked on with @shreygupta2809!
cc @tqchen

[Serving] Add OpenAI compatible function calling to Serving 

---

python/mlc_chat/compiler_pass/rewrite_kv_cache_creation.py
python/mlc_chat/nn/kv_cache.py
python/mlc_chat/op/position_embedding.py
tests/python/model/test_kv_cache.py

This PR supports the in-place rotary embedding function with the `rotary_dim` arg, so that it can apply to models like GPT-NeoX, Phi, etc..

[Op] Inplace RoPE supporting rotary dim

---

python/mlc_chat/nn/kv_cache.py

This PR adds a new function to PagedKVCache in MLC to return in-sequence positions for each location in a batch of sequences that is being forwarded. This function helps apply positional embeddings for language models (e.g., GPT-2, GPT-BigCode) that do not use Rotary positional embeddings.

[KVCache] Support returning query positions

---

python/mlc_chat/nn/kv_cache.py

This PR supports a "None" Rotary Embedding mode in PagedKVCache. When the mode is None, the rotary embedding will not be applied to when computing attention.

[KVCache] Support mode "None" for Rotary Embedding

---

python/mlc_chat/quantization/awq_quantization.py
python/mlc_chat/quantization/ft_quantization.py
python/mlc_chat/quantization/group_quantization.py
python/mlc_chat/quantization/utils.py

This PR reverts the change introduced in https://github.com/mlc-ai/mlc-llm/pull/1731 where we skip quantizing `lm_head` to avoid the dynamic vocab issue.
This led to performance degradation as pointed out in https://github.com/mlc-ai/mlc-llm/issues/1723.
Instead, we fall back to `GroupQuantizeLinear` for `lm_head`, which preserves performance and avoids the dynamic vocab size issue.
Performance change on RTX 4090
Prefill: 
throughput: **950.792 --> 973.859 tok/s**
total tokens: 7 tok
Decode:
throughput: **214.372 --> 223.491 tok/s**
total tokens: 256 tok

[FT] Fallback to GroupQuantize for lm head in FasterTransformer

---

python/mlc_chat/compiler_pass/pipeline.py
python/mlc_chat/compiler_pass/scatter_tuple_get_item.py

This PR introduces a pass that scatters the TupleGetItems of packed parameters centered at the beginning of Relax functions. This is because currently doing TupleGetItems in runtime for hundreds of times will cause significant CPU delay, which can be hidden when these operations are scattered, so that they can run in parallel with GPU kernels.

[Pass] Scatter centralized TupleGetItems

---

cpp/conv_templates.cc
python/mlc_chat/conversation_template.py

Remove the extra `\n` from the llama-2 system prompt to match with [Meta implementation](https://github.com/facebookresearch/llama/blob/ef351e9cd9496c579bf9f2bb036ef11bdc5ca3d2/llama/generation.py#L320-L353)

[Bug] Fix Llama2 System Prompt 

---

python/mlc_chat/op/moe_matmul.py
python/mlc_chat/quantization/group_quantization.py

This PR fixes #1752 . When using `faster_transformer`, the out_type of `indptr` is `int64`, but `dequantize_group_gemm` expects `int32`. 
An argument for `indptr_dtype` is added to the function to fix this.
Note that when using faster_transformer, the shape of `indptr` is `(num_experts,)` instead of `(num_experts + 1,)`

[Mixtral] Support int64 indptr

---

cpp/conv_templates.cc
python/mlc_chat/compiler_pass/pipeline.py
python/mlc_chat/compiler_pass/rewrite_kv_cache_creation.py
python/mlc_chat/model/gpt2/gpt2_model.py
python/mlc_chat/nn/kv_cache.py

This PR migrates GPT-2 model to the new PagedKVCache interface.
In GPT-2, attention calculation requires an additional feature `scale_attn_by_inverse_layer_idx`. It provides a scaling factor per attention layer when calculating the attention score, before applying the softmax function. Therefore, we need to support this additional parameter in PagedKVCache interface.
```
USER: i have this dream that one day
ASSISTANT: 
we can do a transpacific commercial plane and we can take you to the moon, we can take you to Mars, we can take you to Venus. And I can show you how to get there, because you know, I'm a technologist, I'm a mathematician, I'm a geologist, I'm a astrophysicist, I'm a space engineer. I can show you how to get there."
```

[KVCache] Migrate GPT-2 model to PagedKVCache, add support for attention score scaling in PagedKVCache

---

python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/nn/kv_cache.py

This PR migrates GPT-NeoX model to the new PagedKVCache interface.
```
mlc_chat chat HF://mlc-ai/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC --device "cuda:0" --overrides context_window_size=1024
<human>: Write me a poem about spring
<bot>: 
Spring is in the air
The birds are singing
The flowers are blooming
The sun is out
It's time for a walk
It's time for a run
It's time for a picnic
It's time for a bike ride
```
This PR also fixes a bug in paged KV cache kernel. Previously, it won't work with an attention head dimension of 80 and f32 quantization.

[KVCache][Bugfix] Fix KV cache kernel tile size. Migrate GPT-NeoX model to PagedKVCache

---

python/mlc_chat/model/gpt_neox/gpt_neox_model.py

Given we have switched over to use PagedKVCache, the previous effect-based KV cache can be removed so that they will not be initialzied at runtime (where the initialization may cause extra memory usage).

[GPTNeoX] Remove the "effect" KV Cache

---

python/mlc_chat/op/moe_matmul.py

This PR fixes a bug introduced by PR #1778 . When using `faster_transformer` the type of `indptr` is `int64`, and it's shape is `(num_experts,)` instead of `(num_experts+1,)`. The instances from `indptr[i]` to `indptr[i+1]` are assigned to the $i^{th}$ expert. The previous PR incorrectly calculates this assignment. We need to insert `0` at position 0 in `indptr` for correcting this.

[Mixtral] Fix indptr shape in dequantize_group_gemm

---

cpp/llm_chat.cc

This PR supports reading eos/bos token id from mlc-chat-config.json to handle models that have different bos/eos.
Co-authored-by: Charlie Ruan <53290280+CharlieFRuan@users.noreply.github.com>

[ChatModule] Read bos/eos from mlc-chat-config.json

---

android/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/library/src/main/assets/app-config.json
android/library/src/main/java/ai/mlc/mlcllm/ChatModule.java

This PR restores undoes the changes in #1798 to remove the `kv_cache_config`  argument from the `reload` function in android. This is due to the changes from #1809. Additionally, verified Gemma model on android and added it to the `app-config.son` by default.

[Android] Add Gemma model to Android

---

CMakeLists.txt
cpp/serve/grammar/grammar.cc
cpp/serve/grammar/grammar.h
cpp/serve/grammar/grammar_builder.h
cpp/serve/grammar/grammar_parser.cc
cpp/serve/grammar/grammar_parser.h
cpp/serve/grammar/grammar_serializer.cc
cpp/serve/grammar/grammar_serializer.h
cpp/serve/grammar/grammar_simplifier.cc
cpp/serve/grammar/grammar_simplifier.h
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher.h
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/serve/grammar/grammar_state_matcher_state.h
cpp/serve/grammar/support.h
cpp/support/encoding.cc
cpp/support/encoding.h
cpp/tokenizers.cc
cpp/tokenizers.h
python/mlc_chat/serve/__init__.py
python/mlc_chat/serve/grammar.py
tests/python/conftest.py
tests/python/serve/test_grammar_parser.py
tests/python/serve/test_grammar_state_matcher.py

This PR brings is the 2nd part of the support of grammar guided generation. It
- designs a visitor for visiting and mutating the BNF AST, provides a normalizer utility, and
- brings an effecient implementation of non-deterministic pushdown automata (NPDA) to match a character sequence to the specified grammar.
See grammar_state_matcher.h and grammar_state_matcher.cc for more details.
```
class GrammarStateMatcherNode : public Object {
public:
/*!
* \brief Accept one token and update the state of the matcher.
* \param token_id The id of the token to accept.
* \return Whether the token is accepted.
*/
virtual bool AcceptToken(int32_t token_id) = 0;
/*!
* \brief Find the set of tokens that are acceptable for the next step and store them in a
* bitmask.
* \param next_token_bitmask The bitmask …
```

[Serving][Grammar] BNF grammar simplifier and matcher

---

python/mlc_chat/conversation_template.py
python/mlc_chat/serve/async_engine.py
python/mlc_chat/serve/engine.py
tests/python/serve/server/test_server.py

This PR supports Mixtral in MLC serve. The main thing is only introducing the Mistral conversation template to Python registry so that MLC Serve can use.
Besides that, this PR updates the KV cache capacity analysis to make it more accurate in terms of usage calculation, while being conservative since there is a known issue regarding batch-prefill embedding taking which may lead to OOM. We will reset the follow up on the issue with a fix in the future and then enable the estimation to use more GPU vRAM.

[Serving] Support Mixtral in MLC Serve

---

cpp/serve/data.cc

Prior to this PR, `u_char` was used while it is not a standard type in C++, which causes Windows build failure.
This PR fixes it by using `unsigned char`.

[Fix] Fix `u_char` for Windows build

---

mlc_llm/core.py

Instead of a python function that returns an updated `IRModule`, the new `optimize_mod_pipeline` function returns a `tvm.ir.transform.Pass` which can be applied to an `IRModule`.

[Build] Replace mod_transform_before_build with IRModule pass

---

python/mlc_chat/support/convert_tiktoken.py
python/setup.py

This PR moves the import of transformers into the function body of tiktoken tokenizer conversion, so we do not have a force dependency on transformers.

[Python] Lazy import of transformers for tiktoken conversion

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/grammar/grammar.cc
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher.h
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/serve/grammar/support.h
cpp/serve/logit_processor.cc
cpp/serve/request_state.cc
cpp/serve/request_state.h
python/mlc_chat/compiler_pass/attach_to_ir_module.py
python/mlc_chat/protocol/openai_api_protocol.py
python/mlc_chat/protocol/protocol_utils.py
python/mlc_chat/serve/config.py
tests/python/serve/server/test_server.py
tests/python/serve/test_grammar_state_matcher.py
tests/python/serve/test_serve_engine_grammar.py

This PR is the 3rd part of the grammar-guided generation. This intregrates the grammar framework into the generation process, and supports JSON output for now.
The API this PR provides is compatible with the OpenAI api.
```
@dataclass
class ResponseFormat:
type: Literal["text", "json_object"] = "text"
json_schema: Optional[str] = None
@dataclass
class GenerationConfig:
response_format: ResponseFormat = ResponseFormat(type="text")
```
```
response_format: { "type": "text" } # text generation, by default
response_format: { "type": "json_object" } # json generation
response_format: { "type": "json_object", json_schema="..."} # json generation with schema
```
JSON generation with schema is not supported yet, but has been planned to be realized in the future.
```
Single token prefill latency: …
```

[Serving][Grammar] Integrate JSON grammar into the generation pipeline

---

mlc_llm/relax_model/param_manager.py
mlc_llm/transform/reorder_transform_func.py

Prior to this commit, the `ReorderTransformFunc` required several components of the `ParamManager` to use.  The functionality it provides, reordering dataflow blocks to minimize the liveset, is useful outside of the context of the `ParamManager`.  This commit makes the following changes, allowing it to be used independently of the `ParamManager`.
- Generate the `pidx2binname` dictionary outside of `ReorderTransformFunc`
- Allow parameters to be separate `func.params`, rather than a single bundled tuple parameter.

[Utils] Allow ReorderTransformFunc to be used without param manager

---

python/mlc_chat/model/phi/phi_model.py

This PR migrates Phi-2 for Paged KV cache Attention as a part of Model definition migration according to #1749 .
This was worked on collaboratively with @shreygupta2809.
cc @CharlieFRuan @tqchen

[SLM] Migrate Phi-2 to paged KV Cache #1871

---

mlc_llm/core.py

PR #1852 missed to apply the BundleModelParams pass and thus made the compiled models not runnable through ChatModule (#1864). This PR fixes the issue.

[Fix] Add the missing BundleModelParams pass

---

docs/compilation/compile_models.rst
docs/compilation/convert_weights.rst

There's an link on the MLC-LLM that the link is expired (mentioned in one issue before). Updated the website with the new link

Fix MLC-LLM website link weight convert not accessible

---

ci/task/pylint.sh
cpp/serve/engine_actions/action_commons.cc
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher.h
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/serve/logit_processor.cc
cpp/serve/request_state.cc
python/mlc_chat/protocol/openai_api_protocol.py
python/mlc_chat/protocol/protocol_utils.py
python/mlc_chat/serve/grammar.py
tests/python/serve/test_grammar_parser.py
tests/python/serve/test_grammar_state_matcher.py

This PR adds a feature for GrammarStateMatcher that it can accept a stop token when previous accepted tokens reach the end of the grammar. 
This will help the caller side when enabling accepting the stop token will simplify the logic. For our case, we can accept tokens in RequestModelStateNode::CommitToken, that is, immidiately after generation and before checking if end token occurs.
The matcher is terminated after accepting the stop token, i.e. no accept_token or find_next_rejected_tokens operations can be performed. The termination state can be canceled using Rollback().
`is_terminated` method is used to detect if the matcher enters the termination mode:
```
def is_terminated(self) -> bool:
"""Check if the matcher has accepted the stop token and terminated. See also …
```

[Serving][Grammar] Support termination state in GrammarStateMatcher

---

python/mlc_chat/cli/model_metadata.py
python/mlc_chat/compiler_pass/rewrite_kv_cache_creation.py
python/mlc_chat/serve/engine.py

Prior to this PR, the serving engine memory usage estimation reads model config for fields such as `num_key_value_heads`, `num_hidden_layers`, etc.. However, since not every model share the same set of config names (#1854), the estimation fails for models that do not have this set of config field names.
This PR makes the following changes. First, it attaches these field values into the model's metadata, in which way we unify the field names for different models effectively. Then, when estimating the memory usage, we read these fields from the metadata, rather than model config, so we are safe for the name inconsistency.

[Serving] Estimate KV cache memory usage with metadata

---

python/mlc_chat/conversation_template.py

This PR adds the phi-2 model template to MLC serve.
For testing
1. Start server
```python -m mlc_chat.serve.server --model ./dist/phi-2-q4f16_1-MLC/ --model-lib-path ./dist/phi-2-q4f16_1-MLC/phi-2-q4f16_1-cuda.so --device auto --max-batch-size 2 --enable-tracing --host 127.0.0.1 --port 8000 --max-total-seq-length 8000```
2. Send request
```python test_server_rest_api.py```
```python
import requests
import json
model = "./dist/phi-2-q4f16_1-MLC/"
port = 8000
payload = {
"model": f"{model}",
"messages": [{"role": "user", "content": "Tell me about Machine Learning in 200 words."}],
"stream": False,
}
r = requests.post(f"http://127.0.0.1:{port}/v1/chat/completions", json=payload)
if r.status_code != 200:
print(r.json())
else:
print(r.json()["choices"][0]["message"]["content"])
```
cc @tqchen

[Serving] Add Phi-2 conv template to mlc serve

---

python/mlc_chat/nn/kv_cache.py

Prior to this PR, our TIR prefill attention kernel assumes the head dim to be a multiple of 32. As reported by #1826, this assumption does not always hold.
This PR fixes this issue so that models with different head dim can also compile.

[Attn] Fix attention kernel for head dim not divisble by 32

---

cmake/gen_cmake_config.py
python/mlc_chat/support/auto_target.py

This PR enables thrust for CUDA targets so that we can dispatch some operators (e.g., cumsum) to thrust.

[Python] Enable "thrust" for CUDA by default

---

python/mlc_chat/model/baichuan/baichuan_model.py
python/mlc_chat/model/gemma/gemma_model.py
python/mlc_chat/model/gpt2/gpt2_model.py
python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/model/internlm/internlm_model.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/model/mixtral/mixtral_model.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/model/qwen/qwen_model.py
python/mlc_chat/model/stable_lm/stablelm_model.py

This PR contains four changes:
1. It removes the duplicate `batch_forward` defined in model definitions. This function was widely used prior to our migration to PagedKVCache, since before migration the attention codepath of single sequence forward and batch forward differ. But since our migration, the codepaths are unified into one, and therefore we can safely remove most `batch_forward` functions.
2. It moves `op.ccl_broadcast_from_worker0` from model main forward (which will be called at the beginning of prefill/decode) to embedding. This change has two benefits. Firstly, the token ids taken by `embed` was not broadcasted across workers, and it is possible for workers other than 0 to have illegal token ids which is not in the range of vocab size, and moving the broadcasting to `embed` …

[Model] Remove redundant `batch_forward` and move broadcast

---

python/mlc_chat/model/qwen2/qwen2_model.py

This PR migrates Qwen2 model to the new PagedKVCache interface.
Screenshot

[KVCache]Migrate Qwen2 model to PagedKVCache

---

cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc

The header `<numeric>` was missed, which may have caused build failure on Windows. This PR adds the header.

[Serving] Add missing header for `std::iota`

---

cpp/serve/model.cc

This PR fixes a severe bug introduced by #1899.
Since #1899, we no longer copy the embedding back from worker 0 when using tensor parallelism. However, we did not synchronize with the worker 0.
This will cause the following issue: in batch prefill, we will continuously call TokenEmbed for multiple times. Each time, we will copy the token ids to the `token_ids` NDArray on worker 0. If we do not synchronize with worker 0, then it is possible that the local token ids have been updated for multiple times, before the first `CopyToWorker0` really starts to execute on the worker 0 side. As a result, at the time of executing the token ids copy to worker 0, the local token ids might be wrong (by "wrong", say we are executing the copying of seq 0's token ids, then the actual local token ids array …

[Serving] Fix Model TokenEmbed function with TP

---

cpp/llm_chat.cc
cpp/serve/model.cc
python/mlc_chat/compiler_pass/attach_to_ir_module.py
python/mlc_chat/model/baichuan/baichuan_model.py
python/mlc_chat/model/gemma/gemma_model.py
python/mlc_chat/model/gpt2/gpt2_model.py
python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_chat/model/gpt_neox/gpt_neox_model.py
python/mlc_chat/model/internlm/internlm_model.py
python/mlc_chat/model/llama/llama_model.py
python/mlc_chat/model/orion/orion_model.py
python/mlc_chat/model/phi/phi_model.py
python/mlc_chat/model/qwen/qwen_model.py
python/mlc_chat/model/qwen2/qwen2_model.py
python/mlc_chat/model/rwkv5/rwkv5_model.py
python/mlc_chat/model/stable_lm/stablelm_model.py

Prior to this PR, there is a trailing reshape kernel at the end of the embedding func. The reshape is not necessarily needed to be as a kernel, which consumes extra time during execution. This PR eliminates the reshape in the embedding function by updating the signature of the embedding func, so that now it only takes the plain 1D token ids as input.

[Model] Eliminate the reshape in embedding func

---

python/mlc_chat/compiler_pass/low_batch_specialization.py
python/mlc_chat/compiler_pass/pipeline.py

When batch size is small, GEMM in MLP of decode stage can be dispatched into a specialized GEMV-like schedule to improve efficiency.
GEMM with a dynamic var in spatial axis will now be lowered into 
```
if dyn_var <= 8:
low_batch_gemv()
else:
normal_gemm()
```

Low batch GEMM using GEMV-like schedule

---

cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc

Following up #1906, this PR removes the synchronization given it is avoidable. We use another approach to avoid the write-after-write issue.
The key to address the issue is to make sure the addresses to be copied to worker 0 is not rewritten before the copy actually happens. So we pre-allocate a large host array to hold all the token ids, and for each sequence, we copy its token ids to the offset given when calling TokenEmbed, so that we can make sure an address will not be written twice before copy happens.

[Serving] Avoid unnecessary worker sync in Model

---

cpp/serve/grammar/grammar.cc
cpp/serve/grammar/grammar.h
cpp/serve/grammar/grammar_builder.h
cpp/serve/grammar/grammar_parser.cc
cpp/serve/grammar/grammar_serializer.cc
cpp/serve/grammar/grammar_serializer.h
cpp/serve/grammar/grammar_simplifier.cc
cpp/serve/grammar/grammar_simplifier.h
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/serve/grammar/grammar_state_matcher_state.h
python/mlc_chat/serve/grammar.py
tests/python/serve/test_grammar_parser.py
tests/python/serve/test_grammar_state_matcher_custom.py
tests/python/serve/test_grammar_state_matcher_json.py

This PR enhances GrammarStateMatcher to support general grammar that can be provided as EBNF. This PR makes to enhancements:
- Support rules starting with reference to another rule. Previously every rule must start with a character class.
- Support both character range + star (`[a-z]*`) and expression + star (`("a" | another_rule "b")*`)
When the user provides some special grammars, especially those containing deep nesting or providing many parsing possiblities when parsing prefixes, the performance will significantly decrease. This will be further optimized in the following pull requests.
cc @tqchen @MasterJH5574

[Serving][Grammar] Enhance GrammarStateMatcher to support general grammar

---

python/mlc_chat/compiler_pass/dispatch_kv_cache_creation.py
python/mlc_chat/nn/kv_cache.py

With https://github.com/apache/tvm/pull/16684 merged in, the KV cache creation will fail when compiling models. This PR fixes the problem by using `call_pure_packed`.

[Fix] KVCache creation with call_pure_packed

---

docs/install/mlc_llm.rst
docs/install/tvm.rst

We have deprecated the wheel support for CUDA 11.7/11.8 due to TVM thrust compatibility with old CUDA versions.

[Docs] Deprecating CUDA 11.7/11.8 support

---

python/mlc_llm/model/mistral/mistral_model.py

The latest TVM introduces the wellformedness check of the IR. The mistral model definition breaks the wellformedness due to the purity. This PR fixes this issue.

[Fix] Fix KV cache call in mistral

---

cpp/llm_chat.cc

This PR removes the eos_token_ids from the ChatModule given it is nowhere used actually.

[ChatModule] Remove eos_token_ids

---

python/mlc_llm/serve/engine.py

This PR constrains the KV cache capacity for Metal devices to 32768, in order to avoid large tensors in KV cache. This is because right now Metal runtime has performance issue when running a kernel where when some input buffer is very large, even if little of the large buffer is accesed in the kernel.

[Serve] Constrain KV cache capacity on Metal

---

python/mlc_llm/compiler_pass/attach_logit_processor.py
python/mlc_llm/compiler_pass/pipeline.py

Make the kernels in `AttachLogitProcessFunc` to be aware of maximum threads, fixing https://github.com/mlc-ai/mlc-llm/issues/1951.
Most code change is due to indentation, the main change is changing `1024` to `tx`, where `tx` is
```
tx = 1024  # default
max_num_threads_per_block = get_max_num_threads_per_block(target)
if max_num_threads_per_block < tx:
tx = max_num_threads_per_block
check_thread_limits(target, bdx=tx, bdy=1, bdz=1, gdz=1)
```

[LogitProcessor] Add max thread awareness to logit processing kernels

---

python/mlc_llm/interface/compiler_flags.py

This PR supports the detection of if FlashInfer is enabled when building TVM, so that FlashInfer won't be enabled when TVM is not built with FlashInfer enabled.

[CompilerFlag] Detect if FlashInfer is enabled from libinfo

---

tests/python/serve/server/test_server.py

`test_server::is_json_or_json_prefix` is used to check the output is JSON or a prefix of JSON. 
It uses json.loads internally. However, json.loads (i.e. json.decode) is token-based instead of char based. If half a token is left at the end of the string, it cannot be matched.
This PR adds another check for the rest "half a token" if it exists.

[Serving][Fix] Fix JSON output check in test_server.py

---

python/mlc_llm/conversation_template.py

Since we don't have the `add_bos` field: https://github.com/mlc-ai/mlc-llm/blob/main/cpp/conversation.h#L73 in the new Conversation template, we should add the bos token into the system_prefix_token_ids, so that it will be added to the tokenized prompt.

[Conv] Add bos_token to llama and mistral in ConvTemplateRegistry

---

python/mlc_llm/interface/compiler_flags.py
python/mlc_llm/support/auto_target.py

In the latest gpu, cuda arch may not be integer, e.g `sm_90a`. This fixes a few places that rely on integer parsing.
cc @tqchen @MasterJH5574

[Fix] Fix handling of non-numerical cuda arch

---

cpp/serve/grammar/grammar.cc
cpp/serve/grammar/grammar.h
cpp/serve/grammar/grammar_builder.h
cpp/serve/grammar/grammar_parser.cc
cpp/serve/grammar/grammar_parser.h
cpp/serve/grammar/grammar_simplifier.cc
cpp/serve/grammar/grammar_simplifier.h
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/serve/grammar/grammar_state_matcher_state.h
python/mlc_llm/serve/grammar.py
tests/python/serve/test_grammar_state_matcher_custom.py

This PR supports specifying the name of the main rule when parsing a grammar, and adds internal support for specifying the main rule in the grammar AST. New interface for parser:
```
def from_ebnf_string(
ebnf_string: str,
main_rule: str = "main",
normalize: bool = True,
simplify: bool = True,
) -> "BNFGrammar":
pass
```

[Serving][Grammar] Support specifying the main rule in grammar

---

python/mlc_llm/support/auto_target.py

This PR fixes the missing patch for target with `sm_90a` arch, as follow up pr of #1976.
cc: @vinx13

[Fix] Fix `MLC_MULTI_ARCH` with arch `sm_90a`

---

python/mlc_llm/conversation_template.py
python/mlc_llm/protocol/conversation_protocol.py
tests/python/protocol/test_converation_protocol.py

The current prompt format for Llama-2 and Mistral is not completely correct.
This PR updates the code to strictly follow the official prompt format for the two models. Also adds in missing conv templates to ConvTemplateRegistry.

Fix Llama-2 and Mistral conversation template. Update ConvTemplateRegistry

---

cpp/serve/engine.cc
cpp/serve/model.cc
cpp/serve/model.h

This PR temporarily fixes sampler selection logic for speculative decoding. As GPU sampler support for speculative decoding is not ready, speculative decoding will use cpu sampler.

[SpecDecode] Fix sampler selection.

---

python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/json_schema_converter.py
tests/python/serve/test_json_schema_converter.py

This PR adds a generic utility to convert json schema, especially generated from pydantic, to EBNF grammar. This helps the grammar guided generation when we provide a json schema as the restriction.
This converter features the support of json standard indent style in the output grammar.
API:
```
def json_schema_to_ebnf(
json_schema: str,
*,
indent: Optional[int] = None,
separators: Optional[Tuple[str, str]] = None,
strict_mode: bool = True,
) -> str:
"""Convert JSON schema string to EBNF grammar string.
Parameters
----------
json_schema : str
The JSON schema string.
indent : Optional[int]
The number of spaces for each indent. If it is None, there will be no indent or newline.
The indent and separators parameters follow the same convention as
`json.dumps()`.
separators : …
```

[Serving][Grammar] Utility to convert json schema to EBNF grammar

---

python/mlc_llm/nn/kv_cache.py

This PR fixes the mistake of passing wrong number of heads to the attention result merge kernel.

[Attn] Fix the construction of attn result merge kernel

---

android/library/prepare_model_lib.py
android/library/src/main/assets/app-config.json
ios/prepare_model_lib.py

This PR adds validation of symbols in iOS and android build. During static library build, we need the right model_lib for us to point to the packaged model executables.
Not doing so correctly will results in vm_load_executable not found which is not informative.
This PR we validate the compiled model lib by dumping the global symbols and ensure the list of model libs matches with each other.
In future we should perhaps lift the validation to mlc_llm package.

[iOS][Android] Add validation of library file for iOS and Android build

---

cpp/serve/model.cc

The changes in https://github.com/apache/tvm/pull/16750 modified the signature of the Storage, this pull request updates the caller code in mlc-llm to accommodate the new Storage class signature. Ran into build error w/o the change.
```
mlc-llm/cpp/serve/model.cc:67:96: error: no matching function for call to ‘tvm::runtime::memory::Storage::Storage(tvm::runtime::memory::Buffer)’
67 |         memory::Storage(allocator->Alloc(device_host, {prefill_chunk_size_}, DataType::Int(32)));
```
cc: @MasterJH5574 @vinx13 @tqchen

[Serve] add allocator in Storage as the upstream change

---

python/mlc_llm/compiler_pass/pipeline.py
python/mlc_llm/interface/compile.py
python/mlc_llm/interface/compiler_flags.py

This PR introduces the IPC memory and customized all-reduce kernel dispatches for tensor parallelism. We add a new compiler flag `--allreduce-strategy`, which supports `"ring"`, `"one-shot"` and `"two-shot"`. The flag defaults to `"ring"`, which means this PR makes no difference if people do not manually change the all-reduce strategy.
As of now the IPC-memory-backed customized all-reduce kernels are only available on CUDA.
To enable all-reduce strategies other than "ring", here are some example compile commands:
```python
python -m mlc_llm compile model/mlc-chat-config.json --device cuda --opt "allreduce-strategy=one-shot" -o model/lib.so
python -m mlc_llm compile model/mlc-chat-config.json --device cuda --opt "allreduce-strategy=two-shot" -o model/lib.so
```
Please be aware that, you …

[Compiler] Support IPC memory and customized all-reduce kernels

---

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py

This PR corrects the assertion after latest changes in apache/tvm that updates some nn.Module behavior.

[Fix] Fix KV cache creation pass after nn.Module changes

---

ios/prepare_model_lib.py

`tar_list.append(valid_paths[ls0])` is introduced by mistake in https://github.com/mlc-ai/mlc-llm/pull/1993, which fails the prepare_libs.sh with error: 
```
ios/prepare_model_lib.py", line 39, in main
tar_list.append(valid_paths[ls0])
^^^
NameError: name 'ls0' is not defined
```

[iOS] Fix typo in prepare_model_lib.py

---

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py

This particular assertion is unstable recently given the back-and-forth upstream TVM nn.Module exporter behavior.

Remove unstable assertion in KV cache creation dispatch

---

python/mlc_llm/support/preshard.py

When the pre-sharded version of a certain model is not available, the program will default back to the normal workflow without issuing any alert. Now, when someone attempts to convert to a pre-sharded model but cannot, the program will throw a warning message to inform users that it will revert to the standard model conversion process.

more info for preshard 

---

python/mlc_llm/serve/server/popen_server.py
tests/python/serve/server/conftest.py

This PR fixes several problems in the PopenServer:
- Add check for the server is not started and the request returns a fail number, e.g. 502. And changed the retry time to 0.1s.
- Add a `__enter__` and `__exit__` method for PopenServer. When the program is interrupted, using `with` clause (`__enter__` and `__exit__`) can ensure the server always terminates. When using `start()` and `terminate()`, the server  may still be staying in the background even though the parent process ends.

[Serving][Fix] Fix problems in PopenServer

---

python/mlc_llm/compiler_pass/pipeline.py
python/mlc_llm/interface/compile.py
python/mlc_llm/interface/compiler_flags.py

This PR supports the auto mode for IPC all-reduce strategy. It renames the strategy from `allreduce-strategy` to `ipc-allreduce-strategy` in the compiler optimization flags. The default RING mode is renamed to NONE mode, which, when specified, uses nccl all-reduce without any IPC memory rewrite.
So right now to enable IPC all-reduce, the ideal way is to do `ipc-allreduce-strategy=auto`.

[Compiler] Support AUTO mode for all-reduce strategy

---

python/mlc_llm/conversation_template.py
python/mlc_llm/protocol/conversation_protocol.py
python/mlc_llm/protocol/openai_api_protocol.py
python/mlc_llm/serve/entrypoints/entrypoint_utils.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py

This is a follow-up PR to #1974 . 
1. Added base64 image support
2. Merged the `as_prompt` and `as_prompt_list` functions in `conversation_protocol.py`
3. `get_image_from_url` uses model config to determine image input size

[LLaVa] Follow-up for TODOs in LLaVa model

---

python/mlc_llm/compiler_pass/pipeline.py

This PR moves the position of GPU IPC memory lowering pass in pipeline, so that it applies after the CUDA graph rewrite to enable CUDA graph with the customized all-reduce kernels.

[Pipeline] Defer GPU IPC memory lowering

---

cpp/serve/engine.cc
cpp/serve/model.cc
cpp/serve/model.h

This PR removes the synchronization in `Model` when Chrome tracing is not enabled. It can help some logit process kernels launching earlier.

[Model] Skip TVMSynchronize when tracing is not enabled

---

cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/logit_processor.cc
cpp/serve/model.cc
cpp/serve/sampler/gpu_sampler.cc

This PR supports MLC serve with NVTX which helps analyzing benchmarking results.
**Note.** To enable NVTX, please add `set(USE_NVTX ON)` to file `build/config.cmake`.

[Serving] Support NVTX for benchmarking

---

cpp/serve/async_threaded_engine.cc
cpp/serve/async_threaded_engine.h
cpp/serve/engine.cc
cpp/serve/engine.h
python/mlc_llm/serve/async_engine.py
python/mlc_llm/serve/entrypoints/debug_entrypoints.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py
tests/python/serve/test_serve_engine_grammar.py

This PR enhances the AsyncThreadEngine by separating the callback invocation to another thread, in order to reduce the CPU time overhead of invoking Python callback.

[Serve] Separate callback invocation to another thread in AsyncEngine

---

python/mlc_llm/conversation_template.py

This PR fixes a bug in LLaVa which used to output a random token after the first `.` token (i.e. after the end of the first sentence). 
In the [HF reference](https://huggingface.co/docs/transformers/en/model_doc/llava), there is supposed to be a newline (`\n`) between the image and the prompt. It turns out having a newline anywhere in the prompt fixes this issue. So passing it as part of the system prompt.

[LLaVa] Fix random token output after first sentence

---

python/mlc_llm/nn/kv_cache.py
python/mlc_llm/op/position_embedding.py

This PR enhances the TIR attention-related functions to support matching arbitrary element offests. This makes room for the KV cache to allocate a large array the all the auxiliary data and do slicing on it.
This PR should affect nothing for the current codebase, given all the element offsets are zeros as of now.

[KVCache] Support matching arbitrary element offset for aux data

---

python/mlc_llm/testing/__init__.py
python/mlc_llm/testing/debug_chat.py

This PR implements `testing.DebugChat` for end-to-end model debugging in Python.
- It debugs autoregressive decoding fully in Python via the `prefill` and `decode` interface. 
- It supports debugging instrument (either default or customized) to dump intermediate values for each VM function call.
- Given a prompt, it also prints out the parsed prompt, input tokens, output tokens and output text.
- The default instrument will dump intermediate values of all VM function calls into .npz files, and also alert user about `NaN` or `INF` values in the outputs.
- Also add a simple CLI for quick debugging.
Example usage (under ROOT/python):
```
$ python mlc_llm/testing/debug_chat.py "hello there" --generate-len 3 --model ../dist/Llama-2-7b-chat-hf-q4f16_1-MLC --model-lib-path …
```

Implement testing.DebugChat for end-to-end model debugging in Python

---

ci/jenkinsfile.groovy

The incoming WASM runtime requires 3rdparty for builds. This PR enables the submodule clone for WASM model compilation in CI.

[CI] Enable submodule clone for WASM model compilation

---

cpp/serve/model.cc
cpp/serve/model.h

With PagedKVCache supporting fork at a specified position, this PR updates `Model` interface accordingly. The fork position defaults to -1, which means the last position.

[Serve] Fork sequence at specified positions

---

ci/task/test_model_compile.sh
cpp/serve/grammar/grammar_state_matcher.cc
docs/install/emcc.rst
python/mlc_llm/serve/grammar.py
python/mlc_llm/support/auto_target.py
scripts/prep_emcc_deps.sh
web/Makefile
web/README.md
web/emcc/mlc_wasm_runtime.cc

This PR supports wasm runtime in MLC. The main change is a `web` folder, built similarly to [tvm/web](https://github.com/apache/tvm/tree/main/web).
By running `make` under `web`,  we create artifact `mlc_wasm_runtime.bc`, which is passed into the model library's wasm (see changes in `auto_target.py`), so that during runtime, WebLLM can directly use functions defined in MLC-LLM that are registered globally in TVM.
Currently, only global TVM functions in grammar are included in the wasm (see the included list in `web/emcc/mlc_wasm_runtime.cc`). We also define macro `COMPILE_MLC_WASM_RUNTIME` so that dependencies can be minimized (otherwise we need to build the entire `tokenizers-cpp` into the wasm). `FindNextTokenBitmaskAsNDArray()` is defined additionally to help Web runtime deal with …

[WebGPU] Add mlc wasm runtime, support grammar in web

---

CMakeLists.txt

Prior to this commit, the `CMakeLists.txt` file checked a cmake `TVM_HOME` variable, but did not check the usual `TVM_HOME` environment variable.  If this variable is set, it should be used.

[Build] Use TVM_HOME environment variable

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/model.cc
python/mlc_llm/serve/async_engine.py
python/mlc_llm/serve/engine.py

This PR supports input chunking with regard to customized "prefill chunk size" (field `prefill_chunk_size` in `mlc-chat-config.json`). With this PR, we can now chunk a long input into multiples when there is an upper limit on the prefill chunk size. Only `TokenData` is supported for now.

[Serving] Support input chunking

---

python/mlc_llm/compiler_pass/estimate_memory_usage.py

The function for metadata has global symbol `main` that is inconsistent with the function name

Fix mismatch of metadata func and global symbol

---

cpp/serve/function_table.cc
cpp/support/utils.h

This PR enables setting the CPU affinity of disco workers in MLC, following the support in apache/tvm#16807. The purpose is to try reduce the CPU core switch overhead brought to disco workers which may cause extra bubble times in disco workers before/during tasks.
We use a macro `MLC_DISCO_WORKER_CPU_BINDING` to specify the CPU affinities of workers. This is by default not used. To enable it, you can run the command like
```shell
MLC_DISCO_WORKER_CPU_BINDING=64,65,66,67 python some_mlc_app.py
```
to specify the four CPU core ids for the four workers.

[Disco] Set worker CPU affinity with env variable

---

python/mlc_llm/compiler_pass/fuse_dequantize_matmul_ewise.py
python/mlc_llm/interface/compiler_flags.py
python/mlc_llm/model/llama/llama_quantization.py
python/mlc_llm/model/mixtral/mixtral_model.py
python/mlc_llm/model/mixtral/mixtral_quantization.py
python/mlc_llm/model/model.py
python/mlc_llm/nn/expert.py
python/mlc_llm/op/cutlass.py
python/mlc_llm/op/moe_matmul.py
python/mlc_llm/quantization/__init__.py
python/mlc_llm/quantization/fp8_quantization.py
python/mlc_llm/quantization/per_tensor_quantization.py
python/mlc_llm/quantization/quantization.py
python/mlc_llm/quantization/utils.py

This introduces a new quantization mode FP8 per-tensor quantization that quantizes both weight and activation. `e5m2_e5m2_float16` uses `e5m2_float8` for both inputs and weights, the outputs and the un-quantized parts are in fp16. Calibration is not supported in this PR.
Co-authored-by: Chris Sullivan \<csullivan@octo.ai\>
Co-authored-by: Joseph McMahan \<jmcmahan@octoml.ai\>
cc @tqchen @csullivan @JosephTheOctonaut @MasterJH5574

[Quantization] Introduce PerTensor and F8 quantization

---

cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h

This PR renames the AsyncThreadedEngine to ThreadedEngine to prepare for follow up refactors of Python interface. Meanwhile, this PR exposes a creation function for AsyncThreadedEngine so that it can be further used by others, such as JSONFFIEngine.

[Serving][Refactor] Rename AsyncThreadedEngine to ThreadedEngine

---

tests/python/serve/benchmark.py

Add cuda profiling in the test script. Rename `batch-size` to `max-num-sequence`
Co-authored-by: Wuwei Lin <[wuwei@apache.org](mailto:wuwei@apache.org)>
cc: @vinx13

[Serving] Add cuda profiling in benchmark test

---

cpp/serve/engine_actions/new_request_prefill.cc

This PR fixes a bug when trying to chunk an input and do prefill. The stats prior ot this PR was wrong.

[Serving][Fix] Fix chunked prefill condition

---

cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h

This PR separates the creation and initialization of ThreadedEngine for multi-threading use cases. So we can make sure that the ThreadedEngine instance is created before any other operations (such as initialization, running background loop, etc.).

[Serving] Separating ThreadedEngine creation and initialization

---

docs/deploy/rest.rst

This updates the rest docs to use `mlc_llm serve` and also adds a quick start section.

[Rest] Update REST API docs

---

python/mlc_llm/serve/engine.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_engine.py

This PR aligns the Python API of chat completions and completions MLC serve with the OpenAI Python package https://github.com/openai/openai-python.
Specifically, say we first create an engine or async engine, then we can use entrance `engine.chat.completions.create(...)` for chat completions.
We will add more use examples in the codebase after another few refactors.

[Serving][Refactor] OpenAI API Python interface alignment

---

docs/install/tvm.rst

Fixed one slight issue of tvm install: would require specify python=3.11 on the platform otherwise will encounter python not found error on 4090 Linux issue.

[DOC] fix small python env install error

---

python/mlc_llm/quantization/awq_quantization.py
python/mlc_llm/quantization/ft_quantization.py
python/mlc_llm/quantization/group_quantization.py
python/mlc_llm/quantization/utils.py

This PR strenthens the MoE gate checks to include checking number of experts, given the real MoE gate router layer's output feature number is the number of experts and is usually very small.
This PR comes from a regression that there is a layer in RWKV6 that ends with name "gate" is not for MoE at all.

[Quantization] Stricter checks for MoE gate

---

cpp/metadata/model.h

This PR fixes the picojson uses in MLC that conflicts with the latest changes on the picojson side.

[Metadata] Include picojson rather than forward declaring

---

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py
python/mlc_llm/op/attention.py

Enable flashinfer when group_size == 6

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/logit_processor.cc
cpp/serve/model.cc
cpp/serve/model.h
cpp/serve/request_state.cc
cpp/serve/request_state.h
cpp/serve/sampler/cpu_sampler.cc
python/mlc_llm/compiler_pass/attach_sampler.py
python/mlc_llm/model/eagle/eagle_loader.py
python/mlc_llm/model/eagle/eagle_model.py
python/mlc_llm/model/eagle/eagle_quantization.py
python/mlc_llm/model/llama/llama_model.py
python/mlc_llm/model/model.py
python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/config.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine_spec.py

1. Add Eagle-Llama-7b-chat model support.
2. Add speculative decoding support with Eagle.

[SpecDecode] Support Eagle in speculative decoding

---

python/mlc_llm/compiler_pass/attach_sampler.py
python/mlc_llm/compiler_pass/attach_support_info.py

This PR attaches the attributes of `tir.non_negative_var` for memory planning.

[Pass] Attach non-negative TIR var attributes

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine.h
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
python/mlc_llm/cli/serve.py
python/mlc_llm/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/server/popen_server.py
python/mlc_llm/serve/sync_engine.py
tests/python/json_ffi/test_json_ffi_engine.py
tests/python/serve/benchmark.py
tests/python/serve/evaluate_engine.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_grammar.py
tests/python/serve/test_serve_engine_image.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

This PR is a refactor of the engine's contructor interface and the serve CLI interface.
This PR introduces the "mode" argument for engine, which has options "local", "interactive" and "server". The choice of mode will affect the automatically inferred value of `max_batch_size`, `max_total_sequence_length` and `prefill_chunk_size` (only effective when arguements are not specified. Once an argument is specified, we will not override it). For detailed specification of the mode, please check out the CLI help messages in `mlc_llm/help.py` or the engine constructor in `mlc_llm/serve/engine.py`.
No matter which mode is chosen, we will print out the current mode and the values of these arguments, for peopple to understand the settings of the engine. We also provide hints on how to adjust the …

[Serving][Refactor] Engine constructor interface refactor

---

cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/sampler/gpu_sampler.cc

Prior to this PR, due to the improper prefill policy on `n` (parallel generation), the engine will loop forever when the a request has `n` larger than the maximum batch size that the engine can support.
This PR fixes this issue by updating the prefill action, and with this PR, even the "interactive" engine mode can well support multiple parallel generation.
After this fix, it is possible that a request require 10 parallel generation while the max batch size is 1. Given the shapes of temporary NDArrays in GPU sampler is determined by the max batch size, GPU sampler does not natively support sampling 10 tokens at a time. To approach this issue, this PR introduces chunking to GPU sampler. Therefore, in this particular case, the GPU sampler will have chunk size 1, and the 10 required samples …

[Serving] Fix support of large `n` under low max batch size

---

docs/compilation/compile_models.rst
docs/compilation/convert_weights.rst
docs/deploy/javascript.rst
docs/deploy/python_chat_module.rst
docs/deploy/python_engine.rst
docs/index.rst
examples/python/sample_mlc_engine.py
python/mlc_llm/__init__.py

This PR revamps the landing documentation page.
* The Python API panel is changed from showing ChatModule to showing Engine.
* A new panel "REST Server" is added to show a quick start example of launching REST server and send request.
* A "what to do next" section is introduced at the bottom of the landing page.
Todo items for future PR:
* add the page of Python API with Engine.
* revamp weight conversion page.
* revamp model library compilation page.

[Docs] Revamp landing page with Engine Python API and server

---

python/mlc_llm/model/eagle/eagle_model.py

This PR added an optional fc bias option so that mixtral eagle model could be loaded.
Fix referenced from https://github.com/SafeAILab/EAGLE/blob/08dc06ccb428f2d3cf8380933ea50ed3e4178168/eagle/model/ea_model.py#L42
CC: @KnowingNothing @tqchen

[Minor][SpecInfer] Fix Optional FC Bias for Mixtral Eagle Model

---

docs/deploy/python_engine.rst
docs/get_started/introduction.rst
docs/get_started/quick_start.rst
examples/python/sample_mlc_engine.py
python/mlc_llm/__init__.py
python/mlc_llm/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/server/server_context.py
python/mlc_llm/serve/sync_engine.py
tests/python/serve/evaluate_engine.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_grammar.py
tests/python/serve/test_serve_engine_image.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

We rename the public Python serve interface from `Engine` to `LLMEngine` (and from `AsyncEngine` to `AsyncLLMEngine` accordingly) for better class name clarity.
This is because in cases people do wildcard import, in which case the name `Engine` itself does not convey enough meaning.

[Serving][Python] Rename Engine to LLMEngine

---

cpp/json_ffi/json_ffi_engine.cc
cpp/llm_chat.cc
cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine.h
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h
cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h
python/mlc_llm/cli/serve.py
python/mlc_llm/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/server/popen_server.py
python/mlc_llm/serve/sync_engine.py
tests/python/json_ffi/test_json_ffi_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine_spec.py

This PR refactors EngineConfig for a cleaner interface of internal Engine constructor in MLC serve. This is a preparation step towards the engine reload/unload which will be introduced in follow-up PRs for JSONFFIEngine functionality on mobile and other platforms.

[Serving] EngineConfig refactor

---

cpp/serve/function_table.cc

The disco `CallPacked` function cannot handle `std::move()` very well. A previous engine refactor PR introduced a regression that broke our tensor parallelism support. This commit fixes the issue.

[Serving][HotFix] No `std::move()` for disco CallPacked

---

docs/deploy/cli.rst
docs/get_started/introduction.rst
docs/get_started/quick_start.rst
docs/prebuilt_models.rst
examples/python/sample_mlc_engine.py

This PR updates the huggingface repo examples to use Llama3.

[Docs] Update example for Llama3

---

README.md

Previous link is now a 404.
- 404: https://llm.mlc.ai/docs/deploy/python.html
- 200: https://llm.mlc.ai/docs/deploy/python_engine.html

Fix broken link to Python API

---

python/mlc_llm/chat_module.py
python/mlc_llm/cli/delivery.py
python/mlc_llm/interface/jit.py
python/mlc_llm/support/auto_device.py
python/mlc_llm/support/download.py

The uses of `subprocess.run` in the codebase did not pass the environment, which may cause some issues in cases.

[Misc] Pass env along when calling `subprocess.run`

---

cpp/serve/engine_actions/batch_verify.cc
tests/python/serve/test_serve_engine_spec.py

- According to https://github.com/mlc-ai/mlc-llm/issues/2167 ， the problem that the output of spec decoding in q0f32 is inconsistent with the single model of q0f32 has been fixed. 
- Modified the test_engine_generate function located in [tests/python/serve/test_serve_engine_spec.py](https://github.com/mlc-ai/mlc-llm/blob/main/tests/python/serve/test_serve_engine_spec.py) to support comparison of the output of a single model and the output of spec decoding
- The accuracy comparison with hugging face is left (because the current version of llama-2-7b of q0f32 cannot be consistent with the output of hugging face model)
- The output of spec decoding for q0f16 cannot be consistent with the output of a single model of q0f16, but this may be due to floating point errors.

Fix the output inconsistent bug of q0f32 spec decoding

---

cpp/json_ffi/json_ffi_engine.cc
cpp/serve/engine.cc
cpp/serve/engine.h
cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h
tests/python/json_ffi/test_json_ffi_engine.py

This PR brings the support of reload (reload the engine with a new model), unload (unload the current running model) and reset (reset the engine to the initial states without unloading) to ThreadedEngine and JSONFFIEngine.
These functions are useful for app bindings for iOS/Android.

[Serving] Support ThreadedEngine Reload/Unload/Reset

---

cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/json_schema_converter.cc
python/mlc_llm/serve/grammar.py
web/emcc/mlc_wasm_runtime.cc

Update `web/emcc/mlc_wasm_runtime.cc` to include the recent grammar schema implementation.
Change `GrammarStateMatcherFromTokenTable()` to take in a list of string rather than unpacking them so that each string is an element. This is to avoid error `RangeError: Maximum call stack size exceeded` in platforms like Javascript, especially with the recent 128000 vocab size of Llama 3.
Made sure `test_grammar_state_matcher_json.py` still passes.

[WASM] Support grammar schema in wasm

---

cpp/json_ffi/json_ffi_engine.cc
cpp/serve/function_table.cc
cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h
cpp/support/utils.h
python/mlc_llm/serve/engine_base.py
tests/python/json_ffi/test_json_ffi_engine.py

This PR introduces the support of loading system libraries. Now in engine reload, when the given library path starts with `"system://"`, we recognize this as a system library and will try to load the the library from the path after the `"system://"` prefix.
This PR also decouples the InitBackgroundEngine of ThreadedEngine into two parts, where the reload is now called explicitly when initializing the engine. This can be also done for the JSONFFIEngine. However, we need to move the construction of streamers in JSONFFIEngine before doing the same thing for JSONFFIEngine. So this is marked as a TODO item.

[Serving] Support loading system library

---

docs/install/mlc_llm.rst
docs/install/tvm.rst
python/mlc_llm/chat_module.py
python/mlc_llm/interface/jit.py
python/mlc_llm/serve/engine_base.py

Previously we do JIT when AOT lib lookup failed.
The error message can become cryptic when JIT also fails, it will show up as cannot find None-vulkan.dll.
This PR changes the behavior to only to lookup when model_lib_path is provided, or only to JIT when it is not. This will leads to cleaner error message overall.

[JIT] Better organize JIT and AOT handling

---

docs/get_started/quick_start.rst

This commit updates the quick start to mention Llama 3 8B instead of Llama 2 7B. The code blocks where already updated in #2169.
Docs changes only, no code changes.
A few notes:
- Do we need to update the VRAM recommendation, considering the model is slightly larger (and goes up to 8K context)?
- Do we need to retest this guide on different devices?
- Is the Android APK up-to-date enough to run Llama 3?
(see also #2194)

[Docs] Update quick start to mention Llama 3 8B

---

cpp/serve/engine.cc
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/sampler/gpu_sampler.cc

This PR updates the draft verification of the normal mode speculative decoding. Prior to this PR, we did not effectively leverage all the draft tokens, and this PR fixes the issue.

[Serving][Spec] Fix normal mode verification for extra draft token

---

README.md
docs/deploy/python_engine.rst
docs/get_started/introduction.rst
docs/get_started/quick_start.rst
examples/python/sample_mlc_engine.py
python/mlc_llm/__init__.py
python/mlc_llm/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/serve/__init__.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/server/server_context.py
python/mlc_llm/serve/sync_engine.py
tests/python/serve/evaluate_engine.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_grammar.py
tests/python/serve/test_serve_engine_image.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

This commit renames the LLMEngine to MLCEngine.

[Python] Rename LLMEngine to MLCEngine

---

python/mlc_llm/interface/compiler_flags.py
python/mlc_llm/support/auto_target.py

In the PR #1976   detect_cuda_arch returned a list of strings, which caused ft_quantization to crash on [call_pure_packed("cutlass.ft_preprocess_weight",](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/quantization/ft_quantization.py#L210). This commit returns a list of integers and adds an assert to check that the string of architecture must contain numbers only.
cc @vinx13 @cyx-6 @tqchen

[Fix] CUDA architecture detection bug fix

---

python/mlc_llm/compiler_pass/pipeline.py
python/mlc_llm/compiler_pass/rewrite_softmax.py
python/mlc_llm/support/max_thread_check.py
tests/python/op/test_two_stage_softmax.py

This PR introduces the compiler pass that rewrites the normal softmax to a two-stage softmax. This is based on our finding that when vocabulary size is large, the normal softmax cannot have high-enough parallelism on GPU. So we partition the workload into two stages for better parallelism and better performance.

[Pass] Support two-stage softmax

---

cpp/json_ffi/json_ffi_engine.cc
cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine.h
cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/sync_engine.py
tests/python/json_ffi/_ffi_api.py
tests/python/json_ffi/test_json_ffi_engine.py

This PR supports creating EngineConfig from a JSON string, which is useful for JSONFFIEngine and its API bindings.
This commit also removes the device from the EngineConfig for better clarity.

[Serving] Creating EngineConfig from JSON

---

cpp/serve/engine.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h

[Serving] Share disco sessions among multiple model function tables

---

docs/install/mlc_llm.rst

This PR adds alias `mlc_llm="python -m mlc_llm"` to allow users instal mlc_llm python package via environment variable
and user can directly use command `mlc_llm` in bash

[DOC] Improve Install via environment variable

---

cpp/serve/grammar/grammar_parser.cc
cpp/serve/grammar/grammar_serializer.cc
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/support/encoding.cc
cpp/support/encoding.h

This PR simplifies the tool function names in encoding.h. The new names are
- PrintAsUTF8
- PrintAsEscaped
- ParseNextUTF8
- ParseUTF8
- ParseNextUTF8OrEscaped
Also make ParseNextUTF8 return the new char pointer instead of the number of chars processed to make the interface simpler.

[Support] Simplify function names in encoding.h

---

cpp/serve/event_trace_recorder.cc

This PR fixes a typo of a variable name in event_trace_recorder which might be confusing. The dumped timestamps are actually in us instead of ms.

[Fix] fix a typo in event_trace_recorder

---

cpp/serve/engine.cc
cpp/tokenizers.cc
cpp/tokenizers.h
python/mlc_llm/interface/gen_config.py

This PR supports the Bytelevel BPE and ByteFallback BPE when post-processing the token table.
This PR changes the behavior of Tokenizer::TokenTable to provide raw tokens from the underlying tokenizer instead of the post-processed ones. Another static method Tokenizer::PostProcessTokenTable is provided to process the token table.
PostProcessTokenTable supports two methods, which are common in most tokenizers, to decode token: byte-fallback BPE (like in LLaMA2), and byte-level BPE (like in LLaMA3 and GPT2). For details see PostProcessTokenTable.
The method of post-processing is automatically detected in `gen_config.py` with name `token_table_postproc_method` and will be provided to the tokenizer in the engine.
cc @tqchen 
cc @CharlieFRuan Plz note this change in tokenizer

[Tokenizer] Support ByteLevel BPE in tokenizer token table

---

cpp/serve/draft_token_workspace_manager.cc
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h
cpp/serve/sampler/gpu_sampler.cc
python/mlc_llm/interface/compile.py
python/mlc_llm/model/eagle/eagle_model.py
python/mlc_llm/model/llama/llama_model.py

This change `BatchPrefill/DecodeToLastHiden` to return on-worker hidden states which can be used as next input. This avoids transfer between worker and engine.
cc @tqchen

[Eagle] Avoid worker - engine transfer for hidden states

---

cpp/serve/sampler/gpu_sampler.cc

[Sampler] Avoid unnecessary sync in GPU verifier

---

cpp/serve/engine.cc
cpp/tokenizers.h

I am seeing errors like this when running `mlc_llm serve`.
```
tvm._ffi.base.TVMError: Traceback (most recent call last):
6: mlc::llm::serve::ThreadedEngineImpl::RunBackgroundLoop()
at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:143
5: mlc::llm::serve::ThreadedEngineImpl::EngineReloadImpl(mlc::llm::serve::EngineConfig)
at /workspace/mlc-llm/cpp/serve/threaded_engine.cc:240
4: mlc::llm::serve::Engine::Create(mlc::llm::serve::EngineConfig, DLDevice, tvm::runtime::Optional<tvm::runtime::PackedFunc>, tvm::runtime::Optional<mlc::llm::serve::EventTraceRecorder>)
at /workspace/mlc-llm/cpp/serve/engine.cc:424
3: mlc::llm::serve::EngineImpl::EngineImpl(mlc::llm::serve::EngineConfig, DLDevice, tvm::runtime::Optional<tvm::runtime::PackedFunc>, …
```

Fix typo in token_postproc_method names

---

cpp/serve/function_table.cc
cpp/serve/sampler/gpu_sampler.cc

[Sampler] Add missing sync in gpu verifier

---

cpp/conv_templates.cc
python/mlc_llm/conversation_template.py

Llama-2 chat template has system prompt directly followed by the user message after `\n\n`
cc @MasterJH5574 @tqchen

[Model] Remove redundant space in llama2 tokenizer

---

python/mlc_llm/serve/engine.py

add some try...except captures.

[Serving] Add some try-except captures in AsyncMLCEngine

---

cpp/serve/engine_actions/eagle_new_request_prefill.cc

This make sure tokens are shifted by one (the first token is dropped, and the last committed token is append) for eagle.
cc @tqchen

[Eagle] Fix token shifting for prefill step

---

cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/sampler/gpu_sampler.cc
python/mlc_llm/compiler_pass/attach_sampler.py
python/mlc_llm/compiler_pass/rewrite_softmax.py
python/mlc_llm/op/top_p_pivot.py

This PR integrates the pivot-based prob renormalization for top-p sampling, whose performance is a few times faster than the current sort-based top-p sampling on CUDA.

[Sampler] Use pivot-based renormalization for top-p sampling

---

cpp/json_ffi/conv_template.cc
cpp/json_ffi/conv_template.h
cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/openai_api_protocol.cc
cpp/json_ffi/openai_api_protocol.h
cpp/metadata/model.cc
cpp/serve/config.cc
cpp/serve/grammar/grammar_parser.cc
cpp/support/json_parser.h

This PR updates the error checking in JSONFFIEngine and related request parsing to use the Result class.

[JSONFFI] Update JSONFFI error checking with the Result class

---

python/mlc_llm/model/baichuan/baichuan_model.py
python/mlc_llm/model/chatglm3/chatglm3_model.py
python/mlc_llm/model/gemma/gemma_model.py
python/mlc_llm/model/gpt2/gpt2_model.py
python/mlc_llm/model/gpt_bigcode/gpt_bigcode_model.py
python/mlc_llm/model/gpt_neox/gpt_neox_model.py
python/mlc_llm/model/internlm/internlm_model.py
python/mlc_llm/model/llama/llama_model.py
python/mlc_llm/model/mistral/mistral_model.py
python/mlc_llm/model/orion/orion_model.py
python/mlc_llm/model/phi/phi_model.py
python/mlc_llm/model/qwen/qwen_model.py
python/mlc_llm/model/qwen2/qwen2_model.py
python/mlc_llm/model/stable_lm/stablelm_model.py

By default the prefill chunk size is set to the context window size or the sliding window size. When the number is large, our memory planning during model compilation will allocate a lot memory.
Given we have support for input chunking, we can reduce the prefill chunk size to a small value to save runtime memory.
This PR sets the prefill chunk size to be at most 2048.

[GenConfig] Set upper bound for prefill chunk size

---

.gitmodules
CMakeLists.txt
cpp/json_ffi/conv_template.cc
cpp/json_ffi/conv_template.h
cpp/json_ffi/image_utils.cc
cpp/json_ffi/image_utils.h
cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/json_ffi_engine.h
python/mlc_llm/model/llava/llava_model.py
python/mlc_llm/serve/data.py
tests/python/json_ffi/test_json_ffi_engine_image.py

This PR adds support for Image input in JSONFFIEngine, so that now LLaVa model can be used. 
The image has to be passed as base64 encoded. See `tests/python/json_ffi/test_json_ffi_engine_image.py` for example usage.
For reading the image in C++, the header-only file `stb_image.h` is being used from the [nothings/stb](https://github.com/nothings/stb/tree/master) repository. This repository has been added as a submodule in `3rdparty/`
The image has to be pre-processed before passing into the LLaVa model (which uses CLIP Vision model). Currently Bilinear interpolation is being used for resizing, instead of [Huggingface CLIPImageProcessor](https://github.com/huggingface/transformers/blob/9fe3f585bb4ea29f209dc705d269fbe292e1128f/src/transformers/models/clip/image_processing_clip.py#L97)'s …

[Serving] Image support in JSONFFIEngine

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action.h

This PR fixes a bug which does not pass the speculative decoding draft length to the draft generation stage.

[Serving][Fix] Pass draft length when constructing draft action

---

python/mlc_llm/compiler_pass/attach_sampler.py

This PR updates the AttachGPUSamplingFunc pass to make each sampling func have independent dynamic vocab size var. So we do not have to read the vocab size from the prefill function.

[Pass] Fix sampling func attachment to not read existing vocab size

---

python/mlc_llm/help.py
python/mlc_llm/serve/server/popen_server.py

The current 60-second timeout in PopenServer is insufficient for the small_draft speculative mode on an 8-GPU setup.
cc: @tqchen @vinx13

Increase the timeout in PopenServer

---

cpp/llm_chat.cc

1. Avoid the cpu softmax for different penality config by having copy sync to gpu and use gpu softmax.
2. Disable decode token time counter for first token.
It improved 10 to15% for decode performance for few llm models (Qwen model uplifted from 10.8 tok/sec - > 11.8 tok/sec)

[LLM-CHAT] Enable gpu softmax for penality softmax

---

python/mlc_llm/embeddings/embeddings.py
python/mlc_llm/model/bert/bert_loader.py
python/mlc_llm/model/bert/bert_model.py
python/mlc_llm/model/bert/bert_quantization.py
python/mlc_llm/model/gpt2/gpt2_model.py
python/mlc_llm/model/model.py
python/mlc_llm/model/model_preset.py
python/mlc_llm/op/attention.py

This PR supports text embedding in MLC-LLM with a BERT encoder-only model.
Example usage: https://github.com/rickzx/mlc-llm/blob/18aa7ee378b826a61ce4baa98e4bab1bf3d64038/python/mlc_llm/embeddings/embeddings.ipynb

[SLM] Support BERT architecture. Implement a text embedding module

---

cpp/serve/model.cc

[Serving] Log batch size in NVTX

---

android/mlc4j/prepare_libs.py

This PR adds the `-j` option to cmake build to parallelize the build job over CPU cores.

[Android] Add `-j` option to cmake build

---

cpp/json_ffi/conv_template.cc
cpp/json_ffi/conv_template.h
cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/openai_api_protocol.cc
cpp/json_ffi/openai_api_protocol.h
ios/MLCEngineExample/MLCEngineExample/MLCEngineExampleApp.swift
ios/MLCSwift/Sources/Swift/LLMEngine.swift
ios/MLCSwift/Sources/Swift/OpenAIProtocol.swift
tests/python/json_ffi/test_json_ffi_engine.py

This PR refactors JSONFFI conv template to use immutable processing. This helps to prevent bugs from multiple requests and concurrent access to the conversation data structure.
It also reduces the need to deep copy the struct.
MISC refactor: allows multiple system prompt processing, allow passing in content as string

[REFACTOR] Refactor JSONFFI Conv template

---

cpp/serve/engine_state.cc
cpp/serve/threaded_engine.cc
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/entrypoints/debug_entrypoints.py

Expose the Reset in engine to debug_entrypoints, will use it (instead of re-deploying) to help measure the acceptance rate.
cc: @vinx13 @tqchen

[Serving] Add reset_engine in debug_entrypoints

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h
cpp/serve/engine_actions/batch_prefill_base.cc
cpp/serve/model.cc
cpp/serve/model.h
cpp/serve/request_state.cc
cpp/serve/request_state.h
python/mlc_llm/serve/config.py

Mistral now works on `Engine` serving:
```
mlc-llm-head % python -m mlc_llm serve HF://mlc-ai/OpenHermes-2.5-Mistral-7B-q4f16_1-MLC
```
```
import requests
payload = {
"model": "HF://mlc-ai/OpenHermes-2.5-Mistral-7B-q4f16_1-MLC",
"messages": [
{"role": "user", "content": "Write a haiku about apples."},
],
"stream": False
}
r = requests.post("http://127.0.0.1:8000/v1/chat/completions", json=payload)
choices = r.json()["choices"]
for choice in choices:
print(f"{choice['message']['content']}\n")
```
Output:
```
Crimson fruit, ripe and sweet,
Nature's bounty, a treasure trove,
Graceful in their fall.
```

[Bugfix] Make sequence_length dtype int64 in EngineConfig. Fix Mistral engine serving issue

---

cpp/serve/engine_actions/action_commons.h
cpp/serve/engine_actions/batch_prefill_base.cc

This PR fixes a bug of prefill chunking in the interactive mode. The bug counts requests with remaining inputs as running requests which turns out disabling the prefill of the remaining inputs.
This PR fixes by no longer counting requests with unfinished inputs as running requests for decode.

[Fix][Serving] Fix prefill chunk in interactive mode

---

python/mlc_llm/json_ffi/engine.py
python/mlc_llm/serve/engine_base.py

This PR fixes the self ref in engine and enable auto terminate in deleter.

[Engine] Fix the self-ref in engine

---

cpp/serve/engine_actions/action_commons.cc
cpp/serve/grammar/grammar_state_matcher_preproc.h
cpp/serve/grammar/grammar_state_matcher_state.h
cpp/serve/grammar/json_schema_converter.cc
cpp/serve/request_state.h
cpp/serve/sampler/cpu_sampler.cc

This PR updates the occurences of `.size() - 1` with static_cast to avoid the integer underflow.

[Fix] Use static_cast for `.size()` for safety

---

tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_grammar.py
tests/python/serve/test_serve_engine_prefix_cache.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

This PR updates the test files to use JIT by default as much as possible, in order to make tests runnable out of the box.
Of course, they can be locally tweaked to use local models.
For Eagle/Llava/rwkv, given we don't have them delivered yet, they are kept as using local model lib now.

[Test] Use HF model for JIT as much as possible

---

cpp/serve/engine_state.cc
cpp/serve/engine_state.h
cpp/serve/prefix_cache.cc
cpp/serve/prefix_cache.h

This PR refactors the reset logic in prefix cache and disable forking from sequences with sliding windows enabled.

[Fix] Fix prefix cache reset and forking logic

---

python/mlc_llm/support/constants.py
python/mlc_llm/testing/__init__.py
python/mlc_llm/testing/pytest_utils.py
tests/python/json_ffi/test_json_ffi_engine.py
tests/python/json_ffi/test_json_ffi_engine_image.py

This PR introduce a new env var MLC_TEST_MODEL_PATH to allow a list of model path specified for test model search purposes.
If not found, an error message would appear and we auto skip test in both pytest and normal running settings.
The path defaults to the cached HF path so as long as we run mlc_llm chat the model can be found. But we do not automatically download to avoid excessive networking in CI settings.
Followup PR needed for remaining testcases

[TESTING] Introduce testing util to manage models

---

CMakeLists.txt
android/mlc4j/CMakeLists.txt
android/mlc4j/prepare_libs.py
ci/task/test_model_compile.sh
cmake/gen_cmake_config.py
docs/compilation/package_libraries_and_weights.rst
docs/deploy/android.rst
docs/deploy/ios.rst
docs/install/emcc.rst
docs/install/mlc_llm.rst
ios/prepare_libs.sh
python/mlc_llm/cli/package.py
python/mlc_llm/support/auto_target.py
rust/README.md
web/Makefile
web/prep_emcc_deps.sh

This PR updates to use MLC_LLM_SOURCE_DIR to specify the directory of mlc llm source directory.
The reason for this update is that the term XXX_HOME was usually meant to be used in different scenarios in ML frameworks.
For example, both torch and huggingface have TORCH_HOME and HF_HOME pointing to their local cache directory.
The variable MLC_LLM_SOURCE_DIR is aligned with cmake naming convention (CMAKE_SOURCE_DIR).
Also updated TVM_HOME to TVM_SOURCE_DIR
We will have followup PR to udpate MLC_CACHE_DIR to MLC_LLM_HOME, following the existing practices.

[REFACTOR][Rename]  MLC_LLM_SOURCE_DIR and TVM_SOURCE_DIR source directory env 

---

python/mlc_llm/interface/jit.py
python/mlc_llm/support/constants.py
python/mlc_llm/support/download.py
rust/README.md
rust/build.rs

This PR changes the MLC_CACHE_DIR env to MLC_LLM_HOME. This change aligns with most of the packages.

[REFACTOR][ENV] MLC_CACHE_DIR to MLC_LLM_HOME

---

cpp/serve/config.cc
cpp/serve/prefix_cache.cc

This PR fixes issues with prefix cache when used together with MLCEngine. It also fixes an issue when prefix_cache_max_num_recycling_seqs == 0

[PREFIX-CACHE] Fix some issues with prefix cache

---

cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/metrics.cc
cpp/serve/metrics.h
python/mlc_llm/interface/chat.py
tests/python/serve/test_serve_engine_prefix_cache.py
tests/python/serve/test_serve_engine_spec.py

This PR run another round of cleanup of metrics.
- Remove less useful ones
- Reorganize by labels in prometheus style

[REFACTOR] Cleanup Metrics

---

cpp/serve/metrics.cc

This commit fixes a bug when serializing SpecDecodeMetrics.

[Fix] Fix the serialization of SpecDecodeMetrics

---

cpp/serve/config.cc
docs/deploy/rest.rst
docs/install/emcc.rst
python/mlc_llm/cli/serve.py
python/mlc_llm/interface/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/server/popen_server.py
python/mlc_llm/serve/sync_engine.py
tests/python/serve/evaluate_engine.py
tests/python/serve/server/conftest.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_async_engine_spec.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_image.py
tests/python/serve/test_serve_engine_prefix_cache.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

This PR lifts the EngineConfig as one engine constructor, so that we can hide most less important arguments in EngineConfig, and thus focus the user attention to the few key arguments.
`mlc_llm serve` CLI and PopenServer are updated accordingly. Documentation is updated accordingly.

[Refactor] Expose EngineConfig in engine constructor

---

python/mlc_llm/serve/radix_tree.py

Seems function descriptions for `PagedRadixTree.add` and `PagedRadixTree.extend` are misleading.
Fixed according to implementations in radix_tree.cc

[FIX] fix comments in radix_tree.py

---

cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/metrics.h
cpp/serve/prefix_cache.cc
cpp/serve/prefix_cache.h
tests/python/serve/test_serve_engine_prefix_cache.py
tests/python/serve/test_serve_engine_spec.py

* This PR fixes the metric names referenced in tests which were not updated together with previous PRs.
* This PR fixes the static PrefixCacheMode member introduced in #2397. The way of fix using the static class members is not correct, which essentially disables PrefixCache forever. This is because when checking the `mode` member of a PrefixCache instance, it is always the base class mode (which is `kDisabled`) being returned.
* This PR also adds a missing header for chrono.

[Fix] Fix metric names in tests and static PrefixCacheModes

---

cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/json_ffi_engine.h
cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/request.cc
cpp/serve/request_state.cc
cpp/serve/threaded_engine.cc
cpp/serve/threaded_engine.h
docs/deploy/rest.rst
python/mlc_llm/cli/serve.py
python/mlc_llm/interface/serve.py
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/protocol/debug_protocol.py
python/mlc_llm/protocol/openai_api_protocol.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py
python/mlc_llm/serve/request.py
python/mlc_llm/serve/server/server_context.py
python/mlc_llm/serve/sync_engine.py
tests/python/json_ffi/test_json_ffi_engine.py
tests/python/serve/test_serve_sync_engine.py

This PR reorganizes GenerationConfig, DebugConfig and FFI.
- Internally, we now directly use the config object instead of json stream.
- Request construction turns into engine side so it can make use of debug_config.
- Ignore eos now moves to debug_config option.
- Removes most string based re-export of gen conifg.

[REFACTOR] Reorganize GenerationConfig DebugConfig and FFI

---

cpp/serve/engine_actions/batch_prefill_base.cc

This PR fixes an issue that causes vector index out of bound. This happens in speculative decoding, when an model can accept inputs while the other cannot.
We still need to look into this inconsistency. Ideally all models should behave the same.

[Fix] Fix vector OOB when no inputs can be prefilled in spec decode

---

cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/openai_api_protocol.cc
python/mlc_llm/interface/chat.py

This PR supports chat CLI with arguments override.
Right now, arguments supported are: `top_p`, `temperature`, `presence_penalty`, `frequency_penalty`, `max_tokens`, `seed`, `stop`.
This PR adds the corresponding support to the ChatCompletion request parsing for JSONFFIEngine.

[Chat] Support chat completion config override

---

python/mlc_llm/serve/engine.py
python/mlc_llm/support/constants.py
python/mlc_llm/testing/pytest_utils.py
tests/python/serve/test_serve_async_engine.py
tests/python/serve/test_serve_engine.py
tests/python/serve/test_serve_engine_grammar.py
tests/python/serve/test_serve_engine_prefix_cache.py
tests/python/serve/test_serve_engine_rnn.py
tests/python/serve/test_serve_engine_spec.py
tests/python/serve/test_serve_sync_engine.py

This PR updates tests to use the `require_test_model` testing util for better out-of-box testing while avoid automatic downloading.
Some tests that require manually model compilation are kept in the old test style (e.g., with model "llava", "eagle", etc.).
This PR also fixes some typing issues suggested by mypy.

[Test][Refactor] Update tests to use require_test_model

---

python/mlc_llm/chat_module.py
python/mlc_llm/support/auto_config.py
python/mlc_llm/support/constants.py
python/mlc_llm/support/download.py

This PR introduces support for MLC_DOWNLOAD_POLICY and MLC_LLM_READONLY_WEIGHT_CACHES
Allows reading from readonly cache besides MLC_LLM_HOME. Also introduces a domain subfolder in cached weights

[DOWNLOAD] MLC_DOWNLOAD_POLICY and MLC_LLM_READONLY_WEIGHT_CACHES

---

cpp/serve/data.cc
cpp/serve/engine.cc
cpp/serve/grammar/grammar_state_matcher.cc
cpp/serve/grammar/grammar_state_matcher.h
cpp/serve/grammar/grammar_state_matcher_base.h
cpp/streamer.cc
cpp/tokenizers.cc
cpp/tokenizers.h
python/mlc_llm/interface/gen_config.py
python/mlc_llm/serve/grammar.py
python/mlc_llm/tokenizer.py
tests/python/serve/test_grammar_state_matcher_json.py

This PR adds a new `TokenizerInfo` class that contains useful information about the tokenizer during generation. It is auto-detected from tokenizer.json if it exists. Otherwise it raises a warning and uses the default value (byte fallback tokenizer, not prepend/strip space).

[Tokenizer] Auto-detect TokenizerInfo from tokenizer.json

---

android/MLCEngineExample/mlc-package-config.json
python/mlc_llm/chat_module.py
python/mlc_llm/cli/delivery.py
python/mlc_llm/contrib/embeddings/embeddings.py
python/mlc_llm/interface/gen_config.py
python/mlc_llm/interface/jit.py
python/mlc_llm/interface/package.py
python/mlc_llm/op/position_embedding.py
python/mlc_llm/protocol/__init__.py
python/mlc_llm/protocol/error_protocol.py
python/mlc_llm/protocol/mlc_chat_config.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/support/constants.py
python/mlc_llm/support/download.py
python/mlc_llm/testing/debug_chat.py

This PR removes the all dependencies from chat_module.py So we can prepare for deprecating this module.
This PR refactors and moves MLCChatConfig to protocol. This helps us to consolidate all API spec and config files under the protocol folder.
The protocol folder mainly keeps the data schema and metadata, most of the actions(gen_config) are still kept in their current location.

[REFACTOR] Remove dependencies on legacy chat_module

---

android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatView.kt
android/mlc4j/src/main/java/ai/mlc/mlcllm/JSONFFIEngine.java
android/mlc4j/src/main/java/ai/mlc/mlcllm/MLCEngine.kt
android/mlc4j/src/main/java/ai/mlc/mlcllm/OpenAIProtocol.kt
cpp/serve/config.cc

This PR switchs MLC Chat to use MLC Engine in Android app
cc @Kartik14 @tqchen

[Android] Switch MLC Chat to use MLCEngine

---

cpp/tokenizers.cc
python/mlc_llm/protocol/mlc_chat_config.py
web/emcc/mlc_wasm_runtime.cc

This PR updates MLC's wasm runtime to catch up with the latest changes to grammar:
- https://github.com/mlc-ai/mlc-llm/pull/2248
- https://github.com/mlc-ai/mlc-llm/pull/2335
- https://github.com/mlc-ai/mlc-llm/pull/2416
We mainly expose `PostProcessTokenTable()` and `PostProcessToken()` as global func, and compile all the necessary code needed in `cpp/tokenizers.cc` while skipping others with `COMPILE_MLC_WASM_RUNTIME` to avoid dependency to `tokenizers-cpp`.
The only change needed from WebLLM in runtime is to call `PostProcessTokenTable()` with the correct post processing method before creating `GrammarStateMatcher` from token table.
Verified with Llama-2 and Llama-3 grammar (w/ and w/o schema) in WebLLM.
Also fix `eos_token_id` type to avoid pydantic error; Phi-3 has 3 eos token ids as …

[Grammar][Wasm] Update new grammar to wasm runtime

---

python/mlc_llm/nn/kv_cache.py
python/mlc_llm/op/position_embedding.py

This PR updates the RoPE calculation to use float32 for multiplication and addition. This is motivated by the observation that calculating RoPE in float16 may cause accuracy issue.

[Model] Use float32 for RoPE calculation

---

cpp/serve/logit_processor.cc
python/mlc_llm/compiler_pass/attach_logit_processor.py

This PR updates the mask values in LogitProcessor to the min value of float32. Prior to this PR it was -1e10. This update is the safest for softmax as long as the masking is always the last step in logit processor.

[LogitProcessor] Use min float value as the mask value

---

python/mlc_llm/conversation_template.py
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/protocol/error_protocol.py
python/mlc_llm/protocol/openai_api_protocol.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py
python/mlc_llm/serve/sync_engine.py

This PR sets the parameter `by_alias=True` for all the `model_dump_json` of pydantic classes, so that aliases are always respected.

[Protocol] Use `by_alias=True` when dumping pydantic classes

---

python/mlc_llm/conversation_template.py

Add `</s>`, token 2, as stop token for phi3. Motivated by grammar.
Though `</s>` is not described as the stop token anywhere in the official phi-3 HF repo, when we do not mask `</s>` at the end of a json generation, it is possible to be generated as shown in the screenshot.
This is because the following lines accept `</s>` as a stop token in grammar state matcher regardless whether `</s>` is registered as the stop token in MLC:
https://github.com/mlc-ai/mlc-llm/blob/d1f5f51afcdba14399ed5df4b64bf0eeed0d9d8e/cpp/serve/grammar/grammar_state_matcher_preproc.h#L316-L318
While we could modify the lines above to only add stop tokens that are registered in `mlc-chat-config.json`, adding `</s>` into phi-3's stop tokens may be an easier way for now.
Motivating error:

[Fix][Phi3] Add `</s>` as stop token for phi3

---

python/mlc_llm/conversation_template.py
python/mlc_llm/interface/gen_config.py

Add conversation template for Hermes 2 Pro Llama 3: https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B
The template is exactly the same as `open_hermes_mistral`, except for the stop token ids (due to it being llama3 based).
Converted weights are now on HF. Verified both regular chatting, and function calling with grammar.

[Hermes2] Add conv template for Hermes2-Pro-Llama3

---

cpp/metadata/model.cc
cpp/metadata/model.h
cpp/serve/config.cc
python/mlc_llm/interface/compile.py
python/mlc_llm/model/qwen2/qwen2_model.py

This PR adds the max_batch_size at compile time to metadata for runtime to read.
**Note.** This may be a breaking change for the compiled model libraries. And please set environment variable `MLC_JIT_POLICY=REDO` to recompile the models with JIT, or manually recompile the model libraries.
This PR also adds the max_batch_size to qwen2.

[Compile] Add max_batch_size to metadata

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc
cpp/serve/engine_actions/eagle_batch_draft.cc

This PR adds ICHECK to make sure that the running batch size in BatchDecode and BatchDraft does not exceed the `max_num_sequence` as in the engine config.
The prefill actions should keep this invariant. And the ICHECKs added mainly serve for internal error detection and report purpose.

[Serving] Add ICHECK for running batch size

---

cpp/serve/logit_processor.cc
cpp/serve/model.cc
cpp/serve/sampler/gpu_sampler.cc

This PR updates the host memory in model, logit processor and GPUSampler that for CUDA and ROCm the pinned memory will be used for the host arrays, which may be faster than the default CPU memory during copying.

[Serving] Use preferred host memory for host NDArrays

---

python/mlc_llm/interface/compiler_flags.py

This makes cuda graph default ON at O2 since it is generally helpful.

[CUDA] Turn on cuda graph at O2

---

cpp/json_ffi/json_ffi_engine.cc
cpp/serve/engine.cc
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/serve/engine_base.py
tests/python/json_ffi/test_json_ffi_engine_mock.py
tests/python/serve/test_serve_engine_mock.py

This PR introduces a MockEchoEngine that echos the inputs prompt and the generation conflig(as part of usage.extra).
The engine can be used to create unit-test cases that covers engine API handling. Note that mock tests cannot replace real engine tests.

[TEST] MockEchoEngine

---

cpp/json_ffi/image_utils.cc

A recent bump in dmlc has changed the `Write` signature of `dmlc::Stream`. This commit updates the codebase to follow the upstream change.

[Fix] Fix JSONFFI MemoryBufferStream after dmlc bump

---

cpp/json_ffi/json_ffi_engine.cc
cpp/json_ffi/json_ffi_engine.h
cpp/json_ffi/openai_api_protocol.cc
cpp/json_ffi/openai_api_protocol.h
cpp/serve/config.cc
cpp/serve/config.h
ios/MLCEngineExample/MLCEngineExample/MLCEngineExampleApp.swift
ios/MLCSwift/Sources/Swift/LLMEngine.swift
tests/python/json_ffi/test_json_ffi_engine_mock.py

This PR enables n generation and pass in json schema in JSON FFI.

[JSON-FFI] Enable n generation and pass in json schema

---

python/mlc_llm/cli/delivery.py

Example usage:
```
python -m mlc_llm.cli.delivery --username mlc_ai --token <HF_TOKEN> --spec <Path to model-delivery-config.json> --log <Path to model-delivered-log.json> --output <Converted output dir> --hf-local-dir <HF local cache>
```

Refactor model delivery script to use pydantic

---

python/mlc_llm/bench/__init__.py
python/mlc_llm/bench/metrics.py
python/mlc_llm/bench/prompts.py
python/mlc_llm/bench/replay.py
python/mlc_llm/bench/request.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py

This PR:
- Adds a util to replay requests, we can replay the generated/saved request events with it.
- Adds prompts generator for benchmarking.
- Implements OpenAIRequestSender to help handle the request to deployed endpoint.
- Calculates some perf statistics like ttft, decode token latency.
cc: @tqchen

[Bench] Add mlc bench

---

cpp/serve/draft_token_workspace_manager.cc
cpp/serve/draft_token_workspace_manager.h
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/model.cc

Enable n-sampling for Medusa spec decoding

---

docs/deploy/mlc_chat_config.rst
python/mlc_llm/protocol/mlc_chat_config.py

This PR removes legacy mean_gen_len from the config

[CONFIG] Remove mean_gen_len from the config

---

cpp/serve/config.cc
tests/python/serve/server/conftest.py

This PR fixes an issue which causes the int64 multiplication overflow when sliding window is enabled.

[Fix][Config] Max total sequence length overflow with sliding window

---

cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h
python/mlc_llm/nn/kv_cache.py
python/mlc_llm/op/tree_attn.py
tests/python/op/test_tree_attn.py

This PR integrates the recent support of tree-attention in PagedKVCache into the speculative decoding in MLC. Right now only chains are supported. Tree-based speculative decoding is on the project road map and we are planning to support it in recent future.

[Serving] PagedKVCache tree-attention integration

---

cpp/tokenizers/tokenizers.cc

This PR fixes the global func name for `TokenizerDecode`, which was not updated when adding the namespace `tokenizers`.

[Fix] Fix the global func name of TokenizerDecode

---

python/mlc_llm/interface/calibrate.py
python/mlc_llm/op/moe_matmul.py
python/mlc_llm/quantization/fp8_quantization.py
python/mlc_llm/quantization/per_tensor_quantization.py

This changes FP8 quantization to use f32 scale. It allows offloading to the matmul scaling pattern in cublas.
cc @tqchen

[FP8] Use f32 scale to enable better fusion

---

cpp/serve/data.cc
cpp/serve/data.h
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc
cpp/serve/engine_actions/batch_prefill_base.cc
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/request_state.cc
cpp/serve/sampler/cpu_sampler.cc
cpp/serve/sampler/gpu_sampler.cc
python/mlc_llm/support/constants.py

Currently we use `sampled_token_id.first` to find the sampled token id of a SampleResult object, which is obscure. This PR provides a `GetTokenId` API for SampleResult to get the sampled token id.
This PR also updates the testing model path to include `./dist/`.

[Fix] Provide a GetTokenId API for SampleResult

---

cpp/serve/metrics.h
ios/MLCSwift/Sources/Swift/LLMEngine.swift

This PR fixes an issue of the per-request metrics, where division-by-0 may happen when the request does not run any decode step.
The division-by-0 results in `inf`, and is added into a JSON file. However, `inf` is usually not recognized as a float value in JSON grammar. Thus JSON parsers fail on parsing any JSON string that comes with `inf` wihtout being quoted.

[Fix] Fix metrics division by 0

---

android/MLCChat/mlc-package-config.json
docs/deploy/android.rst

This PR updates the order of mode list for Android App and the APK link in the document.
1. Phi-3-mini-4k-instruct-q4f16_1-MLC
2. Qwen1.5-1.8B-Chat-q4f16_1-MLC (new)
3. gemma-2b-q4f16_1-MLC
4. Llama-3-8B-Instruct-q3f16_1-MLC
5. Mistral-7B-Instruct-v0.3-q4f16_1-MLC
cc @tqchen

[Android] Updates the order of mode list and the APK link in the document

---

cpp/serve/sampler/cpu_sampler.cc

This PR adds a shortcut in the top-p renormalization in CPU sampler, which skips the renormalization when top-p is 1.0.

[Sampler] Skip top-p renormalization if top-p is 1 in CPUSampler

---

docs/deploy/webllm.rst
docs/index.rst
docs/requirements.txt

This PR renames https://llm.mlc.ai/docs/deploy/javascript.html to https://llm.mlc.ai/docs/deploy/webllm.html.
Rename `WebLLM and JavaScript API` to `WebLLM Javascript SDK`.
Also update `docs/requirements.txt` to be more complete.

[Docs] Rename javascript.rst to webllm.rst

---

python/mlc_llm/conversation_template/__init__.py
python/mlc_llm/conversation_template/tinyllama.py
python/mlc_llm/interface/gen_config.py

TinyLlama v1.0 does not use chatml anymore, unlike v0.4. This PR adds the conv template following https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0/blob/main/tokenizer_config.json

[Conv] Add tinyLlama v1.0 conv template

---

cpp/tokenizers/tokenizers.cc

Previously the tokenizer would segfault when analyzing a tokenizer that did not have a tokenizer.json file. This is due to `TokenizerInfo()` is called previously, which creates a null object. This PR fixes this problem.

[Tokenizer][Fix] Fix SegFault when analyzing tokenizers without tokenizer.json

---

python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py

This PR applies the stop strings and stop token ids defined in conversation tempalte to the raw text completions. So that whenever the model outputs a stop token id or stop string, the raw generation can stop.
Prior to this commit, the raw text never stops when the max tokens is not given. This commit helps reduce the frequency of such events. Nevertheless, if the model does not output a stop string/token id, the generation will still not be going to stop.

[Serving] Use stop strs and token ids for completions

---

cpp/serve/engine.cc
cpp/serve/function_table.cc
cpp/serve/function_table.h
cpp/serve/model.cc
cpp/serve/model.h
docs/deploy/cli.rst
docs/deploy/python_engine.rst
docs/deploy/rest.rst
docs/get_started/introduction.rst
python/mlc_llm/cli/calibrate.py
python/mlc_llm/cli/chat.py
python/mlc_llm/cli/serve.py
python/mlc_llm/interface/chat.py
python/mlc_llm/interface/compiler_flags.py
python/mlc_llm/interface/help.py
python/mlc_llm/interface/jit.py
python/mlc_llm/interface/serve.py
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/sync_engine.py

This PR supports the command line overrides for model JIT compilation. This is especially helpful for enabling tensor parallelism out of box, so people don't need to manually tweak `mlc-chat-config.json` to use tensor parallelism.

[Serving] Support tensor parallel shards override in command line

---

android/mlc4j/prepare_libs.py

This commit escapes the backslashes and quotation marks in Android package build.

[Android] Escape backslashes and quotation marks

---

docs/deploy/cli.rst
docs/deploy/python_engine.rst
docs/get_started/introduction.rst
python/mlc_llm/cli/calibrate.py
python/mlc_llm/cli/chat.py
python/mlc_llm/cli/compile.py
python/mlc_llm/cli/serve.py
python/mlc_llm/interface/chat.py
python/mlc_llm/interface/help.py
python/mlc_llm/interface/serve.py
python/mlc_llm/json_ffi/engine.py
python/mlc_llm/serve/config.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/sync_engine.py

This PR introduces override options to the Python side EngineConfig so that they'll be reflected in JIT model compilation.

[EngineConfig] Add override options

---

docs/deploy/cli.rst

This PR fixes a typo in the documentation.

[Docs] Fix typo in mlc_llm chat command

---

cpp/tokenizers/tokenizers.cc

This PR updates the tokenzier load logic, so that we prioritize the use of HuggingFace and SentencePiece tokenizers over the ByteLevelBPE tokenizer.
This fixes the issue that token `<im_start>` in Qwen model is tokenized into multiple tokens when the ByteLevelBPE tokenizer is chosen when available.

[Tokenizer] Priorize HuggingFace/SentencePiece over ByteLevelBPE

---

python/mlc_llm/model/qwen2_moe/qwen2_moe_model.py

This PR introduces the multi-GPU support for the Qwen-MoE model. Validated on 4090x2.

[Model] Support Multi-GPU for Qwen-MoE model

---

cpp/serve/metrics.cc

This PR adds the missing fields that were not cleared up in `EngineMetrics::Reset`.

[Metrics] Add missing fields in `Reset`

---

docs/deploy/webllm.rst
docs/install/emcc.rst

Update documentation for WebLLM. Currently we only provide a high-level view for WebLLM runtime here, and refer user to the WebLLM repo README for more. The documentation focuses on adding their own model variant / model library for WebLLM. Will follow up with more thorough runtime documentation.

[Doc] Update WebLLM doc

---

python/mlc_llm/model/gemma/gemma_model.py

This PR updates the Gemma config so that MLC can work properly with Gemma 1.1.

[Model] Gemma 1.1 compatibility

---

cpp/serve/engine_actions/batch_prefill_base.cc
tests/python/serve/test_serve_sync_engine.py

This PR adds the support for the hybrid prefill. So during the prefill engine action, it will do the decode for running requests as well.
cc: @tqchen @vinx13 @MasterJH5574

[Serving] Hybrid prefill

---

docs/get_started/quick_start.rst

Fix broken links for convert weights and compile model pages in the Quick Start page

Update quick_start.rst to fix broken links

---

cpp/serve/engine_actions/batch_prefill_base.cc

This PR fixes a bug which fails to set the prefill finish time and results in metric error.

[Fix] Set the missed prefill finish time

---

cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc

This PR updates the prefix cache to align the logic of enabling sliding window. Now only leaf sequence is enabled sliding window attention.
cc: @tqchen @MasterJH5574

[Fix] Prefix cache only enables sliding window on leaf sequence

---

android/mlc4j/CMakeLists.txt
android/mlc4j/src/cpp/tvm_runtime.h

This PR updates the include directories for the Android app so that we can avoid using macros for src file include.

[Android] Update include path for tvm runtime src

---

cpp/serve/engine_actions/batch_prefill_base.cc
cpp/serve/engine_actions/batch_prefill_base.h
cpp/serve/engine_actions/new_request_prefill.cc

This PR fixes an issue that may cause duplicate prefix updates for the decode requests in the hybrid prefill action.

[Fix] Mark the decode requests in hybrid prefill

---

python/mlc_llm/nn/kv_cache.py

The current single-page copy kernel misses a predicate, which may cause incorrect attention results in serving, when RemoveRequest is involved.

[Fix] Fix KV cache single-page copy kernel

---

cpp/grammar/grammar_state_matcher.cc
cpp/tokenizers/tokenizers.h
python/mlc_llm/grammar/grammar.py
python/mlc_llm/interface/gen_config.py

This PR addresses an issue with Grammar for models like `Phi-3` and `Qwen2`, where `vocab_size` read from `config.json` can be larger than `tokenizer->GetVocabSize()`. For instance, `Phi-3` has 32064 according to its `config.json`, but its `tokenizer.json` only has information up to `32010` (making `GetVocabSize()` 32011). See [this thread](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/discussions/47) for why it may be the case. In such cases, since our Grammar uses `tokenizer->GetVocabSize()` throughout, we do not mask out the dummy tokens (32011-32063), hence potentially sampling them and accepting them, leading to error like the following
```
[FATAL] mlc-llm/cpp/grammar/grammar_state_matcher.cc:202: Check failed: (token_id >= 0 && token_id < init_ctx_->vocab_size) is false: …
```

[Fix][Bitmask] Mask dummy padded tokens for grammar

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc
cpp/serve/engine_actions/batch_jumpforward.cc
cpp/serve/engine_actions/batch_prefill_base.cc
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_actions/new_request_prefill.cc
cpp/serve/engine_state.cc
cpp/serve/engine_state.h
cpp/serve/request_state.h

This PR updates GetRunningRequestStateEntries to make it lazy. We use a dirty flag to check whether the running request state entries are changed since the last recompute.
We make this improvement due to the observation that this function may cause some CPU overhead. During consecutive rounds of batch decode, the running requests don't change, so we can effectively use this dirty flag to avoid recomputation.

[Engine] Lazy recompute in GetRunningRequestStateEntries

---

cpp/serve/engine_actions/eagle_new_request_prefill.cc

This PR fixes the prefix cache bug with eagle mode on. The prefilled offset is forgotten to be shifted in this case.
cc: @vinx13

[Fix] Fix prefix cache reuse with eagle mode

---

cpp/serve/engine_actions/batch_prefill_base.cc

This PR defers the collection of decode inputs in hybrid prefill, as the collection of decode inputs may cause much CPU overhead while it ends up no prefill can be performed. By deferring the collection of decode inputs, we can quickly decide whether prefill is doable, and this decision does not involve too much CPU overhead.

[Engine] Defer the collection of decode inputs in prefill

---

python/mlc_llm/model/mistral/mistral_model.py

It looks like the new model uses a smaller rope dimension based on head_dim, so the assertion doesn't hold any more. However, the underlying kernels already use head_dim as the rope dimension so removing the assert fixes the conversion, which seems to work.
The tekken tokenzier seems to be just tiktoken, and it seems to work fine with the byte level encoder. I did notice some issues with displaying emojis in the chat but not sure if that's related to the tokenizer.

support mistral-nemo

---

python/mlc_llm/conversation_template/phi.py
python/mlc_llm/interface/gen_config.py
python/mlc_llm/model/llava/llava_model.py
python/mlc_llm/model/model.py
python/mlc_llm/model/phi3/phi3_loader.py
python/mlc_llm/model/phi3v/phi3v_image.py
python/mlc_llm/model/phi3v/phi3v_loader.py
python/mlc_llm/model/phi3v/phi3v_model.py
python/mlc_llm/model/phi3v/phi3v_quantization.py
python/mlc_llm/model/vision/__init__.py
python/mlc_llm/model/vision/clip_vision.py
python/mlc_llm/serve/data.py

This PR adds support for Phi3-vision. Use the HF weights and config from https://huggingface.co/microsoft/Phi-3-vision-128k-instruct
Example:
```
import json
from mlc_llm.serve import data
from mlc_llm.serve.sync_engine import EngineConfig, SyncMLCEngine
from mlc_llm.protocol.generation_config import GenerationConfig
def get_test_image(config) -> data.ImageData:
url = "https://www.ilankelman.org/stopsigns/australia.jpg"
return data.ImageData.phi3v_from_url(url, config)
if __name__ == "__main__":
model = "HF://mengshyu/Phi-3-vision-128k-instruct-q4f16_1-MLC"
engine = SyncMLCEngine(
model=model,
mode="server",
engine_config=EngineConfig(max_total_sequence_length=4096),
)
max_tokens = 256
with open("./dist/Phi-3-vision-128k-instruct-q4f16_1-MLC/mlc-chat-config.json", "r", encoding="utf-8") …
```

[SLM] Introduce microsoft/Phi-3 vision

---

python/mlc_llm/op/moe_misc.py

If `x` has `nan` or `-inf` values, the condition `x[vi,vk] > local_top_k[0]` may be false.  Falling back to the condition `x[vi,vk] > local_top_k[1]` then reads the uninitialized value in `local_top_k[1]`.
This can also result in out-of-bounds memory access.  If all values in `x[vi,vk]` are `nan` or `-inf` along some row `vi`, then `local_top_k_index[1]` is never populated.  For mixture-of-experts models, when `gating_softmax_topk` is used to select the expert, this uninitialized value is then used as an array index.
This commit updates the `top2_softmax_norm_func` implementation in `gating_softmax_topk` to initialize both elements of the `local_top_k` and `local_top_k_index` arrays, matching the implementation of `top4_softmax_norm_func`.

Initialize all `local_top_k` values in `gating_softmax_topk`

---

cpp/serve/model.cc

Fixed calling packed function in disco with rvalue which is not supported

[Serving] Fix spec decoding call packed with rvalue

---

python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_utils.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py

This PR adds a context manager to properly cleanup during async for exception.
Naively use the try except pattern will results in bug when we chain up async generators and exception get raised not inside the try except in between iterations.

[ASYNC] Properly abort cleanup in async handling

---

python/mlc_llm/cli/worker.py

This commit updates `mlc_llm.cli.worker` to be compatible with upstream TVM https://github.com/apache/tvm/pull/17180, which adds a `num_groups` argument to the disco worker function.
To de-couple this compatibility from a general TVM version bump, this commit has a check on the number of `worker.py` arguments provided, to determine whether the `num_groups` argument is present.  After the TVM version used by MLC-LLM is updated to include the upstream changes, this check can be removed.

Update worker.py for compatibility with upstream TVM

---

cpp/json_ffi/conv_template.cc
python/mlc_llm/conversation_template/gemma.py

The `system_prefix_token_ids` of conv template already contains the bos token usually, which should be processed when converting message list to a single prompt. However, the C++ side didn't well respect this field before.

[C++] Handle system_prefix_token_ids in C++ Conv template

---

docs/deploy/android.rst

Add NDK version requirement in docs to avoid build package

[Android] Add NDK version requirement in docs to avoid build package

---

cpp/serve/model.cc
python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/executor.py
python/mlc_llm/bench/request_record.py

This PR adopts multi-processing to send requests in the benchmark when the number of concurrent requests is larger than 32. This is because when the number of concurrent requests is too high, asyncio may have large pressure and won't be able to send requests fast on time.
One caveat is that with multi-processing, we are not able to display an accurate progress bar with tqdm as before.

[Bench] Adopting multi-processing to send requests

---

python/mlc_llm/conversation_template/hermes.py
python/mlc_llm/conversation_template/llama.py
python/mlc_llm/protocol/openai_api_protocol.py
python/mlc_llm/serve/engine_base.py

This PR removes assertions where `tool` cannot appear in `messages` in the request, and add corresponding role `tool` for Llama3.1 and Hermes2 in the chat template. Note `ipython` in Llama3.1 is essentially `tool`.
As a result, we have basic support for function calling without using the field `ChatCompletionRequest.tools` for Llama3.1 and Hermes2.
For Hermes2, we are able to run the [official example](https://huggingface.co/NousResearch/Hermes-2-Theta-Llama-3-8B#prompt-format-for-function-calling) with MLCEngine: https://gist.github.com/CharlieFRuan/d0a7885d306e79d85a26d1791997edc7
For Llama3.1, we support all usages except when `Environment: ipython` is enabled since the `seps` in that case can be `<eom_id>` instead of `<eot_id>`, and more logics are needed to determine which one to …

[Tool] Prelim support for function calling with Llama3.1 and Hermes2

---

cpp/metadata/model.cc
cpp/serve/config.cc
cpp/serve/engine.cc

Support for RWKV in mlc-llm seems to be broken after commit [b310ee1cccd92fe5939d4f5825063e7cca10cc0f](https://github.com/mlc-ai/mlc-llm/commit/b310ee1cccd92fe5939d4f5825063e7cca10cc0f). 
For example, [here](https://github.com/mlc-ai/mlc-llm/blob/03a50c25bf3c57034508ea3812bec269b67b1dd0/cpp/serve/engine.cc#L774) in ``InferForRNNState()`` it ensures that ``max_single_sequence_length.has_value()`` is false, while right after that [it](https://github.com/mlc-ai/mlc-llm/blob/03a50c25bf3c57034508ea3812bec269b67b1dd0/cpp/serve/engine.cc#L785) checks to ensure the opposite.
BTW the prefix_cache functionality is also broken for RNN models. Disabling that makes RWKV inference without problems. I'm not sure how to fix that tho :P

[Fix] Fix config parsing for rnn models like RWKV

---

cpp/serve/config.cc

This PR fixes a bug which fails to properly handle the cases where the max single sequence length and max total sequence length are set with values larger than the default values.

[BugFix][Config] Fix up-scaling sequence length

---

tests/python/op/test_tree_attn.py

Since #2682  added a positional argument `rope_scaling`, the test_tree_attn.py script couldn't run the tests. After adding a dummy argument, test_tree_attn.py was able to run the unit tests and pass all 24 test cases.

[FIX] Add a positional argument for tree_attn

---

.github/workflows/windows-build.yaml

This PR enables the long file paths for Windows CI since the FlashInfer kernel file paths may be longer than the Windows limit.

[CI] Enable long file paths for Windows CI

---

python/mlc_llm/conversation_template/__init__.py
python/mlc_llm/conversation_template/qwen2.py
python/mlc_llm/interface/gen_config.py

Added `qwen2` for chat template. Qwen2 used to use `chatml` for template, which has the wrong stop token id `2`. Instead, it should be `[151643, 151645]`.

[Fix] Fix qwen2 chat template

---

python/mlc_llm/bench/dataset.py

This PR renames the json schema dataset to `json-mode-eval`, as follow up of #2775.

[Bench] Rename json schema dataset

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_processor.py

This PR improves the benchmark compatibility to support other frameworks.
Some notes:
* Now the default temperature and top-p are set to 1 unless explicitly specified by `--temperature` and `top-p`.
* Now with ShareGPT dataset we will not add the `ignore_eos` flag.

[Bench] Improve benchmark compatibility

---

cpp/grammar/grammar_state_matcher.cc
cpp/grammar/grammar_state_matcher.h
python/mlc_llm/grammar/grammar.py
tests/python/grammar/test_grammar_state_matcher_json.py

This PR adds `SetStopTokenIds` to `GrammarStateMatcher`, registering `mlc.grammar.GrammarStateMatcherSetStopTokenIds`.
The method overrides existing default stop token ids of the matcher with user-provided ones. The motivation is that, for cases like tool calling where a json is wrapped between special tokens (e.g. `<tool_call>{TOOL_CALL_JSON}</tool_call>` for Hermes2), we want to instantiate a grammar state matcher when seeing `<tool_call>`, and make `</tool_call>` to be the only acceptable token after the closing `}`.
For Llama3.1, we may need a form of stop string (instead of stop token) since it can only be wrapped between special strings.
Tested with `tests/python/grammar/test_grammar_state_matcher_json.py` manually.

[Grammar] Add SetStopTokenIds for tool calling

---

cpp/serve/function_table.cc

This PR fixes an issue on Android that queries a global multi-gpu function while that function does not exist.

[C++] Skip getting global multi-gpu function when disco not enabled

---

python/mlc_llm/model/minicpm/minicpm_model.py
python/mlc_llm/model/model_preset.py

This PR updates the Minicpm model with the `tie_word_embedding` option, as most models in the Minicpm family, like `MiniCPM-2B-sft-bf16`, require `tie_word_embedding` to be turned on.
The preset of `minicpm_2b_sft_bf16` is also added in this PR.
Here is the demonstration after the update:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ mlc_llm chat dist/MiniCPM-2B-sft-bf16-q4f16_1-MLC \
>              --device "cuda:0" --overrides context_window_size=2048 \
>              --model-lib ./dist/libs/MiniCPM-2B-sft-bf16-q4f16_1-cuda.so
[2024-08-15 00:02:59] INFO auto_device.py:79: Found device: cuda:0
[2024-08-15 00:02:59] INFO engine_base.py:143: Using library model: ./dist/libs/MiniCPM-2B-sft-bf16-q4f16_1-cuda.so
[00:02:59] /home/tlopex/mlc-llm/cpp/serve/config.cc:668: Under mode …
```

[Model] Add tie_word_embedding option for Minicpm model

---

ios/MLCChat/MLCChat.xcodeproj/project.pbxproj
ios/MLCChat/MLCChat/Views/ChatView.swift
ios/MLCChat/MLCChat/Views/MessageView.swift

use [swift-markdown-ui](https://github.com/gonzalezreal/swift-markdown-ui) to render the text.
| markdown ON | markdown OFF |
|---------|---------|
| <img src="https://github.com/user-attachments/assets/77100c7a-fdfc-43cc-847c-783e9303cddd" width="300" alt="IMG_0111" /> | <img src="https://github.com/user-attachments/assets/da586612-3f3a-4e6a-8969-5b49c69bb03f" width="300" alt="IMG_0110" /> |

feat: use swift-markdown-ui to display markdown text in an iOS app

---

python/mlc_llm/quantization/utils.py

Packed weight save as int32 by default, don't follow storage data type. If don't set storage type to int32, it will cause dtype of q_weight don't match.

Save the packed_weight as storage data type

---

android/MLCChat/app/build.gradle
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatView.kt
android/MLCChat/settings.gradle

similar as this iOS PR: https://github.com/mlc-ai/mlc-llm/pull/2809, use [compose-markdown](https://github.com/jeziellago/compose-markdown) to render the markdown text as default
| markdown ON | markdown OFF |
|---------|---------|
| <img src="https://github.com/user-attachments/assets/b3e4c1c6-8dbd-44aa-820a-578d11c1acb0" width="300" alt="IMG_0111" /> | <img src="https://github.com/user-attachments/assets/00c88a65-c095-4e9c-be28-73e2bc79e0a6" width="300" alt="IMG_0110" /> |

[Android]: render markdown text as default

---

python/mlc_llm/compiler_pass/pipeline.py

This PR switches the pass `VMBuiltinLower` in the compilation pipeline to `LowerRuntimeBuiltin` due to deprecation.

[Pipeline] Switch VMBuiltinLower to LowerRuntimeBuiltin

---

cpp/multi_gpu/multi_gpu_loader.cc

This PR enables the weight pre-sharding for pipeline parallelism, which can significant reduce the runtime weight loading time.

[MultiGPU] Enable pre-sharding for pipeline parallelism

---

cpp/serve/sampler/cpu_sampler.cc

The CPU sampler has typo which prevents from running speculative decoding. This PR fixes the bug.

[Sampler] Fix CPU sampler for speculative decoding

---

python/mlc_llm/compiler_pass/attach_sampler.py
python/mlc_llm/compiler_pass/attach_softmax_with_temperature.py
python/mlc_llm/compiler_pass/attach_spec_decode_aux_funcs.py
python/mlc_llm/nn/kv_cache.py
python/mlc_llm/op/position_embedding.py
python/mlc_llm/op/top_p_pivot.py
python/mlc_llm/op/tree_attn.py

This PR improves the RoPE embedding implementation:
* We adopt a better way for Llama3.1 RoPE scaling computation.
* We observed some overhead caused by the recomputation of a same expression in the RoPE kernel. Therefore, we explicitly apply some common-subexpression elimination (CSE) at the TIR level for the RoPE kernel.
In this PR, we also updates some `tir.Var` definition to `tir.SizeVar` which indicates that the variable is non-negative.

[Op] Improve the RoPE embedding implementation

---

cpp/serve/engine_actions/eagle_batch_verify.cc

Update the length of decode token in eagle mode, so we can get the decode metrics, otherwise, it's always 0.
/metrics
decode_tokens_sum       73
decode_tokens_per_s     5.658155349407193
/stats
prefill: 1.0 tok/s, decode: 5.4 tok/s

Update the length of decode token in eagle mode

---

python/mlc_llm/model/phi3/phi3_model.py
python/mlc_llm/nn/kv_cache.py
python/mlc_llm/op/position_embedding.py

This PR brings the Phi-3.5 model support, particularly the `longrope` RoPE scaling.

[Model] Support Phi-3.5

---

ios/MLCChat/mlc-package-config.json

This PR adds the Phi3.5 model into the iOS `mlc-package-config.json`.

[iOS] Add Phi3.5 into `mlc-package-config.json`

---

docs/deploy/rest.rst

This PR updates the documentation for the clarity of the supported number of additional models. As of now we only support one additional model for speculative decoding

[Docs] Clarifying the number of additional model

---

docs/install/gpu.rst
docs/install/mlc_llm.rst
docs/install/tvm.rst

This PR updates the installation instructions for ROCm after our ROCm support upgraded to ROCm 6.1/6.2.

[Docs] Update installation instructions for ROCm

---

python/mlc_llm/model/llama/llama_model.py

This PR removed `assert self.head_dim * self.num_attention_heads == self.hidden_size` from `llama_model.py`, since this assertion is not always true -- LLaMA variants may have different relationships `num_attention_heads * head_dim`.

Remove hidden size assertion in LLaMA model

---

cpp/serve/engine.cc
python/mlc_llm/op/position_embedding.py

This PR fixes the prompt message of pipeline parallelism when the socket address is 0.0.0.0.
This PR also updates the positional embedding TIR function to use int32 dtype.

[MultiGPU] Fix pipeline parallelism prompt message

---

cpp/serve/engine_actions/batch_prefill_base.cc

This PR fixes the absense of seq len info update, when prefix cache removes the sequence in kvcache.

[Fix] Update seq len info after prefix cache operation

---

python/mlc_llm/model/phi3/phi3_model.py
python/mlc_llm/model/phi3v/phi3v_model.py

This PR fixes the attribute mismatch in the Phi3 Vision model
Additionally, we are using the RoPE mode "long" for Phi3 Vision, even though the RoPE mode in config.json is set to "su". This change is due to the warning message: "The class Phi3SuScaledRotaryEmbedding is deprecated and will be removed in version 5 of Transformers. Please use Phi3LongRoPEScaledRotaryEmbedding instead," as mentioned in modeling_phi3.py in the HF/Transformers library.

[Fix] Attribute mismatch in Phi-3-Vision Model

---

python/mlc_llm/model/rwkv6/rwkv6_model.py

This PR fixes some of the tensor dimension definition in rwkv6_model.py so that RWKV v6 7B/14B models can be correctly loaded.
*BTW RWKV v6 model compilation seems to be currently broken. See #2873.

[Fix] Fix RWKV v6 weights loading for 7B/14B models

---

cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/batch_decode.cc
cpp/serve/engine_actions/batch_draft.cc

This PR introduces some prerequisite operations to support automatic switching between speculative decoding mode and the normal batch decode mode.
Specifically, this PR
* removes the constraint that the BatchDecode action is applicable when there is only one model.
* enhances the BatchDraft action so whenever the committed tokens of a request in the draft model is lagging behind the committed tokens in the main model, the BatchDraft action will automatically prefill all the lagging-behind part into the draft model when generating the draft.
These changes are tested locally.

[Engine] Preparation for switching between spec-decode mode and normal mode

---

python/mlc_llm/bench/dataset.py

This PR updates the benchmark to truncate input text from dataset to the maximum context length supported by the model. With this, the benchmark will no longer run into the warning of "token indices sequence length is longer than the specified maximum sequence length for this model".

[Bench] Truncate to model max length when tokenizing

---

python/mlc_llm/conversation_template/hermes.py
python/mlc_llm/interface/gen_config.py

Added Hermes 3 support.
- uses almost the same conversation template as Hermes-2-Pro, except for system message and stop tokens.
- able to reuse WASM of Llama 3.1.

Added hermes 3 support

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/request_processor.py

This PR adds the support of multi round conversation when benchmarked with fixed concurrent request mode. When enabled, the chat history will be logged and appended during benchmark.

[Bench] Support multi round conversation

---

cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h
cpp/serve/engine_actions/auto_spec_decode.cc
cpp/serve/engine_actions/batch_draft.cc
cpp/serve/engine_actions/batch_prefill_base.cc
cpp/serve/engine_actions/batch_verify.cc
cpp/serve/engine_actions/eagle_batch_draft.cc
cpp/serve/engine_actions/eagle_batch_verify.cc
cpp/serve/engine_actions/eagle_new_request_prefill.cc
cpp/serve/engine_state.h
cpp/serve/metrics.h
python/mlc_llm/interface/help.py
python/mlc_llm/serve/config.py

This PR introduces the initial support of speculative decoding, which is enabled when the `spec_draft_length` is 0 (its default value is also changed to 0 in this PR so that the adaptive mode is enabled by default).
The goal of adaptive speculative decoding is to dynamically adjust the draft length depending on the engine's running state. For the initial version, we use a fixed table for the draft length selection. We will follow up with more powerful draft length selection.
This PR also fixes a few bugs after the introduction of tree draft.

[Engine][Spec] Initiali adaptive speculative decoding

---

python/mlc_llm/testing/debug_chat.py

This PR supports feeding an image url to DebugChat by generalizing its implementation for tokenization and embedding. Previous pure-text usage remains the same, and users can pass in `--image-url` followed by the image URL.
We also add `--disable-instrument` to disable dumping kernel input/output details for faster generation when instrumenting is not needed.

[Vision] Support image input in DebugChat

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/request_processor.py
python/mlc_llm/bench/request_record.py

This PR updates the benchmark to use OpenAI entrypoint `v1/completions` as the default to remove the impact of `v1/chat/completions` on conversation template and system prompt. The previous endpoint is renamed to `openai-chat`, and the naming here is aligned with vLLM.
This PR also fixes the TPOT calculation. Previously it used "number of output tokens - 1" as the divisor, and this PR changes "1" to the number of tokens in the first output chunk.

[Bench] Use OpenAI v1/completions as default

---

python/mlc_llm/model/phi3v/phi3v_model.py
python/mlc_llm/model/vision/image_processing.py

Prior to this PR, when compiling/running phi3.5-vision on non-CUDA backend like Metal, we would run into the following issues:
- Shape inference would exceed int32 (CUDA does not run into this as we use int64 on CUDA), leading to error in runtime:
```
TVMError: Assert fail: (T.Div(new_h - 2147483185, 336) - -6391320) * 336 == T.Cast("int32", resize2d1_var_lv4_shape[1]), Argument resize2d1.var_lv4.shape[1] has an unsatisfied constraint: new_h + T.Div((new_h + 336 - 1) // 336 * 336 - new_h, 2) + ((new_h + 336 - 1) // 336 * 336 - new_h - T.Div((new_h + 336 - 1) // 336 * 336 - new_h, 2)) == T.Cast("int32", resize2d1_var_lv4_shape[1])
```   
- If naively keeping int64 on Metal, we run into:
- `TVMError: Check failed: blockSize <= maxTotalThreadsPerThreadgroup (1024 vs. 896) :`
- This is …

[Vision][Fix] Enable image processing kernel on non-CUDA backends

---

python/mlc_llm/protocol/conversation_protocol.py

Phi3.5-vision has the following rules for formatting messages with images according to https://huggingface.co/microsoft/Phi-3.5-vision-instruct#input-formats:
- Single image: `<|user|>\n<|image_1|>\n{prompt}<|end|>\n<|assistant|>\n`
- Multi image: `<|user|>\n<|image_1|>\n<|image_2|>\n{prompt}<|end|>\n<|assistant|>\n`
Currently, our protocol misses the `\n` separator for the image.
In future when we support more vision models, how the image is formatted should be inside the conversation template rather than hardcoded.

[Vision][Fix] Follow phi3.5-vision prompt format for image

---

cpp/serve/engine_actions/batch_verify.cc
cpp/serve/sampler/gpu_sampler.cc

This PR fixes a critical bug which does not properly set the top-p value for the probabilities computed by the main model in batch verification. This bug leads to a huge decrease of the speculative decoding accuracy.

[Fix][Spec] Fix incorrect top-p normalization in batch verification

---

python/mlc_llm/bench/request_processor.py

This PR fixes the sampling of dataset in benchmark. Otherwise the sampled requests may refer to the same object and cause issues.

[Fix] Deepcopy reqeust when sampling dataset

---

python/mlc_llm/compiler_pass/attach_logit_processor.py

The PR contains typo fix in repetition penalty calculations.
The testing code is attached.
To test this fix it is necessary to add samplers_wrapper.cc and samplers_wrapper.h to <MLC-LLM>/cpp/serve/ folder and compile mlc-llm project. This wrappers allows to get access to "apply_penalty_inplace" kernel from python code.
After that it will be possible to run test_repetition_penalty.py which performs validation of "apply_penalty_inplace" kernel against transformers' RepetitionPenaltyLogitsProcessor.
[testing_code.zip](https://github.com/user-attachments/files/17110134/testing_code.zip)

Repetition penalty calculation fix

---

python/mlc_llm/bench/dataset.py

This PR fixes the benchmark dataset processing. We used `tokenizer.model_max_length` as the length of truncation, but for some tokenizers (e.g., Llama3), the value of `model_max_length` is an infinitely large integer, which causes error in the truncation.
This PR fixes it by setting an internal maximum limit of 100k.

[Bench] Fix the dataset truncation

---

python/mlc_llm/interface/gen_config.py

`"custom"` is added earlier for WebLLM, and it is no longer needed. Currently specifying as `"custom"` runs into error.

[Conv] Remove custom from gen_config CONV_TEMPLATES

---

cpp/serve/engine.cc
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/action_commons.h

Fixed a leak of draft token slots because they are not released when requests are finished

[Serving] Remove draft tokens after finishing request

---

docs/install/mlc_llm.rst
docs/install/tvm.rst

This PR updates documents to add the CUDA 12.3 packages and deprecate the 12.1 package support. We need CUDA 12.3 for some CUTLASS kernels in H100 GPUs.

[Docs] Support CUDA 12.3 packages; deprecate 12.1 packages

---

cpp/serve/metrics.cc

This PR fixes the metrics serialization where the division-by-zero may happen, producing "nan" in the serialized string and failing JSON parsing.

[Metric] Fix the devision-by-zero in spec-decode metrics

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_processor.py
python/mlc_llm/bench/request_record.py

This PR updates the benchmark with the following changes:
1. Fix the preprocessing of ShareGPT dataset. In ShareGPT dataset, sometimes a conversation entry starts with role GPT instead of role human, but previously the benchmark always selects the first message as the input and second as output. Therefore it might cause sending the GPT output in the dataset as a request input to benchmark servers. This does not align with the expectation and we thus fix it.
2. We make sure that for a given seed, given tokenizer and a given number of requests, the sampled requests are always the same across different runs. This improves the determinism and reproducibility.
3. Introduce logging raw request records into file. The raw request records include all information of a request, including its input …

[Fix][Bench] Improve determinism and log dump

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_record.py

This PR supports applying tokenizer chat template in benchmarking. It needs to be manually specified via flag `--apply-chat-template`.
In the following cases `--apply-chat-template` is not supported:
* when `--input-len` is also specified, which means the input text needs truncation.
* when the dataset is not ShareGPT.
* when the tokenizer does not have `chat_template` defined.

[Bench] Support applying chat template

---

python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_processor.py

This PR specializes the OpenAI endpoint with the option of "not attaching `debug_config`". Prior to this PR, when `--ignore-eos` is enabled, a `debug_config` field is included in the payload for MLC to recognize. However, some backend servers (e.g., vLLM) do not support this `debug_config` field. So we need to manually specify not attaching this field when benchmarking these backends.

[Bench] Specialize OpenAI endpoint for backends not supporting debug config

---

python/mlc_llm/bench/api_endpoint.py

This PR updates the backend names, introducing one name per backend framework. These backends may refer to the same api endpoint.

[Bench] Update API backend names

---

README.md

The discord badge was not hyperlinking to the server properly due to quotes in the link

Fix discord badge in readme

---

python/mlc_llm/support/download_cache.py

The official git clone instructions from HuggingFace does not contain the `.git` suffix, so this PR updates the git clone URL in MLC.

[Download] Update HuggingFace git clone URL

---

docs/deploy/android.rst

Relative Path causes this error. https://github.com/mlc-ai/mlc-llm/issues/2600 
One can really only use an absolute path here

Fix relativ path comment

---

cmake/gen_cmake_config.py

`USE_CUTLASS`, `USE_CUBLAS` and `USE_FLASHINFER` depend on CUDA being enabled. Similarly, `USE_OPENCL_ENABLE_HOST_PTR` depends on OpenCL being enabled.

Simplify obvious choices in gen_cmake_config.py

---

docs/compilation/convert_weights.rst
docs/deploy/mlc_chat_config.rst

Updated path pointers in both docs files to point to the `conversation_template` directory instead of linking to the non-existent `conversation_template.py` file, @Hzfengsy please help merge.

[docs] Updated conversation template doc

---

cpp/serve/function_table.cc

This PR fixes the function table initialization, so that when sliding window is enabled, we won't pick the FlashInfer attn kernel.

[Fix] Disable FlashInfer when sliding window is enabled

---

python/setup.py

This PR adds the sentencepiece package as a Python installation requirement for tokenizer coverage when running `gen_config`.

[Python] Add sentencepiece as installation requirement

---

python/mlc_llm/model/deepseek/deepseek_model.py

This PR updates the default prefill chunk size from 2048 to 8192 of Deepseek, just the same as other models.

[Model] Update default prefill chunk size of Deepseek

---

python/mlc_llm/model/vision/clip_vision.py
python/mlc_llm/quantization/group_quantization.py

This PR ensures that vision encoder layers are excluded from quantization, improving accuracy for models with vision components.

[Model] Keep vision encoder weights unquantized to maintain accuracy

---

cpp/serve/function_table.cc
cpp/serve/function_table.h
python/mlc_llm/compiler_pass/attach_cuda_graph_alloc_init_func.py
python/mlc_llm/compiler_pass/pipeline.py

This PR adds a function that invokes the storage allocation function generated by CUDA Graph rewrite. With this function, we now manually trigger the storage allocation at initialization time.
The reason we need this is because that the storage allocation may contain CUDA IPC memory alloc that has to run through a Disco session. So when a function that needs CUDA graph storage allocation runs first outside a Disco session, there might be error caused if we did not initialize the allocation in advance.

[C++] Invoke storage allocation for CUDA Graph explicitly

---

python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/request_processor.py
python/mlc_llm/bench/request_record.py
python/mlc_llm/cli/delivery.py
python/mlc_llm/cli/lib_delivery.py
python/mlc_llm/cli/model_metadata.py
python/mlc_llm/serve/engine.py
python/mlc_llm/serve/engine_base.py
python/mlc_llm/serve/sync_engine.py
python/mlc_llm/support/logging.py

Fixes #2780
This adds a environment variable `MLC_UNSET_LOGGING` to force the logging format to be disabled. It also removes `enable_logging` calls except for in MLC entrypoints (e.g. CLI main).

[Python] Add flag to disable logging config

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/api_endpoint.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_processor.py
python/mlc_llm/bench/request_record.py

Add Loogle and React dataset. Add fake warmup option to avoid initalizing prefix cache.

Add prefix-cache dataset in mlc bench

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/dataset.py
python/mlc_llm/bench/request_processor.py

This PR introduces the per-gpu-workload mode to MLC bench. Under this mode, the specified "num_concurrent_requests" and "request_rate" denote the workload **per GPU**, which means the overall workload of the entire serving system for benchmarking will be multiplied by the number of GPUs.
Meanwhile, this PR deprecates the argument `--testset-name` in favor of `--dataset-path` for Loogle dataset.

[Bench] Add "per-gpu-workload" mode

---

cpp/serve/config.cc
cpp/serve/config.h
cpp/serve/engine.cc
cpp/serve/engine_actions/action.h
cpp/serve/engine_actions/action_commons.cc
cpp/serve/engine_actions/disagg_prepare_recv.cc
cpp/serve/engine_actions/disagg_remote_send.cc
python/mlc_llm/interface/serve.py
python/mlc_llm/protocol/debug_protocol.py
python/mlc_llm/protocol/microserving_protocol.py
python/mlc_llm/router/router.py
python/mlc_llm/serve/entrypoints/__init__.py
python/mlc_llm/serve/entrypoints/microserving_entrypoints.py
python/mlc_llm/serve/entrypoints/openai_entrypoints.py
python/mlc_llm/serve/server/popen_server.py

This PR refactors the MicroServing REST API. With this PR, we now have all the microserving REST APIs under file
`python/mlc_llm/serve/entrypoints/microserving_entrypoints.py`. And relative protocol data structures are placed under `python/mlc_llm/protocol/microserving_protocol.py`. These REST APIs essentially wrap and redirect to the OpenAI `v1/completions` API.
Besides, this PR applies some API name renaming to be consistent with writeups.

[Serve] MicroServing API refactor

---

python/mlc_llm/model/gpt_j/gpt_j_model.py
python/mlc_llm/model/olmo/olmo_model.py

This PR supports TP function of GPTJ Model and fix minor typo of OlMo Model.

[SLM] GPTJ Multi-GPU support

---

python/mlc_llm/interface/compiler_flags.py

This PR resets the default IPC allreduce strategy under O2 mode to NONE for platform compatability.

[Compile] Reset custom allreduce flag in O2 mode to NONE

---

cpp/serve/function_table.cc
cpp/serve/model.cc
cpp/support/vlm_utils.cc
cpp/support/vlm_utils.h
python/mlc_llm/compiler_pass/low_batch_specialization.py
python/mlc_llm/model/phi3v/phi3v_image.py
python/mlc_llm/model/phi3v/phi3v_model.py
python/mlc_llm/model/vision/image_processing.py
python/mlc_llm/testing/debug_chat.py

This PR fixes the cached buffer allocation for larger new images and supports dynamic shapes in the vision encoder.

[Model] Fix cached buffer allocation and fix dynamic shape in Phi3v

---

python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py

This PR updates the Deepseek-v2 model implementation with the updated RoPE position arrays. Prior to this PR, we will query the RoPE positions for every single layer, while in fact these arrays can be reused and thus only one query is sufficient.

[Model] Reuse RoPE positions for Deepseek-v2 model

---

ci/task/pylint.sh
ci/task/test_model_compile.sh
ci/task/test_unittest.sh
docs/install/mlc_llm.rst
docs/install/tvm.rst

This PR adds the field `--no-index` to mlc-ai/mlc-llm pip install commands to bypass PyPI.

[Fix] Add `--no-index` to pip install commands

---

python/mlc_llm/conversation_template/deepseek.py
python/mlc_llm/interface/gen_config.py

This PR removes `deepseek_v3` conversation template, and adds `deepseek_r1_qwen` and `deepseek_r1_llama`, which only differ by the stop token. Note that DeepSeek V3 has its own stop token id, different from the R1's.

[Fix] Fix deepseek r1 stop tokens

---

python/mlc_llm/bench/__main__.py
python/mlc_llm/bench/dataset.py

This PR introduces [WildChat dataset](https://huggingface.co/datasets/allenai/WildChat) to mlc_llm bench.

[Bench] Add WildChat dataset

---

python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py

This PR fuses the rope operation with the matrix transposes which we were doing before the rope operation. Have tested the model(after compiling) post the changes.

[Deepseek-V2] Fused rope implementation

---

python/mlc_llm/model/deepseek_v2/deepseek_v2_loader.py
python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py
tests/python/integration/test_model_compile.py

This PR introduces the initial weight absorption implementation for the Deepseek-v2/v3 models. This implementation will be further enhanced with new KV cache attention interfaces for MLA.

[Model] Initial weight absorption impl for Deepseek-v2/v3

---

python/mlc_llm/compiler_pass/blas_dispatch.py
python/mlc_llm/interface/compile.py

This PR fixes a minor place which didn't print out the overriden model config during model compilation.
It also updates the Python import path subject to the latest TVM changes.

[Config] Print the overriden config during model compilation

---

cpp/tokenizers/tokenizers.cc

This PR removes a redundant debug logging message.

[Tokenizer] Remove redundant debug log print

---

cpp/serve/model.cc

Engine trace results are not accurate unless this is set so each model call knows to explicitly synchronize. Seems to have been accidentally omitted from constructor initializer list. See: https://github.com/mlc-ai/mlc-llm/issues/3132

Fixed missing trace_enabled from model constructor, which caused inaccurate profiling reports

---

python/mlc_llm/support/auto_target.py

Fixes `relax.build` function calls in `auto_target.py` to use `relax_pipeline` instead of `pipeline`

Auto_target.py Build Fix

---

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py

This PR resolves a compatibility issue with the TVM library by removing an unsupported argument. The issue arose when the `TIRPagedKVCache` class was instantiated with an `enable\_disaggregation` argument, which is not recognized by the TVM library.
Changes Made
------------
*   Modified the `create\_tir\_paged\_kv\_cache` function to remove the `enable\_disaggregation` argument from the kwargs dictionary before passing it to the `TIRPagedKVCache` constructor.
Benefits
--------
*   Resolves the compatibility issue with the TVM library, ensuring that the codebase can work seamlessly with the library.
*   Prevents potential errors and exceptions that may arise due to the unsupported argument.
Testing
-------
*   Verified that the modified code compiles successfully without any errors.
* …

[Fix] Resolve TVM Compatibility Issue by Removing Unsupported Argument

---

python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py

**PR Summary**: Make [enable_disaggregation](https://github.com/akshatsehgal/mlc-llm/blob/fix/tvm-compatibility-issue/python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py#L183) Argument Optional in [DispatchKVCacheCreation](https://github.com/akshatsehgal/mlc-llm/blob/fix/tvm-compatibility-issue/python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py)
This pull request addresses an issue in the [DispatchKVCacheCreation](https://github.com/akshatsehgal/mlc-llm/blob/fix/tvm-compatibility-issue/python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py) class where the [enable_disaggregation](https://github.com/akshatsehgal/mlc-llm/blob/fix/tvm-compatibility-issue/python/mlc_llm/compiler_pass/dispatch_kv_cache_creation.py#L183) argument was causing the `TIRPagedKVCache` …

Make enable_disaggregation Argument Optional in DispatchKVCacheCreation

---

python/mlc_llm/model/gemma3/gemma3_loader.py
python/mlc_llm/model/gemma3/gemma3_model.py
python/mlc_llm/model/gemma3/gemma3_quantization.py
python/mlc_llm/model/model.py

Adds model support for Gemma3, currently in progress. QK normalization has been added as described in the technical documentation for Gemma3, but current there is an issue with short/truncated generation and significant slowdown after the first few prompts.
Additionally, there is also a lack of local/global attention layer interweaving, similar to Gemma2 in MLC-LLM, as well as support for the multimodal capabilities of Gemma3

[Model] Gemma3 Support

---

android/mlc4j/src/cpp/tvm_runtime.h

This PR fixes `tvm_runtime.h` for android, which removes the include of a removed file, and inserts the include of a new source file.  This fixes the broken android app build flow.

[Android] Fix header after recent tvm runtime refactor

---

python/mlc_llm/conversation_template/gemma.py

Currently for all the gemma3 instruction models, we reused the previous gemma conv template. However, there is a difference in the stop token.
- In gemma2, the stop tokens are 1, 107: https://huggingface.co/google/gemma-2-2b-it/blob/main/generation_config.json
- In gemma3, the stop tokens are 1, 106: https://huggingface.co/google/gemma-3-1b-it/blob/main/generation_config.json
This PR add a new `gemma3_instruction` conv template, and will manually update the already-uploaded gemma 3 models on HF.
In gemma3, 107 is `\n`. So currently whenever the model tries to change to a new line, it ends generation.

[Fix] Fix gemma 3 conv template stop token

---

ci/task/pylint.sh
python/mlc_llm/compiler_pass/dispatch_triton_kernel.py
python/mlc_llm/compiler_pass/fuse_add_norm.py
python/mlc_llm/compiler_pass/fuse_dequantize_take.py
python/mlc_llm/compiler_pass/pipeline.py
python/mlc_llm/conversation_template/deepseek.py
python/mlc_llm/interface/gen_config.py
python/mlc_llm/loader/utils.py
python/mlc_llm/model/deepseek_v2/deepseek_v2_loader.py
python/mlc_llm/model/deepseek_v2/deepseek_v2_model.py
python/mlc_llm/model/deepseek_v2/deepseek_v2_quantization.py
python/mlc_llm/model/gemma3/gemma3_model.py
python/mlc_llm/model/model.py
python/mlc_llm/model/model_preset.py
python/mlc_llm/op/batch_matmul.py
python/mlc_llm/op/cutlass.py
python/mlc_llm/op/moe_matmul.py
python/mlc_llm/op/moe_misc.py
python/mlc_llm/op/triton.py
python/mlc_llm/quantization/__init__.py
python/mlc_llm/quantization/block_scale_quantization.py
python/mlc_llm/quantization/quantization.py
python/mlc_llm/quantization/utils.py
python/mlc_llm/support/tensor_parallel.py
python/mlc_llm/testing/debug_chat.py
tests/python/op/test_fp8_block_matmul.py

This PR introduces the Deepseek-v3 support with blockwise scale quantization. Deepseek-V3-0324 is also supported. R1 will be supported after a followup PR with the conversation template update.
More bfloat16 related optimizations will be added in the future for performance.
Some blockwise scale matmul kernels are adapted from SGLang project (http://github.com/sgl-project/sglang).

[Model] Deepseek-v3 support

---

python/mlc_llm/interface/compiler_flags.py

This PR enables using cuBLAS GeMM dispatch for bfloat16 gemm.

[Optim] Enable cuBLAS GeMM for bfloat16

---

android/MLCChat/app/src/main/AndroidManifest.xml
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/ChatView.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/MainActivity.kt
android/MLCChat/app/src/main/java/ai/mlc/mlcchat/NavView.kt
cpp/json_ffi/conv_template.cc

This PR introduces the support of LLaVA and Phi-V on android device.
Not thoroughly tested, but it works on my device. (Android 14.0)
checkpoints:
- https://huggingface.co/davidlightmysterion/llava-1.5-7b-hf-q4f16_1-MLC
- https://huggingface.co/mlc-ai/Phi-3.5-vision-instruct-q4f16_1-MLC

[Android] Support LLaVA and Phi-V

---

ci/build-environment.yaml

The Windows CI error `Compatibility with CMake < 3.5 has been removed from CMake.` is caused because CMake 4.0 has removed compatibility with versions of CMake older than 3.5.
The proper fix would be to upgrade msgpack-c version in tokenizers-cpp.
CMake: https://www.kitware.com/cmake-4-0-0-available-for-download/
CI failure: https://github.com/mlc-ai/mlc-llm/actions/runs/14776403076/job/41485528478

[CI][Fix] Temp fix for Windows CI error

---

android/MLCChat/mlc-package-config.json
android/mlc4j/CMakeLists.txt
android/mlc4j/prepare_libs.py
android/mlc4j/src/cpp/tvm_runtime.h
android/mlc4j/src/main/java/ai/mlc/mlcllm/JSONFFIEngine.java

This PR updates the Android build flow after recent FFI refactors.
Llama3 and Qwen3 models are verified on Samsung S23.

[Android] Update Android build flow after FFI refactor

---

android/mlc4j/CMakeLists.txt
android/mlc4j/src/cpp/tvm_runtime.h
cpp/multi_gpu/builtin.cc
cpp/multi_gpu/multi_gpu_loader.cc
cpp/serve/sampler/cpu_sampler.cc
python/mlc_llm/cli/model_metadata.py
python/mlc_llm/contrib/embeddings/embeddings.py
python/mlc_llm/testing/debug_chat.py

Following recent upstream changes that rename `relax_vm` to `vm`, we update the MLC side accordingly with the rename.

[Refactor] Rename `relax_vm` to `vm`

---

python/mlc_llm/interface/package.py

This PR fixes a symbol name mismatch caused by an upstream refactor in apache/tvm#18042.

[iOS][Android] Fix symbol name for library module after refactor

---

cpp/serve/function_table.cc

This PR fixes a bug of device specification. Prior to recent runtime refactors, the `Device null_device{DLDeviceType(0), 0}` is treated as a null for `Optional<Device>`, but this is no longer true in the latest runtime. Therefore, we use `Optional<Device>(std::nullopt)` to replace the previous `null_device` for a correct device specification.

[MultiGPU] Fix dist runtime device specification

---

python/mlc_llm/cli/model_metadata.py

This PR prints out the memory usage of KV cache: MB for one token's KV cache, and the total MB for model weights + intermediate buffers + a 4K-long KV cache.
If somehow the required fields are not present in `config` and `metadata` (e.g. for an old model), we do nothing.
Sample output in CLI:
```
[2025-05-03 21:44:24] INFO model_metadata.py:94: Total memory usage without KV cache: 2254.16 MB (Parameters: 923.16 MB. Temporary buffer: 1331.00 MB)
[2025-05-03 21:44:24] INFO model_metadata.py:128: KV cache size: 0.11 MB per token in the context window
[2025-05-03 21:44:24] INFO model_metadata.py:133: Total memory usage with a 4K KV cache: 2702.16 MB
```

[CLI] Report KV cache memory usage in mlc_llm compile

---

cpp/serve/event_trace_recorder.h

This PR fixes the initialization of EventTraceRecorder after the enhancement of ObjectRef null safety.
Prior to this PR, EventTraceRecorder is designed as a not-nullable class, while it doesn't have a corresponding constructor and is initialized by `make_object` in an external function. This is considered invalid with the ObjectRef null safety enhancement. Therefore, we relax the requirement and allow it to be nullable.

[C++] Fix EventTraceRecorder initialization

---

cpp/serve/function_table.cc
cpp/serve/function_table.h

Following #3332, this PR fixes a few places where `nullptr` is used to initialize non-nullable objects.
These bugs won't lead to compilation errors. They, however, lead to runtime errors that may look confusing.

[C++] Fix non-nullable object initialization

---

cpp/json_ffi/json_ffi_engine.cc
cpp/multi_gpu/builtin.cc
cpp/multi_gpu/multi_gpu_loader.cc
cpp/serve/data.cc
cpp/serve/engine.cc
cpp/serve/event_trace_recorder.cc
cpp/serve/model.cc
cpp/serve/radix_tree.cc
cpp/serve/request.cc
cpp/serve/threaded_engine.cc
cpp/tokenizers/streamer.cc
cpp/tokenizers/tokenizers.cc

Following apache/tvm#18312, this PR updates the `TVM_FFI_STATIC_INIT_BLOCK` to functional style.

[C++] Update TVM_FFI_STATIC_INIT_BLOCK to fn style

---

cpp/serve/sampler/sampler.h
python/mlc_llm/compiler_pass/attach_sampler.py

Add "metal" to AttachGPUSamplingFunc transform_module list to include GPU sampling functions for models compiled for metal. Update SupportGPUSampler function to use GPU sampling functions for metal during runtime.

[Serve] Enable GPU sampler for Metal

---

cpp/tokenizers/streamer.h

This PR fixes a field that wasn't initialized previously in StopStrHandler. It did not cause any error before so was not noticed, until the latest TVM FFI bump that reveals this problem.

[C++] Fix StopStrHandler initialization
